### Importing libraries

In [ ]:
import pickle

In [ ]:

import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow)
  Downloading flatbuffers-25.9.23-py2.py3-none-any.whl.metadata (875 bytes)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.6.0)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (6.32.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.3)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.75.1)
Collecting tensorboard~=2.20.0 (from tensorflow)
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.3)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (14.1.0)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/lib/python3/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.3.6)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard~=2.20.0->tensorflow)
  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard~=2.20.0->tensorflow)
  Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)
Downloading tensorflow-2.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (620.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 620.7/620.7 MB 862.6 kB/s eta 0:00:00
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.9.23-py2.py3-none-any.whl (30 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 6.3 MB/s eta 0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 110.4 MB/s eta 0:00:00
Downloading tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 159.2 MB/s eta 0:00:00
Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 127.3 MB/s eta 0:00:00
Downloading werkzeug-3.1.3-py3-none-any.whl (224 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 22.8 MB/s eta 0:00:00
Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 7.2 MB/s eta 0:00:00
Installing collected packages: libclang, flatbuffers, wheel, werkzeug, tensorboard-data-server, google_pasta, tensorboard, astunparse, tensorflow
Successfully installed astunparse-1.6.3 flatbuffers-25.9.23 google_pasta-0.2.0 libclang-18.1.1 tensorboard-2.20.0 tensorboard-data-server-0.7.2 tensorflow-2.20.0 werkzeug-3.1.3 wheel-0.45.1

In [4]:
import tensorflow as tf

/usr/local/lib/python3.12/dist-packages/jax/_src/cloud_tpu_init.py:82: UserWarning: Transparent hugepages are not enabled. TPU runtime startup and shutdown time should be significantly improved on TPU v5e and newer. If not already set, you may need to enable transparent hugepages in your VM image (sudo sh -c "echo always > /sys/kernel/mm/transparent_hugepage/enabled")
  warnings.warn(

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [6]:
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [ ]:
from joblib import dump, load

In [ ]:
import xgboost as xgb
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
from sklearn.feature_selection import RFE

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from sklearn.svm import SVC

In [ ]:
from xgboost import XGBClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
import numpy as np
import pandas as pd
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dropout
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split

In [ ]:
from keras.models import load_model
from keras.layers import Dense
from keras import Model

In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
import joblib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
early_stopping = EarlyStopping(monitor='val_loss',   # metric to monitor for improvement
                               patience=5,            # number of epochs with no improvement after which training will be stopped
                               restore_best_weights=True)  # restore model weights from the epoch with the best value of the monitored metric

### Data preprocessing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/FYP/final_dataset.csv")

In [ ]:
dataset.head(2)

,State_Name,District_Name,Crop_Year,Season,Area,Production,temperature,pH,rainfall,crop
0,Andhra Pradesh,ANANTAPUR,1997,Kharif,21400.0,2600.0,30.015194,6.540823,60.740755,arhar/tur
1,Andhra Pradesh,CHITTOOR,1997,Kharif,6100.0,900.0,34.173228,6.539902,64.741612,arhar/tur

In [ ]:
dataset.isnull().sum()

State_Name          0
District_Name       0
Crop_Year           0
Season              0
Area                0
Production       1829
temperature         0
pH                  0
rainfall            0
crop                0
dtype: int64

In [ ]:
dataset = dataset.drop(["State_Name", "District_Name", "Production", "Area"], axis=1)

In [ ]:
correlation_matrix = dataset.corr()

ValueError: could not convert string to float: 'Kharif     '

In [ ]:
plt.figure(figsize=(10, 8))  # Adjust the size as needed
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix')
plt.show()

In [ ]:
dataset.head(2)

   Crop_Year       Season  temperature        pH   rainfall       crop
0       1997  Kharif         30.015194  6.540823  60.740755  arhar/tur
1       1997  Kharif         34.173228  6.539902  64.741612  arhar/tur

In [ ]:
# Perform one-hot encoding
new_dataset = pd.get_dummies(dataset, columns=['Season'])
new_dataset.head(2)

,Crop_Year,temperature,pH,rainfall,crop,Season_Autumn,Season_Kharif,Season_Rabi,Season_Summer,Season_Whole Year,Season_Winter
0,1997,30.015194,6.540823,60.740755,arhar/tur,False,True,False,False,False,False
1,1997,34.173228,6.539902,64.741612,arhar/tur,False,True,False,False,False,False

In [ ]:
features = new_dataset.drop("crop", axis=1)
labels = dataset["crop"]

In [ ]:
print("Number of crops: ",len(labels.unique()))

Number of crops:  20

In [ ]:
Encoder = LabelEncoder()
labels = Encoder.fit_transform(labels)

In [ ]:
features = features.drop("Season_Autumn     ", axis=1)

In [ ]:
features.head(2)

,Crop_Year,temperature,pH,rainfall,Season_Kharif,Season_Rabi,Season_Summer,Season_Whole Year,Season_Winter
0,1997,30.015194,6.540823,60.740755,True,False,False,False,False
1,1997,34.173228,6.539902,64.741612,True,False,False,False,False

In [ ]:
features_1997 = features[0:6127]
labels_1997 = labels[0:6127]

In [ ]:
features_1997.iloc[-1]

Crop_Year                  1997
temperature           13.901182
pH                     6.184159
rainfall              68.400292
Season_Kharif             False
Season_Rabi                True
Season_Summer             False
Season_Whole Year         False
Season_Winter             False
Name: 6126, dtype: object

In [ ]:
features_1998 = features[6127:14039]
labels_1998 = labels[6127:14039]

In [ ]:
features_1999 = features[14040:22398]
labels_1999 = labels[14040:22398]
features_2000 = features[22399:31134]
labels_2000 = labels[22399:31134]
features_2001 = features[31135:39904]
labels_2001 = labels[31135:39904]
features_2002 = features[39905:49040]
labels_2002 = labels[39905:49040]
features_2003 = features[49041:58480]
labels_2003 = labels[49041:58480]
features_2004 = features[58481:67507]
labels_2004 = labels[58481:67507]
features_2005 = features[67508:76576]
labels_2005 = labels[67508:76576]
features_2006 = features[76577:85802]
labels_2006 = labels[76577:85802]

In [ ]:
features_2007 = features[85803:95471]
labels_2007 = labels[85803:95471]
features_2008 = features[95472:105004]
labels_2008 = labels[95472:105004]
features_2009 = features[105005:114275]
labels_2009 = labels[105005:114275]
features_2010 = features[114276:123761]
labels_2010 = labels[114276:123761]
features_2011 = features[123762:132928]
labels_2011 = labels[123762:132928]
features_2012 = features[132929:141600]
labels_2012 = labels[132929:141600]
features_2013 = features[141603:150195]
labels_2013 = labels[141603:150195]
features_2014 = features[150196:157158]
labels_2014 = labels[150196:157158]
features_2015 = features[157161:157639]
labels_2015 = labels[157161:157639]

In [ ]:
features_1997 = features_1997.drop("Crop_Year", axis=1)
features_1998 = features_1998.drop("Crop_Year", axis=1)
features_1999 = features_1999.drop("Crop_Year", axis=1)
features_2000 = features_2000.drop("Crop_Year", axis=1)
features_2001 = features_2001.drop("Crop_Year", axis=1)
features_2002 = features_2002.drop("Crop_Year", axis=1)
features_2003 = features_2003.drop("Crop_Year", axis=1)
features_2004 = features_2004.drop("Crop_Year", axis=1)
features_2005 = features_2005.drop("Crop_Year", axis=1)
features_2006 = features_2006.drop("Crop_Year", axis=1)
features_2007 = features_2007.drop("Crop_Year", axis=1)
features_2008 = features_2008.drop("Crop_Year", axis=1)
features_2009 = features_2009.drop("Crop_Year", axis=1)
features_2010 = features_2010.drop("Crop_Year", axis=1)
features_2011 = features_2011.drop("Crop_Year", axis=1)
features_2012 = features_2012.drop("Crop_Year", axis=1)
features_2013 = features_2013.drop("Crop_Year", axis=1)
features_2014 = features_2014.drop("Crop_Year", axis=1)
features_2015 = features_2015.drop("Crop_Year", axis=1)
features_1997.iloc[-1]

temperature           13.901182
pH                     6.184159
rainfall              68.400292
Season_Kharif             False
Season_Rabi                True
Season_Summer             False
Season_Whole Year         False
Season_Winter             False
Name: 6126, dtype: object

In [ ]:
Encoder.inverse_transform(np.array([11]))

array(['potato'], dtype=object)

## Feature Scaling

In [ ]:
features_1997 = features_1997.to_numpy()
features_1998 = features_1998.to_numpy()
features_1999 = features_1999.to_numpy()
features_2000 = features_2000.to_numpy()
features_2001 = features_2001.to_numpy()
features_2002 = features_2002.to_numpy()
features_2003 = features_2003.to_numpy()
features_2004 = features_2004.to_numpy()
features_2005 = features_2005.to_numpy()
features_2006 = features_2006.to_numpy()
features_2007 = features_2007.to_numpy()
features_2008 = features_2008.to_numpy()
features_2009 = features_2009.to_numpy()
features_2010 = features_2010.to_numpy()
features_2011 = features_2011.to_numpy()
features_2012 = features_2012.to_numpy()
features_2013 = features_2013.to_numpy()
features_2014 = features_2014.to_numpy()
features_2015 = features_2015.to_numpy()

In [ ]:
# 1997
sc = MinMaxScaler(feature_range = (0, 1))
features_1997 = sc.fit_transform(features_1997)

In [ ]:
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_1997.joblib')

['/content/drive/MyDrive/FYP/FYP Scalers/scaler_1997.joblib']

In [ ]:
sc = MinMaxScaler(feature_range = (0, 1))
features_1998 = sc.fit_transform(features_1998)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_1998.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_1999 = sc.fit_transform(features_1999)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_1999.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2000 = sc.fit_transform(features_2000)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2000.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2001 = sc.fit_transform(features_2001)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2001.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2002 = sc.fit_transform(features_2002)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2002.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2003 = sc.fit_transform(features_2003)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2003.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2004 = sc.fit_transform(features_2004)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2004.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2005 = sc.fit_transform(features_2005)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2005.joblib')

['/content/drive/MyDrive/FYP/FYP Scalers/scaler_2005.joblib']

In [ ]:
sc = MinMaxScaler(feature_range = (0, 1))
features_2006 = sc.fit_transform(features_2006)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2006.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2007 = sc.fit_transform(features_2007)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2007.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2008 = sc.fit_transform(features_2008)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2008.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2009 = sc.fit_transform(features_2009)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2009.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2010 = sc.fit_transform(features_2010)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2010.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2011 = sc.fit_transform(features_2011)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2011.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2012 = sc.fit_transform(features_2012)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2012.joblib')

['/content/drive/MyDrive/FYP/FYP Scalers/scaler_2012.joblib']

In [ ]:
sc = MinMaxScaler(feature_range = (0, 1))
features_2013 = sc.fit_transform(features_2013)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2013.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2014 = sc.fit_transform(features_2014)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2014.joblib')
sc = MinMaxScaler(feature_range = (0, 1))
features_2015 = sc.fit_transform(features_2015)
dump(sc, '/content/drive/MyDrive/FYP/FYP Scalers/scaler_2015.joblib')

['/content/drive/MyDrive/FYP/FYP Scalers/scaler_2015.joblib']

In [ ]:
features_2015.shape

(478, 8)

## Splitting the data into training and testing sets 1997

In [ ]:
kf = StratifiedKFold(n_splits=3)

In [ ]:
for x, y in kf.split(features_1997, labels_1997):
  x_train, x_test = features_1997[x], features_1997[y]
  y_train, y_test = labels_1997[x], labels_1997[y]

In [ ]:
for x, y in kf.split(x_test, y_test):
  X_test, x_val = x_test[x], x_test[y]
  Y_test, y_val = y_test[x], y_test[y]

## 1997 Model Architecture

In [ ]:
model_97 = Sequential(
    [
        Dense(units=200, activation="relu"),
        Dropout(0.5),
        Dense(units=100, activation="relu"),
        Dropout(0.5),
        Dense(units=50, activation="relu"),
        Dropout(0.5),
        Dense(units=20, activation="softmax")
    ]
)

## Model training Year: 1997

In [ ]:
model_97.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.sparse_categorical_crossentropy, metrics=["accuracy"])
history = model_97.fit(x_train, y_train, epochs=100)

Epoch 1/100
128/128 [==============================] - 7s 8ms/step - loss: 1.0443 - accuracy: 0.6685
Epoch 2/100
128/128 [==============================] - 1s 9ms/step - loss: 0.9652 - accuracy: 0.6803
Epoch 3/100
128/128 [==============================] - 1s 9ms/step - loss: 0.9794 - accuracy: 0.6568
Epoch 4/100
128/128 [==============================] - 1s 10ms/step - loss: 0.9858 - accuracy: 0.6563
Epoch 5/100
128/128 [==============================] - 1s 9ms/step - loss: 1.0048 - accuracy: 0.6595
Epoch 6/100
128/128 [==============================] - 1s 10ms/step - loss: 0.9606 - accuracy: 0.6715
Epoch 7/100
128/128 [==============================] - 1s 7ms/step - loss: 0.9466 - accuracy: 0.6788
Epoch 8/100
128/128 [==============================] - 1s 7ms/step - loss: 0.9435 - accuracy: 0.6764
Epoch 9/100
128/128 [==============================] - 1s 7ms/step - loss: 0.9875 - accuracy: 0.6656
Epoch 10/100
128/128 [==============================] - 1s 7ms/step - loss: 0.9109 - accuracy: 0.6761
Epoch 11/100
128/128 [==============================] - 1s 7ms/step - loss: 0.9184 - accuracy: 0.6805
Epoch 12/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8946 - accuracy: 0.6930
Epoch 13/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8951 - accuracy: 0.6876
Epoch 14/100
128/128 [==============================] - 1s 8ms/step - loss: 0.9284 - accuracy: 0.6842
Epoch 15/100
128/128 [==============================] - 1s 9ms/step - loss: 0.9088 - accuracy: 0.6813
Epoch 16/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8923 - accuracy: 0.6896
Epoch 17/100
128/128 [==============================] - 1s 9ms/step - loss: 0.8962 - accuracy: 0.6798
Epoch 18/100
128/128 [==============================] - 1s 10ms/step - loss: 0.9134 - accuracy: 0.6783
Epoch 19/100
128/128 [==============================] - 1s 9ms/step - loss: 0.8965 - accuracy: 0.6742
Epoch 20/100
128/128 [==============================] - 1s 9ms/step - loss: 0.8833 - accuracy: 0.6967
Epoch 21/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8487 - accuracy: 0.6967
Epoch 22/100
128/128 [==============================] - 1s 7ms/step - loss: 0.9134 - accuracy: 0.6928
Epoch 23/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8702 - accuracy: 0.6947
Epoch 24/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8912 - accuracy: 0.6952
Epoch 25/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8590 - accuracy: 0.6903
Epoch 26/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8514 - accuracy: 0.6996
Epoch 27/100
128/128 [==============================] - 1s 8ms/step - loss: 0.8906 - accuracy: 0.6874
Epoch 28/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8876 - accuracy: 0.6928
Epoch 29/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8358 - accuracy: 0.7033
Epoch 30/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8467 - accuracy: 0.7031
Epoch 31/100
128/128 [==============================] - 1s 10ms/step - loss: 0.8124 - accuracy: 0.7111
Epoch 32/100
128/128 [==============================] - 1s 10ms/step - loss: 0.8330 - accuracy: 0.6987
Epoch 33/100
128/128 [==============================] - 1s 10ms/step - loss: 0.8555 - accuracy: 0.6977
Epoch 34/100
128/128 [==============================] - 1s 9ms/step - loss: 0.8886 - accuracy: 0.6879
Epoch 35/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8821 - accuracy: 0.6864
Epoch 36/100
128/128 [==============================] - 1s 9ms/step - loss: 0.8588 - accuracy: 0.6999
Epoch 37/100
128/128 [==============================] - 1s 8ms/step - loss: 0.8274 - accuracy: 0.7043
Epoch 38/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8279 - accuracy: 0.7119
Epoch 39/100
128/128 [==============================] - 1s 8ms/step - loss: 0.8443 - accuracy: 0.6969
Epoch 40/100
128/128 [==============================] - 1s 8ms/step - loss: 0.8445 - accuracy: 0.7080
Epoch 41/100
128/128 [==============================] - 1s 9ms/step - loss: 0.8254 - accuracy: 0.7163
Epoch 42/100
128/128 [==============================] - 1s 8ms/step - loss: 0.8328 - accuracy: 0.7028
Epoch 43/100
128/128 [==============================] - 1s 8ms/step - loss: 0.8039 - accuracy: 0.7136
Epoch 44/100
128/128 [==============================] - 2s 12ms/step - loss: 0.8378 - accuracy: 0.7026
Epoch 45/100
128/128 [==============================] - 1s 10ms/step - loss: 0.8324 - accuracy: 0.7055
Epoch 46/100
128/128 [==============================] - 1s 9ms/step - loss: 0.8260 - accuracy: 0.7048
Epoch 47/100
128/128 [==============================] - 1s 8ms/step - loss: 0.7965 - accuracy: 0.7207
Epoch 48/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7951 - accuracy: 0.7155
Epoch 49/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7982 - accuracy: 0.7043
Epoch 50/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8430 - accuracy: 0.6957
Epoch 51/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8375 - accuracy: 0.6955
Epoch 52/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8303 - accuracy: 0.7070
Epoch 53/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8281 - accuracy: 0.7053
Epoch 54/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7892 - accuracy: 0.7173
Epoch 55/100
128/128 [==============================] - 1s 8ms/step - loss: 0.8028 - accuracy: 0.7173
Epoch 56/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8059 - accuracy: 0.7050
Epoch 57/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7931 - accuracy: 0.7200
Epoch 58/100
128/128 [==============================] - 1s 11ms/step - loss: 0.7690 - accuracy: 0.7241
Epoch 59/100
128/128 [==============================] - 1s 11ms/step - loss: 0.8029 - accuracy: 0.7111
Epoch 60/100
128/128 [==============================] - 1s 11ms/step - loss: 0.8707 - accuracy: 0.6960
Epoch 61/100
128/128 [==============================] - 1s 8ms/step - loss: 0.7791 - accuracy: 0.7295
Epoch 62/100
128/128 [==============================] - 1s 8ms/step - loss: 0.7818 - accuracy: 0.7258
Epoch 63/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7785 - accuracy: 0.7263
Epoch 64/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7880 - accuracy: 0.7241
Epoch 65/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8004 - accuracy: 0.7126
Epoch 66/100
128/128 [==============================] - 1s 7ms/step - loss: 0.8073 - accuracy: 0.7136
Epoch 67/100
128/128 [==============================] - 1s 9ms/step - loss: 0.8018 - accuracy: 0.7126
Epoch 68/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7795 - accuracy: 0.7136
Epoch 69/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7764 - accuracy: 0.7116
Epoch 70/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7620 - accuracy: 0.7231
Epoch 71/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7920 - accuracy: 0.7224
Epoch 72/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7804 - accuracy: 0.7239
Epoch 73/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7984 - accuracy: 0.7177
Epoch 74/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7703 - accuracy: 0.7082
Epoch 75/100
128/128 [==============================] - 1s 8ms/step - loss: 0.7659 - accuracy: 0.7258
Epoch 76/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7527 - accuracy: 0.7209
Epoch 77/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7492 - accuracy: 0.7256
Epoch 78/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7930 - accuracy: 0.7148
Epoch 79/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7795 - accuracy: 0.7248
Epoch 80/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7840 - accuracy: 0.7266
Epoch 81/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7857 - accuracy: 0.7200
Epoch 82/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7841 - accuracy: 0.7234
Epoch 83/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7744 - accuracy: 0.7261
Epoch 84/100
128/128 [==============================] - 1s 6ms/step - loss: 0.8111 - accuracy: 0.7151
Epoch 85/100
128/128 [==============================] - 1s 8ms/step - loss: 0.7869 - accuracy: 0.7248
Epoch 86/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7789 - accuracy: 0.7207
Epoch 87/100
128/128 [==============================] - 1s 6ms/step - loss: 0.7456 - accuracy: 0.7322
Epoch 88/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7805 - accuracy: 0.7261
Epoch 89/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7771 - accuracy: 0.7222
Epoch 90/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7849 - accuracy: 0.7212
Epoch 91/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7758 - accuracy: 0.7204
Epoch 92/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7513 - accuracy: 0.7285
Epoch 93/100
128/128 [==============================] - 1s 7ms/step - loss: 0.7518 - accuracy: 0.7346
Epoch 94/100
128/128 [==============================] - 1s 6ms/step - loss: 0.7653 - accuracy: 0.7278
Epoch 95/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7842 - accuracy: 0.7283
Epoch 96/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7978 - accuracy: 0.7175
Epoch 97/100
128/128 [==============================] - 1s 5ms/step - loss: 0.8249 - accuracy: 0.7141
Epoch 98/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7817 - accuracy: 0.7283
Epoch 99/100
128/128 [==============================] - 1s 5ms/step - loss: 0.7620 - accuracy: 0.7209
Epoch 100/100
128/128 [==============================] - 1s 6ms/step - loss: 0.7384 - accuracy: 0.7307

In [ ]:
model_97.compile(optimizer=tf.keras.optimizers.Adam(0.0001), loss=tf.keras.losses.sparse_categorical_crossentropy, metrics=["accuracy"])
history = model_97.fit(x_train, y_train, epochs=100)

Epoch 1/100
128/128 [==============================] - 3s 5ms/step - loss: 0.6994 - accuracy: 0.7417
Epoch 2/100
128/128 [==============================] - 1s 5ms/step - loss: 0.6512 - accuracy: 0.7491
Epoch 3/100
128/128 [==============================] - 1s 5ms/step - loss: 0.6473 - accuracy: 0.7616
Epoch 4/100
128/128 [==============================] - 1s 5ms/step - loss: 0.6253 - accuracy: 0.7682
Epoch 5/100
128/128 [==============================] - 1s 5ms/step - loss: 0.6265 - accuracy: 0.7599
Epoch 6/100
128/128 [==============================] - 1s 5ms/step - loss: 0.6205 - accuracy: 0.7660
Epoch 7/100
128/128 [==============================] - 1s 5ms/step - loss: 0.6151 - accuracy: 0.7611
Epoch 8/100
128/128 [==============================] - 1s 6ms/step - loss: 0.6210 - accuracy: 0.7718
Epoch 9/100
128/128 [==============================] - 1s 5ms/step - loss: 0.6197 - accuracy: 0.7665
Epoch 10/100
128/128 [==============================] - 1s 5ms/step - loss: 0.6135 - accuracy: 0.7652
Epoch 11/100
128/128 [==============================] - 1s 5ms/step - loss: 0.6133 - accuracy: 0.7657
Epoch 12/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5973 - accuracy: 0.7780
Epoch 13/100
128/128 [==============================] - 1s 7ms/step - loss: 0.6040 - accuracy: 0.7763
Epoch 14/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5989 - accuracy: 0.7726
Epoch 15/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5951 - accuracy: 0.7750
Epoch 16/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5950 - accuracy: 0.7792
Epoch 17/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5928 - accuracy: 0.7770
Epoch 18/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5952 - accuracy: 0.7868
Epoch 19/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5780 - accuracy: 0.7785
Epoch 20/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5778 - accuracy: 0.7831
Epoch 21/100
128/128 [==============================] - 1s 5ms/step - loss: 0.6183 - accuracy: 0.7748
Epoch 22/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5770 - accuracy: 0.7799
Epoch 23/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5770 - accuracy: 0.7882
Epoch 24/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5714 - accuracy: 0.7848
Epoch 25/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5851 - accuracy: 0.7846
Epoch 26/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5823 - accuracy: 0.7829
Epoch 27/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5772 - accuracy: 0.7836
Epoch 28/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5703 - accuracy: 0.7797
Epoch 29/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5754 - accuracy: 0.7767
Epoch 30/100
128/128 [==============================] - 1s 6ms/step - loss: 0.5657 - accuracy: 0.7905
Epoch 31/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5827 - accuracy: 0.7829
Epoch 32/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5727 - accuracy: 0.7919
Epoch 33/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5665 - accuracy: 0.7878
Epoch 34/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5698 - accuracy: 0.7848
Epoch 35/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5765 - accuracy: 0.7831
Epoch 36/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5540 - accuracy: 0.7875
Epoch 37/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5664 - accuracy: 0.7819
Epoch 38/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5693 - accuracy: 0.7860
Epoch 39/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5666 - accuracy: 0.7880
Epoch 40/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5687 - accuracy: 0.7919
Epoch 41/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5580 - accuracy: 0.7814
Epoch 42/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5545 - accuracy: 0.7873
Epoch 43/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5437 - accuracy: 0.7878
Epoch 44/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5632 - accuracy: 0.7914
Epoch 45/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5663 - accuracy: 0.7912
Epoch 46/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5506 - accuracy: 0.7971
Epoch 47/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5558 - accuracy: 0.7924
Epoch 48/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5409 - accuracy: 0.7944
Epoch 49/100
128/128 [==============================] - 1s 6ms/step - loss: 0.5480 - accuracy: 0.7988
Epoch 50/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5489 - accuracy: 0.7956
Epoch 51/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5498 - accuracy: 0.7949
Epoch 52/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5632 - accuracy: 0.7976
Epoch 53/100
128/128 [==============================] - 1s 6ms/step - loss: 0.5431 - accuracy: 0.7885
Epoch 54/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5641 - accuracy: 0.7966
Epoch 55/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5504 - accuracy: 0.7909
Epoch 56/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5516 - accuracy: 0.7917
Epoch 57/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5393 - accuracy: 0.7949
Epoch 58/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5446 - accuracy: 0.8020
Epoch 59/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5420 - accuracy: 0.7934
Epoch 60/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5322 - accuracy: 0.7961
Epoch 61/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5412 - accuracy: 0.7963
Epoch 62/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5383 - accuracy: 0.7956
Epoch 63/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5524 - accuracy: 0.7951
Epoch 64/100
128/128 [==============================] - 1s 6ms/step - loss: 0.5328 - accuracy: 0.7985
Epoch 65/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5552 - accuracy: 0.7980
Epoch 66/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5404 - accuracy: 0.7980
Epoch 67/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5341 - accuracy: 0.8044
Epoch 68/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5334 - accuracy: 0.7985
Epoch 69/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5301 - accuracy: 0.7990
Epoch 70/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5325 - accuracy: 0.8005
Epoch 71/100
128/128 [==============================] - 1s 8ms/step - loss: 0.5311 - accuracy: 0.7998
Epoch 72/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5297 - accuracy: 0.8005
Epoch 73/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5394 - accuracy: 0.7958
Epoch 74/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5376 - accuracy: 0.7966
Epoch 75/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5287 - accuracy: 0.7944
Epoch 76/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5355 - accuracy: 0.7958
Epoch 77/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5249 - accuracy: 0.7966
Epoch 78/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5430 - accuracy: 0.7973
Epoch 79/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5258 - accuracy: 0.7980
Epoch 80/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5235 - accuracy: 0.8088
Epoch 81/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5327 - accuracy: 0.7976
Epoch 82/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5387 - accuracy: 0.7983
Epoch 83/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5256 - accuracy: 0.8017
Epoch 84/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5341 - accuracy: 0.7973
Epoch 85/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5094 - accuracy: 0.8066
Epoch 86/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5302 - accuracy: 0.7944
Epoch 87/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5313 - accuracy: 0.8005
Epoch 88/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5305 - accuracy: 0.8010
Epoch 89/100
128/128 [==============================] - 1s 7ms/step - loss: 0.5057 - accuracy: 0.8115
Epoch 90/100
128/128 [==============================] - 1s 8ms/step - loss: 0.5189 - accuracy: 0.8034
Epoch 91/100
128/128 [==============================] - 1s 6ms/step - loss: 0.5112 - accuracy: 0.8083
Epoch 92/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5247 - accuracy: 0.8064
Epoch 93/100
128/128 [==============================] - 1s 6ms/step - loss: 0.5338 - accuracy: 0.7993
Epoch 94/100
128/128 [==============================] - 1s 6ms/step - loss: 0.5127 - accuracy: 0.8027
Epoch 95/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5137 - accuracy: 0.8056
Epoch 96/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5253 - accuracy: 0.8024
Epoch 97/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5169 - accuracy: 0.8064
Epoch 98/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5196 - accuracy: 0.8056
Epoch 99/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5317 - accuracy: 0.8034
Epoch 100/100
128/128 [==============================] - 1s 5ms/step - loss: 0.5203 - accuracy: 0.8010

In [ ]:
model_97.compile(optimizer=tf.keras.optimizers.Adam(0.00001), loss=tf.keras.losses.sparse_categorical_crossentropy, metrics=["accuracy"])
history = model_97.fit(x_train, y_train, epochs=100)

In [ ]:
test_loss, test_accuracy = model_97.evaluate(x_train, y_train)

print(f'Training Loss of 1997: {test_loss:.4f}')
print(f'Training Accuracy of 1997: {test_accuracy:.4f}')

test_loss, test_accuracy = model_97.evaluate(x_val, y_val)

print(f'Validation Loss of 1997: {test_loss:.4f}')
print(f'Validation Accuracy of 1997: {test_accuracy:.4f}')

128/128 [==============================] - 2s 3ms/step - loss: 0.4073 - accuracy: 0.8441
Training Loss of 1997: 0.4073
Training Accuracy of 1997: 0.8441
22/22 [==============================] - 0s 6ms/step - loss: 1.0136 - accuracy: 0.7485
Validation Loss of 1997: 1.0136
Validation Accuracy of 1997: 0.7485

In [ ]:
"""

test_loss, test_accuracy = model_97.evaluate(x_test, y_test)

print(f'Test Loss of 1997: {test_loss:.4f}')
print(f'Test Accuracy of 1997: {test_accuracy:.4f}')
"""

In [ ]:
# model_97.save("/content/drive/MyDrive/FYP/Trained Models/1997.keras")

In [ ]:
model_97 = tf.keras.models.load_model("/content/drive/MyDrive/FYP/Deep learning models/1997.keras")

In [ ]:
params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(x_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

In [ ]:
predictions = model.predict(dtrain)

In [ ]:
# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_train, predictions)

print("XGBoost Train Accuracy:", accuracy)

In [ ]:
model.save_model("/content/drive/MyDrive/FYP/Machine Learning Models/xgb_97.model")

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/1997.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)

# Train the classifier
knn.fit(x_train, y_train)
predictions = knn.predict(x_train)
accuracy = accuracy_score(y_train, predictions)
print("Train Accuracy:", accuracy)

# Make predictions on the test data
predictions = knn.predict(x_val)

# Calculate accuracy
accuracy = accuracy_score(y_val, predictions)
print("Validation Accuracy:", accuracy)

In [ ]:
nb_classifier = GaussianNB()

# Train the classifier
nb_classifier.fit(x_train, y_train)

# Make predictions on the test data
predictions = nb_classifier.predict(x_val)

# Calculate accuracy
accuracy = accuracy_score(y_val, predictions)
print("Accuracy:", accuracy)

In [ ]:
svm_classifier = SVC(kernel='linear', decision_function_shape='ovr')  # OvR strategy

# Train the classifier
svm_classifier.fit(x_train, y_train)

# Make predictions on the test data
predictions = svm_classifier.predict(x_val)

# Calculate accuracy
accuracy = accuracy_score(y_val, predictions)
print("Accuracy:", accuracy)

## Splitting the data into training and testing sets 1998

### Stratified sampling

In [ ]:
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_1998, labels_1998):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_1998)

numpy.ndarray

In [ ]:
fold1[0]

array([ 128,  129,  130, ..., 7909, 7910, 7911])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_1998[x]
    y_train = labels_1998[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_1998[x]))
    y_train = np.vstack((y_train, labels_1998[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_1998[x]
    y_test = labels_1998[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_1998[x]))
    y_test = np.vstack((y_test, labels_1998[x]))

In [ ]:
# Second iteration of Stratified KFold for test set
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_1998[x]
    y_train = labels_1998[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_1998[x]))
    y_train = np.vstack((y_train, labels_1998[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_1998[x]
    y_test = labels_1998[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_1998[x]))
    y_test = np.vstack((y_test, labels_1998[x]))

In [ ]:
# Third iteration of Stratified KFold for training test and cross validation set
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_1998[x]
    y_train = labels_1998[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_1998[x]))
    y_train = np.vstack((y_train, labels_1998[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_1998[x]
    y_test = labels_1998[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_1998[x]))
    y_test = np.vstack((y_test, labels_1998[x]))

In [ ]:
y_train.shape

(5274, 1)

## Model Training 1998

In [ ]:
model_98 = Sequential()

In [ ]:
model_98.add(Dense(units=700, activation="relu"))
model_98.add(Dropout(0.2))
model_98.add(Dense(units=250, activation="relu"))
model_98.add(Dropout(0.2))
model_98.add(Dense(units=128, activation="relu"))
model_98.add(Dropout(0.2))
model_98.add(Dense(units=64, activation="relu"))
model_98.add(Dropout(0.2))
model_98.add(Dense(units=45, activation="relu"))
model_98.add(Dropout(0.2))
model_98.add(Dense(units=28, activation="relu"))
model_98.add(Dropout(0.2))
model_98.add(Dense(units=20, activation="softmax"))

In [ ]:
model_98.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_98.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
165/165 [==============================] - 5s 4ms/step - loss: 2.5965 - accuracy: 0.1741
Epoch 2/100
165/165 [==============================] - 1s 6ms/step - loss: 2.0212 - accuracy: 0.3134
Epoch 3/100
165/165 [==============================] - 1s 4ms/step - loss: 1.7614 - accuracy: 0.3881
Epoch 4/100
165/165 [==============================] - 1s 5ms/step - loss: 1.5837 - accuracy: 0.4329
Epoch 5/100
165/165 [==============================] - 1s 6ms/step - loss: 1.4575 - accuracy: 0.4693
Epoch 6/100
165/165 [==============================] - 1s 6ms/step - loss: 1.3221 - accuracy: 0.5192
Epoch 7/100
165/165 [==============================] - 1s 6ms/step - loss: 1.2486 - accuracy: 0.5425
Epoch 8/100
165/165 [==============================] - 1s 4ms/step - loss: 1.1759 - accuracy: 0.5571
Epoch 9/100
165/165 [==============================] - 1s 7ms/step - loss: 1.1557 - accuracy: 0.5707
Epoch 10/100
165/165 [==============================] - 1s 8ms/step - loss: 1.1396 - accuracy: 0.5776
Epoch 11/100
165/165 [==============================] - 1s 5ms/step - loss: 1.0749 - accuracy: 0.6033
Epoch 12/100
165/165 [==============================] - 1s 4ms/step - loss: 1.0372 - accuracy: 0.6143
Epoch 13/100
165/165 [==============================] - 1s 4ms/step - loss: 1.0263 - accuracy: 0.6236
Epoch 14/100
165/165 [==============================] - 1s 4ms/step - loss: 0.9840 - accuracy: 0.6303
Epoch 15/100
165/165 [==============================] - 1s 4ms/step - loss: 0.9903 - accuracy: 0.6342
Epoch 16/100
165/165 [==============================] - 1s 5ms/step - loss: 0.9643 - accuracy: 0.6532
Epoch 17/100
165/165 [==============================] - 1s 4ms/step - loss: 0.9452 - accuracy: 0.6523
Epoch 18/100
165/165 [==============================] - 1s 4ms/step - loss: 0.9417 - accuracy: 0.6579
Epoch 19/100
165/165 [==============================] - 1s 4ms/step - loss: 0.9248 - accuracy: 0.6614
Epoch 20/100
165/165 [==============================] - 1s 5ms/step - loss: 0.8995 - accuracy: 0.6771
Epoch 21/100
165/165 [==============================] - 1s 6ms/step - loss: 0.8951 - accuracy: 0.6706
Epoch 22/100
165/165 [==============================] - 1s 6ms/step - loss: 0.9006 - accuracy: 0.6714
Epoch 23/100
165/165 [==============================] - 1s 5ms/step - loss: 0.8980 - accuracy: 0.6779
Epoch 24/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8761 - accuracy: 0.6860
Epoch 25/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8688 - accuracy: 0.6870
Epoch 26/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8744 - accuracy: 0.6775
Epoch 27/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8511 - accuracy: 0.6915
Epoch 28/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8574 - accuracy: 0.6942
Epoch 29/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8190 - accuracy: 0.7057
Epoch 30/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8300 - accuracy: 0.7042
Epoch 31/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8361 - accuracy: 0.7082
Epoch 32/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8227 - accuracy: 0.7093
Epoch 33/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8173 - accuracy: 0.7053
Epoch 34/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8104 - accuracy: 0.7059
Epoch 35/100
165/165 [==============================] - 1s 4ms/step - loss: 0.8041 - accuracy: 0.7188
Epoch 36/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7874 - accuracy: 0.7228
Epoch 37/100
165/165 [==============================] - 1s 6ms/step - loss: 0.8001 - accuracy: 0.7211
Epoch 38/100
165/165 [==============================] - 1s 6ms/step - loss: 0.8049 - accuracy: 0.7148
Epoch 39/100
165/165 [==============================] - 1s 6ms/step - loss: 0.7821 - accuracy: 0.7190
Epoch 40/100
165/165 [==============================] - 1s 5ms/step - loss: 0.7823 - accuracy: 0.7201
Epoch 41/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7703 - accuracy: 0.7273
Epoch 42/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7819 - accuracy: 0.7228
Epoch 43/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7844 - accuracy: 0.7150
Epoch 44/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7546 - accuracy: 0.7319
Epoch 45/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7753 - accuracy: 0.7309
Epoch 46/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7604 - accuracy: 0.7243
Epoch 47/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7610 - accuracy: 0.7317
Epoch 48/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7494 - accuracy: 0.7315
Epoch 49/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7704 - accuracy: 0.7262
Epoch 50/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7497 - accuracy: 0.7309
Epoch 51/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7512 - accuracy: 0.7397
Epoch 52/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7449 - accuracy: 0.7323
Epoch 53/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7502 - accuracy: 0.7272
Epoch 54/100
165/165 [==============================] - 1s 5ms/step - loss: 0.7484 - accuracy: 0.7340
Epoch 55/100
165/165 [==============================] - 1s 6ms/step - loss: 0.7242 - accuracy: 0.7395
Epoch 56/100
165/165 [==============================] - 1s 6ms/step - loss: 0.7371 - accuracy: 0.7465
Epoch 57/100
165/165 [==============================] - 1s 5ms/step - loss: 0.7191 - accuracy: 0.7399
Epoch 58/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7110 - accuracy: 0.7499
Epoch 59/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7303 - accuracy: 0.7440
Epoch 60/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7245 - accuracy: 0.7402
Epoch 61/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7145 - accuracy: 0.7355
Epoch 62/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7202 - accuracy: 0.7418
Epoch 63/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7336 - accuracy: 0.7476
Epoch 64/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7238 - accuracy: 0.7490
Epoch 65/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7364 - accuracy: 0.7395
Epoch 66/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7135 - accuracy: 0.7444
Epoch 67/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6920 - accuracy: 0.7524
Epoch 68/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6913 - accuracy: 0.7567
Epoch 69/100
165/165 [==============================] - 1s 5ms/step - loss: 0.7065 - accuracy: 0.7495
Epoch 70/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6856 - accuracy: 0.7522
Epoch 71/100
165/165 [==============================] - 1s 6ms/step - loss: 0.7352 - accuracy: 0.7404
Epoch 72/100
165/165 [==============================] - 1s 6ms/step - loss: 0.7093 - accuracy: 0.7488
Epoch 73/100
165/165 [==============================] - 1s 6ms/step - loss: 0.7032 - accuracy: 0.7473
Epoch 74/100
165/165 [==============================] - 1s 5ms/step - loss: 0.7048 - accuracy: 0.7459
Epoch 75/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7040 - accuracy: 0.7493
Epoch 76/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7257 - accuracy: 0.7450
Epoch 77/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7142 - accuracy: 0.7469
Epoch 78/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6904 - accuracy: 0.7562
Epoch 79/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7098 - accuracy: 0.7491
Epoch 80/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6717 - accuracy: 0.7622
Epoch 81/100
165/165 [==============================] - 1s 4ms/step - loss: 0.7234 - accuracy: 0.7427
Epoch 82/100
165/165 [==============================] - 1s 6ms/step - loss: 0.6921 - accuracy: 0.7509
Epoch 83/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6878 - accuracy: 0.7552
Epoch 84/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6924 - accuracy: 0.7533
Epoch 85/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6799 - accuracy: 0.7600
Epoch 86/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6980 - accuracy: 0.7596
Epoch 87/100
165/165 [==============================] - 1s 5ms/step - loss: 0.6734 - accuracy: 0.7647
Epoch 88/100
165/165 [==============================] - 1s 6ms/step - loss: 0.6729 - accuracy: 0.7613
Epoch 89/100
165/165 [==============================] - 1s 6ms/step - loss: 0.6762 - accuracy: 0.7560
Epoch 90/100
165/165 [==============================] - 1s 6ms/step - loss: 0.6730 - accuracy: 0.7573
Epoch 91/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6867 - accuracy: 0.7581
Epoch 92/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6943 - accuracy: 0.7586
Epoch 93/100
165/165 [==============================] - 1s 5ms/step - loss: 0.6758 - accuracy: 0.7603
Epoch 94/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6779 - accuracy: 0.7624
Epoch 95/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6545 - accuracy: 0.7728
Epoch 96/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6588 - accuracy: 0.7586
Epoch 97/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6767 - accuracy: 0.7592
Epoch 98/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6513 - accuracy: 0.7679
Epoch 99/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6659 - accuracy: 0.7634
Epoch 100/100
165/165 [==============================] - 1s 4ms/step - loss: 0.6796 - accuracy: 0.7594

In [ ]:
model_98.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_98.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
165/165 [==============================] - 4s 6ms/step - loss: 0.6254 - accuracy: 0.7725
Epoch 2/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5968 - accuracy: 0.7816
Epoch 3/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5910 - accuracy: 0.7880
Epoch 4/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5918 - accuracy: 0.7856
Epoch 5/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5894 - accuracy: 0.7882
Epoch 6/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5882 - accuracy: 0.7928
Epoch 7/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5854 - accuracy: 0.7901
Epoch 8/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5718 - accuracy: 0.7981
Epoch 9/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5825 - accuracy: 0.7918
Epoch 10/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5710 - accuracy: 0.7945
Epoch 11/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5941 - accuracy: 0.7952
Epoch 12/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5721 - accuracy: 0.8009
Epoch 13/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5775 - accuracy: 0.7943
Epoch 14/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5695 - accuracy: 0.7924
Epoch 15/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5808 - accuracy: 0.7920
Epoch 16/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5609 - accuracy: 0.7984
Epoch 17/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5751 - accuracy: 0.7947
Epoch 18/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5795 - accuracy: 0.7914
Epoch 19/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5677 - accuracy: 0.7990
Epoch 20/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5787 - accuracy: 0.7945
Epoch 21/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5676 - accuracy: 0.8000
Epoch 22/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5535 - accuracy: 0.8009
Epoch 23/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5579 - accuracy: 0.7990
Epoch 24/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5616 - accuracy: 0.7994
Epoch 25/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5664 - accuracy: 0.7967
Epoch 26/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5600 - accuracy: 0.7998
Epoch 27/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5607 - accuracy: 0.8019
Epoch 28/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5620 - accuracy: 0.8000
Epoch 29/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5661 - accuracy: 0.7941
Epoch 30/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5678 - accuracy: 0.7983
Epoch 31/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5634 - accuracy: 0.7945
Epoch 32/100
165/165 [==============================] - 1s 7ms/step - loss: 0.5567 - accuracy: 0.7996
Epoch 33/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5696 - accuracy: 0.7920
Epoch 34/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5638 - accuracy: 0.7971
Epoch 35/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5557 - accuracy: 0.8022
Epoch 36/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5541 - accuracy: 0.8015
Epoch 37/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7981
Epoch 38/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5571 - accuracy: 0.8022
Epoch 39/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5762 - accuracy: 0.7964
Epoch 40/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5510 - accuracy: 0.7964
Epoch 41/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5623 - accuracy: 0.8002
Epoch 42/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.8022
Epoch 43/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.8038
Epoch 44/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.8060
Epoch 45/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.8081
Epoch 46/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.8043
Epoch 47/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5499 - accuracy: 0.8020
Epoch 48/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.8072
Epoch 49/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5536 - accuracy: 0.7979
Epoch 50/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5559 - accuracy: 0.8038
Epoch 51/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5452 - accuracy: 0.8100
Epoch 52/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5496 - accuracy: 0.8051
Epoch 53/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5611 - accuracy: 0.7984
Epoch 54/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5511 - accuracy: 0.8062
Epoch 55/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5387 - accuracy: 0.8106
Epoch 56/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.8024
Epoch 57/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.8049
Epoch 58/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5575 - accuracy: 0.7994
Epoch 59/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5343 - accuracy: 0.8053
Epoch 60/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.8087
Epoch 61/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5425 - accuracy: 0.8074
Epoch 62/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5513 - accuracy: 0.8047
Epoch 63/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5422 - accuracy: 0.8068
Epoch 64/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5246 - accuracy: 0.8140
Epoch 65/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5405 - accuracy: 0.8123
Epoch 66/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5384 - accuracy: 0.8060
Epoch 67/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5468 - accuracy: 0.8036
Epoch 68/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5401 - accuracy: 0.8077
Epoch 69/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5406 - accuracy: 0.8053
Epoch 70/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5446 - accuracy: 0.8015
Epoch 71/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5417 - accuracy: 0.8085
Epoch 72/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.8060
Epoch 73/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5522 - accuracy: 0.7981
Epoch 74/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.8057
Epoch 75/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5327 - accuracy: 0.8153
Epoch 76/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.8123
Epoch 77/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.8045
Epoch 78/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5374 - accuracy: 0.8055
Epoch 79/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5332 - accuracy: 0.8093
Epoch 80/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.8110
Epoch 81/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.8066
Epoch 82/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5279 - accuracy: 0.8113
Epoch 83/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5420 - accuracy: 0.8032
Epoch 84/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5366 - accuracy: 0.8047
Epoch 85/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5272 - accuracy: 0.8100
Epoch 86/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.8100
Epoch 87/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.8108
Epoch 88/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5380 - accuracy: 0.8091
Epoch 89/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.8017
Epoch 90/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.8111
Epoch 91/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5387 - accuracy: 0.8123
Epoch 92/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5372 - accuracy: 0.8079
Epoch 93/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.8075
Epoch 94/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.8140
Epoch 95/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.8129
Epoch 96/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.8165
Epoch 97/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.8077
Epoch 98/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.8085
Epoch 99/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.8045
Epoch 100/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5330 - accuracy: 0.8098

In [ ]:
model_98.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_98.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

In [ ]:
model_98.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_98.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
165/165 [==============================] - 3s 4ms/step - loss: 0.5237 - accuracy: 0.8155
Epoch 2/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.8111
Epoch 3/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.8119
Epoch 4/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5368 - accuracy: 0.8093
Epoch 5/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.8096
Epoch 6/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5323 - accuracy: 0.8127
Epoch 7/100
165/165 [==============================] - 1s 7ms/step - loss: 0.5257 - accuracy: 0.8070
Epoch 8/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5207 - accuracy: 0.8132
Epoch 9/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5164 - accuracy: 0.8165
Epoch 10/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5184 - accuracy: 0.8121
Epoch 11/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5264 - accuracy: 0.8111
Epoch 12/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5160 - accuracy: 0.8161
Epoch 13/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5266 - accuracy: 0.8102
Epoch 14/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.8117
Epoch 15/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5297 - accuracy: 0.8123
Epoch 16/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5167 - accuracy: 0.8100
Epoch 17/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5355 - accuracy: 0.8062
Epoch 18/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5286 - accuracy: 0.8100
Epoch 19/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.8115
Epoch 20/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.8157
Epoch 21/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5134 - accuracy: 0.8180
Epoch 22/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.8111
Epoch 23/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5254 - accuracy: 0.8127
Epoch 24/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5147 - accuracy: 0.8176
Epoch 25/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5358 - accuracy: 0.8106
Epoch 26/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5277 - accuracy: 0.8153
Epoch 27/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5338 - accuracy: 0.8127
Epoch 28/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.8165
Epoch 29/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5232 - accuracy: 0.8104
Epoch 30/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.8201
Epoch 31/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5186 - accuracy: 0.8085
Epoch 32/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.8119
Epoch 33/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.8148
Epoch 34/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.8140
Epoch 35/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5114 - accuracy: 0.8146
Epoch 36/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5247 - accuracy: 0.8075
Epoch 37/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.8151
Epoch 38/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5229 - accuracy: 0.8163
Epoch 39/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.8140
Epoch 40/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5189 - accuracy: 0.8157
Epoch 41/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5071 - accuracy: 0.8185
Epoch 42/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5130 - accuracy: 0.8151
Epoch 43/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5261 - accuracy: 0.8176
Epoch 44/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.8189
Epoch 45/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5205 - accuracy: 0.8165
Epoch 46/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.8182
Epoch 47/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.8132
Epoch 48/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.8233
Epoch 49/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.8155
Epoch 50/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.8197
Epoch 51/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.8148
Epoch 52/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.8153
Epoch 53/100
165/165 [==============================] - 1s 4ms/step - loss: 0.4986 - accuracy: 0.8225
Epoch 54/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5074 - accuracy: 0.8178
Epoch 55/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.8203
Epoch 56/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.8157
Epoch 57/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.8223
Epoch 58/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5161 - accuracy: 0.8149
Epoch 59/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5245 - accuracy: 0.8151
Epoch 60/100
165/165 [==============================] - 1s 7ms/step - loss: 0.5208 - accuracy: 0.8168
Epoch 61/100
165/165 [==============================] - 1s 5ms/step - loss: 0.5129 - accuracy: 0.8129
Epoch 62/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.8104
Epoch 63/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5184 - accuracy: 0.8132
Epoch 64/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.8184
Epoch 65/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5194 - accuracy: 0.8142
Epoch 66/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.8121
Epoch 67/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5389 - accuracy: 0.8140
Epoch 68/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.8161
Epoch 69/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.8089
Epoch 70/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5217 - accuracy: 0.8130
Epoch 71/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5133 - accuracy: 0.8185
Epoch 72/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.8168
Epoch 73/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.8132
Epoch 74/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.8163
Epoch 75/100
165/165 [==============================] - 1s 6ms/step - loss: 0.4984 - accuracy: 0.8193
Epoch 76/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5140 - accuracy: 0.8144
Epoch 77/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5167 - accuracy: 0.8125
Epoch 78/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.8182
Epoch 79/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5153 - accuracy: 0.8142
Epoch 80/100
165/165 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.8195
Epoch 81/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5208 - accuracy: 0.8153
Epoch 82/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.8246
Epoch 83/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5119 - accuracy: 0.8149
Epoch 84/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.8172
Epoch 85/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5065 - accuracy: 0.8191
Epoch 86/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5180 - accuracy: 0.8138
Epoch 87/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.8178
Epoch 88/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.8178
Epoch 89/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.8189
Epoch 90/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.8149
Epoch 91/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.8187
Epoch 92/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5185 - accuracy: 0.8157
Epoch 93/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5160 - accuracy: 0.8159
Epoch 94/100
165/165 [==============================] - 1s 6ms/step - loss: 0.5100 - accuracy: 0.8153
Epoch 95/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5068 - accuracy: 0.8208
Epoch 96/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.8199
Epoch 97/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.8157
Epoch 98/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.8208
Epoch 99/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5109 - accuracy: 0.8204
Epoch 100/100
165/165 [==============================] - 1s 4ms/step - loss: 0.5175 - accuracy: 0.8108

In [ ]:
model_98.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_98.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

In [ ]:
# model_98.save("/content/drive/MyDrive/FYP/Trained Models/1998.keras")

In [ ]:
predictions = model(x_val)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

0

In [ ]:
model = tf.keras.models.load_model("/content/drive/MyDrive/FYP/Trained Models/1998.keras")

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_val, predicted_labels)

In [ ]:
accuracy

0.5779411764705882

In [ ]:
params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.8

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/1998.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 1999

### Stratified sampling

In [ ]:
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_1999, labels_1999):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_1999)

numpy.ndarray

In [ ]:
fold1[0]

array([ 130,  131,  132, ..., 8355, 8356, 8357])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_1999[x]
    y_train = labels_1999[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_1999[x]))
    y_train = np.vstack((y_train, labels_1999[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_1999[x]
    y_test = labels_1999[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_1999[x]))
    y_test = np.vstack((y_test, labels_1999[x]))

In [ ]:
# Second iteration of Stratified KFold for test set
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_1999[x]
    y_train = labels_1999[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_1999[x]))
    y_train = np.vstack((y_train, labels_1999[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_1999[x]
    y_test = labels_1999[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_1999[x]))
    y_test = np.vstack((y_test, labels_1999[x]))

In [ ]:
# Third iteration of Stratified KFold for training test and cross validation set
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_1999[x]
    y_train = labels_1999[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_1999[x]))
    y_train = np.vstack((y_train, labels_1999[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_1999[x]
    y_test = labels_1999[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_1999[x]))
    y_test = np.vstack((y_test, labels_1999[x]))

In [ ]:
y_train.shape

(5572, 1)

## Model Training 1999

In [ ]:
model = Sequential()

In [ ]:
# model.add(tf.keras.layers.Flatten())
model.add(Dropout(0.5))
model.add(Dense(units=250, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(units=128, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(units=64, activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(units=45, activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(units=28, activation="relu"))
model.add(Dense(units=20, activation="softmax"))

In [ ]:
adv_config = nsl.configs.make_adv_reg_config(multiplier=0.2, adv_step_size=0.05)
model_99 = nsl.keras.AdversarialRegularization(model, adv_config=adv_config)

In [ ]:
model_99.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_99.fit({'feature': X_train, 'label': y_train}, batch_size=32, epochs=5)
except Exception as ex:
  print(ex)

Epoch 1/5
in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1150, in train_step
        y_pred = self(x, training=True)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/tmp/__autograph_generated_file334wfs1b.py", line 25, in tf__call
        (outputs, labeled_loss, metrics, tape) = ag__.converted_call(ag__.ld(self)._forward_pass, (ag__.ld(inputs), ag__.ld(labels), ag__.ld(sample_weights), ag__.ld(kwargs)), None, fscope)
    File "/tmp/__autograph_generated_file8vztwfgs.py", line 14, in tf___forward_pass
        outputs = ag__.converted_call(ag__.ld(self)._call_base_model, (ag__.ld(inputs),), dict(**ag__.ld(base_model_kwargs)), fscope)
    File "/tmp/__autograph_generated_filef5eq48zx.py", line 75, in tf___call_base_model
        retval_ = ag__.converted_call(ag__.ld(self).base_model, (ag__.ld(inputs),), dict(**ag__.ld(kwargs)), fscope)

    AttributeError: Exception encountered when calling layer 'AdversarialRegularization' (type AdversarialRegularization).

    in user code:

        File "/usr/local/lib/python3.10/dist-packages/neural_structured_learning/keras/adversarial_regularization.py", line 675, in call  *
            outputs, labeled_loss, metrics, tape = self._forward_pass(
        File "/usr/local/lib/python3.10/dist-packages/neural_structured_learning/keras/adversarial_regularization.py", line 654, in _forward_pass  *
            outputs = self._call_base_model(inputs, **base_model_kwargs)
        File "/usr/local/lib/python3.10/dist-packages/neural_structured_learning/keras/adversarial_regularization.py", line 647, in _call_base_model  *
            return self.base_model(inputs, **kwargs)
        File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
        File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py", line 87, in call
            input_shape = inputs.shape

        AttributeError: Exception encountered when calling layer 'flatten' (type Flatten).

        'dict' object has no attribute 'shape'

        Call arguments received by layer 'flatten' (type Flatten):
          • inputs={'feature': 'tf.Tensor(shape=(None, 8), dtype=float32)'}


    Call arguments received by layer 'AdversarialRegularization' (type AdversarialRegularization):
      • inputs={'feature': 'tf.Tensor(shape=(None, 8), dtype=float32)', 'label': 'tf.Tensor(shape=(None, 1), dtype=int64)'}
      • kwargs={'training': 'True'}

In [ ]:
model_99.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_99.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
175/175 [==============================] - 3s 5ms/step - loss: 0.7157 - accuracy: 0.7294
Epoch 2/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6957 - accuracy: 0.7419
Epoch 3/100
175/175 [==============================] - 1s 5ms/step - loss: 0.7123 - accuracy: 0.7335
Epoch 4/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6882 - accuracy: 0.7428
Epoch 5/100
175/175 [==============================] - 1s 6ms/step - loss: 0.7020 - accuracy: 0.7337
Epoch 6/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6945 - accuracy: 0.7439
Epoch 7/100
175/175 [==============================] - 1s 6ms/step - loss: 0.7033 - accuracy: 0.7421
Epoch 8/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6998 - accuracy: 0.7396
Epoch 9/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6857 - accuracy: 0.7369
Epoch 10/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6848 - accuracy: 0.7455
Epoch 11/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6744 - accuracy: 0.7507
Epoch 12/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6800 - accuracy: 0.7408
Epoch 13/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6774 - accuracy: 0.7491
Epoch 14/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6939 - accuracy: 0.7412
Epoch 15/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6878 - accuracy: 0.7464
Epoch 16/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6658 - accuracy: 0.7477
Epoch 17/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6918 - accuracy: 0.7448
Epoch 18/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6848 - accuracy: 0.7468
Epoch 19/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6755 - accuracy: 0.7514
Epoch 20/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6768 - accuracy: 0.7469
Epoch 21/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6790 - accuracy: 0.7450
Epoch 22/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6839 - accuracy: 0.7509
Epoch 23/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6858 - accuracy: 0.7457
Epoch 24/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6794 - accuracy: 0.7471
Epoch 25/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6714 - accuracy: 0.7516
Epoch 26/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6757 - accuracy: 0.7462
Epoch 27/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6793 - accuracy: 0.7469
Epoch 28/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6937 - accuracy: 0.7430
Epoch 29/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6585 - accuracy: 0.7547
Epoch 30/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6628 - accuracy: 0.7563
Epoch 31/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6767 - accuracy: 0.7500
Epoch 32/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6784 - accuracy: 0.7477
Epoch 33/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6731 - accuracy: 0.7523
Epoch 34/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6602 - accuracy: 0.7520
Epoch 35/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6665 - accuracy: 0.7536
Epoch 36/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6766 - accuracy: 0.7459
Epoch 37/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6574 - accuracy: 0.7522
Epoch 38/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6788 - accuracy: 0.7478
Epoch 39/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6679 - accuracy: 0.7509
Epoch 40/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6664 - accuracy: 0.7520
Epoch 41/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6655 - accuracy: 0.7520
Epoch 42/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6701 - accuracy: 0.7473
Epoch 43/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6767 - accuracy: 0.7507
Epoch 44/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6621 - accuracy: 0.7448
Epoch 45/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6662 - accuracy: 0.7446
Epoch 46/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6496 - accuracy: 0.7577
Epoch 47/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6645 - accuracy: 0.7477
Epoch 48/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6693 - accuracy: 0.7452
Epoch 49/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6622 - accuracy: 0.7509
Epoch 50/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6669 - accuracy: 0.7541
Epoch 51/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6600 - accuracy: 0.7536
Epoch 52/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6636 - accuracy: 0.7586
Epoch 53/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6632 - accuracy: 0.7459
Epoch 54/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6592 - accuracy: 0.7532
Epoch 55/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6638 - accuracy: 0.7566
Epoch 56/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6562 - accuracy: 0.7547
Epoch 57/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6506 - accuracy: 0.7583
Epoch 58/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6673 - accuracy: 0.7495
Epoch 59/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6657 - accuracy: 0.7500
Epoch 60/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6657 - accuracy: 0.7493
Epoch 61/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6529 - accuracy: 0.7516
Epoch 62/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6645 - accuracy: 0.7509
Epoch 63/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6618 - accuracy: 0.7557
Epoch 64/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6729 - accuracy: 0.7491
Epoch 65/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6518 - accuracy: 0.7584
Epoch 66/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6498 - accuracy: 0.7550
Epoch 67/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6448 - accuracy: 0.7583
Epoch 68/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6639 - accuracy: 0.7529
Epoch 69/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6413 - accuracy: 0.7584
Epoch 70/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6631 - accuracy: 0.7547
Epoch 71/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6552 - accuracy: 0.7532
Epoch 72/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6504 - accuracy: 0.7575
Epoch 73/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6689 - accuracy: 0.7468
Epoch 74/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6569 - accuracy: 0.7583
Epoch 75/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6462 - accuracy: 0.7572
Epoch 76/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6457 - accuracy: 0.7608
Epoch 77/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6587 - accuracy: 0.7507
Epoch 78/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6632 - accuracy: 0.7514
Epoch 79/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6434 - accuracy: 0.7523
Epoch 80/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6527 - accuracy: 0.7563
Epoch 81/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6354 - accuracy: 0.7590
Epoch 82/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6469 - accuracy: 0.7570
Epoch 83/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6470 - accuracy: 0.7577
Epoch 84/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6430 - accuracy: 0.7606
Epoch 85/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6554 - accuracy: 0.7548
Epoch 86/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6474 - accuracy: 0.7547
Epoch 87/100
175/175 [==============================] - 1s 7ms/step - loss: 0.6496 - accuracy: 0.7543
Epoch 88/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6437 - accuracy: 0.7563
Epoch 89/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6555 - accuracy: 0.7538
Epoch 90/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6527 - accuracy: 0.7579
Epoch 91/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6510 - accuracy: 0.7593
Epoch 92/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6539 - accuracy: 0.7575
Epoch 93/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6475 - accuracy: 0.7618
Epoch 94/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6460 - accuracy: 0.7586
Epoch 95/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6506 - accuracy: 0.7599
Epoch 96/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6589 - accuracy: 0.7548
Epoch 97/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6291 - accuracy: 0.7658
Epoch 98/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6385 - accuracy: 0.7633
Epoch 99/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6483 - accuracy: 0.7566
Epoch 100/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6415 - accuracy: 0.7638

In [ ]:
model_99.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_99.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
175/175 [==============================] - 3s 6ms/step - loss: 0.6240 - accuracy: 0.7676
Epoch 2/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6184 - accuracy: 0.7703
Epoch 3/100
175/175 [==============================] - 1s 7ms/step - loss: 0.6144 - accuracy: 0.7717
Epoch 4/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6125 - accuracy: 0.7683
Epoch 5/100
175/175 [==============================] - 1s 7ms/step - loss: 0.6139 - accuracy: 0.7696
Epoch 6/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6098 - accuracy: 0.7732
Epoch 7/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6049 - accuracy: 0.7740
Epoch 8/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6104 - accuracy: 0.7715
Epoch 9/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6130 - accuracy: 0.7640
Epoch 10/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6008 - accuracy: 0.7776
Epoch 11/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6035 - accuracy: 0.7739
Epoch 12/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6068 - accuracy: 0.7775
Epoch 13/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5922 - accuracy: 0.7773
Epoch 14/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6050 - accuracy: 0.7739
Epoch 15/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6049 - accuracy: 0.7742
Epoch 16/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6169 - accuracy: 0.7674
Epoch 17/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6010 - accuracy: 0.7785
Epoch 18/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5960 - accuracy: 0.7755
Epoch 19/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6097 - accuracy: 0.7685
Epoch 20/100
175/175 [==============================] - 1s 7ms/step - loss: 0.6177 - accuracy: 0.7755
Epoch 21/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5975 - accuracy: 0.7757
Epoch 22/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5967 - accuracy: 0.7723
Epoch 23/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5961 - accuracy: 0.7778
Epoch 24/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6034 - accuracy: 0.7719
Epoch 25/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6052 - accuracy: 0.7687
Epoch 26/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6151 - accuracy: 0.7649
Epoch 27/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6110 - accuracy: 0.7685
Epoch 28/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6040 - accuracy: 0.7732
Epoch 29/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5997 - accuracy: 0.7728
Epoch 30/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5966 - accuracy: 0.7762
Epoch 31/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5987 - accuracy: 0.7732
Epoch 32/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5992 - accuracy: 0.7721
Epoch 33/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5882 - accuracy: 0.7776
Epoch 34/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5980 - accuracy: 0.7733
Epoch 35/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5995 - accuracy: 0.7764
Epoch 36/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5971 - accuracy: 0.7706
Epoch 37/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5830 - accuracy: 0.7812
Epoch 38/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5875 - accuracy: 0.7794
Epoch 39/100
175/175 [==============================] - 1s 6ms/step - loss: 0.6016 - accuracy: 0.7730
Epoch 40/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5953 - accuracy: 0.7785
Epoch 41/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5984 - accuracy: 0.7780
Epoch 42/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5852 - accuracy: 0.7827
Epoch 43/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5935 - accuracy: 0.7782
Epoch 44/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5972 - accuracy: 0.7721
Epoch 45/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5834 - accuracy: 0.7809
Epoch 46/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5896 - accuracy: 0.7760
Epoch 47/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6020 - accuracy: 0.7703
Epoch 48/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5831 - accuracy: 0.7839
Epoch 49/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5873 - accuracy: 0.7810
Epoch 50/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5839 - accuracy: 0.7785
Epoch 51/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5900 - accuracy: 0.7825
Epoch 52/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5844 - accuracy: 0.7802
Epoch 53/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5899 - accuracy: 0.7782
Epoch 54/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5832 - accuracy: 0.7810
Epoch 55/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5799 - accuracy: 0.7775
Epoch 56/100
175/175 [==============================] - 1s 7ms/step - loss: 0.6023 - accuracy: 0.7796
Epoch 57/100
175/175 [==============================] - 1s 5ms/step - loss: 0.6000 - accuracy: 0.7766
Epoch 58/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5917 - accuracy: 0.7793
Epoch 59/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5979 - accuracy: 0.7766
Epoch 60/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5852 - accuracy: 0.7775
Epoch 61/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5923 - accuracy: 0.7771
Epoch 62/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5948 - accuracy: 0.7785
Epoch 63/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5883 - accuracy: 0.7769
Epoch 64/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5941 - accuracy: 0.7739
Epoch 65/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5875 - accuracy: 0.7787
Epoch 66/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5940 - accuracy: 0.7782
Epoch 67/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5853 - accuracy: 0.7809
Epoch 68/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5883 - accuracy: 0.7798
Epoch 69/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5746 - accuracy: 0.7836
Epoch 70/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5960 - accuracy: 0.7782
Epoch 71/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5940 - accuracy: 0.7791
Epoch 72/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5992 - accuracy: 0.7737
Epoch 73/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5826 - accuracy: 0.7823
Epoch 74/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5899 - accuracy: 0.7762
Epoch 75/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5899 - accuracy: 0.7798
Epoch 76/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5889 - accuracy: 0.7830
Epoch 77/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5765 - accuracy: 0.7803
Epoch 78/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5878 - accuracy: 0.7782
Epoch 79/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5932 - accuracy: 0.7855
Epoch 80/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5754 - accuracy: 0.7834
Epoch 81/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5803 - accuracy: 0.7814
Epoch 82/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5837 - accuracy: 0.7789
Epoch 83/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5903 - accuracy: 0.7809
Epoch 84/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5787 - accuracy: 0.7775
Epoch 85/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5837 - accuracy: 0.7771
Epoch 86/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5730 - accuracy: 0.7784
Epoch 87/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5876 - accuracy: 0.7794
Epoch 88/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5864 - accuracy: 0.7836
Epoch 89/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5875 - accuracy: 0.7805
Epoch 90/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5777 - accuracy: 0.7854
Epoch 91/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5896 - accuracy: 0.7791
Epoch 92/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5969 - accuracy: 0.7773
Epoch 93/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5715 - accuracy: 0.7872
Epoch 94/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5711 - accuracy: 0.7859
Epoch 95/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5863 - accuracy: 0.7832
Epoch 96/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5884 - accuracy: 0.7810
Epoch 97/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5831 - accuracy: 0.7819
Epoch 98/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5899 - accuracy: 0.7796
Epoch 99/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5775 - accuracy: 0.7855
Epoch 100/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5820 - accuracy: 0.7859

In [ ]:
model_99.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_99.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
175/175 [==============================] - 3s 6ms/step - loss: 0.5812 - accuracy: 0.7805
Epoch 2/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5767 - accuracy: 0.7812
Epoch 3/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5859 - accuracy: 0.7866
Epoch 4/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5853 - accuracy: 0.7802
Epoch 5/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5773 - accuracy: 0.7866
Epoch 6/100
175/175 [==============================] - 1s 4ms/step - loss: 0.5673 - accuracy: 0.7854
Epoch 7/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5705 - accuracy: 0.7857
Epoch 8/100
175/175 [==============================] - 1s 4ms/step - loss: 0.5789 - accuracy: 0.7845
Epoch 9/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5615 - accuracy: 0.7913
Epoch 10/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5735 - accuracy: 0.7798
Epoch 11/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5882 - accuracy: 0.7848
Epoch 12/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5660 - accuracy: 0.7855
Epoch 13/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5689 - accuracy: 0.7866
Epoch 14/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5746 - accuracy: 0.7832
Epoch 15/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5780 - accuracy: 0.7857
Epoch 16/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5799 - accuracy: 0.7819
Epoch 17/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5799 - accuracy: 0.7758
Epoch 18/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5646 - accuracy: 0.7884
Epoch 19/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5658 - accuracy: 0.7821
Epoch 20/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5750 - accuracy: 0.7872
Epoch 21/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5657 - accuracy: 0.7827
Epoch 22/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5891 - accuracy: 0.7762
Epoch 23/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5728 - accuracy: 0.7900
Epoch 24/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5757 - accuracy: 0.7884
Epoch 25/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5804 - accuracy: 0.7837
Epoch 26/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5609 - accuracy: 0.7888
Epoch 27/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5731 - accuracy: 0.7859
Epoch 28/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5620 - accuracy: 0.7866
Epoch 29/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5873 - accuracy: 0.7757
Epoch 30/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5665 - accuracy: 0.7900
Epoch 31/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5805 - accuracy: 0.7846
Epoch 32/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5655 - accuracy: 0.7843
Epoch 33/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5814 - accuracy: 0.7794
Epoch 34/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5807 - accuracy: 0.7823
Epoch 35/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5770 - accuracy: 0.7818
Epoch 36/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5770 - accuracy: 0.7841
Epoch 37/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5684 - accuracy: 0.7879
Epoch 38/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5688 - accuracy: 0.7850
Epoch 39/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5616 - accuracy: 0.7828
Epoch 40/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5650 - accuracy: 0.7906
Epoch 41/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5707 - accuracy: 0.7902
Epoch 42/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5684 - accuracy: 0.7846
Epoch 43/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5709 - accuracy: 0.7872
Epoch 44/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5749 - accuracy: 0.7854
Epoch 45/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5652 - accuracy: 0.7929
Epoch 46/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5811 - accuracy: 0.7807
Epoch 47/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5716 - accuracy: 0.7879
Epoch 48/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5674 - accuracy: 0.7830
Epoch 49/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5788 - accuracy: 0.7828
Epoch 50/100
175/175 [==============================] - 1s 4ms/step - loss: 0.5710 - accuracy: 0.7846
Epoch 51/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5698 - accuracy: 0.7904
Epoch 52/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5651 - accuracy: 0.7902
Epoch 53/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5707 - accuracy: 0.7873
Epoch 54/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5732 - accuracy: 0.7845
Epoch 55/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5791 - accuracy: 0.7800
Epoch 56/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5708 - accuracy: 0.7843
Epoch 57/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5510 - accuracy: 0.7934
Epoch 58/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5693 - accuracy: 0.7803
Epoch 59/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5656 - accuracy: 0.7872
Epoch 60/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5731 - accuracy: 0.7837
Epoch 61/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5650 - accuracy: 0.7900
Epoch 62/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5705 - accuracy: 0.7810
Epoch 63/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5701 - accuracy: 0.7900
Epoch 64/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5690 - accuracy: 0.7812
Epoch 65/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5733 - accuracy: 0.7916
Epoch 66/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5589 - accuracy: 0.7938
Epoch 67/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5618 - accuracy: 0.7886
Epoch 68/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5636 - accuracy: 0.7907
Epoch 69/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5777 - accuracy: 0.7848
Epoch 70/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5704 - accuracy: 0.7863
Epoch 71/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5609 - accuracy: 0.7886
Epoch 72/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5580 - accuracy: 0.7906
Epoch 73/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5691 - accuracy: 0.7884
Epoch 74/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5761 - accuracy: 0.7807
Epoch 75/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5803 - accuracy: 0.7825
Epoch 76/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5755 - accuracy: 0.7873
Epoch 77/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5647 - accuracy: 0.7913
Epoch 78/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5578 - accuracy: 0.7893
Epoch 79/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5821 - accuracy: 0.7827
Epoch 80/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5710 - accuracy: 0.7868
Epoch 81/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5618 - accuracy: 0.7868
Epoch 82/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5678 - accuracy: 0.7866
Epoch 83/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5684 - accuracy: 0.7830
Epoch 84/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5592 - accuracy: 0.7886
Epoch 85/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5682 - accuracy: 0.7863
Epoch 86/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5719 - accuracy: 0.7846
Epoch 87/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5614 - accuracy: 0.7911
Epoch 88/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5565 - accuracy: 0.7895
Epoch 89/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5663 - accuracy: 0.7873
Epoch 90/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5657 - accuracy: 0.7886
Epoch 91/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5589 - accuracy: 0.7918
Epoch 92/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5738 - accuracy: 0.7875
Epoch 93/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5580 - accuracy: 0.7920
Epoch 94/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5788 - accuracy: 0.7863
Epoch 95/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5734 - accuracy: 0.7866
Epoch 96/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5705 - accuracy: 0.7852
Epoch 97/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5702 - accuracy: 0.7863
Epoch 98/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5701 - accuracy: 0.7818
Epoch 99/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5638 - accuracy: 0.7895
Epoch 100/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5653 - accuracy: 0.7864

In [ ]:
model_99.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_99.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
175/175 [==============================] - 3s 6ms/step - loss: 0.5716 - accuracy: 0.7866
Epoch 2/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5616 - accuracy: 0.7900
Epoch 3/100
175/175 [==============================] - 1s 7ms/step - loss: 0.5614 - accuracy: 0.7870
Epoch 4/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5746 - accuracy: 0.7855
Epoch 5/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5671 - accuracy: 0.7850
Epoch 6/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5611 - accuracy: 0.7934
Epoch 7/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5511 - accuracy: 0.7950
Epoch 8/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5673 - accuracy: 0.7924
Epoch 9/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5600 - accuracy: 0.7900
Epoch 10/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5642 - accuracy: 0.7810
Epoch 11/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5702 - accuracy: 0.7924
Epoch 12/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5628 - accuracy: 0.7913
Epoch 13/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5690 - accuracy: 0.7879
Epoch 14/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5683 - accuracy: 0.7872
Epoch 15/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5634 - accuracy: 0.7906
Epoch 16/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5630 - accuracy: 0.7909
Epoch 17/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5592 - accuracy: 0.7880
Epoch 18/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5510 - accuracy: 0.7950
Epoch 19/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5618 - accuracy: 0.7920
Epoch 20/100
175/175 [==============================] - 1s 8ms/step - loss: 0.5715 - accuracy: 0.7863
Epoch 21/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5546 - accuracy: 0.7873
Epoch 22/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5677 - accuracy: 0.7873
Epoch 23/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5629 - accuracy: 0.7906
Epoch 24/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5583 - accuracy: 0.7897
Epoch 25/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5577 - accuracy: 0.7915
Epoch 26/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5653 - accuracy: 0.7839
Epoch 27/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5629 - accuracy: 0.7902
Epoch 28/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5605 - accuracy: 0.7882
Epoch 29/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5635 - accuracy: 0.7884
Epoch 30/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5741 - accuracy: 0.7857
Epoch 31/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5745 - accuracy: 0.7830
Epoch 32/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5737 - accuracy: 0.7904
Epoch 33/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5593 - accuracy: 0.7902
Epoch 34/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5648 - accuracy: 0.7907
Epoch 35/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5603 - accuracy: 0.7909
Epoch 36/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5579 - accuracy: 0.7924
Epoch 37/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5734 - accuracy: 0.7909
Epoch 38/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5749 - accuracy: 0.7884
Epoch 39/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5676 - accuracy: 0.7879
Epoch 40/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5717 - accuracy: 0.7830
Epoch 41/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5576 - accuracy: 0.7927
Epoch 42/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5650 - accuracy: 0.7909
Epoch 43/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5685 - accuracy: 0.7845
Epoch 44/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5544 - accuracy: 0.7913
Epoch 45/100
175/175 [==============================] - 1s 4ms/step - loss: 0.5692 - accuracy: 0.7866
Epoch 46/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5613 - accuracy: 0.7861
Epoch 47/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5717 - accuracy: 0.7877
Epoch 48/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5729 - accuracy: 0.7880
Epoch 49/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5577 - accuracy: 0.7913
Epoch 50/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5705 - accuracy: 0.7845
Epoch 51/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5647 - accuracy: 0.7852
Epoch 52/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5712 - accuracy: 0.7870
Epoch 53/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5680 - accuracy: 0.7904
Epoch 54/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5527 - accuracy: 0.7929
Epoch 55/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5644 - accuracy: 0.7906
Epoch 56/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5630 - accuracy: 0.7859
Epoch 57/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5687 - accuracy: 0.7839
Epoch 58/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5584 - accuracy: 0.7895
Epoch 59/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5645 - accuracy: 0.7938
Epoch 60/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5600 - accuracy: 0.7933
Epoch 61/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5655 - accuracy: 0.7897
Epoch 62/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5711 - accuracy: 0.7893
Epoch 63/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5712 - accuracy: 0.7884
Epoch 64/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5570 - accuracy: 0.7882
Epoch 65/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5634 - accuracy: 0.7886
Epoch 66/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5668 - accuracy: 0.7855
Epoch 67/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5735 - accuracy: 0.7859
Epoch 68/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5620 - accuracy: 0.7893
Epoch 69/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5617 - accuracy: 0.7888
Epoch 70/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5623 - accuracy: 0.7959
Epoch 71/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5668 - accuracy: 0.7863
Epoch 72/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5575 - accuracy: 0.7902
Epoch 73/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5528 - accuracy: 0.7925
Epoch 74/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5693 - accuracy: 0.7846
Epoch 75/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5523 - accuracy: 0.7929
Epoch 76/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5626 - accuracy: 0.7909
Epoch 77/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5644 - accuracy: 0.7882
Epoch 78/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5672 - accuracy: 0.7889
Epoch 79/100
175/175 [==============================] - 1s 4ms/step - loss: 0.5598 - accuracy: 0.7922
Epoch 80/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5683 - accuracy: 0.7884
Epoch 81/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5673 - accuracy: 0.7898
Epoch 82/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5584 - accuracy: 0.7920
Epoch 83/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5625 - accuracy: 0.7915
Epoch 84/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5684 - accuracy: 0.7888
Epoch 85/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5706 - accuracy: 0.7868
Epoch 86/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5612 - accuracy: 0.7861
Epoch 87/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5734 - accuracy: 0.7891
Epoch 88/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5618 - accuracy: 0.7898
Epoch 89/100
175/175 [==============================] - 1s 6ms/step - loss: 0.5545 - accuracy: 0.7931
Epoch 90/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5609 - accuracy: 0.7895
Epoch 91/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5602 - accuracy: 0.7929
Epoch 92/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5568 - accuracy: 0.7879
Epoch 93/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5596 - accuracy: 0.7931
Epoch 94/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5532 - accuracy: 0.7907
Epoch 95/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5548 - accuracy: 0.7931
Epoch 96/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5576 - accuracy: 0.7897
Epoch 97/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5669 - accuracy: 0.7857
Epoch 98/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5564 - accuracy: 0.7880
Epoch 99/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5726 - accuracy: 0.7848
Epoch 100/100
175/175 [==============================] - 1s 5ms/step - loss: 0.5665 - accuracy: 0.7837

In [ ]:
# model_99.save("/content/drive/MyDrive/FYP/Trained Models/1999.keras")
model = tf.keras.models.load_model("/content/drive/MyDrive/FYP/Trained Models/2015.keras")

In [ ]:
predictions = model(x_val)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

18

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_val, predicted_labels)

In [ ]:
accuracy

0.3176470588235294

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.763235294117647

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/1999.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2000

### Stratified sampling

In [ ]:
k_fold = StratifiedKFold(n_splits=2, shuffle=True, random_state=42)

# Iterate over the folds
for train_index, test_index in k_fold.split(features_2000, labels_2000):
    # Split the data into train and test sets for this fold
    X_train, X_test = features_2000[train_index], features_2000[test_index]
    y_train, y_test = labels_2000[train_index], labels_2000[test_index]

for train_index, test_index in k_fold.split(X_test, y_test):
    # Split the data into validation and test sets for this fold
    x_val, x_test = X_test[train_index], X_test[test_index]
    y_val, Y_test = y_test[train_index], y_test[test_index]

## Model Training 2000

Applying transfer learning

In [ ]:
pre_trained_model = load_model('/content/drive/MyDrive/FYP/Trained Models/2005.keras')

In [ ]:
feature_extractor = Model(inputs=pre_trained_model.input, outputs=pre_trained_model.layers[-2].output)

In [ ]:
model_2000 = Model(inputs=feature_extractor.input, outputs=Dense(units=20, activation="softmax")(feature_extractor.output))

In [ ]:
"""
model_2000.add(Dense(units=520, activation="relu", kernel_initializer='random_normal'))
model_2000.add(Dropout(0.2))
model_2000.add(Dense(units=250, activation="relu", kernel_initializer='random_normal'))
model_2000.add(Dropout(0.2))
model_2000.add(Dense(units=128, activation="relu", kernel_initializer='glorot_uniform'))
model_2000.add(Dropout(0.2))
model_2000.add(Dense(units=64, activation="relu", kernel_initializer='glorot_uniform'))
model_2000.add(Dropout(0.2))
model_2000.add(Dense(units=45, activation="relu", kernel_initializer='random_uniform'))
model_2000.add(Dropout(0.2))
model_2000.add(Dense(units=28, activation="relu", kernel_initializer='random_uniform'))
model_2000.add(Dense(units=20, activation="softmax"))"""

'\nmodel_2000.add(Dense(units=520, activation="relu", kernel_initializer=\'random_normal\'))\nmodel_2000.add(Dropout(0.2))\nmodel_2000.add(Dense(units=250, activation="relu", kernel_initializer=\'random_normal\'))\nmodel_2000.add(Dropout(0.2))\nmodel_2000.add(Dense(units=128, activation="relu", kernel_initializer=\'glorot_uniform\'))\nmodel_2000.add(Dropout(0.2))\nmodel_2000.add(Dense(units=64, activation="relu", kernel_initializer=\'glorot_uniform\'))\nmodel_2000.add(Dropout(0.2))\nmodel_2000.add(Dense(units=45, activation="relu", kernel_initializer=\'random_uniform\'))\nmodel_2000.add(Dropout(0.2))\nmodel_2000.add(Dense(units=28, activation="relu", kernel_initializer=\'random_uniform\'))\nmodel_2000.add(Dense(units=20, activation="softmax"))'

Model training

In [ ]:
model_2000.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2000.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
182/182 [==============================] - 5s 12ms/step - loss: 2.6523 - accuracy: 0.3306
Epoch 2/100
182/182 [==============================] - 2s 13ms/step - loss: 1.0969 - accuracy: 0.6388
Epoch 3/100
182/182 [==============================] - 2s 13ms/step - loss: 0.9334 - accuracy: 0.6756
Epoch 4/100
182/182 [==============================] - 6s 31ms/step - loss: 0.8361 - accuracy: 0.7096
Epoch 5/100
182/182 [==============================] - 3s 15ms/step - loss: 0.8049 - accuracy: 0.7096
Epoch 6/100
182/182 [==============================] - 3s 14ms/step - loss: 0.7586 - accuracy: 0.7281
Epoch 7/100
182/182 [==============================] - 3s 16ms/step - loss: 0.7584 - accuracy: 0.7223
Epoch 8/100
182/182 [==============================] - 3s 14ms/step - loss: 0.7433 - accuracy: 0.7288
Epoch 9/100
182/182 [==============================] - 4s 21ms/step - loss: 0.7433 - accuracy: 0.7362
Epoch 10/100
182/182 [==============================] - 4s 21ms/step - loss: 0.7059 - accuracy: 0.7431
Epoch 11/100
182/182 [==============================] - 2s 13ms/step - loss: 0.7067 - accuracy: 0.7415
Epoch 12/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6902 - accuracy: 0.7421
Epoch 13/100
182/182 [==============================] - 2s 13ms/step - loss: 0.6925 - accuracy: 0.7462
Epoch 14/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6827 - accuracy: 0.7489
Epoch 15/100
182/182 [==============================] - 3s 14ms/step - loss: 0.6731 - accuracy: 0.7477
Epoch 16/100
182/182 [==============================] - 3s 15ms/step - loss: 0.6837 - accuracy: 0.7474
Epoch 17/100
182/182 [==============================] - 3s 14ms/step - loss: 0.6854 - accuracy: 0.7446
Epoch 18/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6732 - accuracy: 0.7464
Epoch 19/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6651 - accuracy: 0.7570
Epoch 20/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6650 - accuracy: 0.7585
Epoch 21/100
182/182 [==============================] - 2s 13ms/step - loss: 0.6585 - accuracy: 0.7567
Epoch 22/100
182/182 [==============================] - 3s 15ms/step - loss: 0.6497 - accuracy: 0.7603
Epoch 23/100
182/182 [==============================] - 3s 14ms/step - loss: 0.6687 - accuracy: 0.7567
Epoch 24/100
182/182 [==============================] - 3s 14ms/step - loss: 0.6714 - accuracy: 0.7472
Epoch 25/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6624 - accuracy: 0.7585
Epoch 26/100
182/182 [==============================] - 2s 13ms/step - loss: 0.6437 - accuracy: 0.7563
Epoch 27/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6612 - accuracy: 0.7597
Epoch 28/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6618 - accuracy: 0.7608
Epoch 29/100
182/182 [==============================] - 3s 15ms/step - loss: 0.6409 - accuracy: 0.7591
Epoch 30/100
182/182 [==============================] - 3s 15ms/step - loss: 0.6464 - accuracy: 0.7532
Epoch 31/100
182/182 [==============================] - 3s 14ms/step - loss: 0.6680 - accuracy: 0.7505
Epoch 32/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6501 - accuracy: 0.7591
Epoch 33/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6416 - accuracy: 0.7627
Epoch 34/100
182/182 [==============================] - 2s 10ms/step - loss: 0.6394 - accuracy: 0.7580
Epoch 35/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6445 - accuracy: 0.7548
Epoch 36/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6428 - accuracy: 0.7647
Epoch 37/100
182/182 [==============================] - 2s 10ms/step - loss: 0.6263 - accuracy: 0.7608
Epoch 38/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6414 - accuracy: 0.7585
Epoch 39/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6281 - accuracy: 0.7582
Epoch 40/100
182/182 [==============================] - 1s 8ms/step - loss: 0.6313 - accuracy: 0.7635
Epoch 41/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6426 - accuracy: 0.7561
Epoch 42/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6335 - accuracy: 0.7594
Epoch 43/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6361 - accuracy: 0.7635
Epoch 44/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6279 - accuracy: 0.7591
Epoch 45/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6276 - accuracy: 0.7649
Epoch 46/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6354 - accuracy: 0.7611
Epoch 47/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6252 - accuracy: 0.7652
Epoch 48/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6479 - accuracy: 0.7587
Epoch 49/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6269 - accuracy: 0.7611
Epoch 50/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6132 - accuracy: 0.7670
Epoch 51/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6067 - accuracy: 0.7647
Epoch 52/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6132 - accuracy: 0.7716
Epoch 53/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6244 - accuracy: 0.7647
Epoch 54/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6226 - accuracy: 0.7642
Epoch 55/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6524 - accuracy: 0.7539
Epoch 56/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6234 - accuracy: 0.7658
Epoch 57/100
182/182 [==============================] - 2s 9ms/step - loss: 0.6277 - accuracy: 0.7625
Epoch 58/100
182/182 [==============================] - 2s 10ms/step - loss: 0.6315 - accuracy: 0.7654
Epoch 59/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6155 - accuracy: 0.7682
Epoch 60/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6111 - accuracy: 0.7630
Epoch 61/100
182/182 [==============================] - 1s 8ms/step - loss: 0.6374 - accuracy: 0.7575
Epoch 62/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6115 - accuracy: 0.7663
Epoch 63/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6261 - accuracy: 0.7676
Epoch 64/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6153 - accuracy: 0.7661
Epoch 65/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6229 - accuracy: 0.7601
Epoch 66/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6258 - accuracy: 0.7622
Epoch 67/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6335 - accuracy: 0.7570
Epoch 68/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6152 - accuracy: 0.7671
Epoch 69/100
182/182 [==============================] - 2s 12ms/step - loss: 0.6106 - accuracy: 0.7630
Epoch 70/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6266 - accuracy: 0.7603
Epoch 71/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6122 - accuracy: 0.7683
Epoch 72/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6268 - accuracy: 0.7625
Epoch 73/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6183 - accuracy: 0.7661
Epoch 74/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6223 - accuracy: 0.7639
Epoch 75/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6221 - accuracy: 0.7627
Epoch 76/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6180 - accuracy: 0.7706
Epoch 77/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6224 - accuracy: 0.7646
Epoch 78/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6096 - accuracy: 0.7670
Epoch 79/100
182/182 [==============================] - 2s 8ms/step - loss: 0.6086 - accuracy: 0.7639
Epoch 80/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6011 - accuracy: 0.7664
Epoch 81/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6118 - accuracy: 0.7683
Epoch 82/100
182/182 [==============================] - 2s 10ms/step - loss: 0.6058 - accuracy: 0.7714
Epoch 83/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6273 - accuracy: 0.7654
Epoch 84/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6094 - accuracy: 0.7671
Epoch 85/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6164 - accuracy: 0.7671
Epoch 86/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6283 - accuracy: 0.7639
Epoch 87/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5988 - accuracy: 0.7743
Epoch 88/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5965 - accuracy: 0.7721
Epoch 89/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6316 - accuracy: 0.7620
Epoch 90/100
182/182 [==============================] - 2s 9ms/step - loss: 0.6159 - accuracy: 0.7661
Epoch 91/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6044 - accuracy: 0.7664
Epoch 92/100
182/182 [==============================] - 2s 11ms/step - loss: 0.6098 - accuracy: 0.7687
Epoch 93/100
182/182 [==============================] - 2s 9ms/step - loss: 0.6110 - accuracy: 0.7678
Epoch 94/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6102 - accuracy: 0.7682
Epoch 95/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6319 - accuracy: 0.7635
Epoch 96/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6083 - accuracy: 0.7652
Epoch 97/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6307 - accuracy: 0.7652
Epoch 98/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6154 - accuracy: 0.7687
Epoch 99/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5980 - accuracy: 0.7737
Epoch 100/100
182/182 [==============================] - 1s 7ms/step - loss: 0.6106 - accuracy: 0.7670

In [ ]:
model_2000.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2000.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
182/182 [==============================] - 4s 12ms/step - loss: 0.5866 - accuracy: 0.7754
Epoch 2/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5695 - accuracy: 0.7809
Epoch 3/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5739 - accuracy: 0.7802
Epoch 4/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5701 - accuracy: 0.7846
Epoch 5/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5743 - accuracy: 0.7779
Epoch 6/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5519 - accuracy: 0.7881
Epoch 7/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5707 - accuracy: 0.7814
Epoch 8/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5629 - accuracy: 0.7790
Epoch 9/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5556 - accuracy: 0.7877
Epoch 10/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5547 - accuracy: 0.7860
Epoch 11/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5603 - accuracy: 0.7798
Epoch 12/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5599 - accuracy: 0.7814
Epoch 13/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5516 - accuracy: 0.7845
Epoch 14/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5639 - accuracy: 0.7853
Epoch 15/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5586 - accuracy: 0.7817
Epoch 16/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5538 - accuracy: 0.7838
Epoch 17/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5668 - accuracy: 0.7805
Epoch 18/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5503 - accuracy: 0.7846
Epoch 19/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5399 - accuracy: 0.7834
Epoch 20/100
182/182 [==============================] - 2s 8ms/step - loss: 0.5600 - accuracy: 0.7810
Epoch 21/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5652 - accuracy: 0.7797
Epoch 22/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5617 - accuracy: 0.7819
Epoch 23/100
182/182 [==============================] - 2s 10ms/step - loss: 0.5510 - accuracy: 0.7915
Epoch 24/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5571 - accuracy: 0.7853
Epoch 25/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5507 - accuracy: 0.7865
Epoch 26/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5670 - accuracy: 0.7819
Epoch 27/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5621 - accuracy: 0.7840
Epoch 28/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5430 - accuracy: 0.7925
Epoch 29/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5545 - accuracy: 0.7788
Epoch 30/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5539 - accuracy: 0.7853
Epoch 31/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5511 - accuracy: 0.7867
Epoch 32/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5542 - accuracy: 0.7864
Epoch 33/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5607 - accuracy: 0.7804
Epoch 34/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5593 - accuracy: 0.7862
Epoch 35/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5496 - accuracy: 0.7924
Epoch 36/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5565 - accuracy: 0.7829
Epoch 37/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5602 - accuracy: 0.7786
Epoch 38/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5526 - accuracy: 0.7833
Epoch 39/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5510 - accuracy: 0.7888
Epoch 40/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5560 - accuracy: 0.7805
Epoch 41/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5508 - accuracy: 0.7883
Epoch 42/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5325 - accuracy: 0.7853
Epoch 43/100
182/182 [==============================] - 2s 12ms/step - loss: 0.5616 - accuracy: 0.7884
Epoch 44/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5387 - accuracy: 0.7883
Epoch 45/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5470 - accuracy: 0.7908
Epoch 46/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5574 - accuracy: 0.7846
Epoch 47/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5457 - accuracy: 0.7843
Epoch 48/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5568 - accuracy: 0.7814
Epoch 49/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5569 - accuracy: 0.7860
Epoch 50/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5463 - accuracy: 0.7857
Epoch 51/100
182/182 [==============================] - 2s 10ms/step - loss: 0.5633 - accuracy: 0.7817
Epoch 52/100
182/182 [==============================] - 2s 12ms/step - loss: 0.5493 - accuracy: 0.7876
Epoch 53/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5487 - accuracy: 0.7850
Epoch 54/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5423 - accuracy: 0.7852
Epoch 55/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5439 - accuracy: 0.7901
Epoch 56/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5324 - accuracy: 0.7910
Epoch 57/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5419 - accuracy: 0.7922
Epoch 58/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5430 - accuracy: 0.7884
Epoch 59/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5362 - accuracy: 0.7901
Epoch 60/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5553 - accuracy: 0.7871
Epoch 61/100
182/182 [==============================] - 2s 10ms/step - loss: 0.5614 - accuracy: 0.7805
Epoch 62/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5405 - accuracy: 0.7912
Epoch 63/100
182/182 [==============================] - 3s 16ms/step - loss: 0.5355 - accuracy: 0.7937
Epoch 64/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5379 - accuracy: 0.7884
Epoch 65/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5411 - accuracy: 0.7864
Epoch 66/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5538 - accuracy: 0.7883
Epoch 67/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5556 - accuracy: 0.7852
Epoch 68/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5709 - accuracy: 0.7812
Epoch 69/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5523 - accuracy: 0.7846
Epoch 70/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5562 - accuracy: 0.7828
Epoch 71/100
182/182 [==============================] - 2s 10ms/step - loss: 0.5443 - accuracy: 0.7872
Epoch 72/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5434 - accuracy: 0.7877
Epoch 73/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5323 - accuracy: 0.7955
Epoch 74/100
182/182 [==============================] - 2s 9ms/step - loss: 0.5357 - accuracy: 0.7883
Epoch 75/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5290 - accuracy: 0.7876
Epoch 76/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5527 - accuracy: 0.7829
Epoch 77/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5397 - accuracy: 0.7898
Epoch 78/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5398 - accuracy: 0.7853
Epoch 79/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5342 - accuracy: 0.7888
Epoch 80/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5371 - accuracy: 0.7962
Epoch 81/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5454 - accuracy: 0.7905
Epoch 82/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5490 - accuracy: 0.7883
Epoch 83/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5548 - accuracy: 0.7867
Epoch 84/100
182/182 [==============================] - 2s 10ms/step - loss: 0.5515 - accuracy: 0.7829
Epoch 85/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5396 - accuracy: 0.7889
Epoch 86/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5532 - accuracy: 0.7864
Epoch 87/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5471 - accuracy: 0.7824
Epoch 88/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5486 - accuracy: 0.7834
Epoch 89/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5441 - accuracy: 0.7841
Epoch 90/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5427 - accuracy: 0.7924
Epoch 91/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5364 - accuracy: 0.7895
Epoch 92/100
182/182 [==============================] - 2s 10ms/step - loss: 0.5369 - accuracy: 0.7908
Epoch 93/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5385 - accuracy: 0.7929
Epoch 94/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5464 - accuracy: 0.7841
Epoch 95/100
182/182 [==============================] - 2s 9ms/step - loss: 0.5408 - accuracy: 0.7865
Epoch 96/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5384 - accuracy: 0.7907
Epoch 97/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5415 - accuracy: 0.7962
Epoch 98/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5419 - accuracy: 0.7960
Epoch 99/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5349 - accuracy: 0.7925
Epoch 100/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5502 - accuracy: 0.7843

In [ ]:
model_2000.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2000.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
182/182 [==============================] - 3s 8ms/step - loss: 0.5247 - accuracy: 0.7953
Epoch 2/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5241 - accuracy: 0.7955
Epoch 3/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5255 - accuracy: 0.7929
Epoch 4/100
182/182 [==============================] - 2s 10ms/step - loss: 0.5264 - accuracy: 0.7919
Epoch 5/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5101 - accuracy: 0.8023
Epoch 6/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5099 - accuracy: 0.8046
Epoch 7/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4993 - accuracy: 0.8041
Epoch 8/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5155 - accuracy: 0.8004
Epoch 9/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5115 - accuracy: 0.8025
Epoch 10/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4991 - accuracy: 0.8006
Epoch 11/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5094 - accuracy: 0.7963
Epoch 12/100
182/182 [==============================] - 2s 12ms/step - loss: 0.5150 - accuracy: 0.8011
Epoch 13/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4995 - accuracy: 0.8042
Epoch 14/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5033 - accuracy: 0.7999
Epoch 15/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5043 - accuracy: 0.8039
Epoch 16/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5095 - accuracy: 0.8039
Epoch 17/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4995 - accuracy: 0.8032
Epoch 18/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5123 - accuracy: 0.8006
Epoch 19/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5142 - accuracy: 0.7987
Epoch 20/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5241 - accuracy: 0.7950
Epoch 21/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5121 - accuracy: 0.8016
Epoch 22/100
182/182 [==============================] - 2s 10ms/step - loss: 0.4994 - accuracy: 0.8010
Epoch 23/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5033 - accuracy: 0.8065
Epoch 24/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5032 - accuracy: 0.8006
Epoch 25/100
182/182 [==============================] - 1s 8ms/step - loss: 0.4984 - accuracy: 0.8025
Epoch 26/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4974 - accuracy: 0.8042
Epoch 27/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5003 - accuracy: 0.8037
Epoch 28/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4984 - accuracy: 0.8053
Epoch 29/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5073 - accuracy: 0.8044
Epoch 30/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5042 - accuracy: 0.7999
Epoch 31/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5134 - accuracy: 0.7991
Epoch 32/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5075 - accuracy: 0.7996
Epoch 33/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5075 - accuracy: 0.8006
Epoch 34/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5050 - accuracy: 0.7987
Epoch 35/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4975 - accuracy: 0.8041
Epoch 36/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5032 - accuracy: 0.8035
Epoch 37/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5053 - accuracy: 0.8027
Epoch 38/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4947 - accuracy: 0.8044
Epoch 39/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4977 - accuracy: 0.8008
Epoch 40/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5065 - accuracy: 0.8001
Epoch 41/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4997 - accuracy: 0.8022
Epoch 42/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4907 - accuracy: 0.8047
Epoch 43/100
182/182 [==============================] - 1s 8ms/step - loss: 0.5001 - accuracy: 0.8056
Epoch 44/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4959 - accuracy: 0.8082
Epoch 45/100
182/182 [==============================] - 2s 12ms/step - loss: 0.5065 - accuracy: 0.8058
Epoch 46/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4966 - accuracy: 0.8023
Epoch 47/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4958 - accuracy: 0.8030
Epoch 48/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4904 - accuracy: 0.8071
Epoch 49/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4875 - accuracy: 0.8101
Epoch 50/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4940 - accuracy: 0.8053
Epoch 51/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4959 - accuracy: 0.8070
Epoch 52/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4971 - accuracy: 0.8035
Epoch 53/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4903 - accuracy: 0.8083
Epoch 54/100
182/182 [==============================] - 2s 9ms/step - loss: 0.4853 - accuracy: 0.8087
Epoch 55/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4994 - accuracy: 0.8082
Epoch 56/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4945 - accuracy: 0.8029
Epoch 57/100
182/182 [==============================] - 2s 9ms/step - loss: 0.4937 - accuracy: 0.8059
Epoch 58/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4940 - accuracy: 0.8032
Epoch 59/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5008 - accuracy: 0.8051
Epoch 60/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5020 - accuracy: 0.8030
Epoch 61/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4919 - accuracy: 0.8010
Epoch 62/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4971 - accuracy: 0.8073
Epoch 63/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4994 - accuracy: 0.8077
Epoch 64/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4982 - accuracy: 0.8087
Epoch 65/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5035 - accuracy: 0.8020
Epoch 66/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5005 - accuracy: 0.8056
Epoch 67/100
182/182 [==============================] - 2s 12ms/step - loss: 0.5008 - accuracy: 0.8058
Epoch 68/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4898 - accuracy: 0.8066
Epoch 69/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4975 - accuracy: 0.8004
Epoch 70/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5007 - accuracy: 0.8039
Epoch 71/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4955 - accuracy: 0.8080
Epoch 72/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5001 - accuracy: 0.8025
Epoch 73/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4961 - accuracy: 0.8020
Epoch 74/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4973 - accuracy: 0.8061
Epoch 75/100
182/182 [==============================] - 2s 8ms/step - loss: 0.5029 - accuracy: 0.8061
Epoch 76/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4936 - accuracy: 0.8047
Epoch 77/100
182/182 [==============================] - 2s 12ms/step - loss: 0.4946 - accuracy: 0.8010
Epoch 78/100
182/182 [==============================] - 2s 10ms/step - loss: 0.4948 - accuracy: 0.8073
Epoch 79/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4907 - accuracy: 0.8046
Epoch 80/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4886 - accuracy: 0.8114
Epoch 81/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4998 - accuracy: 0.8013
Epoch 82/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4948 - accuracy: 0.8097
Epoch 83/100
182/182 [==============================] - 1s 7ms/step - loss: 0.5008 - accuracy: 0.8051
Epoch 84/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4940 - accuracy: 0.8054
Epoch 85/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4817 - accuracy: 0.8080
Epoch 86/100
182/182 [==============================] - 2s 9ms/step - loss: 0.4927 - accuracy: 0.8078
Epoch 87/100
182/182 [==============================] - 2s 12ms/step - loss: 0.4902 - accuracy: 0.8089
Epoch 88/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4954 - accuracy: 0.8075
Epoch 89/100
182/182 [==============================] - 2s 9ms/step - loss: 0.4960 - accuracy: 0.8034
Epoch 90/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4966 - accuracy: 0.8023
Epoch 91/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4932 - accuracy: 0.8059
Epoch 92/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4885 - accuracy: 0.8023
Epoch 93/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4976 - accuracy: 0.8044
Epoch 94/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4975 - accuracy: 0.8066
Epoch 95/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4947 - accuracy: 0.8087
Epoch 96/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4852 - accuracy: 0.8104
Epoch 97/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4953 - accuracy: 0.8092
Epoch 98/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5010 - accuracy: 0.8058
Epoch 99/100
182/182 [==============================] - 2s 11ms/step - loss: 0.5015 - accuracy: 0.7996
Epoch 100/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4941 - accuracy: 0.8049

In [ ]:
model_2000.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2000.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
182/182 [==============================] - 4s 8ms/step - loss: 0.4932 - accuracy: 0.8128
Epoch 2/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4958 - accuracy: 0.8063
Epoch 3/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4924 - accuracy: 0.8094
Epoch 4/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4930 - accuracy: 0.8083
Epoch 5/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4847 - accuracy: 0.8104
Epoch 6/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4900 - accuracy: 0.8037
Epoch 7/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4850 - accuracy: 0.8085
Epoch 8/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4861 - accuracy: 0.8063
Epoch 9/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4937 - accuracy: 0.8035
Epoch 10/100
182/182 [==============================] - 2s 12ms/step - loss: 0.4804 - accuracy: 0.8106
Epoch 11/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4895 - accuracy: 0.8106
Epoch 12/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4884 - accuracy: 0.8113
Epoch 13/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4937 - accuracy: 0.8121
Epoch 14/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4847 - accuracy: 0.8109
Epoch 15/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4885 - accuracy: 0.8070
Epoch 16/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4810 - accuracy: 0.8121
Epoch 17/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4815 - accuracy: 0.8097
Epoch 18/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4774 - accuracy: 0.8116
Epoch 19/100
182/182 [==============================] - 1s 8ms/step - loss: 0.4857 - accuracy: 0.8083
Epoch 20/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4929 - accuracy: 0.8082
Epoch 21/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4834 - accuracy: 0.8063
Epoch 22/100
182/182 [==============================] - 2s 10ms/step - loss: 0.4869 - accuracy: 0.8109
Epoch 23/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4918 - accuracy: 0.8090
Epoch 24/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4864 - accuracy: 0.8065
Epoch 25/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4965 - accuracy: 0.8065
Epoch 26/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4862 - accuracy: 0.8126
Epoch 27/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4928 - accuracy: 0.8077
Epoch 28/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4873 - accuracy: 0.8075
Epoch 29/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4849 - accuracy: 0.8094
Epoch 30/100
182/182 [==============================] - 2s 9ms/step - loss: 0.4878 - accuracy: 0.8071
Epoch 31/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4813 - accuracy: 0.8152
Epoch 32/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4836 - accuracy: 0.8111
Epoch 33/100
182/182 [==============================] - 2s 8ms/step - loss: 0.4881 - accuracy: 0.8161
Epoch 34/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4819 - accuracy: 0.8118
Epoch 35/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4896 - accuracy: 0.8087
Epoch 36/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4811 - accuracy: 0.8051
Epoch 37/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4804 - accuracy: 0.8123
Epoch 38/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4942 - accuracy: 0.8085
Epoch 39/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4952 - accuracy: 0.8094
Epoch 40/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4777 - accuracy: 0.8099
Epoch 41/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4830 - accuracy: 0.8094
Epoch 42/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4842 - accuracy: 0.8078
Epoch 43/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4837 - accuracy: 0.8109
Epoch 44/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4914 - accuracy: 0.8068
Epoch 45/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4790 - accuracy: 0.8156
Epoch 46/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4881 - accuracy: 0.8073
Epoch 47/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4929 - accuracy: 0.8061
Epoch 48/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4868 - accuracy: 0.8082
Epoch 49/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4789 - accuracy: 0.8123
Epoch 50/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4932 - accuracy: 0.8059
Epoch 51/100
182/182 [==============================] - 1s 8ms/step - loss: 0.4926 - accuracy: 0.8059
Epoch 52/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4825 - accuracy: 0.8073
Epoch 53/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4855 - accuracy: 0.8063
Epoch 54/100
182/182 [==============================] - 2s 10ms/step - loss: 0.4775 - accuracy: 0.8108
Epoch 55/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4867 - accuracy: 0.8097
Epoch 56/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4949 - accuracy: 0.8030
Epoch 57/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4860 - accuracy: 0.8080
Epoch 58/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4881 - accuracy: 0.8046
Epoch 59/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4802 - accuracy: 0.8085
Epoch 60/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4888 - accuracy: 0.8085
Epoch 61/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4874 - accuracy: 0.8078
Epoch 62/100
182/182 [==============================] - 2s 9ms/step - loss: 0.4792 - accuracy: 0.8138
Epoch 63/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4873 - accuracy: 0.8073
Epoch 64/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4828 - accuracy: 0.8109
Epoch 65/100
182/182 [==============================] - 2s 8ms/step - loss: 0.4916 - accuracy: 0.8030
Epoch 66/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4835 - accuracy: 0.8130
Epoch 67/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4776 - accuracy: 0.8089
Epoch 68/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4818 - accuracy: 0.8070
Epoch 69/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4843 - accuracy: 0.8070
Epoch 70/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4853 - accuracy: 0.8087
Epoch 71/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4881 - accuracy: 0.8089
Epoch 72/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4808 - accuracy: 0.8102
Epoch 73/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4820 - accuracy: 0.8108
Epoch 74/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4800 - accuracy: 0.8121
Epoch 75/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4896 - accuracy: 0.8118
Epoch 76/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4776 - accuracy: 0.8169
Epoch 77/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4799 - accuracy: 0.8120
Epoch 78/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4871 - accuracy: 0.8054
Epoch 79/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4866 - accuracy: 0.8089
Epoch 80/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4878 - accuracy: 0.8073
Epoch 81/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4803 - accuracy: 0.8114
Epoch 82/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4926 - accuracy: 0.8059
Epoch 83/100
182/182 [==============================] - 2s 9ms/step - loss: 0.4746 - accuracy: 0.8140
Epoch 84/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4769 - accuracy: 0.8157
Epoch 85/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4929 - accuracy: 0.8063
Epoch 86/100
182/182 [==============================] - 2s 9ms/step - loss: 0.4745 - accuracy: 0.8101
Epoch 87/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4896 - accuracy: 0.8046
Epoch 88/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4932 - accuracy: 0.8058
Epoch 89/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4835 - accuracy: 0.8101
Epoch 90/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4919 - accuracy: 0.8023
Epoch 91/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4815 - accuracy: 0.8095
Epoch 92/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4861 - accuracy: 0.8085
Epoch 93/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4904 - accuracy: 0.8104
Epoch 94/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4880 - accuracy: 0.8051
Epoch 95/100
182/182 [==============================] - 2s 11ms/step - loss: 0.4775 - accuracy: 0.8097
Epoch 96/100
182/182 [==============================] - 2s 12ms/step - loss: 0.4766 - accuracy: 0.8065
Epoch 97/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4916 - accuracy: 0.8018
Epoch 98/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4802 - accuracy: 0.8116
Epoch 99/100
182/182 [==============================] - 1s 7ms/step - loss: 0.4870 - accuracy: 0.8106
Epoch 100/100
182/182 [==============================] - 1s 8ms/step - loss: 0.4874 - accuracy: 0.8097

In [ ]:
model_2000.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2000.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

In [ ]:
model_2000.save("/content/drive/MyDrive/FYP/Trained Models/2000.keras")

In [ ]:
model2000 = tf.keras.models.load_model("/content/drive/MyDrive/FYP/Deep learning models/2000.keras")

In [ ]:
test_loss, test_accuracy = model2000.evaluate(X_train, y_train)

print(f'Training Loss of GRU: {test_loss:.4f}')
print(f'Training Accuracy of GRU: {test_accuracy:.4f}')

test_loss, test_accuracy = model2000.evaluate(x_val, y_val)

print(f'Validation Loss of GRU: {test_loss:.4f}')
print(f'Validation Accuracy of GRU: {test_accuracy:.4f}')

137/137 [==============================] - 2s 7ms/step - loss: 0.5034 - accuracy: 0.8299
Training Loss of GRU: 0.5034
Training Accuracy of GRU: 0.8299
69/69 [==============================] - 0s 6ms/step - loss: 0.4208 - accuracy: 0.8411
Validation Loss of GRU: 0.4208
Validation Accuracy of GRU: 0.8411

In [ ]:
predictions = model2000(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

0

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.8252805129379437

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.864010989010989

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2000.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2001

### Stratified sampling

In [ ]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2001, labels_2001):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2001)

numpy.ndarray

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2001[x]
    y_train = labels_2001[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2001[x]))
    y_train = np.vstack((y_train, labels_2001[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2001[x]
    y_test = labels_2001[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2001[x]))
    y_test = np.vstack((y_test, labels_2001[x]))

In [ ]:
# Second iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2001[x]
    y_train = labels_2001[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2001[x]))
    y_train = np.vstack((y_train, labels_2001[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2001[x]
    y_test = labels_2001[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2001[x]))
    y_test = np.vstack((y_test, labels_2001[x]))

In [ ]:
# Third iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2001[x]
    y_train = labels_2001[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2001[x]))
    y_train = np.vstack((y_train, labels_2001[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2001[x]
    y_test = labels_2001[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2001[x]))
    y_test = np.vstack((y_test, labels_2001[x]))

In [ ]:
y_train.shape

(5846, 1)

## Model Training 2001

In [ ]:
model_2001 = Sequential()

In [ ]:
model_2001.add(Dense(units=520, activation="relu"))
model_2001.add(Dropout(0.5))
model_2001.add(Dense(units=250, activation="relu"))
model_2001.add(Dropout(0.3))
model_2001.add(Dense(units=128, activation="relu"))
model_2001.add(Dropout(0.3))
model_2001.add(Dense(units=64, activation="relu"))
model_2001.add(Dropout(0.2))
model_2001.add(Dense(units=45, activation="relu"))
model_2001.add(Dropout(0.2))
model_2001.add(Dense(units=28, activation="relu"))
model_2001.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2001.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2001.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
183/183 [==============================] - 3s 4ms/step - loss: 2.4957 - accuracy: 0.1936
Epoch 2/100
183/183 [==============================] - 1s 4ms/step - loss: 1.8438 - accuracy: 0.3435
Epoch 3/100
183/183 [==============================] - 1s 4ms/step - loss: 1.5406 - accuracy: 0.4372
Epoch 4/100
183/183 [==============================] - 1s 4ms/step - loss: 1.3417 - accuracy: 0.4868
Epoch 5/100
183/183 [==============================] - 1s 4ms/step - loss: 1.2404 - accuracy: 0.5323
Epoch 6/100
183/183 [==============================] - 1s 4ms/step - loss: 1.1566 - accuracy: 0.5653
Epoch 7/100
183/183 [==============================] - 1s 4ms/step - loss: 1.1142 - accuracy: 0.5802
Epoch 8/100
183/183 [==============================] - 1s 4ms/step - loss: 1.0607 - accuracy: 0.6025
Epoch 9/100
183/183 [==============================] - 1s 5ms/step - loss: 1.0419 - accuracy: 0.6179
Epoch 10/100
183/183 [==============================] - 1s 5ms/step - loss: 0.9941 - accuracy: 0.6310
Epoch 11/100
183/183 [==============================] - 1s 5ms/step - loss: 0.9690 - accuracy: 0.6331
Epoch 12/100
183/183 [==============================] - 1s 5ms/step - loss: 0.9670 - accuracy: 0.6379
Epoch 13/100
183/183 [==============================] - 1s 5ms/step - loss: 0.9499 - accuracy: 0.6468
Epoch 14/100
183/183 [==============================] - 1s 4ms/step - loss: 0.9223 - accuracy: 0.6524
Epoch 15/100
183/183 [==============================] - 1s 4ms/step - loss: 0.9051 - accuracy: 0.6582
Epoch 16/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8776 - accuracy: 0.6642
Epoch 17/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8871 - accuracy: 0.6723
Epoch 18/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8598 - accuracy: 0.6731
Epoch 19/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8706 - accuracy: 0.6726
Epoch 20/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8561 - accuracy: 0.6772
Epoch 21/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8425 - accuracy: 0.6865
Epoch 22/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8534 - accuracy: 0.6829
Epoch 23/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8389 - accuracy: 0.6861
Epoch 24/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8330 - accuracy: 0.6832
Epoch 25/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8288 - accuracy: 0.6870
Epoch 26/100
183/183 [==============================] - 1s 4ms/step - loss: 0.8259 - accuracy: 0.6923
Epoch 27/100
183/183 [==============================] - 1s 5ms/step - loss: 0.8154 - accuracy: 0.6902
Epoch 28/100
183/183 [==============================] - 1s 6ms/step - loss: 0.8189 - accuracy: 0.6957
Epoch 29/100
183/183 [==============================] - 1s 5ms/step - loss: 0.7897 - accuracy: 0.7003
Epoch 30/100
183/183 [==============================] - 1s 6ms/step - loss: 0.8093 - accuracy: 0.6950
Epoch 31/100
183/183 [==============================] - 1s 5ms/step - loss: 0.8001 - accuracy: 0.6986
Epoch 32/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7947 - accuracy: 0.6960
Epoch 33/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7765 - accuracy: 0.7080
Epoch 34/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7740 - accuracy: 0.7087
Epoch 35/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7678 - accuracy: 0.7119
Epoch 36/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7739 - accuracy: 0.7053
Epoch 37/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7664 - accuracy: 0.7133
Epoch 38/100
183/183 [==============================] - 1s 5ms/step - loss: 0.7558 - accuracy: 0.7104
Epoch 39/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7776 - accuracy: 0.7092
Epoch 40/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7604 - accuracy: 0.7116
Epoch 41/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7647 - accuracy: 0.7102
Epoch 42/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7579 - accuracy: 0.7137
Epoch 43/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7454 - accuracy: 0.7196
Epoch 44/100
183/183 [==============================] - 1s 5ms/step - loss: 0.7481 - accuracy: 0.7212
Epoch 45/100
183/183 [==============================] - 1s 6ms/step - loss: 0.7468 - accuracy: 0.7195
Epoch 46/100
183/183 [==============================] - 1s 6ms/step - loss: 0.7326 - accuracy: 0.7258
Epoch 47/100
183/183 [==============================] - 1s 6ms/step - loss: 0.7459 - accuracy: 0.7176
Epoch 48/100
183/183 [==============================] - 1s 6ms/step - loss: 0.7417 - accuracy: 0.7171
Epoch 49/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7461 - accuracy: 0.7150
Epoch 50/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7248 - accuracy: 0.7261
Epoch 51/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7304 - accuracy: 0.7299
Epoch 52/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7211 - accuracy: 0.7267
Epoch 53/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7242 - accuracy: 0.7299
Epoch 54/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7020 - accuracy: 0.7296
Epoch 55/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7293 - accuracy: 0.7308
Epoch 56/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7214 - accuracy: 0.7277
Epoch 57/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7292 - accuracy: 0.7234
Epoch 58/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7037 - accuracy: 0.7311
Epoch 59/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7059 - accuracy: 0.7338
Epoch 60/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7064 - accuracy: 0.7301
Epoch 61/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7190 - accuracy: 0.7251
Epoch 62/100
183/183 [==============================] - 1s 5ms/step - loss: 0.7190 - accuracy: 0.7275
Epoch 63/100
183/183 [==============================] - 1s 5ms/step - loss: 0.7171 - accuracy: 0.7304
Epoch 64/100
183/183 [==============================] - 1s 6ms/step - loss: 0.7047 - accuracy: 0.7338
Epoch 65/100
183/183 [==============================] - 1s 5ms/step - loss: 0.7171 - accuracy: 0.7333
Epoch 66/100
183/183 [==============================] - 1s 5ms/step - loss: 0.6947 - accuracy: 0.7338
Epoch 67/100
183/183 [==============================] - 1s 4ms/step - loss: 0.7027 - accuracy: 0.7400
Epoch 68/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6885 - accuracy: 0.7381
Epoch 69/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6981 - accuracy: 0.7395
Epoch 70/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6938 - accuracy: 0.7367
Epoch 71/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6925 - accuracy: 0.7398
Epoch 72/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6843 - accuracy: 0.7427
Epoch 73/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6952 - accuracy: 0.7383
Epoch 74/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6784 - accuracy: 0.7496
Epoch 75/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6804 - accuracy: 0.7374
Epoch 76/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6929 - accuracy: 0.7381
Epoch 77/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6873 - accuracy: 0.7492
Epoch 78/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6912 - accuracy: 0.7427
Epoch 79/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6788 - accuracy: 0.7427
Epoch 80/100
183/183 [==============================] - 1s 6ms/step - loss: 0.6772 - accuracy: 0.7426
Epoch 81/100
183/183 [==============================] - 1s 6ms/step - loss: 0.6746 - accuracy: 0.7540
Epoch 82/100
183/183 [==============================] - 1s 5ms/step - loss: 0.6854 - accuracy: 0.7420
Epoch 83/100
183/183 [==============================] - 1s 5ms/step - loss: 0.6740 - accuracy: 0.7444
Epoch 84/100
183/183 [==============================] - 1s 5ms/step - loss: 0.6648 - accuracy: 0.7467
Epoch 85/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6734 - accuracy: 0.7491
Epoch 86/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6659 - accuracy: 0.7485
Epoch 87/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6952 - accuracy: 0.7385
Epoch 88/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6822 - accuracy: 0.7391
Epoch 89/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6602 - accuracy: 0.7501
Epoch 90/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6740 - accuracy: 0.7432
Epoch 91/100
183/183 [==============================] - 1s 5ms/step - loss: 0.6649 - accuracy: 0.7426
Epoch 92/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6594 - accuracy: 0.7460
Epoch 93/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6581 - accuracy: 0.7528
Epoch 94/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6650 - accuracy: 0.7465
Epoch 95/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6605 - accuracy: 0.7532
Epoch 96/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6659 - accuracy: 0.7504
Epoch 97/100
183/183 [==============================] - 1s 5ms/step - loss: 0.6738 - accuracy: 0.7492
Epoch 98/100
183/183 [==============================] - 1s 6ms/step - loss: 0.6583 - accuracy: 0.7535
Epoch 99/100
183/183 [==============================] - 1s 5ms/step - loss: 0.6681 - accuracy: 0.7513
Epoch 100/100
183/183 [==============================] - 1s 5ms/step - loss: 0.6497 - accuracy: 0.7593

In [ ]:
model_2001.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2001.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
183/183 [==============================] - 3s 4ms/step - loss: 0.6363 - accuracy: 0.7586
Epoch 2/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6162 - accuracy: 0.7653
Epoch 3/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6173 - accuracy: 0.7657
Epoch 4/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6047 - accuracy: 0.7675
Epoch 5/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6100 - accuracy: 0.7663
Epoch 6/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6110 - accuracy: 0.7708
Epoch 7/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6035 - accuracy: 0.7667
Epoch 8/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5899 - accuracy: 0.7751
Epoch 9/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6117 - accuracy: 0.7718
Epoch 10/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5988 - accuracy: 0.7763
Epoch 11/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6005 - accuracy: 0.7706
Epoch 12/100
183/183 [==============================] - 1s 5ms/step - loss: 0.6037 - accuracy: 0.7752
Epoch 13/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5984 - accuracy: 0.7749
Epoch 14/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5926 - accuracy: 0.7752
Epoch 15/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5982 - accuracy: 0.7677
Epoch 16/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5988 - accuracy: 0.7727
Epoch 17/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5916 - accuracy: 0.7710
Epoch 18/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5867 - accuracy: 0.7752
Epoch 19/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5976 - accuracy: 0.7759
Epoch 20/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5940 - accuracy: 0.7684
Epoch 21/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5900 - accuracy: 0.7759
Epoch 22/100
183/183 [==============================] - 1s 4ms/step - loss: 0.6006 - accuracy: 0.7694
Epoch 23/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5917 - accuracy: 0.7757
Epoch 24/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5939 - accuracy: 0.7740
Epoch 25/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5930 - accuracy: 0.7749
Epoch 26/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5911 - accuracy: 0.7795
Epoch 27/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5929 - accuracy: 0.7737
Epoch 28/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5959 - accuracy: 0.7757
Epoch 29/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5774 - accuracy: 0.7763
Epoch 30/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5974 - accuracy: 0.7684
Epoch 31/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5768 - accuracy: 0.7850
Epoch 32/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5891 - accuracy: 0.7778
Epoch 33/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5921 - accuracy: 0.7804
Epoch 34/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5808 - accuracy: 0.7804
Epoch 35/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5906 - accuracy: 0.7723
Epoch 36/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5762 - accuracy: 0.7819
Epoch 37/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5771 - accuracy: 0.7797
Epoch 38/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5844 - accuracy: 0.7780
Epoch 39/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5769 - accuracy: 0.7797
Epoch 40/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5766 - accuracy: 0.7795
Epoch 41/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5844 - accuracy: 0.7778
Epoch 42/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5859 - accuracy: 0.7739
Epoch 43/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5803 - accuracy: 0.7800
Epoch 44/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5822 - accuracy: 0.7781
Epoch 45/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5769 - accuracy: 0.7781
Epoch 46/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5846 - accuracy: 0.7802
Epoch 47/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5819 - accuracy: 0.7816
Epoch 48/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5854 - accuracy: 0.7800
Epoch 49/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5743 - accuracy: 0.7814
Epoch 50/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5844 - accuracy: 0.7781
Epoch 51/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5549 - accuracy: 0.7836
Epoch 52/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5772 - accuracy: 0.7788
Epoch 53/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5775 - accuracy: 0.7809
Epoch 54/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5733 - accuracy: 0.7850
Epoch 55/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5733 - accuracy: 0.7804
Epoch 56/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5735 - accuracy: 0.7797
Epoch 57/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5766 - accuracy: 0.7764
Epoch 58/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5845 - accuracy: 0.7787
Epoch 59/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5663 - accuracy: 0.7846
Epoch 60/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5635 - accuracy: 0.7863
Epoch 61/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5684 - accuracy: 0.7822
Epoch 62/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5671 - accuracy: 0.7787
Epoch 63/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5789 - accuracy: 0.7822
Epoch 64/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5666 - accuracy: 0.7826
Epoch 65/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5814 - accuracy: 0.7798
Epoch 66/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5660 - accuracy: 0.7836
Epoch 67/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5659 - accuracy: 0.7846
Epoch 68/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5590 - accuracy: 0.7857
Epoch 69/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5647 - accuracy: 0.7829
Epoch 70/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5871 - accuracy: 0.7773
Epoch 71/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5638 - accuracy: 0.7874
Epoch 72/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5665 - accuracy: 0.7834
Epoch 73/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5755 - accuracy: 0.7810
Epoch 74/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5721 - accuracy: 0.7826
Epoch 75/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5764 - accuracy: 0.7828
Epoch 76/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5681 - accuracy: 0.7834
Epoch 77/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5527 - accuracy: 0.7891
Epoch 78/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5688 - accuracy: 0.7855
Epoch 79/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5602 - accuracy: 0.7944
Epoch 80/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5641 - accuracy: 0.7838
Epoch 81/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5681 - accuracy: 0.7855
Epoch 82/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5806 - accuracy: 0.7852
Epoch 83/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5645 - accuracy: 0.7824
Epoch 84/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5652 - accuracy: 0.7812
Epoch 85/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5613 - accuracy: 0.7869
Epoch 86/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5701 - accuracy: 0.7893
Epoch 87/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5503 - accuracy: 0.7910
Epoch 88/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5680 - accuracy: 0.7879
Epoch 89/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5695 - accuracy: 0.7879
Epoch 90/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5574 - accuracy: 0.7867
Epoch 91/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5621 - accuracy: 0.7848
Epoch 92/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7882
Epoch 93/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5652 - accuracy: 0.7865
Epoch 94/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5533 - accuracy: 0.7896
Epoch 95/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7903
Epoch 96/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5620 - accuracy: 0.7833
Epoch 97/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5498 - accuracy: 0.7879
Epoch 98/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5553 - accuracy: 0.7862
Epoch 99/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5685 - accuracy: 0.7822
Epoch 100/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7923

In [ ]:
model_2001.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2001.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
183/183 [==============================] - 2s 4ms/step - loss: 0.5526 - accuracy: 0.7874
Epoch 2/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5317 - accuracy: 0.7983
Epoch 3/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5236 - accuracy: 0.7993
Epoch 4/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5259 - accuracy: 0.7980
Epoch 5/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5161 - accuracy: 0.8004
Epoch 6/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5217 - accuracy: 0.8035
Epoch 7/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.8067
Epoch 8/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5229 - accuracy: 0.8017
Epoch 9/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5226 - accuracy: 0.8009
Epoch 10/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7995
Epoch 11/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5216 - accuracy: 0.7985
Epoch 12/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.8014
Epoch 13/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.8053
Epoch 14/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.8024
Epoch 15/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5177 - accuracy: 0.8023
Epoch 16/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5143 - accuracy: 0.8023
Epoch 17/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5182 - accuracy: 0.8045
Epoch 18/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5123 - accuracy: 0.8088
Epoch 19/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.8052
Epoch 20/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5131 - accuracy: 0.8060
Epoch 21/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5182 - accuracy: 0.8000
Epoch 22/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5032 - accuracy: 0.8079
Epoch 23/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5207 - accuracy: 0.8053
Epoch 24/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.8047
Epoch 25/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.8064
Epoch 26/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.8038
Epoch 27/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.8029
Epoch 28/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.8045
Epoch 29/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5035 - accuracy: 0.8077
Epoch 30/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5116 - accuracy: 0.8048
Epoch 31/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5124 - accuracy: 0.8060
Epoch 32/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.8052
Epoch 33/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.8026
Epoch 34/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5117 - accuracy: 0.8059
Epoch 35/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.8091
Epoch 36/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5097 - accuracy: 0.8069
Epoch 37/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5162 - accuracy: 0.8045
Epoch 38/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5237 - accuracy: 0.8017
Epoch 39/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5139 - accuracy: 0.8014
Epoch 40/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.8086
Epoch 41/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.8084
Epoch 42/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.8082
Epoch 43/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.8120
Epoch 44/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.8055
Epoch 45/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.8060
Epoch 46/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.8094
Epoch 47/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.8125
Epoch 48/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.8047
Epoch 49/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5077 - accuracy: 0.8057
Epoch 50/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.8069
Epoch 51/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5045 - accuracy: 0.8069
Epoch 52/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.8137
Epoch 53/100
183/183 [==============================] - 1s 5ms/step - loss: 0.5041 - accuracy: 0.8100
Epoch 54/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5031 - accuracy: 0.8043
Epoch 55/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5099 - accuracy: 0.8105
Epoch 56/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5144 - accuracy: 0.8038
Epoch 57/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.8122
Epoch 58/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.8151
Epoch 59/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.8050
Epoch 60/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.8028
Epoch 61/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.8076
Epoch 62/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.8127
Epoch 63/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.8055
Epoch 64/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4989 - accuracy: 0.8117
Epoch 65/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.8112
Epoch 66/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.8117
Epoch 67/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.8076
Epoch 68/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.8103
Epoch 69/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.8074
Epoch 70/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5035 - accuracy: 0.8081
Epoch 71/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4955 - accuracy: 0.8144
Epoch 72/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5074 - accuracy: 0.8079
Epoch 73/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4974 - accuracy: 0.8091
Epoch 74/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.8062
Epoch 75/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.8134
Epoch 76/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5040 - accuracy: 0.8093
Epoch 77/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5071 - accuracy: 0.8118
Epoch 78/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.8135
Epoch 79/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5004 - accuracy: 0.8117
Epoch 80/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.8132
Epoch 81/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.8139
Epoch 82/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.8048
Epoch 83/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.8153
Epoch 84/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.8060
Epoch 85/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.8084
Epoch 86/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4944 - accuracy: 0.8120
Epoch 87/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4992 - accuracy: 0.8079
Epoch 88/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4998 - accuracy: 0.8048
Epoch 89/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4988 - accuracy: 0.8098
Epoch 90/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4930 - accuracy: 0.8124
Epoch 91/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4931 - accuracy: 0.8103
Epoch 92/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4963 - accuracy: 0.8139
Epoch 93/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4874 - accuracy: 0.8110
Epoch 94/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.8047
Epoch 95/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.8120
Epoch 96/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.8074
Epoch 97/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.8127
Epoch 98/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.8084
Epoch 99/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.8106
Epoch 100/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.8165

In [ ]:
model_2001.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2001.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
183/183 [==============================] - 3s 4ms/step - loss: 0.4934 - accuracy: 0.8161
Epoch 2/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.8163
Epoch 3/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4857 - accuracy: 0.8146
Epoch 4/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4899 - accuracy: 0.8113
Epoch 5/100
183/183 [==============================] - 1s 6ms/step - loss: 0.5070 - accuracy: 0.8053
Epoch 6/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4841 - accuracy: 0.8086
Epoch 7/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.8124
Epoch 8/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.8101
Epoch 9/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.8137
Epoch 10/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.8117
Epoch 11/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.8124
Epoch 12/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4841 - accuracy: 0.8122
Epoch 13/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.8115
Epoch 14/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.8103
Epoch 15/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.8100
Epoch 16/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.8106
Epoch 17/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.8173
Epoch 18/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.8151
Epoch 19/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.8089
Epoch 20/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4861 - accuracy: 0.8144
Epoch 21/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4953 - accuracy: 0.8153
Epoch 22/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4991 - accuracy: 0.8141
Epoch 23/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4891 - accuracy: 0.8159
Epoch 24/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4907 - accuracy: 0.8081
Epoch 25/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.8124
Epoch 26/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.8146
Epoch 27/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.8100
Epoch 28/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.8118
Epoch 29/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.8124
Epoch 30/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.8129
Epoch 31/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.8168
Epoch 32/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.8183
Epoch 33/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.8139
Epoch 34/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.8142
Epoch 35/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.8103
Epoch 36/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.8156
Epoch 37/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4875 - accuracy: 0.8130
Epoch 38/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4782 - accuracy: 0.8183
Epoch 39/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4973 - accuracy: 0.8076
Epoch 40/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4932 - accuracy: 0.8074
Epoch 41/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.8135
Epoch 42/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.8142
Epoch 43/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.8165
Epoch 44/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4926 - accuracy: 0.8077
Epoch 45/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.8146
Epoch 46/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4915 - accuracy: 0.8130
Epoch 47/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.8154
Epoch 48/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4902 - accuracy: 0.8144
Epoch 49/100
183/183 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.8088
Epoch 50/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.8118
Epoch 51/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4861 - accuracy: 0.8141
Epoch 52/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4867 - accuracy: 0.8144
Epoch 53/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4875 - accuracy: 0.8154
Epoch 54/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4937 - accuracy: 0.8108
Epoch 55/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4866 - accuracy: 0.8142
Epoch 56/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4954 - accuracy: 0.8103
Epoch 57/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4871 - accuracy: 0.8158
Epoch 58/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.8132
Epoch 59/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.8183
Epoch 60/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.8154
Epoch 61/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.8137
Epoch 62/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.8170
Epoch 63/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.8189
Epoch 64/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.8135
Epoch 65/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4948 - accuracy: 0.8112
Epoch 66/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4880 - accuracy: 0.8156
Epoch 67/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.8122
Epoch 68/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4844 - accuracy: 0.8113
Epoch 69/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.8178
Epoch 70/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4912 - accuracy: 0.8168
Epoch 71/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4832 - accuracy: 0.8135
Epoch 72/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4845 - accuracy: 0.8154
Epoch 73/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4914 - accuracy: 0.8103
Epoch 74/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.8130
Epoch 75/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.8161
Epoch 76/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.8168
Epoch 77/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.8178
Epoch 78/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.8175
Epoch 79/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.8209
Epoch 80/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.8151
Epoch 81/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.8091
Epoch 82/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.8094
Epoch 83/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.8124
Epoch 84/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4815 - accuracy: 0.8180
Epoch 85/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.8130
Epoch 86/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4846 - accuracy: 0.8146
Epoch 87/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4800 - accuracy: 0.8189
Epoch 88/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4826 - accuracy: 0.8163
Epoch 89/100
183/183 [==============================] - 1s 5ms/step - loss: 0.4924 - accuracy: 0.8166
Epoch 90/100
183/183 [==============================] - 1s 6ms/step - loss: 0.4859 - accuracy: 0.8135
Epoch 91/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.8098
Epoch 92/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4912 - accuracy: 0.8079
Epoch 93/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.8094
Epoch 94/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.8183
Epoch 95/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4825 - accuracy: 0.8177
Epoch 96/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.8112
Epoch 97/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4852 - accuracy: 0.8088
Epoch 98/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.8134
Epoch 99/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4824 - accuracy: 0.8127
Epoch 100/100
183/183 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.8146

In [ ]:
model_2001.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2001.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

In [ ]:
model_2001.save("/content/drive/MyDrive/FYP/Trained Models/2001.keras")

In [ ]:
model2001 = tf.keras.models.load_model("/content/drive/MyDrive/FYP/Trained Models/2001.keras")

In [ ]:
predictions = model2001(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

In [ ]:
params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.7852941176470588

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2001.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2002

### Stratified sampling

In [ ]:
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2002, labels_2002):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2002)

numpy.ndarray

In [ ]:
fold1[0]

array([ 129,  130,  131, ..., 9132, 9133, 9134])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2002[x]
    y_train = labels_2002[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2002[x]))
    y_train = np.vstack((y_train, labels_2002[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2002[x]
    y_test = labels_2002[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2002[x]))
    y_test = np.vstack((y_test, labels_2002[x]))

In [ ]:
# Second iteration of Stratified KFold for test set
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2002[x]
    y_train = labels_2002[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2002[x]))
    y_train = np.vstack((y_train, labels_2002[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2002[x]
    y_test = labels_2002[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2002[x]))
    y_test = np.vstack((y_test, labels_2002[x]))

In [ ]:
# Third iteration of Stratified KFold for training test and cross validation set
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2002[x]
    y_train = labels_2002[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2002[x]))
    y_train = np.vstack((y_train, labels_2002[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2002[x]
    y_test = labels_2002[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2002[x]))
    y_test = np.vstack((y_test, labels_2002[x]))

In [ ]:
y_train.shape

(6090, 1)

## Model Training 2002

In [ ]:
model_2002 = Sequential()

In [ ]:
model_2002.add(Dense(units=700, activation="relu"))
model_2002.add(Dropout(0.1))
model_2002.add(Dense(units=250, activation="relu"))
model_2002.add(Dropout(0.1))
model_2002.add(Dense(units=128, activation="relu"))
model_2002.add(Dropout(0.1))
model_2002.add(Dense(units=64, activation="relu"))
model_2002.add(Dropout(0.1))
model_2002.add(Dense(units=45, activation="relu"))
model_2002.add(Dropout(0.1))
model_2002.add(Dense(units=28, activation="relu"))
model_2002.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2002.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2002.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
191/191 [==============================] - 3s 4ms/step - loss: 2.2600 - accuracy: 0.2667
Epoch 2/100
191/191 [==============================] - 1s 4ms/step - loss: 1.3051 - accuracy: 0.5294
Epoch 3/100
191/191 [==============================] - 1s 4ms/step - loss: 1.1195 - accuracy: 0.5939
Epoch 4/100
191/191 [==============================] - 1s 4ms/step - loss: 0.9866 - accuracy: 0.6319
Epoch 5/100
191/191 [==============================] - 1s 4ms/step - loss: 0.9431 - accuracy: 0.6534
Epoch 6/100
191/191 [==============================] - 1s 4ms/step - loss: 0.8838 - accuracy: 0.6629
Epoch 7/100
191/191 [==============================] - 1s 4ms/step - loss: 0.8789 - accuracy: 0.6711
Epoch 8/100
191/191 [==============================] - 1s 5ms/step - loss: 0.8307 - accuracy: 0.6842
Epoch 9/100
191/191 [==============================] - 1s 6ms/step - loss: 0.8233 - accuracy: 0.6834
Epoch 10/100
191/191 [==============================] - 1s 6ms/step - loss: 0.8037 - accuracy: 0.6893
Epoch 11/100
191/191 [==============================] - 1s 6ms/step - loss: 0.7787 - accuracy: 0.6982
Epoch 12/100
191/191 [==============================] - 1s 5ms/step - loss: 0.7687 - accuracy: 0.7016
Epoch 13/100
191/191 [==============================] - 1s 4ms/step - loss: 0.7607 - accuracy: 0.7034
Epoch 14/100
191/191 [==============================] - 1s 4ms/step - loss: 0.7395 - accuracy: 0.7163
Epoch 15/100
191/191 [==============================] - 1s 4ms/step - loss: 0.7296 - accuracy: 0.7126
Epoch 16/100
191/191 [==============================] - 1s 4ms/step - loss: 0.7225 - accuracy: 0.7186
Epoch 17/100
191/191 [==============================] - 1s 4ms/step - loss: 0.7078 - accuracy: 0.7255
Epoch 18/100
191/191 [==============================] - 1s 4ms/step - loss: 0.7181 - accuracy: 0.7213
Epoch 19/100
191/191 [==============================] - 1s 4ms/step - loss: 0.7136 - accuracy: 0.7258
Epoch 20/100
191/191 [==============================] - 1s 4ms/step - loss: 0.7049 - accuracy: 0.7264
Epoch 21/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6942 - accuracy: 0.7309
Epoch 22/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6905 - accuracy: 0.7299
Epoch 23/100
191/191 [==============================] - 1s 4ms/step - loss: 0.7005 - accuracy: 0.7355
Epoch 24/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6800 - accuracy: 0.7455
Epoch 25/100
191/191 [==============================] - 1s 6ms/step - loss: 0.6733 - accuracy: 0.7365
Epoch 26/100
191/191 [==============================] - 1s 6ms/step - loss: 0.6871 - accuracy: 0.7310
Epoch 27/100
191/191 [==============================] - 1s 5ms/step - loss: 0.6626 - accuracy: 0.7402
Epoch 28/100
191/191 [==============================] - 1s 5ms/step - loss: 0.6606 - accuracy: 0.7443
Epoch 29/100
191/191 [==============================] - 1s 5ms/step - loss: 0.6453 - accuracy: 0.7504
Epoch 30/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6732 - accuracy: 0.7407
Epoch 31/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6341 - accuracy: 0.7553
Epoch 32/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6553 - accuracy: 0.7493
Epoch 33/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6417 - accuracy: 0.7450
Epoch 34/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6495 - accuracy: 0.7491
Epoch 35/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6380 - accuracy: 0.7553
Epoch 36/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6452 - accuracy: 0.7465
Epoch 37/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6504 - accuracy: 0.7489
Epoch 38/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6280 - accuracy: 0.7552
Epoch 39/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6376 - accuracy: 0.7514
Epoch 40/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6239 - accuracy: 0.7570
Epoch 41/100
191/191 [==============================] - 1s 5ms/step - loss: 0.6151 - accuracy: 0.7598
Epoch 42/100
191/191 [==============================] - 1s 5ms/step - loss: 0.6210 - accuracy: 0.7580
Epoch 43/100
191/191 [==============================] - 1s 6ms/step - loss: 0.6206 - accuracy: 0.7622
Epoch 44/100
191/191 [==============================] - 1s 5ms/step - loss: 0.6113 - accuracy: 0.7626
Epoch 45/100
191/191 [==============================] - 1s 6ms/step - loss: 0.6221 - accuracy: 0.7575
Epoch 46/100
191/191 [==============================] - 1s 5ms/step - loss: 0.6153 - accuracy: 0.7573
Epoch 47/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6007 - accuracy: 0.7665
Epoch 48/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5993 - accuracy: 0.7663
Epoch 49/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6038 - accuracy: 0.7662
Epoch 50/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6154 - accuracy: 0.7576
Epoch 51/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6180 - accuracy: 0.7588
Epoch 52/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5894 - accuracy: 0.7660
Epoch 53/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5928 - accuracy: 0.7675
Epoch 54/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5964 - accuracy: 0.7675
Epoch 55/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6095 - accuracy: 0.7642
Epoch 56/100
191/191 [==============================] - 1s 4ms/step - loss: 0.6004 - accuracy: 0.7683
Epoch 57/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5911 - accuracy: 0.7721
Epoch 58/100
191/191 [==============================] - 1s 5ms/step - loss: 0.5828 - accuracy: 0.7691
Epoch 59/100
191/191 [==============================] - 1s 5ms/step - loss: 0.5902 - accuracy: 0.7703
Epoch 60/100
191/191 [==============================] - 1s 5ms/step - loss: 0.5904 - accuracy: 0.7700
Epoch 61/100
191/191 [==============================] - 1s 6ms/step - loss: 0.5769 - accuracy: 0.7708
Epoch 62/100
191/191 [==============================] - 1s 5ms/step - loss: 0.5687 - accuracy: 0.7726
Epoch 63/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5865 - accuracy: 0.7713
Epoch 64/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5674 - accuracy: 0.7765
Epoch 65/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5705 - accuracy: 0.7772
Epoch 66/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5919 - accuracy: 0.7677
Epoch 67/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5651 - accuracy: 0.7793
Epoch 68/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5799 - accuracy: 0.7731
Epoch 69/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5726 - accuracy: 0.7700
Epoch 70/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5828 - accuracy: 0.7768
Epoch 71/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5762 - accuracy: 0.7795
Epoch 72/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5758 - accuracy: 0.7759
Epoch 73/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5587 - accuracy: 0.7837
Epoch 74/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5689 - accuracy: 0.7744
Epoch 75/100
191/191 [==============================] - 1s 5ms/step - loss: 0.5690 - accuracy: 0.7798
Epoch 76/100
191/191 [==============================] - 1s 6ms/step - loss: 0.5673 - accuracy: 0.7750
Epoch 77/100
191/191 [==============================] - 1s 5ms/step - loss: 0.5633 - accuracy: 0.7750
Epoch 78/100
191/191 [==============================] - 1s 5ms/step - loss: 0.5559 - accuracy: 0.7860
Epoch 79/100
191/191 [==============================] - 1s 5ms/step - loss: 0.5548 - accuracy: 0.7831
Epoch 80/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5523 - accuracy: 0.7803
Epoch 81/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5599 - accuracy: 0.7846
Epoch 82/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5593 - accuracy: 0.7750
Epoch 83/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5531 - accuracy: 0.7811
Epoch 84/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5785 - accuracy: 0.7759
Epoch 85/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5526 - accuracy: 0.7810
Epoch 86/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5521 - accuracy: 0.7837
Epoch 87/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5386 - accuracy: 0.7878
Epoch 88/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7829
Epoch 89/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5510 - accuracy: 0.7841
Epoch 90/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5491 - accuracy: 0.7831
Epoch 91/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5652 - accuracy: 0.7796
Epoch 92/100
191/191 [==============================] - 1s 5ms/step - loss: 0.5529 - accuracy: 0.7854
Epoch 93/100
191/191 [==============================] - 1s 6ms/step - loss: 0.5398 - accuracy: 0.7915
Epoch 94/100
191/191 [==============================] - 1s 6ms/step - loss: 0.5443 - accuracy: 0.7833
Epoch 95/100
191/191 [==============================] - 1s 5ms/step - loss: 0.5551 - accuracy: 0.7819
Epoch 96/100
191/191 [==============================] - 1s 6ms/step - loss: 0.5364 - accuracy: 0.7818
Epoch 97/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5388 - accuracy: 0.7862
Epoch 98/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5390 - accuracy: 0.7885
Epoch 99/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5432 - accuracy: 0.7872
Epoch 100/100
191/191 [==============================] - 1s 4ms/step - loss: 0.5383 - accuracy: 0.7847

In [ ]:
model_2002.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2002.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
191/191 [==============================] - 3s 4ms/step - loss: 0.5128 - accuracy: 0.7990
Epoch 2/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4906 - accuracy: 0.8053
Epoch 3/100
191/191 [==============================] - 1s 6ms/step - loss: 0.5028 - accuracy: 0.8034
Epoch 4/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4974 - accuracy: 0.7997
Epoch 5/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4927 - accuracy: 0.8059
Epoch 6/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4879 - accuracy: 0.8077
Epoch 7/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4862 - accuracy: 0.8076
Epoch 8/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.8021
Epoch 9/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.8041
Epoch 10/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4972 - accuracy: 0.8013
Epoch 11/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.8048
Epoch 12/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.8084
Epoch 13/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4897 - accuracy: 0.8057
Epoch 14/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.8108
Epoch 15/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.8079
Epoch 16/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.8054
Epoch 17/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4927 - accuracy: 0.8003
Epoch 18/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4726 - accuracy: 0.8110
Epoch 19/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.8064
Epoch 20/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4860 - accuracy: 0.8049
Epoch 21/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4842 - accuracy: 0.8059
Epoch 22/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4765 - accuracy: 0.8126
Epoch 23/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4825 - accuracy: 0.8057
Epoch 24/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.8138
Epoch 25/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.8082
Epoch 26/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4719 - accuracy: 0.8069
Epoch 27/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.8061
Epoch 28/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.8067
Epoch 29/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4751 - accuracy: 0.8053
Epoch 30/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4728 - accuracy: 0.8069
Epoch 31/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4792 - accuracy: 0.8082
Epoch 32/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4742 - accuracy: 0.8094
Epoch 33/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.8059
Epoch 34/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4692 - accuracy: 0.8105
Epoch 35/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4758 - accuracy: 0.8108
Epoch 36/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4674 - accuracy: 0.8146
Epoch 37/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4701 - accuracy: 0.8128
Epoch 38/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4699 - accuracy: 0.8156
Epoch 39/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4727 - accuracy: 0.8108
Epoch 40/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4738 - accuracy: 0.8094
Epoch 41/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4673 - accuracy: 0.8156
Epoch 42/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.8117
Epoch 43/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.8135
Epoch 44/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4706 - accuracy: 0.8095
Epoch 45/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.8092
Epoch 46/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4636 - accuracy: 0.8094
Epoch 47/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4689 - accuracy: 0.8084
Epoch 48/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4733 - accuracy: 0.8103
Epoch 49/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4668 - accuracy: 0.8141
Epoch 50/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4627 - accuracy: 0.8131
Epoch 51/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4533 - accuracy: 0.8148
Epoch 52/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4511 - accuracy: 0.8177
Epoch 53/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4774 - accuracy: 0.8120
Epoch 54/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4679 - accuracy: 0.8130
Epoch 55/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4531 - accuracy: 0.8133
Epoch 56/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4638 - accuracy: 0.8156
Epoch 57/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4588 - accuracy: 0.8144
Epoch 58/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4730 - accuracy: 0.8085
Epoch 59/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4595 - accuracy: 0.8172
Epoch 60/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.8133
Epoch 61/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.8158
Epoch 62/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.8148
Epoch 63/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.8197
Epoch 64/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4542 - accuracy: 0.8177
Epoch 65/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4583 - accuracy: 0.8125
Epoch 66/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4668 - accuracy: 0.8099
Epoch 67/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4523 - accuracy: 0.8154
Epoch 68/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.8122
Epoch 69/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4571 - accuracy: 0.8174
Epoch 70/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4603 - accuracy: 0.8154
Epoch 71/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4641 - accuracy: 0.8135
Epoch 72/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4495 - accuracy: 0.8197
Epoch 73/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4486 - accuracy: 0.8210
Epoch 74/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4654 - accuracy: 0.8110
Epoch 75/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4391 - accuracy: 0.8189
Epoch 76/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.8118
Epoch 77/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4666 - accuracy: 0.8128
Epoch 78/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.8171
Epoch 79/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4525 - accuracy: 0.8197
Epoch 80/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4474 - accuracy: 0.8176
Epoch 81/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4490 - accuracy: 0.8176
Epoch 82/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.8122
Epoch 83/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4440 - accuracy: 0.8177
Epoch 84/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4612 - accuracy: 0.8128
Epoch 85/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4519 - accuracy: 0.8179
Epoch 86/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.8148
Epoch 87/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4556 - accuracy: 0.8181
Epoch 88/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4449 - accuracy: 0.8202
Epoch 89/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4548 - accuracy: 0.8156
Epoch 90/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4586 - accuracy: 0.8186
Epoch 91/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4520 - accuracy: 0.8146
Epoch 92/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4621 - accuracy: 0.8151
Epoch 93/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.8190
Epoch 94/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.8159
Epoch 95/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.8136
Epoch 96/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4530 - accuracy: 0.8153
Epoch 97/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4417 - accuracy: 0.8176
Epoch 98/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4481 - accuracy: 0.8209
Epoch 99/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.8118
Epoch 100/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4476 - accuracy: 0.8169

In [ ]:
model_2002.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2002.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
191/191 [==============================] - 3s 4ms/step - loss: 0.4279 - accuracy: 0.8276
Epoch 2/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4173 - accuracy: 0.8325
Epoch 3/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4075 - accuracy: 0.8345
Epoch 4/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4161 - accuracy: 0.8330
Epoch 5/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4172 - accuracy: 0.8315
Epoch 6/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4105 - accuracy: 0.8294
Epoch 7/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4151 - accuracy: 0.8320
Epoch 8/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4021 - accuracy: 0.8355
Epoch 9/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4074 - accuracy: 0.8327
Epoch 10/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4207 - accuracy: 0.8307
Epoch 11/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4106 - accuracy: 0.8325
Epoch 12/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4074 - accuracy: 0.8348
Epoch 13/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4062 - accuracy: 0.8353
Epoch 14/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4107 - accuracy: 0.8342
Epoch 15/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4055 - accuracy: 0.8328
Epoch 16/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4036 - accuracy: 0.8360
Epoch 17/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4120 - accuracy: 0.8320
Epoch 18/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3957 - accuracy: 0.8399
Epoch 19/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4082 - accuracy: 0.8335
Epoch 20/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3972 - accuracy: 0.8399
Epoch 21/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3977 - accuracy: 0.8369
Epoch 22/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4015 - accuracy: 0.8353
Epoch 23/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3990 - accuracy: 0.8365
Epoch 24/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4041 - accuracy: 0.8360
Epoch 25/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4028 - accuracy: 0.8361
Epoch 26/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4060 - accuracy: 0.8378
Epoch 27/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4025 - accuracy: 0.8369
Epoch 28/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4088 - accuracy: 0.8355
Epoch 29/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4105 - accuracy: 0.8337
Epoch 30/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4032 - accuracy: 0.8397
Epoch 31/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4035 - accuracy: 0.8376
Epoch 32/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3990 - accuracy: 0.8384
Epoch 33/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3996 - accuracy: 0.8373
Epoch 34/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3961 - accuracy: 0.8389
Epoch 35/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4006 - accuracy: 0.8338
Epoch 36/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4024 - accuracy: 0.8374
Epoch 37/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4034 - accuracy: 0.8373
Epoch 38/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3887 - accuracy: 0.8389
Epoch 39/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4026 - accuracy: 0.8327
Epoch 40/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3990 - accuracy: 0.8368
Epoch 41/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3997 - accuracy: 0.8388
Epoch 42/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4039 - accuracy: 0.8360
Epoch 43/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4004 - accuracy: 0.8401
Epoch 44/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3968 - accuracy: 0.8355
Epoch 45/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4028 - accuracy: 0.8322
Epoch 46/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3960 - accuracy: 0.8415
Epoch 47/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4016 - accuracy: 0.8351
Epoch 48/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3964 - accuracy: 0.8371
Epoch 49/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3980 - accuracy: 0.8381
Epoch 50/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4051 - accuracy: 0.8355
Epoch 51/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3949 - accuracy: 0.8433
Epoch 52/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3930 - accuracy: 0.8401
Epoch 53/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3953 - accuracy: 0.8369
Epoch 54/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4043 - accuracy: 0.8291
Epoch 55/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3931 - accuracy: 0.8417
Epoch 56/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3933 - accuracy: 0.8425
Epoch 57/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3959 - accuracy: 0.8419
Epoch 58/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3983 - accuracy: 0.8346
Epoch 59/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4032 - accuracy: 0.8309
Epoch 60/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3959 - accuracy: 0.8353
Epoch 61/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3991 - accuracy: 0.8361
Epoch 62/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4035 - accuracy: 0.8363
Epoch 63/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3943 - accuracy: 0.8412
Epoch 64/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3977 - accuracy: 0.8381
Epoch 65/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3932 - accuracy: 0.8378
Epoch 66/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3912 - accuracy: 0.8389
Epoch 67/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3962 - accuracy: 0.8391
Epoch 68/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3965 - accuracy: 0.8368
Epoch 69/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3926 - accuracy: 0.8365
Epoch 70/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4056 - accuracy: 0.8333
Epoch 71/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3993 - accuracy: 0.8376
Epoch 72/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3934 - accuracy: 0.8333
Epoch 73/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3994 - accuracy: 0.8340
Epoch 74/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3957 - accuracy: 0.8348
Epoch 75/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3963 - accuracy: 0.8407
Epoch 76/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3961 - accuracy: 0.8371
Epoch 77/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3927 - accuracy: 0.8368
Epoch 78/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3940 - accuracy: 0.8376
Epoch 79/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3971 - accuracy: 0.8335
Epoch 80/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4007 - accuracy: 0.8346
Epoch 81/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3929 - accuracy: 0.8381
Epoch 82/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3933 - accuracy: 0.8412
Epoch 83/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3931 - accuracy: 0.8417
Epoch 84/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3935 - accuracy: 0.8404
Epoch 85/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3966 - accuracy: 0.8379
Epoch 86/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3890 - accuracy: 0.8437
Epoch 87/100
191/191 [==============================] - 1s 5ms/step - loss: 0.4072 - accuracy: 0.8335
Epoch 88/100
191/191 [==============================] - 1s 6ms/step - loss: 0.4015 - accuracy: 0.8365
Epoch 89/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3933 - accuracy: 0.8388
Epoch 90/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3891 - accuracy: 0.8384
Epoch 91/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3912 - accuracy: 0.8397
Epoch 92/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3938 - accuracy: 0.8412
Epoch 93/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3832 - accuracy: 0.8453
Epoch 94/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3928 - accuracy: 0.8394
Epoch 95/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3855 - accuracy: 0.8402
Epoch 96/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3960 - accuracy: 0.8432
Epoch 97/100
191/191 [==============================] - 1s 4ms/step - loss: 0.4015 - accuracy: 0.8379
Epoch 98/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3926 - accuracy: 0.8371
Epoch 99/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3920 - accuracy: 0.8346
Epoch 100/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3917 - accuracy: 0.8373

In [ ]:
model_2002.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2002.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
191/191 [==============================] - 3s 4ms/step - loss: 0.3920 - accuracy: 0.8391
Epoch 2/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3931 - accuracy: 0.8345
Epoch 3/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3920 - accuracy: 0.8378
Epoch 4/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3794 - accuracy: 0.8465
Epoch 5/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3847 - accuracy: 0.8391
Epoch 6/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3884 - accuracy: 0.8412
Epoch 7/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3850 - accuracy: 0.8389
Epoch 8/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3859 - accuracy: 0.8443
Epoch 9/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3784 - accuracy: 0.8424
Epoch 10/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3934 - accuracy: 0.8351
Epoch 11/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3892 - accuracy: 0.8401
Epoch 12/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3854 - accuracy: 0.8412
Epoch 13/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3872 - accuracy: 0.8433
Epoch 14/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3884 - accuracy: 0.8401
Epoch 15/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3829 - accuracy: 0.8448
Epoch 16/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3911 - accuracy: 0.8432
Epoch 17/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3858 - accuracy: 0.8402
Epoch 18/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3836 - accuracy: 0.8429
Epoch 19/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3883 - accuracy: 0.8399
Epoch 20/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3885 - accuracy: 0.8401
Epoch 21/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3915 - accuracy: 0.8383
Epoch 22/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3838 - accuracy: 0.8402
Epoch 23/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3854 - accuracy: 0.8392
Epoch 24/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3876 - accuracy: 0.8445
Epoch 25/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3856 - accuracy: 0.8378
Epoch 26/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3874 - accuracy: 0.8392
Epoch 27/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3880 - accuracy: 0.8417
Epoch 28/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3849 - accuracy: 0.8419
Epoch 29/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3817 - accuracy: 0.8401
Epoch 30/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3852 - accuracy: 0.8407
Epoch 31/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3783 - accuracy: 0.8397
Epoch 32/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3839 - accuracy: 0.8442
Epoch 33/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3825 - accuracy: 0.8409
Epoch 34/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3883 - accuracy: 0.8429
Epoch 35/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3853 - accuracy: 0.8412
Epoch 36/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3821 - accuracy: 0.8437
Epoch 37/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3808 - accuracy: 0.8438
Epoch 38/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3972 - accuracy: 0.8411
Epoch 39/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3836 - accuracy: 0.8443
Epoch 40/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3842 - accuracy: 0.8415
Epoch 41/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3791 - accuracy: 0.8420
Epoch 42/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3870 - accuracy: 0.8424
Epoch 43/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3898 - accuracy: 0.8411
Epoch 44/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3893 - accuracy: 0.8407
Epoch 45/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3851 - accuracy: 0.8427
Epoch 46/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3929 - accuracy: 0.8396
Epoch 47/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3831 - accuracy: 0.8430
Epoch 48/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3908 - accuracy: 0.8394
Epoch 49/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3832 - accuracy: 0.8396
Epoch 50/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3804 - accuracy: 0.8433
Epoch 51/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3853 - accuracy: 0.8412
Epoch 52/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3873 - accuracy: 0.8404
Epoch 53/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3833 - accuracy: 0.8433
Epoch 54/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3789 - accuracy: 0.8411
Epoch 55/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3828 - accuracy: 0.8386
Epoch 56/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3798 - accuracy: 0.8455
Epoch 57/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3875 - accuracy: 0.8404
Epoch 58/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3704 - accuracy: 0.8486
Epoch 59/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3832 - accuracy: 0.8425
Epoch 60/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3849 - accuracy: 0.8435
Epoch 61/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3932 - accuracy: 0.8394
Epoch 62/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3854 - accuracy: 0.8443
Epoch 63/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3865 - accuracy: 0.8384
Epoch 64/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3833 - accuracy: 0.8438
Epoch 65/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3738 - accuracy: 0.8483
Epoch 66/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3847 - accuracy: 0.8438
Epoch 67/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3866 - accuracy: 0.8402
Epoch 68/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3830 - accuracy: 0.8432
Epoch 69/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3825 - accuracy: 0.8407
Epoch 70/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3806 - accuracy: 0.8414
Epoch 71/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3848 - accuracy: 0.8424
Epoch 72/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3809 - accuracy: 0.8465
Epoch 73/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3805 - accuracy: 0.8417
Epoch 74/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3816 - accuracy: 0.8420
Epoch 75/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3870 - accuracy: 0.8420
Epoch 76/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3838 - accuracy: 0.8379
Epoch 77/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3869 - accuracy: 0.8366
Epoch 78/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3795 - accuracy: 0.8494
Epoch 79/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3818 - accuracy: 0.8445
Epoch 80/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3829 - accuracy: 0.8456
Epoch 81/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3806 - accuracy: 0.8440
Epoch 82/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3770 - accuracy: 0.8458
Epoch 83/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3800 - accuracy: 0.8438
Epoch 84/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3833 - accuracy: 0.8419
Epoch 85/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3866 - accuracy: 0.8433
Epoch 86/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3804 - accuracy: 0.8419
Epoch 87/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3832 - accuracy: 0.8453
Epoch 88/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3772 - accuracy: 0.8455
Epoch 89/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3810 - accuracy: 0.8429
Epoch 90/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3800 - accuracy: 0.8430
Epoch 91/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3799 - accuracy: 0.8447
Epoch 92/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3807 - accuracy: 0.8412
Epoch 93/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3827 - accuracy: 0.8437
Epoch 94/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3831 - accuracy: 0.8442
Epoch 95/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3772 - accuracy: 0.8468
Epoch 96/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3856 - accuracy: 0.8415
Epoch 97/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3810 - accuracy: 0.8412
Epoch 98/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3859 - accuracy: 0.8452
Epoch 99/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3837 - accuracy: 0.8406
Epoch 100/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3783 - accuracy: 0.8473

In [ ]:
model_2002.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2002.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
191/191 [==============================] - 3s 4ms/step - loss: 0.3830 - accuracy: 0.8438
Epoch 2/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3799 - accuracy: 0.8471
Epoch 3/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3831 - accuracy: 0.8468
Epoch 4/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3747 - accuracy: 0.8468
Epoch 5/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3774 - accuracy: 0.8419
Epoch 6/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3807 - accuracy: 0.8435
Epoch 7/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3757 - accuracy: 0.8445
Epoch 8/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3828 - accuracy: 0.8383
Epoch 9/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3792 - accuracy: 0.8442
Epoch 10/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3772 - accuracy: 0.8427
Epoch 11/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3746 - accuracy: 0.8478
Epoch 12/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3735 - accuracy: 0.8478
Epoch 13/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3743 - accuracy: 0.8456
Epoch 14/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3818 - accuracy: 0.8433
Epoch 15/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3822 - accuracy: 0.8417
Epoch 16/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3817 - accuracy: 0.8453
Epoch 17/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3768 - accuracy: 0.8470
Epoch 18/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3756 - accuracy: 0.8471
Epoch 19/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3778 - accuracy: 0.8473
Epoch 20/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3789 - accuracy: 0.8389
Epoch 21/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3782 - accuracy: 0.8450
Epoch 22/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3756 - accuracy: 0.8420
Epoch 23/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3807 - accuracy: 0.8432
Epoch 24/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3849 - accuracy: 0.8425
Epoch 25/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3862 - accuracy: 0.8424
Epoch 26/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3765 - accuracy: 0.8463
Epoch 27/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3787 - accuracy: 0.8476
Epoch 28/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3769 - accuracy: 0.8443
Epoch 29/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3748 - accuracy: 0.8476
Epoch 30/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3831 - accuracy: 0.8424
Epoch 31/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3792 - accuracy: 0.8391
Epoch 32/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3751 - accuracy: 0.8456
Epoch 33/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3736 - accuracy: 0.8401
Epoch 34/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3784 - accuracy: 0.8435
Epoch 35/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3731 - accuracy: 0.8435
Epoch 36/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3740 - accuracy: 0.8488
Epoch 37/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3771 - accuracy: 0.8473
Epoch 38/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3801 - accuracy: 0.8466
Epoch 39/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3739 - accuracy: 0.8442
Epoch 40/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3790 - accuracy: 0.8514
Epoch 41/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3838 - accuracy: 0.8419
Epoch 42/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3726 - accuracy: 0.8475
Epoch 43/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3789 - accuracy: 0.8422
Epoch 44/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3701 - accuracy: 0.8438
Epoch 45/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3720 - accuracy: 0.8452
Epoch 46/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3763 - accuracy: 0.8396
Epoch 47/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3817 - accuracy: 0.8427
Epoch 48/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3774 - accuracy: 0.8460
Epoch 49/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3795 - accuracy: 0.8479
Epoch 50/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3787 - accuracy: 0.8452
Epoch 51/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3727 - accuracy: 0.8479
Epoch 52/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3767 - accuracy: 0.8479
Epoch 53/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3684 - accuracy: 0.8502
Epoch 54/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3737 - accuracy: 0.8489
Epoch 55/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3759 - accuracy: 0.8425
Epoch 56/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3807 - accuracy: 0.8417
Epoch 57/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3757 - accuracy: 0.8468
Epoch 58/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3781 - accuracy: 0.8450
Epoch 59/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3752 - accuracy: 0.8445
Epoch 60/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3767 - accuracy: 0.8473
Epoch 61/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3790 - accuracy: 0.8435
Epoch 62/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3847 - accuracy: 0.8411
Epoch 63/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3721 - accuracy: 0.8453
Epoch 64/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3766 - accuracy: 0.8440
Epoch 65/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3776 - accuracy: 0.8433
Epoch 66/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3816 - accuracy: 0.8420
Epoch 67/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3836 - accuracy: 0.8437
Epoch 68/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3804 - accuracy: 0.8475
Epoch 69/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3761 - accuracy: 0.8394
Epoch 70/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3766 - accuracy: 0.8409
Epoch 71/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3775 - accuracy: 0.8476
Epoch 72/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3754 - accuracy: 0.8452
Epoch 73/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3801 - accuracy: 0.8478
Epoch 74/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3794 - accuracy: 0.8433
Epoch 75/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3756 - accuracy: 0.8447
Epoch 76/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3737 - accuracy: 0.8486
Epoch 77/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3816 - accuracy: 0.8389
Epoch 78/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3765 - accuracy: 0.8440
Epoch 79/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3749 - accuracy: 0.8430
Epoch 80/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3779 - accuracy: 0.8475
Epoch 81/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3718 - accuracy: 0.8475
Epoch 82/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3748 - accuracy: 0.8458
Epoch 83/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3704 - accuracy: 0.8468
Epoch 84/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3772 - accuracy: 0.8442
Epoch 85/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3769 - accuracy: 0.8445
Epoch 86/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3725 - accuracy: 0.8475
Epoch 87/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3760 - accuracy: 0.8452
Epoch 88/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3647 - accuracy: 0.8524
Epoch 89/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3730 - accuracy: 0.8463
Epoch 90/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3762 - accuracy: 0.8409
Epoch 91/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3764 - accuracy: 0.8476
Epoch 92/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3782 - accuracy: 0.8455
Epoch 93/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3731 - accuracy: 0.8481
Epoch 94/100
191/191 [==============================] - 1s 6ms/step - loss: 0.3785 - accuracy: 0.8447
Epoch 95/100
191/191 [==============================] - 1s 5ms/step - loss: 0.3781 - accuracy: 0.8435
Epoch 96/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3853 - accuracy: 0.8376
Epoch 97/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3754 - accuracy: 0.8491
Epoch 98/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3703 - accuracy: 0.8511
Epoch 99/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3776 - accuracy: 0.8453
Epoch 100/100
191/191 [==============================] - 1s 4ms/step - loss: 0.3804 - accuracy: 0.8447

In [ ]:
model_2002.save("/content/drive/MyDrive/FYP/Trained Models/2002.keras")

In [ ]:
predictions = model_2002(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

0

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.8239737274220033

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.7808823529411765

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2002.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2003

### Stratified sampling

In [ ]:
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2003, labels_2003):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2003)

numpy.ndarray

In [ ]:
fold1[0]

array([ 162,  163,  164, ..., 9436, 9437, 9438])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2003[x]
    y_train = labels_2003[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2003[x]))
    y_train = np.vstack((y_train, labels_2003[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2003[x]
    y_test = labels_2003[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2003[x]))
    y_test = np.vstack((y_test, labels_2003[x]))

In [ ]:
# Second iteration of Stratified KFold for test set
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2003[x]
    y_train = labels_2003[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2003[x]))
    y_train = np.vstack((y_train, labels_2003[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2003[x]
    y_test = labels_2003[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2003[x]))
    y_test = np.vstack((y_test, labels_2003[x]))

In [ ]:
# Third iteration of Stratified KFold for training test and cross validation set
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2003[x]
    y_train = labels_2003[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2003[x]))
    y_train = np.vstack((y_train, labels_2003[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2003[x]
    y_test = labels_2003[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2003[x]))
    y_test = np.vstack((y_test, labels_2003[x]))

In [ ]:
y_train.shape

(6292, 1)

## Model Training 2003

In [ ]:
model_2003 = Sequential()

In [ ]:
model_2003.add(Dense(units=700, activation="relu"))
model_2003.add(Dropout(0.5))
model_2003.add(Dense(units=250, activation="relu"))
model_2003.add(Dropout(0.5))
model_2003.add(Dense(units=128, activation="relu"))
model_2003.add(Dropout(0.5))
model_2003.add(Dense(units=64, activation="relu"))
model_2003.add(Dropout(0.3))
model_2003.add(Dense(units=45, activation="relu"))
model_2003.add(Dropout(0.2))
model_2003.add(Dense(units=28, activation="relu"))
model_2003.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2003.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2003.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
197/197 [==============================] - 3s 6ms/step - loss: 2.6925 - accuracy: 0.1373
Epoch 2/100
197/197 [==============================] - 1s 7ms/step - loss: 2.0541 - accuracy: 0.2864
Epoch 3/100
197/197 [==============================] - 1s 7ms/step - loss: 1.7730 - accuracy: 0.3600
Epoch 4/100
197/197 [==============================] - 1s 7ms/step - loss: 1.5484 - accuracy: 0.4385
Epoch 5/100
197/197 [==============================] - 1s 7ms/step - loss: 1.4103 - accuracy: 0.4835
Epoch 6/100
197/197 [==============================] - 1s 5ms/step - loss: 1.2941 - accuracy: 0.5215
Epoch 7/100
197/197 [==============================] - 1s 5ms/step - loss: 1.2043 - accuracy: 0.5542
Epoch 8/100
197/197 [==============================] - 1s 5ms/step - loss: 1.1826 - accuracy: 0.5502
Epoch 9/100
197/197 [==============================] - 1s 5ms/step - loss: 1.1222 - accuracy: 0.5709
Epoch 10/100
197/197 [==============================] - 1s 5ms/step - loss: 1.0802 - accuracy: 0.5892
Epoch 11/100
197/197 [==============================] - 1s 5ms/step - loss: 1.0817 - accuracy: 0.5917
Epoch 12/100
197/197 [==============================] - 1s 5ms/step - loss: 1.0473 - accuracy: 0.6039
Epoch 13/100
197/197 [==============================] - 1s 5ms/step - loss: 1.0289 - accuracy: 0.6128
Epoch 14/100
197/197 [==============================] - 1s 5ms/step - loss: 0.9964 - accuracy: 0.6206
Epoch 15/100
197/197 [==============================] - 1s 5ms/step - loss: 0.9942 - accuracy: 0.6221
Epoch 16/100
197/197 [==============================] - 1s 6ms/step - loss: 0.9996 - accuracy: 0.6170
Epoch 17/100
197/197 [==============================] - 1s 6ms/step - loss: 0.9689 - accuracy: 0.6324
Epoch 18/100
197/197 [==============================] - 1s 7ms/step - loss: 0.9568 - accuracy: 0.6354
Epoch 19/100
197/197 [==============================] - 1s 7ms/step - loss: 0.9366 - accuracy: 0.6424
Epoch 20/100
197/197 [==============================] - 1s 5ms/step - loss: 0.9484 - accuracy: 0.6403
Epoch 21/100
197/197 [==============================] - 1s 5ms/step - loss: 0.9432 - accuracy: 0.6375
Epoch 22/100
197/197 [==============================] - 1s 5ms/step - loss: 0.9223 - accuracy: 0.6486
Epoch 23/100
197/197 [==============================] - 1s 5ms/step - loss: 0.9169 - accuracy: 0.6558
Epoch 24/100
197/197 [==============================] - 1s 5ms/step - loss: 0.9143 - accuracy: 0.6543
Epoch 25/100
197/197 [==============================] - 1s 5ms/step - loss: 0.9015 - accuracy: 0.6616
Epoch 26/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8906 - accuracy: 0.6647
Epoch 27/100
197/197 [==============================] - 1s 5ms/step - loss: 0.9005 - accuracy: 0.6569
Epoch 28/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8868 - accuracy: 0.6651
Epoch 29/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8833 - accuracy: 0.6642
Epoch 30/100
197/197 [==============================] - 1s 6ms/step - loss: 0.8818 - accuracy: 0.6689
Epoch 31/100
197/197 [==============================] - 1s 7ms/step - loss: 0.8593 - accuracy: 0.6724
Epoch 32/100
197/197 [==============================] - 1s 7ms/step - loss: 0.8521 - accuracy: 0.6772
Epoch 33/100
197/197 [==============================] - 1s 7ms/step - loss: 0.8469 - accuracy: 0.6826
Epoch 34/100
197/197 [==============================] - 1s 7ms/step - loss: 0.8691 - accuracy: 0.6680
Epoch 35/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8458 - accuracy: 0.6887
Epoch 36/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8558 - accuracy: 0.6796
Epoch 37/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8371 - accuracy: 0.6912
Epoch 38/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8438 - accuracy: 0.6864
Epoch 39/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8469 - accuracy: 0.6818
Epoch 40/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8290 - accuracy: 0.6883
Epoch 41/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8234 - accuracy: 0.6904
Epoch 42/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8141 - accuracy: 0.6979
Epoch 43/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8321 - accuracy: 0.6907
Epoch 44/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8112 - accuracy: 0.6963
Epoch 45/100
197/197 [==============================] - 1s 6ms/step - loss: 0.8154 - accuracy: 0.6928
Epoch 46/100
197/197 [==============================] - 1s 7ms/step - loss: 0.8170 - accuracy: 0.6947
Epoch 47/100
197/197 [==============================] - 1s 7ms/step - loss: 0.8116 - accuracy: 0.6918
Epoch 48/100
197/197 [==============================] - 1s 7ms/step - loss: 0.8144 - accuracy: 0.6991
Epoch 49/100
197/197 [==============================] - 1s 6ms/step - loss: 0.8044 - accuracy: 0.7060
Epoch 50/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8169 - accuracy: 0.6977
Epoch 51/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7921 - accuracy: 0.6988
Epoch 52/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7948 - accuracy: 0.7030
Epoch 53/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7987 - accuracy: 0.7065
Epoch 54/100
197/197 [==============================] - 1s 5ms/step - loss: 0.8096 - accuracy: 0.6956
Epoch 55/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7881 - accuracy: 0.7066
Epoch 56/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7941 - accuracy: 0.6999
Epoch 57/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7878 - accuracy: 0.7071
Epoch 58/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7957 - accuracy: 0.7030
Epoch 59/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7892 - accuracy: 0.7077
Epoch 60/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7969 - accuracy: 0.7033
Epoch 61/100
197/197 [==============================] - 1s 6ms/step - loss: 0.7753 - accuracy: 0.7154
Epoch 62/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7744 - accuracy: 0.7077
Epoch 63/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7904 - accuracy: 0.7039
Epoch 64/100
197/197 [==============================] - 1s 6ms/step - loss: 0.7694 - accuracy: 0.7088
Epoch 65/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7654 - accuracy: 0.7187
Epoch 66/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7660 - accuracy: 0.7158
Epoch 67/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7749 - accuracy: 0.7120
Epoch 68/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7755 - accuracy: 0.7134
Epoch 69/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7762 - accuracy: 0.7131
Epoch 70/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7721 - accuracy: 0.7147
Epoch 71/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7843 - accuracy: 0.7123
Epoch 72/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7627 - accuracy: 0.7144
Epoch 73/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7540 - accuracy: 0.7169
Epoch 74/100
197/197 [==============================] - 1s 6ms/step - loss: 0.7427 - accuracy: 0.7204
Epoch 75/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7706 - accuracy: 0.7122
Epoch 76/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7405 - accuracy: 0.7192
Epoch 77/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7501 - accuracy: 0.7181
Epoch 78/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7642 - accuracy: 0.7187
Epoch 79/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7412 - accuracy: 0.7231
Epoch 80/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7447 - accuracy: 0.7271
Epoch 81/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7515 - accuracy: 0.7168
Epoch 82/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7616 - accuracy: 0.7176
Epoch 83/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7552 - accuracy: 0.7166
Epoch 84/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7412 - accuracy: 0.7198
Epoch 85/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7509 - accuracy: 0.7176
Epoch 86/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7571 - accuracy: 0.7182
Epoch 87/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7353 - accuracy: 0.7247
Epoch 88/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7462 - accuracy: 0.7165
Epoch 89/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7478 - accuracy: 0.7195
Epoch 90/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7352 - accuracy: 0.7154
Epoch 91/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7417 - accuracy: 0.7177
Epoch 92/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7330 - accuracy: 0.7250
Epoch 93/100
197/197 [==============================] - 1s 6ms/step - loss: 0.7364 - accuracy: 0.7214
Epoch 94/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7307 - accuracy: 0.7209
Epoch 95/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7455 - accuracy: 0.7203
Epoch 96/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7519 - accuracy: 0.7236
Epoch 97/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7224 - accuracy: 0.7311
Epoch 98/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7428 - accuracy: 0.7231
Epoch 99/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7265 - accuracy: 0.7268
Epoch 100/100
197/197 [==============================] - 1s 7ms/step - loss: 0.7406 - accuracy: 0.7203

In [ ]:
model_2003.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2003.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
197/197 [==============================] - 3s 5ms/step - loss: 0.7008 - accuracy: 0.7363
Epoch 2/100
197/197 [==============================] - 1s 4ms/step - loss: 0.6935 - accuracy: 0.7371
Epoch 3/100
197/197 [==============================] - 1s 5ms/step - loss: 0.7031 - accuracy: 0.7327
Epoch 4/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6845 - accuracy: 0.7390
Epoch 5/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6910 - accuracy: 0.7405
Epoch 6/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6864 - accuracy: 0.7440
Epoch 7/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6785 - accuracy: 0.7503
Epoch 8/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6710 - accuracy: 0.7444
Epoch 9/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6888 - accuracy: 0.7416
Epoch 10/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6841 - accuracy: 0.7435
Epoch 11/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6747 - accuracy: 0.7400
Epoch 12/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6712 - accuracy: 0.7481
Epoch 13/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6638 - accuracy: 0.7514
Epoch 14/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6817 - accuracy: 0.7368
Epoch 15/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6768 - accuracy: 0.7428
Epoch 16/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6746 - accuracy: 0.7467
Epoch 17/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6617 - accuracy: 0.7498
Epoch 18/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6718 - accuracy: 0.7452
Epoch 19/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6764 - accuracy: 0.7376
Epoch 20/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6714 - accuracy: 0.7435
Epoch 21/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6665 - accuracy: 0.7517
Epoch 22/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6681 - accuracy: 0.7449
Epoch 23/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6713 - accuracy: 0.7470
Epoch 24/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6568 - accuracy: 0.7465
Epoch 25/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6604 - accuracy: 0.7440
Epoch 26/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6705 - accuracy: 0.7457
Epoch 27/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6577 - accuracy: 0.7479
Epoch 28/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6773 - accuracy: 0.7490
Epoch 29/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6706 - accuracy: 0.7421
Epoch 30/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6640 - accuracy: 0.7519
Epoch 31/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6682 - accuracy: 0.7510
Epoch 32/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6520 - accuracy: 0.7556
Epoch 33/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6679 - accuracy: 0.7454
Epoch 34/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6665 - accuracy: 0.7481
Epoch 35/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6591 - accuracy: 0.7564
Epoch 36/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6538 - accuracy: 0.7535
Epoch 37/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6614 - accuracy: 0.7537
Epoch 38/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6593 - accuracy: 0.7583
Epoch 39/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6577 - accuracy: 0.7541
Epoch 40/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6510 - accuracy: 0.7540
Epoch 41/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6585 - accuracy: 0.7487
Epoch 42/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6534 - accuracy: 0.7524
Epoch 43/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6462 - accuracy: 0.7600
Epoch 44/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6673 - accuracy: 0.7522
Epoch 45/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6551 - accuracy: 0.7527
Epoch 46/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6552 - accuracy: 0.7506
Epoch 47/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6464 - accuracy: 0.7546
Epoch 48/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6479 - accuracy: 0.7572
Epoch 49/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6642 - accuracy: 0.7537
Epoch 50/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6674 - accuracy: 0.7556
Epoch 51/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6453 - accuracy: 0.7606
Epoch 52/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6482 - accuracy: 0.7537
Epoch 53/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6452 - accuracy: 0.7570
Epoch 54/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6503 - accuracy: 0.7603
Epoch 55/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6480 - accuracy: 0.7545
Epoch 56/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6361 - accuracy: 0.7626
Epoch 57/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6505 - accuracy: 0.7517
Epoch 58/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6487 - accuracy: 0.7568
Epoch 59/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6342 - accuracy: 0.7564
Epoch 60/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6378 - accuracy: 0.7646
Epoch 61/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6507 - accuracy: 0.7530
Epoch 62/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6458 - accuracy: 0.7540
Epoch 63/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6472 - accuracy: 0.7551
Epoch 64/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6463 - accuracy: 0.7541
Epoch 65/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6573 - accuracy: 0.7530
Epoch 66/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6584 - accuracy: 0.7533
Epoch 67/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6456 - accuracy: 0.7552
Epoch 68/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6449 - accuracy: 0.7530
Epoch 69/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6383 - accuracy: 0.7595
Epoch 70/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6433 - accuracy: 0.7630
Epoch 71/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6408 - accuracy: 0.7567
Epoch 72/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6526 - accuracy: 0.7549
Epoch 73/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6400 - accuracy: 0.7545
Epoch 74/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6455 - accuracy: 0.7552
Epoch 75/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6390 - accuracy: 0.7584
Epoch 76/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6292 - accuracy: 0.7670
Epoch 77/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6456 - accuracy: 0.7570
Epoch 78/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6274 - accuracy: 0.7638
Epoch 79/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6370 - accuracy: 0.7581
Epoch 80/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6306 - accuracy: 0.7603
Epoch 81/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6321 - accuracy: 0.7626
Epoch 82/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6420 - accuracy: 0.7589
Epoch 83/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6400 - accuracy: 0.7610
Epoch 84/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6413 - accuracy: 0.7591
Epoch 85/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6399 - accuracy: 0.7619
Epoch 86/100
197/197 [==============================] - 1s 7ms/step - loss: 0.6288 - accuracy: 0.7645
Epoch 87/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6258 - accuracy: 0.7643
Epoch 88/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6303 - accuracy: 0.7602
Epoch 89/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6275 - accuracy: 0.7651
Epoch 90/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6275 - accuracy: 0.7554
Epoch 91/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6237 - accuracy: 0.7700
Epoch 92/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6381 - accuracy: 0.7622
Epoch 93/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6384 - accuracy: 0.7610
Epoch 94/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6222 - accuracy: 0.7641
Epoch 95/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6372 - accuracy: 0.7630
Epoch 96/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6324 - accuracy: 0.7592
Epoch 97/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6284 - accuracy: 0.7624
Epoch 98/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6274 - accuracy: 0.7649
Epoch 99/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6267 - accuracy: 0.7659
Epoch 100/100
197/197 [==============================] - 1s 6ms/step - loss: 0.6278 - accuracy: 0.7653

In [ ]:
model_2003.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2003.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
197/197 [==============================] - 3s 5ms/step - loss: 0.6095 - accuracy: 0.7678
Epoch 2/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6006 - accuracy: 0.7783
Epoch 3/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6042 - accuracy: 0.7730
Epoch 4/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6043 - accuracy: 0.7713
Epoch 5/100
197/197 [==============================] - 1s 5ms/step - loss: 0.6000 - accuracy: 0.7710
Epoch 6/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5871 - accuracy: 0.7761
Epoch 7/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5956 - accuracy: 0.7792
Epoch 8/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5949 - accuracy: 0.7767
Epoch 9/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5951 - accuracy: 0.7751
Epoch 10/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5924 - accuracy: 0.7780
Epoch 11/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5916 - accuracy: 0.7778
Epoch 12/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5949 - accuracy: 0.7716
Epoch 13/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5975 - accuracy: 0.7762
Epoch 14/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5987 - accuracy: 0.7767
Epoch 15/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5859 - accuracy: 0.7794
Epoch 16/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5802 - accuracy: 0.7796
Epoch 17/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5822 - accuracy: 0.7797
Epoch 18/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5900 - accuracy: 0.7807
Epoch 19/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5735 - accuracy: 0.7864
Epoch 20/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5866 - accuracy: 0.7783
Epoch 21/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5804 - accuracy: 0.7810
Epoch 22/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5719 - accuracy: 0.7853
Epoch 23/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5850 - accuracy: 0.7767
Epoch 24/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5884 - accuracy: 0.7730
Epoch 25/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5769 - accuracy: 0.7846
Epoch 26/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5844 - accuracy: 0.7764
Epoch 27/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5833 - accuracy: 0.7788
Epoch 28/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5789 - accuracy: 0.7791
Epoch 29/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5815 - accuracy: 0.7778
Epoch 30/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5837 - accuracy: 0.7786
Epoch 31/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5848 - accuracy: 0.7754
Epoch 32/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5798 - accuracy: 0.7800
Epoch 33/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5792 - accuracy: 0.7770
Epoch 34/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5842 - accuracy: 0.7834
Epoch 35/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5867 - accuracy: 0.7815
Epoch 36/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5809 - accuracy: 0.7829
Epoch 37/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5776 - accuracy: 0.7812
Epoch 38/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5864 - accuracy: 0.7769
Epoch 39/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5858 - accuracy: 0.7808
Epoch 40/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5734 - accuracy: 0.7851
Epoch 41/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5803 - accuracy: 0.7808
Epoch 42/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5788 - accuracy: 0.7805
Epoch 43/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5781 - accuracy: 0.7788
Epoch 44/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5788 - accuracy: 0.7831
Epoch 45/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5719 - accuracy: 0.7840
Epoch 46/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5726 - accuracy: 0.7792
Epoch 47/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5824 - accuracy: 0.7807
Epoch 48/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5791 - accuracy: 0.7835
Epoch 49/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5687 - accuracy: 0.7837
Epoch 50/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5809 - accuracy: 0.7813
Epoch 51/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5728 - accuracy: 0.7905
Epoch 52/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5695 - accuracy: 0.7851
Epoch 53/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5665 - accuracy: 0.7848
Epoch 54/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5782 - accuracy: 0.7824
Epoch 55/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5864 - accuracy: 0.7832
Epoch 56/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5772 - accuracy: 0.7834
Epoch 57/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5711 - accuracy: 0.7834
Epoch 58/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5830 - accuracy: 0.7764
Epoch 59/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5734 - accuracy: 0.7794
Epoch 60/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5732 - accuracy: 0.7808
Epoch 61/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5862 - accuracy: 0.7853
Epoch 62/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5758 - accuracy: 0.7840
Epoch 63/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5605 - accuracy: 0.7870
Epoch 64/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5684 - accuracy: 0.7864
Epoch 65/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5591 - accuracy: 0.7888
Epoch 66/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5819 - accuracy: 0.7757
Epoch 67/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5531 - accuracy: 0.7931
Epoch 68/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5681 - accuracy: 0.7866
Epoch 69/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5747 - accuracy: 0.7872
Epoch 70/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5834 - accuracy: 0.7859
Epoch 71/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5761 - accuracy: 0.7832
Epoch 72/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5777 - accuracy: 0.7837
Epoch 73/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5737 - accuracy: 0.7862
Epoch 74/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5711 - accuracy: 0.7843
Epoch 75/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5780 - accuracy: 0.7831
Epoch 76/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5753 - accuracy: 0.7816
Epoch 77/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5546 - accuracy: 0.7923
Epoch 78/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5736 - accuracy: 0.7843
Epoch 79/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5790 - accuracy: 0.7799
Epoch 80/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5695 - accuracy: 0.7880
Epoch 81/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5785 - accuracy: 0.7850
Epoch 82/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5785 - accuracy: 0.7869
Epoch 83/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5751 - accuracy: 0.7840
Epoch 84/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5666 - accuracy: 0.7856
Epoch 85/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5725 - accuracy: 0.7899
Epoch 86/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5659 - accuracy: 0.7896
Epoch 87/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5626 - accuracy: 0.7845
Epoch 88/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5754 - accuracy: 0.7858
Epoch 89/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5619 - accuracy: 0.7862
Epoch 90/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5998 - accuracy: 0.7783
Epoch 91/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5663 - accuracy: 0.7897
Epoch 92/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5737 - accuracy: 0.7875
Epoch 93/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5599 - accuracy: 0.7854
Epoch 94/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5716 - accuracy: 0.7851
Epoch 95/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5594 - accuracy: 0.7940
Epoch 96/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5708 - accuracy: 0.7845
Epoch 97/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5745 - accuracy: 0.7834
Epoch 98/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5756 - accuracy: 0.7818
Epoch 99/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5643 - accuracy: 0.7875
Epoch 100/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5595 - accuracy: 0.7886

In [ ]:
model_2003.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2003.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
197/197 [==============================] - 4s 4ms/step - loss: 0.5692 - accuracy: 0.7901
Epoch 2/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5602 - accuracy: 0.7886
Epoch 3/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5509 - accuracy: 0.7942
Epoch 4/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5676 - accuracy: 0.7873
Epoch 5/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5591 - accuracy: 0.7870
Epoch 6/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5525 - accuracy: 0.7962
Epoch 7/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5683 - accuracy: 0.7886
Epoch 8/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5817 - accuracy: 0.7908
Epoch 9/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5640 - accuracy: 0.7926
Epoch 10/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5536 - accuracy: 0.7951
Epoch 11/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5644 - accuracy: 0.7885
Epoch 12/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5580 - accuracy: 0.7921
Epoch 13/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5459 - accuracy: 0.7951
Epoch 14/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5605 - accuracy: 0.7923
Epoch 15/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5575 - accuracy: 0.7950
Epoch 16/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5538 - accuracy: 0.7902
Epoch 17/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5512 - accuracy: 0.7953
Epoch 18/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5583 - accuracy: 0.7905
Epoch 19/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5569 - accuracy: 0.7883
Epoch 20/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5523 - accuracy: 0.7926
Epoch 21/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5576 - accuracy: 0.7910
Epoch 22/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5582 - accuracy: 0.7929
Epoch 23/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5463 - accuracy: 0.7904
Epoch 24/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5604 - accuracy: 0.7916
Epoch 25/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7977
Epoch 26/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5601 - accuracy: 0.7962
Epoch 27/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5578 - accuracy: 0.7918
Epoch 28/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5555 - accuracy: 0.7924
Epoch 29/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5551 - accuracy: 0.7924
Epoch 30/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5545 - accuracy: 0.7902
Epoch 31/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5480 - accuracy: 0.7921
Epoch 32/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5453 - accuracy: 0.7970
Epoch 33/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5623 - accuracy: 0.7937
Epoch 34/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5536 - accuracy: 0.7902
Epoch 35/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5495 - accuracy: 0.7956
Epoch 36/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5448 - accuracy: 0.7975
Epoch 37/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5563 - accuracy: 0.7897
Epoch 38/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5586 - accuracy: 0.7889
Epoch 39/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5583 - accuracy: 0.7932
Epoch 40/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5536 - accuracy: 0.7939
Epoch 41/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5541 - accuracy: 0.7908
Epoch 42/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5444 - accuracy: 0.7956
Epoch 43/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5514 - accuracy: 0.7978
Epoch 44/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5507 - accuracy: 0.7951
Epoch 45/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5608 - accuracy: 0.7964
Epoch 46/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5523 - accuracy: 0.7951
Epoch 47/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5585 - accuracy: 0.7897
Epoch 48/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5463 - accuracy: 0.7932
Epoch 49/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5395 - accuracy: 0.7978
Epoch 50/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5553 - accuracy: 0.7929
Epoch 51/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5563 - accuracy: 0.7926
Epoch 52/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5567 - accuracy: 0.7893
Epoch 53/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5455 - accuracy: 0.7928
Epoch 54/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7953
Epoch 55/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5625 - accuracy: 0.7867
Epoch 56/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5552 - accuracy: 0.7990
Epoch 57/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5506 - accuracy: 0.7920
Epoch 58/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5504 - accuracy: 0.7924
Epoch 59/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5493 - accuracy: 0.7929
Epoch 60/100
197/197 [==============================] - 2s 8ms/step - loss: 0.5586 - accuracy: 0.7920
Epoch 61/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5493 - accuracy: 0.7964
Epoch 62/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5513 - accuracy: 0.7964
Epoch 63/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5486 - accuracy: 0.7945
Epoch 64/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5442 - accuracy: 0.7932
Epoch 65/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7953
Epoch 66/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7945
Epoch 67/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.8015
Epoch 68/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5474 - accuracy: 0.7934
Epoch 69/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5491 - accuracy: 0.7947
Epoch 70/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5515 - accuracy: 0.7969
Epoch 71/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5581 - accuracy: 0.7942
Epoch 72/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5448 - accuracy: 0.7966
Epoch 73/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5507 - accuracy: 0.7953
Epoch 74/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5638 - accuracy: 0.7862
Epoch 75/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5405 - accuracy: 0.7969
Epoch 76/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5453 - accuracy: 0.7948
Epoch 77/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5532 - accuracy: 0.7948
Epoch 78/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5527 - accuracy: 0.7908
Epoch 79/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5480 - accuracy: 0.7926
Epoch 80/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5463 - accuracy: 0.7924
Epoch 81/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5410 - accuracy: 0.7970
Epoch 82/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5526 - accuracy: 0.7932
Epoch 83/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5600 - accuracy: 0.7932
Epoch 84/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5504 - accuracy: 0.7962
Epoch 85/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5396 - accuracy: 0.8002
Epoch 86/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5531 - accuracy: 0.7921
Epoch 87/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5549 - accuracy: 0.7961
Epoch 88/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5529 - accuracy: 0.7908
Epoch 89/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5598 - accuracy: 0.7908
Epoch 90/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5456 - accuracy: 0.7974
Epoch 91/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5564 - accuracy: 0.7923
Epoch 92/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5468 - accuracy: 0.7942
Epoch 93/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5432 - accuracy: 0.7945
Epoch 94/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5496 - accuracy: 0.7950
Epoch 95/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5381 - accuracy: 0.7974
Epoch 96/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5521 - accuracy: 0.7908
Epoch 97/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5566 - accuracy: 0.7928
Epoch 98/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5536 - accuracy: 0.7913
Epoch 99/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7966
Epoch 100/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5505 - accuracy: 0.7931

In [ ]:
model_2003.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2003.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
197/197 [==============================] - 4s 6ms/step - loss: 0.5525 - accuracy: 0.7924
Epoch 2/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5588 - accuracy: 0.7953
Epoch 3/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5598 - accuracy: 0.7943
Epoch 4/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5441 - accuracy: 0.8015
Epoch 5/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5480 - accuracy: 0.7943
Epoch 6/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5602 - accuracy: 0.7939
Epoch 7/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5423 - accuracy: 0.7975
Epoch 8/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5376 - accuracy: 0.7972
Epoch 9/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5533 - accuracy: 0.7943
Epoch 10/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5465 - accuracy: 0.7962
Epoch 11/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5477 - accuracy: 0.7961
Epoch 12/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5412 - accuracy: 0.7931
Epoch 13/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5534 - accuracy: 0.7942
Epoch 14/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5539 - accuracy: 0.7918
Epoch 15/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5343 - accuracy: 0.8020
Epoch 16/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5459 - accuracy: 0.7939
Epoch 17/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5530 - accuracy: 0.7901
Epoch 18/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5516 - accuracy: 0.7932
Epoch 19/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5517 - accuracy: 0.7982
Epoch 20/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5449 - accuracy: 0.7969
Epoch 21/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7920
Epoch 22/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7972
Epoch 23/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5526 - accuracy: 0.7945
Epoch 24/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5590 - accuracy: 0.7913
Epoch 25/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5473 - accuracy: 0.7953
Epoch 26/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7923
Epoch 27/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5378 - accuracy: 0.8002
Epoch 28/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5404 - accuracy: 0.7974
Epoch 29/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5400 - accuracy: 0.8007
Epoch 30/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5540 - accuracy: 0.7926
Epoch 31/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5428 - accuracy: 0.7959
Epoch 32/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5484 - accuracy: 0.7910
Epoch 33/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5472 - accuracy: 0.7921
Epoch 34/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5519 - accuracy: 0.7893
Epoch 35/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5517 - accuracy: 0.7955
Epoch 36/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5478 - accuracy: 0.7942
Epoch 37/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5429 - accuracy: 0.7907
Epoch 38/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5454 - accuracy: 0.7959
Epoch 39/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5485 - accuracy: 0.7974
Epoch 40/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5406 - accuracy: 0.7955
Epoch 41/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7951
Epoch 42/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5477 - accuracy: 0.7966
Epoch 43/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5416 - accuracy: 0.7945
Epoch 44/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5408 - accuracy: 0.7945
Epoch 45/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5446 - accuracy: 0.7935
Epoch 46/100
197/197 [==============================] - 1s 7ms/step - loss: 0.5505 - accuracy: 0.7894
Epoch 47/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5450 - accuracy: 0.8005
Epoch 48/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5403 - accuracy: 0.7955
Epoch 49/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7942
Epoch 50/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7918
Epoch 51/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5503 - accuracy: 0.7931
Epoch 52/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7947
Epoch 53/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7966
Epoch 54/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5410 - accuracy: 0.7962
Epoch 55/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5751 - accuracy: 0.7977
Epoch 56/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5456 - accuracy: 0.7970
Epoch 57/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5491 - accuracy: 0.7924
Epoch 58/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5388 - accuracy: 0.7928
Epoch 59/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5435 - accuracy: 0.7964
Epoch 60/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5371 - accuracy: 0.7991
Epoch 61/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5424 - accuracy: 0.7945
Epoch 62/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7962
Epoch 63/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7934
Epoch 64/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5422 - accuracy: 0.7961
Epoch 65/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5482 - accuracy: 0.7937
Epoch 66/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5406 - accuracy: 0.7999
Epoch 67/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5470 - accuracy: 0.7964
Epoch 68/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5423 - accuracy: 0.7986
Epoch 69/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7985
Epoch 70/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5399 - accuracy: 0.7985
Epoch 71/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5420 - accuracy: 0.8002
Epoch 72/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.8002
Epoch 73/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5464 - accuracy: 0.7943
Epoch 74/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5342 - accuracy: 0.8010
Epoch 75/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5488 - accuracy: 0.7996
Epoch 76/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5320 - accuracy: 0.8002
Epoch 77/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5521 - accuracy: 0.7955
Epoch 78/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5381 - accuracy: 0.8007
Epoch 79/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5532 - accuracy: 0.7970
Epoch 80/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7966
Epoch 81/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5340 - accuracy: 0.7978
Epoch 82/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7970
Epoch 83/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5456 - accuracy: 0.7897
Epoch 84/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5511 - accuracy: 0.7931
Epoch 85/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5450 - accuracy: 0.7982
Epoch 86/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5471 - accuracy: 0.7942
Epoch 87/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.8010
Epoch 88/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5502 - accuracy: 0.7928
Epoch 89/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5487 - accuracy: 0.7959
Epoch 90/100
197/197 [==============================] - 1s 6ms/step - loss: 0.5426 - accuracy: 0.8015
Epoch 91/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5451 - accuracy: 0.8009
Epoch 92/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5431 - accuracy: 0.7994
Epoch 93/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7908
Epoch 94/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7978
Epoch 95/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5397 - accuracy: 0.7975
Epoch 96/100
197/197 [==============================] - 1s 5ms/step - loss: 0.5392 - accuracy: 0.8029
Epoch 97/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5483 - accuracy: 0.7929
Epoch 98/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5427 - accuracy: 0.7972
Epoch 99/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5493 - accuracy: 0.7902
Epoch 100/100
197/197 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7974

In [ ]:
model_2003.save("/content/drive/MyDrive/FYP/Trained Models/2003.keras")

In [ ]:
predictions = model_2003(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

0

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.815379726723864

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.8

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2003.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2004

### Stratified sampling

In [ ]:
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2004, labels_2004):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2004)

numpy.ndarray

In [ ]:
fold1[0]

array([ 126,  127,  128, ..., 9023, 9024, 9025])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2004[x]
    y_train = labels_2004[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2004[x]))
    y_train = np.vstack((y_train, labels_2004[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2004[x]
    y_test = labels_2004[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2004[x]))
    y_test = np.vstack((y_test, labels_2004[x]))

In [ ]:
# Second iteration of Stratified KFold for test set
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2004[x]
    y_train = labels_2004[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2004[x]))
    y_train = np.vstack((y_train, labels_2004[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2004[x]
    y_test = labels_2004[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2004[x]))
    y_test = np.vstack((y_test, labels_2004[x]))

In [ ]:
# Third iteration of Stratified KFold for training test and cross validation set
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2004[x]
    y_train = labels_2004[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2004[x]))
    y_train = np.vstack((y_train, labels_2004[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2004[x]
    y_test = labels_2004[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2004[x]))
    y_test = np.vstack((y_test, labels_2004[x]))

In [ ]:
y_train.shape

(6017, 1)

## Model Training 2004

In [ ]:
model_2004 = Sequential()

In [ ]:
model_2004.add(Dense(units=700, activation="relu"))
model_2004.add(Dropout(0.5))
model_2004.add(Dense(units=250, activation="relu"))
model_2004.add(Dropout(0.5))
model_2004.add(Dense(units=128, activation="relu"))
model_2004.add(Dropout(0.5))
model_2004.add(Dense(units=64, activation="relu"))
model_2004.add(Dropout(0.3))
model_2004.add(Dense(units=45, activation="relu"))
model_2004.add(Dropout(0.2))
model_2004.add(Dense(units=28, activation="relu"))
model_2004.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2004.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2004.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
189/189 [==============================] - 5s 7ms/step - loss: 2.7006 - accuracy: 0.1421
Epoch 2/100
189/189 [==============================] - 1s 5ms/step - loss: 2.1448 - accuracy: 0.2531
Epoch 3/100
189/189 [==============================] - 1s 5ms/step - loss: 1.9304 - accuracy: 0.3061
Epoch 4/100
189/189 [==============================] - 1s 5ms/step - loss: 1.7932 - accuracy: 0.3533
Epoch 5/100
189/189 [==============================] - 1s 5ms/step - loss: 1.6525 - accuracy: 0.3962
Epoch 6/100
189/189 [==============================] - 1s 5ms/step - loss: 1.5433 - accuracy: 0.4294
Epoch 7/100
189/189 [==============================] - 1s 5ms/step - loss: 1.4578 - accuracy: 0.4629
Epoch 8/100
189/189 [==============================] - 1s 5ms/step - loss: 1.4381 - accuracy: 0.4742
Epoch 9/100
189/189 [==============================] - 1s 5ms/step - loss: 1.3555 - accuracy: 0.5086
Epoch 10/100
189/189 [==============================] - 1s 5ms/step - loss: 1.2776 - accuracy: 0.5205
Epoch 11/100
189/189 [==============================] - 1s 4ms/step - loss: 1.2500 - accuracy: 0.5333
Epoch 12/100
189/189 [==============================] - 1s 4ms/step - loss: 1.2222 - accuracy: 0.5484
Epoch 13/100
189/189 [==============================] - 1s 5ms/step - loss: 1.1928 - accuracy: 0.5612
Epoch 14/100
189/189 [==============================] - 1s 6ms/step - loss: 1.1679 - accuracy: 0.5701
Epoch 15/100
189/189 [==============================] - 1s 6ms/step - loss: 1.1200 - accuracy: 0.5797
Epoch 16/100
189/189 [==============================] - 1s 6ms/step - loss: 1.1302 - accuracy: 0.5799
Epoch 17/100
189/189 [==============================] - 1s 6ms/step - loss: 1.0952 - accuracy: 0.5927
Epoch 18/100
189/189 [==============================] - 1s 5ms/step - loss: 1.1025 - accuracy: 0.5903
Epoch 19/100
189/189 [==============================] - 1s 4ms/step - loss: 1.0997 - accuracy: 0.5963
Epoch 20/100
189/189 [==============================] - 1s 5ms/step - loss: 1.0713 - accuracy: 0.6023
Epoch 21/100
189/189 [==============================] - 1s 5ms/step - loss: 1.0577 - accuracy: 0.6084
Epoch 22/100
189/189 [==============================] - 1s 5ms/step - loss: 1.0557 - accuracy: 0.6124
Epoch 23/100
189/189 [==============================] - 1s 5ms/step - loss: 1.0320 - accuracy: 0.6181
Epoch 24/100
189/189 [==============================] - 1s 5ms/step - loss: 1.0123 - accuracy: 0.6209
Epoch 25/100
189/189 [==============================] - 1s 5ms/step - loss: 1.0049 - accuracy: 0.6276
Epoch 26/100
189/189 [==============================] - 1s 4ms/step - loss: 0.9940 - accuracy: 0.6357
Epoch 27/100
189/189 [==============================] - 1s 5ms/step - loss: 0.9778 - accuracy: 0.6473
Epoch 28/100
189/189 [==============================] - 1s 5ms/step - loss: 0.9673 - accuracy: 0.6438
Epoch 29/100
189/189 [==============================] - 1s 6ms/step - loss: 0.9681 - accuracy: 0.6475
Epoch 30/100
189/189 [==============================] - 1s 6ms/step - loss: 0.9787 - accuracy: 0.6412
Epoch 31/100
189/189 [==============================] - 1s 6ms/step - loss: 0.9514 - accuracy: 0.6443
Epoch 32/100
189/189 [==============================] - 1s 6ms/step - loss: 0.9471 - accuracy: 0.6531
Epoch 33/100
189/189 [==============================] - 1s 6ms/step - loss: 0.9613 - accuracy: 0.6468
Epoch 34/100
189/189 [==============================] - 1s 4ms/step - loss: 0.9487 - accuracy: 0.6472
Epoch 35/100
189/189 [==============================] - 1s 4ms/step - loss: 0.9411 - accuracy: 0.6553
Epoch 36/100
189/189 [==============================] - 1s 4ms/step - loss: 0.9468 - accuracy: 0.6523
Epoch 37/100
189/189 [==============================] - 1s 5ms/step - loss: 0.9253 - accuracy: 0.6611
Epoch 38/100
189/189 [==============================] - 1s 5ms/step - loss: 0.9215 - accuracy: 0.6628
Epoch 39/100
189/189 [==============================] - 1s 4ms/step - loss: 0.9335 - accuracy: 0.6580
Epoch 40/100
189/189 [==============================] - 1s 4ms/step - loss: 0.9109 - accuracy: 0.6610
Epoch 41/100
189/189 [==============================] - 1s 4ms/step - loss: 0.9040 - accuracy: 0.6721
Epoch 42/100
189/189 [==============================] - 1s 4ms/step - loss: 0.9151 - accuracy: 0.6683
Epoch 43/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8907 - accuracy: 0.6781
Epoch 44/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8915 - accuracy: 0.6767
Epoch 45/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8795 - accuracy: 0.6776
Epoch 46/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8878 - accuracy: 0.6733
Epoch 47/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8825 - accuracy: 0.6792
Epoch 48/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8802 - accuracy: 0.6796
Epoch 49/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8702 - accuracy: 0.6862
Epoch 50/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8559 - accuracy: 0.6851
Epoch 51/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8930 - accuracy: 0.6749
Epoch 52/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8743 - accuracy: 0.6877
Epoch 53/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8543 - accuracy: 0.6890
Epoch 54/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8776 - accuracy: 0.6723
Epoch 55/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8584 - accuracy: 0.6811
Epoch 56/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8651 - accuracy: 0.6849
Epoch 57/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8572 - accuracy: 0.6874
Epoch 58/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8563 - accuracy: 0.6849
Epoch 59/100
189/189 [==============================] - 1s 7ms/step - loss: 0.8519 - accuracy: 0.6917
Epoch 60/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8611 - accuracy: 0.6829
Epoch 61/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8376 - accuracy: 0.6935
Epoch 62/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8453 - accuracy: 0.6957
Epoch 63/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8475 - accuracy: 0.6957
Epoch 64/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8261 - accuracy: 0.6944
Epoch 65/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8427 - accuracy: 0.6879
Epoch 66/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8352 - accuracy: 0.6987
Epoch 67/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8503 - accuracy: 0.6935
Epoch 68/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8307 - accuracy: 0.6994
Epoch 69/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8450 - accuracy: 0.6940
Epoch 70/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8465 - accuracy: 0.6960
Epoch 71/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8253 - accuracy: 0.7000
Epoch 72/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8290 - accuracy: 0.7012
Epoch 73/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8324 - accuracy: 0.7030
Epoch 74/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8163 - accuracy: 0.6960
Epoch 75/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8222 - accuracy: 0.7022
Epoch 76/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8232 - accuracy: 0.7042
Epoch 77/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8187 - accuracy: 0.6995
Epoch 78/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8279 - accuracy: 0.6984
Epoch 79/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8056 - accuracy: 0.7088
Epoch 80/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8161 - accuracy: 0.7000
Epoch 81/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8093 - accuracy: 0.7072
Epoch 82/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8192 - accuracy: 0.7000
Epoch 83/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8042 - accuracy: 0.7037
Epoch 84/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8161 - accuracy: 0.7072
Epoch 85/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8213 - accuracy: 0.7048
Epoch 86/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8113 - accuracy: 0.7037
Epoch 87/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8221 - accuracy: 0.7065
Epoch 88/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7981 - accuracy: 0.7131
Epoch 89/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7945 - accuracy: 0.7095
Epoch 90/100
189/189 [==============================] - 1s 4ms/step - loss: 0.8053 - accuracy: 0.7063
Epoch 91/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7949 - accuracy: 0.7118
Epoch 92/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8205 - accuracy: 0.6962
Epoch 93/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7908 - accuracy: 0.7150
Epoch 94/100
189/189 [==============================] - 1s 6ms/step - loss: 0.8067 - accuracy: 0.7037
Epoch 95/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7985 - accuracy: 0.7097
Epoch 96/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7896 - accuracy: 0.7117
Epoch 97/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7981 - accuracy: 0.7045
Epoch 98/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7928 - accuracy: 0.7190
Epoch 99/100
189/189 [==============================] - 1s 5ms/step - loss: 0.8069 - accuracy: 0.7040
Epoch 100/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7951 - accuracy: 0.7130

In [ ]:
model_2004.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2004.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
189/189 [==============================] - 3s 5ms/step - loss: 0.7700 - accuracy: 0.7196
Epoch 2/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7427 - accuracy: 0.7303
Epoch 3/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7431 - accuracy: 0.7211
Epoch 4/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7452 - accuracy: 0.7284
Epoch 5/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7281 - accuracy: 0.7338
Epoch 6/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7343 - accuracy: 0.7311
Epoch 7/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7380 - accuracy: 0.7314
Epoch 8/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7389 - accuracy: 0.7263
Epoch 9/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7325 - accuracy: 0.7293
Epoch 10/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7172 - accuracy: 0.7336
Epoch 11/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7294 - accuracy: 0.7291
Epoch 12/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7339 - accuracy: 0.7269
Epoch 13/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7224 - accuracy: 0.7376
Epoch 14/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7354 - accuracy: 0.7288
Epoch 15/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7280 - accuracy: 0.7321
Epoch 16/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7101 - accuracy: 0.7449
Epoch 17/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7259 - accuracy: 0.7401
Epoch 18/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7299 - accuracy: 0.7321
Epoch 19/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7230 - accuracy: 0.7343
Epoch 20/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7186 - accuracy: 0.7376
Epoch 21/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7198 - accuracy: 0.7343
Epoch 22/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7160 - accuracy: 0.7391
Epoch 23/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7261 - accuracy: 0.7411
Epoch 24/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7007 - accuracy: 0.7409
Epoch 25/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7239 - accuracy: 0.7334
Epoch 26/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7106 - accuracy: 0.7391
Epoch 27/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7110 - accuracy: 0.7397
Epoch 28/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7171 - accuracy: 0.7353
Epoch 29/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7065 - accuracy: 0.7397
Epoch 30/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7166 - accuracy: 0.7354
Epoch 31/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7043 - accuracy: 0.7414
Epoch 32/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7005 - accuracy: 0.7396
Epoch 33/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7173 - accuracy: 0.7376
Epoch 34/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7134 - accuracy: 0.7396
Epoch 35/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7097 - accuracy: 0.7439
Epoch 36/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7124 - accuracy: 0.7412
Epoch 37/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7000 - accuracy: 0.7446
Epoch 38/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6901 - accuracy: 0.7442
Epoch 39/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7206 - accuracy: 0.7356
Epoch 40/100
189/189 [==============================] - 1s 6ms/step - loss: 0.7039 - accuracy: 0.7412
Epoch 41/100
189/189 [==============================] - 1s 7ms/step - loss: 0.7034 - accuracy: 0.7414
Epoch 42/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7004 - accuracy: 0.7411
Epoch 43/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7143 - accuracy: 0.7402
Epoch 44/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7120 - accuracy: 0.7359
Epoch 45/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6948 - accuracy: 0.7459
Epoch 46/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7015 - accuracy: 0.7451
Epoch 47/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6995 - accuracy: 0.7454
Epoch 48/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6911 - accuracy: 0.7441
Epoch 49/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6835 - accuracy: 0.7485
Epoch 50/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7009 - accuracy: 0.7452
Epoch 51/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6911 - accuracy: 0.7527
Epoch 52/100
189/189 [==============================] - 1s 4ms/step - loss: 0.7145 - accuracy: 0.7457
Epoch 53/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6957 - accuracy: 0.7439
Epoch 54/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6910 - accuracy: 0.7442
Epoch 55/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6880 - accuracy: 0.7426
Epoch 56/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6895 - accuracy: 0.7475
Epoch 57/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6825 - accuracy: 0.7464
Epoch 58/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6924 - accuracy: 0.7517
Epoch 59/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6942 - accuracy: 0.7485
Epoch 60/100
189/189 [==============================] - 1s 5ms/step - loss: 0.7228 - accuracy: 0.7394
Epoch 61/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6989 - accuracy: 0.7439
Epoch 62/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6914 - accuracy: 0.7437
Epoch 63/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6946 - accuracy: 0.7432
Epoch 64/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6911 - accuracy: 0.7444
Epoch 65/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6791 - accuracy: 0.7520
Epoch 66/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6919 - accuracy: 0.7457
Epoch 67/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6908 - accuracy: 0.7457
Epoch 68/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6840 - accuracy: 0.7592
Epoch 69/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6920 - accuracy: 0.7449
Epoch 70/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6723 - accuracy: 0.7562
Epoch 71/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6942 - accuracy: 0.7485
Epoch 72/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6885 - accuracy: 0.7512
Epoch 73/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6896 - accuracy: 0.7497
Epoch 74/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6724 - accuracy: 0.7485
Epoch 75/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6861 - accuracy: 0.7485
Epoch 76/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6790 - accuracy: 0.7507
Epoch 77/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6752 - accuracy: 0.7517
Epoch 78/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6709 - accuracy: 0.7565
Epoch 79/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6813 - accuracy: 0.7510
Epoch 80/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6775 - accuracy: 0.7512
Epoch 81/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6806 - accuracy: 0.7461
Epoch 82/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6785 - accuracy: 0.7497
Epoch 83/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6894 - accuracy: 0.7469
Epoch 84/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6742 - accuracy: 0.7544
Epoch 85/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6829 - accuracy: 0.7524
Epoch 86/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6874 - accuracy: 0.7497
Epoch 87/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6862 - accuracy: 0.7504
Epoch 88/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6878 - accuracy: 0.7466
Epoch 89/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6756 - accuracy: 0.7540
Epoch 90/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6624 - accuracy: 0.7555
Epoch 91/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6606 - accuracy: 0.7527
Epoch 92/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6786 - accuracy: 0.7495
Epoch 93/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6745 - accuracy: 0.7524
Epoch 94/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6926 - accuracy: 0.7507
Epoch 95/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6770 - accuracy: 0.7494
Epoch 96/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6607 - accuracy: 0.7547
Epoch 97/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6697 - accuracy: 0.7580
Epoch 98/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6580 - accuracy: 0.7633
Epoch 99/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6764 - accuracy: 0.7527
Epoch 100/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6751 - accuracy: 0.7545

In [ ]:
model_2004.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2004.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
189/189 [==============================] - 3s 4ms/step - loss: 0.6490 - accuracy: 0.7607
Epoch 2/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6527 - accuracy: 0.7605
Epoch 3/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6412 - accuracy: 0.7643
Epoch 4/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6397 - accuracy: 0.7645
Epoch 5/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6424 - accuracy: 0.7673
Epoch 6/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6388 - accuracy: 0.7705
Epoch 7/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6363 - accuracy: 0.7663
Epoch 8/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6314 - accuracy: 0.7683
Epoch 9/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6367 - accuracy: 0.7668
Epoch 10/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6286 - accuracy: 0.7715
Epoch 11/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6331 - accuracy: 0.7675
Epoch 12/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6422 - accuracy: 0.7633
Epoch 13/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6434 - accuracy: 0.7640
Epoch 14/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6294 - accuracy: 0.7683
Epoch 15/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6239 - accuracy: 0.7657
Epoch 16/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6214 - accuracy: 0.7711
Epoch 17/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6296 - accuracy: 0.7713
Epoch 18/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6200 - accuracy: 0.7740
Epoch 19/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6209 - accuracy: 0.7723
Epoch 20/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6312 - accuracy: 0.7697
Epoch 21/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6330 - accuracy: 0.7680
Epoch 22/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6376 - accuracy: 0.7640
Epoch 23/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6228 - accuracy: 0.7760
Epoch 24/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6237 - accuracy: 0.7702
Epoch 25/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6197 - accuracy: 0.7743
Epoch 26/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6109 - accuracy: 0.7791
Epoch 27/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6235 - accuracy: 0.7697
Epoch 28/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6314 - accuracy: 0.7682
Epoch 29/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6187 - accuracy: 0.7736
Epoch 30/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6096 - accuracy: 0.7726
Epoch 31/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6298 - accuracy: 0.7718
Epoch 32/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6103 - accuracy: 0.7766
Epoch 33/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6214 - accuracy: 0.7716
Epoch 34/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6229 - accuracy: 0.7683
Epoch 35/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6214 - accuracy: 0.7692
Epoch 36/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6129 - accuracy: 0.7766
Epoch 37/100
189/189 [==============================] - 1s 7ms/step - loss: 0.6212 - accuracy: 0.7718
Epoch 38/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6273 - accuracy: 0.7695
Epoch 39/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6266 - accuracy: 0.7733
Epoch 40/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6262 - accuracy: 0.7743
Epoch 41/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6167 - accuracy: 0.7728
Epoch 42/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6140 - accuracy: 0.7766
Epoch 43/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6217 - accuracy: 0.7680
Epoch 44/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6066 - accuracy: 0.7798
Epoch 45/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6212 - accuracy: 0.7710
Epoch 46/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6228 - accuracy: 0.7705
Epoch 47/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6183 - accuracy: 0.7740
Epoch 48/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6119 - accuracy: 0.7785
Epoch 49/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6033 - accuracy: 0.7831
Epoch 50/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6053 - accuracy: 0.7715
Epoch 51/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6160 - accuracy: 0.7725
Epoch 52/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6162 - accuracy: 0.7738
Epoch 53/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6167 - accuracy: 0.7761
Epoch 54/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6163 - accuracy: 0.7750
Epoch 55/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6248 - accuracy: 0.7698
Epoch 56/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6087 - accuracy: 0.7725
Epoch 57/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6118 - accuracy: 0.7726
Epoch 58/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6097 - accuracy: 0.7728
Epoch 59/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6098 - accuracy: 0.7775
Epoch 60/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6082 - accuracy: 0.7803
Epoch 61/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6054 - accuracy: 0.7783
Epoch 62/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6120 - accuracy: 0.7715
Epoch 63/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6159 - accuracy: 0.7702
Epoch 64/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6193 - accuracy: 0.7711
Epoch 65/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6055 - accuracy: 0.7753
Epoch 66/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6088 - accuracy: 0.7793
Epoch 67/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6190 - accuracy: 0.7745
Epoch 68/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6110 - accuracy: 0.7768
Epoch 69/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6142 - accuracy: 0.7745
Epoch 70/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6165 - accuracy: 0.7790
Epoch 71/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6052 - accuracy: 0.7695
Epoch 72/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6046 - accuracy: 0.7820
Epoch 73/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6133 - accuracy: 0.7723
Epoch 74/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6061 - accuracy: 0.7773
Epoch 75/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6171 - accuracy: 0.7743
Epoch 76/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6173 - accuracy: 0.7751
Epoch 77/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5992 - accuracy: 0.7816
Epoch 78/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6112 - accuracy: 0.7725
Epoch 79/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6079 - accuracy: 0.7770
Epoch 80/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6072 - accuracy: 0.7776
Epoch 81/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6161 - accuracy: 0.7693
Epoch 82/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6141 - accuracy: 0.7788
Epoch 83/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6063 - accuracy: 0.7786
Epoch 84/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6063 - accuracy: 0.7780
Epoch 85/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6051 - accuracy: 0.7810
Epoch 86/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6074 - accuracy: 0.7785
Epoch 87/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6160 - accuracy: 0.7718
Epoch 88/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6136 - accuracy: 0.7748
Epoch 89/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6058 - accuracy: 0.7780
Epoch 90/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6112 - accuracy: 0.7761
Epoch 91/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6095 - accuracy: 0.7776
Epoch 92/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6084 - accuracy: 0.7756
Epoch 93/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6015 - accuracy: 0.7768
Epoch 94/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5948 - accuracy: 0.7771
Epoch 95/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5995 - accuracy: 0.7785
Epoch 96/100
189/189 [==============================] - 1s 7ms/step - loss: 0.6085 - accuracy: 0.7723
Epoch 97/100
189/189 [==============================] - 1s 7ms/step - loss: 0.6076 - accuracy: 0.7743
Epoch 98/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6031 - accuracy: 0.7811
Epoch 99/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6037 - accuracy: 0.7859
Epoch 100/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6063 - accuracy: 0.7763

In [ ]:
model_2004.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2004.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
189/189 [==============================] - 3s 5ms/step - loss: 0.5969 - accuracy: 0.7770
Epoch 2/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6044 - accuracy: 0.7773
Epoch 3/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5942 - accuracy: 0.7826
Epoch 4/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5974 - accuracy: 0.7796
Epoch 5/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6105 - accuracy: 0.7735
Epoch 6/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6023 - accuracy: 0.7776
Epoch 7/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6093 - accuracy: 0.7760
Epoch 8/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5996 - accuracy: 0.7828
Epoch 9/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6125 - accuracy: 0.7798
Epoch 10/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6096 - accuracy: 0.7796
Epoch 11/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5962 - accuracy: 0.7833
Epoch 12/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5960 - accuracy: 0.7761
Epoch 13/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5967 - accuracy: 0.7811
Epoch 14/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6039 - accuracy: 0.7776
Epoch 15/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6055 - accuracy: 0.7745
Epoch 16/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5899 - accuracy: 0.7833
Epoch 17/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6034 - accuracy: 0.7776
Epoch 18/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6112 - accuracy: 0.7755
Epoch 19/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6065 - accuracy: 0.7741
Epoch 20/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5925 - accuracy: 0.7841
Epoch 21/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5864 - accuracy: 0.7824
Epoch 22/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5842 - accuracy: 0.7821
Epoch 23/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5943 - accuracy: 0.7838
Epoch 24/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5901 - accuracy: 0.7803
Epoch 25/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5948 - accuracy: 0.7838
Epoch 26/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6016 - accuracy: 0.7771
Epoch 27/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6050 - accuracy: 0.7766
Epoch 28/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5998 - accuracy: 0.7697
Epoch 29/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6057 - accuracy: 0.7821
Epoch 30/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5937 - accuracy: 0.7876
Epoch 31/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6108 - accuracy: 0.7725
Epoch 32/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5912 - accuracy: 0.7776
Epoch 33/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5910 - accuracy: 0.7834
Epoch 34/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5850 - accuracy: 0.7889
Epoch 35/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5861 - accuracy: 0.7861
Epoch 36/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5985 - accuracy: 0.7791
Epoch 37/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6003 - accuracy: 0.7788
Epoch 38/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6020 - accuracy: 0.7790
Epoch 39/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5945 - accuracy: 0.7800
Epoch 40/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5886 - accuracy: 0.7839
Epoch 41/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5946 - accuracy: 0.7791
Epoch 42/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6024 - accuracy: 0.7738
Epoch 43/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5971 - accuracy: 0.7823
Epoch 44/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5985 - accuracy: 0.7823
Epoch 45/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6094 - accuracy: 0.7763
Epoch 46/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5833 - accuracy: 0.7851
Epoch 47/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5930 - accuracy: 0.7833
Epoch 48/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6003 - accuracy: 0.7806
Epoch 49/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5847 - accuracy: 0.7791
Epoch 50/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5898 - accuracy: 0.7783
Epoch 51/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6043 - accuracy: 0.7771
Epoch 52/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6004 - accuracy: 0.7824
Epoch 53/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5977 - accuracy: 0.7761
Epoch 54/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5967 - accuracy: 0.7781
Epoch 55/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5883 - accuracy: 0.7858
Epoch 56/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5974 - accuracy: 0.7780
Epoch 57/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6010 - accuracy: 0.7795
Epoch 58/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5971 - accuracy: 0.7821
Epoch 59/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5952 - accuracy: 0.7824
Epoch 60/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5804 - accuracy: 0.7844
Epoch 61/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5973 - accuracy: 0.7831
Epoch 62/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5945 - accuracy: 0.7829
Epoch 63/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6022 - accuracy: 0.7775
Epoch 64/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5875 - accuracy: 0.7864
Epoch 65/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5898 - accuracy: 0.7841
Epoch 66/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5848 - accuracy: 0.7776
Epoch 67/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5919 - accuracy: 0.7854
Epoch 68/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5952 - accuracy: 0.7781
Epoch 69/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5946 - accuracy: 0.7828
Epoch 70/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5961 - accuracy: 0.7821
Epoch 71/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5789 - accuracy: 0.7879
Epoch 72/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5859 - accuracy: 0.7815
Epoch 73/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5951 - accuracy: 0.7820
Epoch 74/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5851 - accuracy: 0.7806
Epoch 75/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5907 - accuracy: 0.7844
Epoch 76/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5802 - accuracy: 0.7911
Epoch 77/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6005 - accuracy: 0.7815
Epoch 78/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5910 - accuracy: 0.7768
Epoch 79/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5848 - accuracy: 0.7878
Epoch 80/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6013 - accuracy: 0.7821
Epoch 81/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5822 - accuracy: 0.7848
Epoch 82/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5800 - accuracy: 0.7806
Epoch 83/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6007 - accuracy: 0.7758
Epoch 84/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5822 - accuracy: 0.7874
Epoch 85/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5955 - accuracy: 0.7796
Epoch 86/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5985 - accuracy: 0.7811
Epoch 87/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6038 - accuracy: 0.7790
Epoch 88/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5843 - accuracy: 0.7853
Epoch 89/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5867 - accuracy: 0.7881
Epoch 90/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5973 - accuracy: 0.7803
Epoch 91/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5980 - accuracy: 0.7826
Epoch 92/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5873 - accuracy: 0.7829
Epoch 93/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6006 - accuracy: 0.7805
Epoch 94/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5794 - accuracy: 0.7876
Epoch 95/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5892 - accuracy: 0.7770
Epoch 96/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5921 - accuracy: 0.7858
Epoch 97/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6024 - accuracy: 0.7800
Epoch 98/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5938 - accuracy: 0.7805
Epoch 99/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5866 - accuracy: 0.7853
Epoch 100/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5901 - accuracy: 0.7823

In [ ]:
model_2004.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2004.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
189/189 [==============================] - 3s 5ms/step - loss: 0.5970 - accuracy: 0.7795
Epoch 2/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5840 - accuracy: 0.7879
Epoch 3/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5706 - accuracy: 0.7888
Epoch 4/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5831 - accuracy: 0.7901
Epoch 5/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5971 - accuracy: 0.7800
Epoch 6/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5869 - accuracy: 0.7873
Epoch 7/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5862 - accuracy: 0.7858
Epoch 8/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5829 - accuracy: 0.7818
Epoch 9/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5963 - accuracy: 0.7783
Epoch 10/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6044 - accuracy: 0.7823
Epoch 11/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5956 - accuracy: 0.7876
Epoch 12/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5883 - accuracy: 0.7834
Epoch 13/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5912 - accuracy: 0.7823
Epoch 14/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5778 - accuracy: 0.7919
Epoch 15/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5936 - accuracy: 0.7756
Epoch 16/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5820 - accuracy: 0.7869
Epoch 17/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5745 - accuracy: 0.7874
Epoch 18/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5845 - accuracy: 0.7883
Epoch 19/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5957 - accuracy: 0.7831
Epoch 20/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5968 - accuracy: 0.7829
Epoch 21/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5864 - accuracy: 0.7863
Epoch 22/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5937 - accuracy: 0.7824
Epoch 23/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5822 - accuracy: 0.7798
Epoch 24/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5829 - accuracy: 0.7838
Epoch 25/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5816 - accuracy: 0.7856
Epoch 26/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5900 - accuracy: 0.7829
Epoch 27/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5872 - accuracy: 0.7889
Epoch 28/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5882 - accuracy: 0.7848
Epoch 29/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5918 - accuracy: 0.7813
Epoch 30/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5807 - accuracy: 0.7929
Epoch 31/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5858 - accuracy: 0.7836
Epoch 32/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5831 - accuracy: 0.7839
Epoch 33/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5922 - accuracy: 0.7801
Epoch 34/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5950 - accuracy: 0.7766
Epoch 35/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5881 - accuracy: 0.7849
Epoch 36/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5944 - accuracy: 0.7800
Epoch 37/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5840 - accuracy: 0.7886
Epoch 38/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5839 - accuracy: 0.7828
Epoch 39/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5912 - accuracy: 0.7851
Epoch 40/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5793 - accuracy: 0.7848
Epoch 41/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5805 - accuracy: 0.7861
Epoch 42/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5866 - accuracy: 0.7828
Epoch 43/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5904 - accuracy: 0.7853
Epoch 44/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5856 - accuracy: 0.7884
Epoch 45/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5750 - accuracy: 0.7864
Epoch 46/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5873 - accuracy: 0.7829
Epoch 47/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5946 - accuracy: 0.7811
Epoch 48/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5916 - accuracy: 0.7829
Epoch 49/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5789 - accuracy: 0.7859
Epoch 50/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5811 - accuracy: 0.7873
Epoch 51/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5879 - accuracy: 0.7868
Epoch 52/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5737 - accuracy: 0.7864
Epoch 53/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5768 - accuracy: 0.7844
Epoch 54/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5839 - accuracy: 0.7874
Epoch 55/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5944 - accuracy: 0.7781
Epoch 56/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5963 - accuracy: 0.7821
Epoch 57/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5716 - accuracy: 0.7909
Epoch 58/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5888 - accuracy: 0.7864
Epoch 59/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5931 - accuracy: 0.7846
Epoch 60/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6041 - accuracy: 0.7803
Epoch 61/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5888 - accuracy: 0.7836
Epoch 62/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5887 - accuracy: 0.7839
Epoch 63/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5884 - accuracy: 0.7818
Epoch 64/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5940 - accuracy: 0.7846
Epoch 65/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5898 - accuracy: 0.7828
Epoch 66/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5729 - accuracy: 0.7828
Epoch 67/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5879 - accuracy: 0.7826
Epoch 68/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5950 - accuracy: 0.7874
Epoch 69/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6008 - accuracy: 0.7854
Epoch 70/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5912 - accuracy: 0.7864
Epoch 71/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5759 - accuracy: 0.7873
Epoch 72/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5865 - accuracy: 0.7876
Epoch 73/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5832 - accuracy: 0.7846
Epoch 74/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5766 - accuracy: 0.7904
Epoch 75/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5889 - accuracy: 0.7831
Epoch 76/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5848 - accuracy: 0.7864
Epoch 77/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5847 - accuracy: 0.7856
Epoch 78/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5890 - accuracy: 0.7849
Epoch 79/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5850 - accuracy: 0.7848
Epoch 80/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5972 - accuracy: 0.7839
Epoch 81/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5848 - accuracy: 0.7863
Epoch 82/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5926 - accuracy: 0.7780
Epoch 83/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5865 - accuracy: 0.7883
Epoch 84/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5798 - accuracy: 0.7889
Epoch 85/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5861 - accuracy: 0.7811
Epoch 86/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5855 - accuracy: 0.7851
Epoch 87/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5826 - accuracy: 0.7858
Epoch 88/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5889 - accuracy: 0.7818
Epoch 89/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5918 - accuracy: 0.7810
Epoch 90/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5854 - accuracy: 0.7889
Epoch 91/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5751 - accuracy: 0.7873
Epoch 92/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6017 - accuracy: 0.7788
Epoch 93/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5997 - accuracy: 0.7823
Epoch 94/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5877 - accuracy: 0.7826
Epoch 95/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5824 - accuracy: 0.7810
Epoch 96/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5767 - accuracy: 0.7919
Epoch 97/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5764 - accuracy: 0.7836
Epoch 98/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5785 - accuracy: 0.7848
Epoch 99/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5846 - accuracy: 0.7859
Epoch 100/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5840 - accuracy: 0.7839

In [ ]:
model_2004.save("/content/drive/MyDrive/FYP/Trained Models/2004.keras")

In [ ]:
predictions = model_2004(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

0

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.7969425058158857

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.7955882352941176

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2004.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2005

#### Random sampling

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features_2005, labels_2005, test_size=0.2)

In [ ]:
y_train = y_train.astype(int)

In [ ]:
X_train.shape, y_train.shape

((7254, 8), (7254,))

In [ ]:
y_train[:5]

array([ 5, 10, 14, 15,  5])

### Stratified sampling

In [ ]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2005, labels_2005):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
features_2005[0]

array([0.85115831, 0.50252732, 0.13733294, 1.        , 0.        ,
       0.        , 0.        , 0.        ])

In [ ]:
fold1[0]

array([ 126,  127,  128, ..., 9065, 9066, 9067])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2005[x]
    y_train = labels_2005[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2005[x]))
    y_train = np.vstack((y_train, labels_2005[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2005[x]
    y_test = labels_2005[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2005[x]))
    y_test = np.vstack((y_test, labels_2005[x]))

In [ ]:
# Second iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2005[x]
    y_train = labels_2005[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2005[x]))
    y_train = np.vstack((y_train, labels_2005[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2005[x]
    y_test = labels_2005[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2005[x]))
    y_test = np.vstack((y_test, labels_2005[x]))

In [ ]:
# Third iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2005[x]
    y_train = labels_2005[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2005[x]))
    y_train = np.vstack((y_train, labels_2005[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2005[x]
    y_test = labels_2005[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2005[x]))
    y_test = np.vstack((y_test, labels_2005[x]))

In [ ]:
y_train.shape

(6045, 1)

## Model Training 2005

In [ ]:
model_2005 = Sequential()

In [ ]:
model_2005.add(Dense(units=520, activation="relu"))
model_2005.add(Dropout(0.5))
model_2005.add(Dense(units=250, activation="relu"))
model_2005.add(Dropout(0.3))
model_2005.add(Dense(units=128, activation="relu"))
model_2005.add(Dropout(0.3))
model_2005.add(Dense(units=64, activation="relu"))
model_2005.add(Dropout(0.3))
model_2005.add(Dense(units=45, activation="relu"))
model_2005.add(Dropout(0.2))
model_2005.add(Dense(units=28, activation="relu"))
model_2005.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2005.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2005.fit(X_train, y_train, epochs=200)
except Exception as ex:
  print(ex)

Epoch 1/200
189/189 [==============================] - 3s 4ms/step - loss: 2.6433 - accuracy: 0.1694
Epoch 2/200
189/189 [==============================] - 1s 4ms/step - loss: 1.9615 - accuracy: 0.3178
Epoch 3/200
189/189 [==============================] - 1s 5ms/step - loss: 1.6622 - accuracy: 0.4139
Epoch 4/200
189/189 [==============================] - 1s 4ms/step - loss: 1.5042 - accuracy: 0.4711
Epoch 5/200
189/189 [==============================] - 1s 5ms/step - loss: 1.3609 - accuracy: 0.5122
Epoch 6/200
189/189 [==============================] - 1s 5ms/step - loss: 1.2814 - accuracy: 0.5375
Epoch 7/200
189/189 [==============================] - 1s 5ms/step - loss: 1.2475 - accuracy: 0.5479
Epoch 8/200
189/189 [==============================] - 1s 5ms/step - loss: 1.1926 - accuracy: 0.5677
Epoch 9/200
189/189 [==============================] - 1s 6ms/step - loss: 1.1550 - accuracy: 0.5840
Epoch 10/200
189/189 [==============================] - 1s 6ms/step - loss: 1.1119 - accuracy: 0.5891
Epoch 11/200
189/189 [==============================] - 1s 6ms/step - loss: 1.0900 - accuracy: 0.6041
Epoch 12/200
189/189 [==============================] - 1s 6ms/step - loss: 1.0812 - accuracy: 0.6089
Epoch 13/200
189/189 [==============================] - 1s 5ms/step - loss: 1.0622 - accuracy: 0.6106
Epoch 14/200
189/189 [==============================] - 1s 5ms/step - loss: 1.0265 - accuracy: 0.6258
Epoch 15/200
189/189 [==============================] - 1s 5ms/step - loss: 1.0251 - accuracy: 0.6240
Epoch 16/200
189/189 [==============================] - 1s 5ms/step - loss: 0.9983 - accuracy: 0.6341
Epoch 17/200
189/189 [==============================] - 1s 5ms/step - loss: 0.9936 - accuracy: 0.6346
Epoch 18/200
189/189 [==============================] - 1s 5ms/step - loss: 0.9859 - accuracy: 0.6339
Epoch 19/200
189/189 [==============================] - 1s 4ms/step - loss: 0.9608 - accuracy: 0.6496
Epoch 20/200
189/189 [==============================] - 1s 4ms/step - loss: 0.9645 - accuracy: 0.6448
Epoch 21/200
189/189 [==============================] - 1s 5ms/step - loss: 0.9471 - accuracy: 0.6506
Epoch 22/200
189/189 [==============================] - 1s 4ms/step - loss: 0.9379 - accuracy: 0.6599
Epoch 23/200
189/189 [==============================] - 1s 4ms/step - loss: 0.9287 - accuracy: 0.6653
Epoch 24/200
189/189 [==============================] - 1s 5ms/step - loss: 0.9267 - accuracy: 0.6566
Epoch 25/200
189/189 [==============================] - 1s 6ms/step - loss: 0.9095 - accuracy: 0.6761
Epoch 26/200
189/189 [==============================] - 1s 6ms/step - loss: 0.9035 - accuracy: 0.6663
Epoch 27/200
189/189 [==============================] - 1s 6ms/step - loss: 0.9043 - accuracy: 0.6768
Epoch 28/200
189/189 [==============================] - 1s 6ms/step - loss: 0.9051 - accuracy: 0.6705
Epoch 29/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8898 - accuracy: 0.6814
Epoch 30/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8681 - accuracy: 0.6792
Epoch 31/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8711 - accuracy: 0.6792
Epoch 32/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8690 - accuracy: 0.6888
Epoch 33/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8799 - accuracy: 0.6776
Epoch 34/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8779 - accuracy: 0.6758
Epoch 35/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8656 - accuracy: 0.6958
Epoch 36/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8676 - accuracy: 0.6895
Epoch 37/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8568 - accuracy: 0.6907
Epoch 38/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8652 - accuracy: 0.6781
Epoch 39/200
189/189 [==============================] - 1s 4ms/step - loss: 0.8429 - accuracy: 0.6953
Epoch 40/200
189/189 [==============================] - 1s 6ms/step - loss: 0.8502 - accuracy: 0.6883
Epoch 41/200
189/189 [==============================] - 1s 6ms/step - loss: 0.8399 - accuracy: 0.6892
Epoch 42/200
189/189 [==============================] - 1s 6ms/step - loss: 0.8411 - accuracy: 0.6880
Epoch 43/200
189/189 [==============================] - 1s 6ms/step - loss: 0.8388 - accuracy: 0.6930
Epoch 44/200
189/189 [==============================] - 1s 6ms/step - loss: 0.8329 - accuracy: 0.6956
Epoch 45/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8482 - accuracy: 0.6895
Epoch 46/200
189/189 [==============================] - 1s 4ms/step - loss: 0.8394 - accuracy: 0.6870
Epoch 47/200
189/189 [==============================] - 1s 4ms/step - loss: 0.8340 - accuracy: 0.6940
Epoch 48/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8083 - accuracy: 0.7050
Epoch 49/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8215 - accuracy: 0.6974
Epoch 50/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8283 - accuracy: 0.6981
Epoch 51/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8140 - accuracy: 0.7002
Epoch 52/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8117 - accuracy: 0.6974
Epoch 53/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8153 - accuracy: 0.7037
Epoch 54/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8004 - accuracy: 0.7189
Epoch 55/200
189/189 [==============================] - 1s 4ms/step - loss: 0.8166 - accuracy: 0.7049
Epoch 56/200
189/189 [==============================] - 1s 6ms/step - loss: 0.8036 - accuracy: 0.7050
Epoch 57/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7993 - accuracy: 0.7097
Epoch 58/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7872 - accuracy: 0.7075
Epoch 59/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7829 - accuracy: 0.7176
Epoch 60/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7946 - accuracy: 0.7089
Epoch 61/200
189/189 [==============================] - 1s 5ms/step - loss: 0.8077 - accuracy: 0.6989
Epoch 62/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7863 - accuracy: 0.7090
Epoch 63/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7648 - accuracy: 0.7266
Epoch 64/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7868 - accuracy: 0.7085
Epoch 65/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7931 - accuracy: 0.7148
Epoch 66/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7832 - accuracy: 0.7155
Epoch 67/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7762 - accuracy: 0.7161
Epoch 68/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7740 - accuracy: 0.7168
Epoch 69/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7729 - accuracy: 0.7130
Epoch 70/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7741 - accuracy: 0.7196
Epoch 71/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7534 - accuracy: 0.7216
Epoch 72/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7916 - accuracy: 0.7173
Epoch 73/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7528 - accuracy: 0.7213
Epoch 74/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7578 - accuracy: 0.7183
Epoch 75/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7639 - accuracy: 0.7266
Epoch 76/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7429 - accuracy: 0.7290
Epoch 77/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7696 - accuracy: 0.7166
Epoch 78/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7542 - accuracy: 0.7261
Epoch 79/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7606 - accuracy: 0.7183
Epoch 80/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7814 - accuracy: 0.7151
Epoch 81/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7613 - accuracy: 0.7219
Epoch 82/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7526 - accuracy: 0.7203
Epoch 83/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7505 - accuracy: 0.7277
Epoch 84/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7640 - accuracy: 0.7213
Epoch 85/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7652 - accuracy: 0.7239
Epoch 86/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7448 - accuracy: 0.7262
Epoch 87/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7560 - accuracy: 0.7198
Epoch 88/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7488 - accuracy: 0.7272
Epoch 89/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7367 - accuracy: 0.7236
Epoch 90/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7439 - accuracy: 0.7241
Epoch 91/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7334 - accuracy: 0.7290
Epoch 92/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7390 - accuracy: 0.7315
Epoch 93/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7585 - accuracy: 0.7242
Epoch 94/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7411 - accuracy: 0.7318
Epoch 95/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7480 - accuracy: 0.7249
Epoch 96/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7476 - accuracy: 0.7292
Epoch 97/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7523 - accuracy: 0.7266
Epoch 98/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7282 - accuracy: 0.7338
Epoch 99/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7388 - accuracy: 0.7246
Epoch 100/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7428 - accuracy: 0.7322
Epoch 101/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7383 - accuracy: 0.7251
Epoch 102/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7238 - accuracy: 0.7309
Epoch 103/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7320 - accuracy: 0.7297
Epoch 104/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7284 - accuracy: 0.7312
Epoch 105/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7119 - accuracy: 0.7400
Epoch 106/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7314 - accuracy: 0.7342
Epoch 107/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7375 - accuracy: 0.7287
Epoch 108/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7254 - accuracy: 0.7395
Epoch 109/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7234 - accuracy: 0.7395
Epoch 110/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7337 - accuracy: 0.7315
Epoch 111/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7287 - accuracy: 0.7383
Epoch 112/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7346 - accuracy: 0.7307
Epoch 113/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7230 - accuracy: 0.7396
Epoch 114/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7248 - accuracy: 0.7360
Epoch 115/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7247 - accuracy: 0.7370
Epoch 116/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7263 - accuracy: 0.7333
Epoch 117/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7289 - accuracy: 0.7292
Epoch 118/200
189/189 [==============================] - 1s 4ms/step - loss: 0.7069 - accuracy: 0.7375
Epoch 119/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7359 - accuracy: 0.7320
Epoch 120/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7128 - accuracy: 0.7400
Epoch 121/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7167 - accuracy: 0.7347
Epoch 122/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7370 - accuracy: 0.7338
Epoch 123/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7169 - accuracy: 0.7332
Epoch 124/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7172 - accuracy: 0.7376
Epoch 125/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7244 - accuracy: 0.7361
Epoch 126/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7076 - accuracy: 0.7376
Epoch 127/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7211 - accuracy: 0.7409
Epoch 128/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7056 - accuracy: 0.7429
Epoch 129/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7072 - accuracy: 0.7360
Epoch 130/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7225 - accuracy: 0.7398
Epoch 131/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7175 - accuracy: 0.7396
Epoch 132/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7194 - accuracy: 0.7381
Epoch 133/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7067 - accuracy: 0.7388
Epoch 134/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7034 - accuracy: 0.7416
Epoch 135/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7300 - accuracy: 0.7350
Epoch 136/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7041 - accuracy: 0.7419
Epoch 137/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7026 - accuracy: 0.7404
Epoch 138/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7019 - accuracy: 0.7451
Epoch 139/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7296 - accuracy: 0.7335
Epoch 140/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7036 - accuracy: 0.7411
Epoch 141/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7171 - accuracy: 0.7413
Epoch 142/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7020 - accuracy: 0.7457
Epoch 143/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7148 - accuracy: 0.7395
Epoch 144/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7019 - accuracy: 0.7433
Epoch 145/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7103 - accuracy: 0.7388
Epoch 146/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7037 - accuracy: 0.7386
Epoch 147/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6993 - accuracy: 0.7434
Epoch 148/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7168 - accuracy: 0.7388
Epoch 149/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7033 - accuracy: 0.7438
Epoch 150/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6938 - accuracy: 0.7447
Epoch 151/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6955 - accuracy: 0.7416
Epoch 152/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7091 - accuracy: 0.7368
Epoch 153/200
189/189 [==============================] - 1s 7ms/step - loss: 0.7238 - accuracy: 0.7317
Epoch 154/200
189/189 [==============================] - 1s 6ms/step - loss: 0.7017 - accuracy: 0.7459
Epoch 155/200
189/189 [==============================] - 1s 7ms/step - loss: 0.6956 - accuracy: 0.7441
Epoch 156/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6995 - accuracy: 0.7467
Epoch 157/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6956 - accuracy: 0.7411
Epoch 158/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7049 - accuracy: 0.7409
Epoch 159/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6877 - accuracy: 0.7489
Epoch 160/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6973 - accuracy: 0.7481
Epoch 161/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7154 - accuracy: 0.7386
Epoch 162/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6949 - accuracy: 0.7469
Epoch 163/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7032 - accuracy: 0.7421
Epoch 164/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7009 - accuracy: 0.7418
Epoch 165/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6984 - accuracy: 0.7459
Epoch 166/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6912 - accuracy: 0.7517
Epoch 167/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6811 - accuracy: 0.7492
Epoch 168/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6915 - accuracy: 0.7462
Epoch 169/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6987 - accuracy: 0.7454
Epoch 170/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6744 - accuracy: 0.7520
Epoch 171/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6889 - accuracy: 0.7471
Epoch 172/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6777 - accuracy: 0.7514
Epoch 173/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7095 - accuracy: 0.7419
Epoch 174/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6832 - accuracy: 0.7495
Epoch 175/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6806 - accuracy: 0.7504
Epoch 176/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7017 - accuracy: 0.7404
Epoch 177/200
189/189 [==============================] - 1s 5ms/step - loss: 0.7128 - accuracy: 0.7388
Epoch 178/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6850 - accuracy: 0.7567
Epoch 179/200
189/189 [==============================] - 1s 4ms/step - loss: 0.6916 - accuracy: 0.7479
Epoch 180/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6848 - accuracy: 0.7481
Epoch 181/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6902 - accuracy: 0.7499
Epoch 182/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6879 - accuracy: 0.7481
Epoch 183/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6966 - accuracy: 0.7522
Epoch 184/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6847 - accuracy: 0.7497
Epoch 185/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6850 - accuracy: 0.7449
Epoch 186/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6765 - accuracy: 0.7507
Epoch 187/200
189/189 [==============================] - 1s 6ms/step - loss: 0.6804 - accuracy: 0.7505
Epoch 188/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6849 - accuracy: 0.7533
Epoch 189/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6958 - accuracy: 0.7505
Epoch 190/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6987 - accuracy: 0.7444
Epoch 191/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6854 - accuracy: 0.7490
Epoch 192/200
189/189 [==============================] - 1s 4ms/step - loss: 0.6801 - accuracy: 0.7552
Epoch 193/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6782 - accuracy: 0.7553
Epoch 194/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6850 - accuracy: 0.7567
Epoch 195/200
189/189 [==============================] - 1s 5ms/step - loss: 0.6786 - accuracy: 0.7524
Epoch 196/200

In [ ]:
model_2005.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2005.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
189/189 [==============================] - 3s 4ms/step - loss: 0.6660 - accuracy: 0.7595
Epoch 2/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6524 - accuracy: 0.7550
Epoch 3/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6372 - accuracy: 0.7669
Epoch 4/100
189/189 [==============================] - 1s 7ms/step - loss: 0.6460 - accuracy: 0.7624
Epoch 5/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6423 - accuracy: 0.7606
Epoch 6/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6243 - accuracy: 0.7699
Epoch 7/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6219 - accuracy: 0.7701
Epoch 8/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6335 - accuracy: 0.7667
Epoch 9/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6305 - accuracy: 0.7605
Epoch 10/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6219 - accuracy: 0.7694
Epoch 11/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6313 - accuracy: 0.7682
Epoch 12/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6203 - accuracy: 0.7720
Epoch 13/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6307 - accuracy: 0.7667
Epoch 14/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6224 - accuracy: 0.7711
Epoch 15/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6226 - accuracy: 0.7696
Epoch 16/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6225 - accuracy: 0.7677
Epoch 17/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6120 - accuracy: 0.7752
Epoch 18/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6197 - accuracy: 0.7656
Epoch 19/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6237 - accuracy: 0.7649
Epoch 20/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6234 - accuracy: 0.7671
Epoch 21/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6164 - accuracy: 0.7661
Epoch 22/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6221 - accuracy: 0.7686
Epoch 23/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6251 - accuracy: 0.7702
Epoch 24/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6229 - accuracy: 0.7696
Epoch 25/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6202 - accuracy: 0.7712
Epoch 26/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6177 - accuracy: 0.7727
Epoch 27/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6155 - accuracy: 0.7757
Epoch 28/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6157 - accuracy: 0.7677
Epoch 29/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6214 - accuracy: 0.7699
Epoch 30/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6254 - accuracy: 0.7724
Epoch 31/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6255 - accuracy: 0.7676
Epoch 32/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6114 - accuracy: 0.7727
Epoch 33/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6073 - accuracy: 0.7730
Epoch 34/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6096 - accuracy: 0.7754
Epoch 35/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6090 - accuracy: 0.7714
Epoch 36/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6248 - accuracy: 0.7677
Epoch 37/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6182 - accuracy: 0.7755
Epoch 38/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6074 - accuracy: 0.7687
Epoch 39/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6026 - accuracy: 0.7772
Epoch 40/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6345 - accuracy: 0.7626
Epoch 41/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6135 - accuracy: 0.7747
Epoch 42/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6052 - accuracy: 0.7745
Epoch 43/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6093 - accuracy: 0.7780
Epoch 44/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6073 - accuracy: 0.7770
Epoch 45/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6044 - accuracy: 0.7750
Epoch 46/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6052 - accuracy: 0.7803
Epoch 47/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6003 - accuracy: 0.7825
Epoch 48/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6053 - accuracy: 0.7778
Epoch 49/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6081 - accuracy: 0.7755
Epoch 50/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6075 - accuracy: 0.7715
Epoch 51/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6272 - accuracy: 0.7661
Epoch 52/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6142 - accuracy: 0.7729
Epoch 53/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6054 - accuracy: 0.7750
Epoch 54/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6080 - accuracy: 0.7763
Epoch 55/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6008 - accuracy: 0.7742
Epoch 56/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5990 - accuracy: 0.7797
Epoch 57/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6207 - accuracy: 0.7770
Epoch 58/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5978 - accuracy: 0.7838
Epoch 59/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6157 - accuracy: 0.7772
Epoch 60/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6038 - accuracy: 0.7749
Epoch 61/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5952 - accuracy: 0.7790
Epoch 62/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5966 - accuracy: 0.7790
Epoch 63/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6069 - accuracy: 0.7742
Epoch 64/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5968 - accuracy: 0.7772
Epoch 65/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6011 - accuracy: 0.7763
Epoch 66/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5971 - accuracy: 0.7754
Epoch 67/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6038 - accuracy: 0.7772
Epoch 68/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5971 - accuracy: 0.7778
Epoch 69/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5966 - accuracy: 0.7770
Epoch 70/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6063 - accuracy: 0.7752
Epoch 71/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6177 - accuracy: 0.7725
Epoch 72/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6023 - accuracy: 0.7775
Epoch 73/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6052 - accuracy: 0.7763
Epoch 74/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6133 - accuracy: 0.7732
Epoch 75/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6141 - accuracy: 0.7676
Epoch 76/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6031 - accuracy: 0.7740
Epoch 77/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6049 - accuracy: 0.7757
Epoch 78/100
189/189 [==============================] - 1s 4ms/step - loss: 0.6003 - accuracy: 0.7763
Epoch 79/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5944 - accuracy: 0.7792
Epoch 80/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5993 - accuracy: 0.7778
Epoch 81/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6003 - accuracy: 0.7795
Epoch 82/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6103 - accuracy: 0.7740
Epoch 83/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6044 - accuracy: 0.7742
Epoch 84/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5967 - accuracy: 0.7770
Epoch 85/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5889 - accuracy: 0.7792
Epoch 86/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5934 - accuracy: 0.7782
Epoch 87/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6013 - accuracy: 0.7803
Epoch 88/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5929 - accuracy: 0.7831
Epoch 89/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6089 - accuracy: 0.7821
Epoch 90/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6018 - accuracy: 0.7825
Epoch 91/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6077 - accuracy: 0.7795
Epoch 92/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6002 - accuracy: 0.7778
Epoch 93/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5971 - accuracy: 0.7793
Epoch 94/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6115 - accuracy: 0.7694
Epoch 95/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5966 - accuracy: 0.7732
Epoch 96/100
189/189 [==============================] - 1s 7ms/step - loss: 0.6111 - accuracy: 0.7762
Epoch 97/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6051 - accuracy: 0.7732
Epoch 98/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5978 - accuracy: 0.7787
Epoch 99/100
189/189 [==============================] - 1s 6ms/step - loss: 0.6017 - accuracy: 0.7730
Epoch 100/100
189/189 [==============================] - 1s 5ms/step - loss: 0.6010 - accuracy: 0.7803

In [ ]:
model_2005.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2005.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
189/189 [==============================] - 3s 5ms/step - loss: 0.5822 - accuracy: 0.7803
Epoch 2/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5768 - accuracy: 0.7816
Epoch 3/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5568 - accuracy: 0.7902
Epoch 4/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5582 - accuracy: 0.7859
Epoch 5/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5695 - accuracy: 0.7922
Epoch 6/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5750 - accuracy: 0.7901
Epoch 7/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5619 - accuracy: 0.7897
Epoch 8/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5527 - accuracy: 0.7922
Epoch 9/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5618 - accuracy: 0.7849
Epoch 10/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5560 - accuracy: 0.7944
Epoch 11/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5605 - accuracy: 0.7873
Epoch 12/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5561 - accuracy: 0.7884
Epoch 13/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5563 - accuracy: 0.7940
Epoch 14/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5600 - accuracy: 0.7911
Epoch 15/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5550 - accuracy: 0.7888
Epoch 16/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5533 - accuracy: 0.7889
Epoch 17/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5422 - accuracy: 0.7921
Epoch 18/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5530 - accuracy: 0.7932
Epoch 19/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5531 - accuracy: 0.7912
Epoch 20/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5490 - accuracy: 0.7921
Epoch 21/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7975
Epoch 22/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5509 - accuracy: 0.7967
Epoch 23/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5476 - accuracy: 0.7921
Epoch 24/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5471 - accuracy: 0.7934
Epoch 25/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5560 - accuracy: 0.7873
Epoch 26/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5378 - accuracy: 0.8002
Epoch 27/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5508 - accuracy: 0.7922
Epoch 28/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5475 - accuracy: 0.7873
Epoch 29/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5353 - accuracy: 0.7975
Epoch 30/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5585 - accuracy: 0.7871
Epoch 31/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5443 - accuracy: 0.7924
Epoch 32/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5489 - accuracy: 0.7922
Epoch 33/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5554 - accuracy: 0.7926
Epoch 34/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5464 - accuracy: 0.7945
Epoch 35/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5507 - accuracy: 0.7944
Epoch 36/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5454 - accuracy: 0.7954
Epoch 37/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5468 - accuracy: 0.7962
Epoch 38/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5484 - accuracy: 0.7932
Epoch 39/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5430 - accuracy: 0.7949
Epoch 40/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5638 - accuracy: 0.7902
Epoch 41/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5506 - accuracy: 0.7960
Epoch 42/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5552 - accuracy: 0.7937
Epoch 43/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5464 - accuracy: 0.7917
Epoch 44/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5451 - accuracy: 0.7934
Epoch 45/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5485 - accuracy: 0.7947
Epoch 46/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5588 - accuracy: 0.7939
Epoch 47/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5542 - accuracy: 0.7939
Epoch 48/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5412 - accuracy: 0.7972
Epoch 49/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5456 - accuracy: 0.7934
Epoch 50/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5321 - accuracy: 0.8017
Epoch 51/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5404 - accuracy: 0.7929
Epoch 52/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5432 - accuracy: 0.7952
Epoch 53/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5467 - accuracy: 0.7934
Epoch 54/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5423 - accuracy: 0.7972
Epoch 55/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5471 - accuracy: 0.7935
Epoch 56/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5466 - accuracy: 0.7969
Epoch 57/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5403 - accuracy: 0.7945
Epoch 58/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5437 - accuracy: 0.7980
Epoch 59/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5407 - accuracy: 0.7972
Epoch 60/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5492 - accuracy: 0.7978
Epoch 61/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5576 - accuracy: 0.7907
Epoch 62/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5435 - accuracy: 0.7922
Epoch 63/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5429 - accuracy: 0.7927
Epoch 64/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5335 - accuracy: 0.8012
Epoch 65/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5584 - accuracy: 0.7917
Epoch 66/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5423 - accuracy: 0.7964
Epoch 67/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5581 - accuracy: 0.7970
Epoch 68/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5350 - accuracy: 0.7983
Epoch 69/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5463 - accuracy: 0.7997
Epoch 70/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5455 - accuracy: 0.8002
Epoch 71/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5415 - accuracy: 0.8003
Epoch 72/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5427 - accuracy: 0.8022
Epoch 73/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5467 - accuracy: 0.7985
Epoch 74/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5392 - accuracy: 0.8026
Epoch 75/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5402 - accuracy: 0.7970
Epoch 76/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5413 - accuracy: 0.7970
Epoch 77/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5453 - accuracy: 0.7935
Epoch 78/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5465 - accuracy: 0.7955
Epoch 79/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5407 - accuracy: 0.7970
Epoch 80/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5542 - accuracy: 0.7952
Epoch 81/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5349 - accuracy: 0.7962
Epoch 82/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5597 - accuracy: 0.7972
Epoch 83/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5443 - accuracy: 0.8003
Epoch 84/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5510 - accuracy: 0.7937
Epoch 85/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5508 - accuracy: 0.7907
Epoch 86/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5317 - accuracy: 0.8022
Epoch 87/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5309 - accuracy: 0.8023
Epoch 88/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5374 - accuracy: 0.8005
Epoch 89/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5409 - accuracy: 0.7949
Epoch 90/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5372 - accuracy: 0.7987
Epoch 91/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5346 - accuracy: 0.7980
Epoch 92/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5443 - accuracy: 0.7985
Epoch 93/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5497 - accuracy: 0.7954
Epoch 94/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5236 - accuracy: 0.8066
Epoch 95/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5562 - accuracy: 0.7884
Epoch 96/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5326 - accuracy: 0.7988
Epoch 97/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5429 - accuracy: 0.7975
Epoch 98/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5410 - accuracy: 0.7990
Epoch 99/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5358 - accuracy: 0.7983
Epoch 100/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5371 - accuracy: 0.7944

In [ ]:
model_2005.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2005.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
189/189 [==============================] - 3s 5ms/step - loss: 0.5256 - accuracy: 0.8022
Epoch 2/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5423 - accuracy: 0.8000
Epoch 3/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5344 - accuracy: 0.7954
Epoch 4/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5334 - accuracy: 0.7998
Epoch 5/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5362 - accuracy: 0.8002
Epoch 6/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5224 - accuracy: 0.8017
Epoch 7/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5365 - accuracy: 0.7993
Epoch 8/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5315 - accuracy: 0.8003
Epoch 9/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5332 - accuracy: 0.8010
Epoch 10/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5309 - accuracy: 0.7985
Epoch 11/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5242 - accuracy: 0.7995
Epoch 12/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5474 - accuracy: 0.8003
Epoch 13/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5335 - accuracy: 0.7992
Epoch 14/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5455 - accuracy: 0.7945
Epoch 15/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5312 - accuracy: 0.7990
Epoch 16/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5256 - accuracy: 0.8060
Epoch 17/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5305 - accuracy: 0.8020
Epoch 18/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5296 - accuracy: 0.8022
Epoch 19/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5394 - accuracy: 0.7977
Epoch 20/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7942
Epoch 21/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5362 - accuracy: 0.7969
Epoch 22/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5363 - accuracy: 0.8010
Epoch 23/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5381 - accuracy: 0.7972
Epoch 24/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5288 - accuracy: 0.7983
Epoch 25/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5289 - accuracy: 0.8023
Epoch 26/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5302 - accuracy: 0.8013
Epoch 27/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5240 - accuracy: 0.8025
Epoch 28/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5243 - accuracy: 0.7988
Epoch 29/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5377 - accuracy: 0.7959
Epoch 30/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7974
Epoch 31/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5358 - accuracy: 0.8017
Epoch 32/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5245 - accuracy: 0.7992
Epoch 33/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5342 - accuracy: 0.8005
Epoch 34/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5280 - accuracy: 0.8008
Epoch 35/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5381 - accuracy: 0.7945
Epoch 36/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.8045
Epoch 37/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7995
Epoch 38/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5244 - accuracy: 0.8026
Epoch 39/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5186 - accuracy: 0.8000
Epoch 40/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5373 - accuracy: 0.7990
Epoch 41/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5308 - accuracy: 0.8003
Epoch 42/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5227 - accuracy: 0.8025
Epoch 43/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5303 - accuracy: 0.7987
Epoch 44/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5268 - accuracy: 0.7997
Epoch 45/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5320 - accuracy: 0.8038
Epoch 46/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5196 - accuracy: 0.8045
Epoch 47/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5187 - accuracy: 0.8002
Epoch 48/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5293 - accuracy: 0.8050
Epoch 49/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5231 - accuracy: 0.8017
Epoch 50/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5307 - accuracy: 0.8018
Epoch 51/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5333 - accuracy: 0.7998
Epoch 52/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5248 - accuracy: 0.7982
Epoch 53/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5315 - accuracy: 0.8033
Epoch 54/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5258 - accuracy: 0.8053
Epoch 55/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5368 - accuracy: 0.7980
Epoch 56/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5313 - accuracy: 0.8007
Epoch 57/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5322 - accuracy: 0.7972
Epoch 58/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5215 - accuracy: 0.8040
Epoch 59/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5322 - accuracy: 0.7987
Epoch 60/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5302 - accuracy: 0.8041
Epoch 61/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5351 - accuracy: 0.7993
Epoch 62/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5341 - accuracy: 0.7957
Epoch 63/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5296 - accuracy: 0.8065
Epoch 64/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5298 - accuracy: 0.8025
Epoch 65/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5365 - accuracy: 0.8013
Epoch 66/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5242 - accuracy: 0.8045
Epoch 67/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5360 - accuracy: 0.7992
Epoch 68/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5282 - accuracy: 0.8036
Epoch 69/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5236 - accuracy: 0.8046
Epoch 70/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5217 - accuracy: 0.8038
Epoch 71/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5227 - accuracy: 0.8040
Epoch 72/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5305 - accuracy: 0.8036
Epoch 73/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5176 - accuracy: 0.8060
Epoch 74/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5150 - accuracy: 0.8045
Epoch 75/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5324 - accuracy: 0.8007
Epoch 76/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5214 - accuracy: 0.8046
Epoch 77/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5340 - accuracy: 0.8000
Epoch 78/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5211 - accuracy: 0.8038
Epoch 79/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5221 - accuracy: 0.8023
Epoch 80/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5300 - accuracy: 0.8040
Epoch 81/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5312 - accuracy: 0.8023
Epoch 82/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5325 - accuracy: 0.7977
Epoch 83/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5277 - accuracy: 0.7964
Epoch 84/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5195 - accuracy: 0.8040
Epoch 85/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5236 - accuracy: 0.8028
Epoch 86/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5257 - accuracy: 0.8041
Epoch 87/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5227 - accuracy: 0.8060
Epoch 88/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5471 - accuracy: 0.7997
Epoch 89/100
189/189 [==============================] - 1s 8ms/step - loss: 0.5283 - accuracy: 0.8061
Epoch 90/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5284 - accuracy: 0.8023
Epoch 91/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5311 - accuracy: 0.8030
Epoch 92/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5240 - accuracy: 0.8022
Epoch 93/100
189/189 [==============================] - 1s 8ms/step - loss: 0.5237 - accuracy: 0.8050
Epoch 94/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5294 - accuracy: 0.8013
Epoch 95/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5307 - accuracy: 0.8036
Epoch 96/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5260 - accuracy: 0.8010
Epoch 97/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5263 - accuracy: 0.7993
Epoch 98/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5223 - accuracy: 0.7955
Epoch 99/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5366 - accuracy: 0.8020
Epoch 100/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5359 - accuracy: 0.8018

In [ ]:
model_2005.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2005.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
189/189 [==============================] - 4s 6ms/step - loss: 0.5201 - accuracy: 0.8043
Epoch 2/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5271 - accuracy: 0.8026
Epoch 3/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5205 - accuracy: 0.8061
Epoch 4/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5225 - accuracy: 0.8050
Epoch 5/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5239 - accuracy: 0.8018
Epoch 6/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5321 - accuracy: 0.8007
Epoch 7/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5312 - accuracy: 0.8022
Epoch 8/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5256 - accuracy: 0.8010
Epoch 9/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5174 - accuracy: 0.8055
Epoch 10/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5251 - accuracy: 0.8020
Epoch 11/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5276 - accuracy: 0.8002
Epoch 12/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5222 - accuracy: 0.8035
Epoch 13/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5253 - accuracy: 0.8030
Epoch 14/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5243 - accuracy: 0.8046
Epoch 15/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5279 - accuracy: 0.8002
Epoch 16/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5216 - accuracy: 0.8038
Epoch 17/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5293 - accuracy: 0.8051
Epoch 18/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5178 - accuracy: 0.8053
Epoch 19/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5228 - accuracy: 0.8066
Epoch 20/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5228 - accuracy: 0.8091
Epoch 21/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5262 - accuracy: 0.8066
Epoch 22/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5318 - accuracy: 0.8005
Epoch 23/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5244 - accuracy: 0.8022
Epoch 24/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5289 - accuracy: 0.8045
Epoch 25/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5277 - accuracy: 0.8028
Epoch 26/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5302 - accuracy: 0.8018
Epoch 27/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.8020
Epoch 28/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5238 - accuracy: 0.8010
Epoch 29/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5290 - accuracy: 0.8028
Epoch 30/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5274 - accuracy: 0.8035
Epoch 31/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5226 - accuracy: 0.8050
Epoch 32/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5248 - accuracy: 0.8066
Epoch 33/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5276 - accuracy: 0.7985
Epoch 34/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5307 - accuracy: 0.8013
Epoch 35/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5253 - accuracy: 0.8030
Epoch 36/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5174 - accuracy: 0.8038
Epoch 37/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5387 - accuracy: 0.7993
Epoch 38/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5170 - accuracy: 0.8008
Epoch 39/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.8076
Epoch 40/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5316 - accuracy: 0.8028
Epoch 41/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5283 - accuracy: 0.8025
Epoch 42/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5285 - accuracy: 0.8033
Epoch 43/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5269 - accuracy: 0.7983
Epoch 44/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5239 - accuracy: 0.8068
Epoch 45/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5290 - accuracy: 0.7992
Epoch 46/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5209 - accuracy: 0.8010
Epoch 47/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5198 - accuracy: 0.8051
Epoch 48/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5290 - accuracy: 0.8038
Epoch 49/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5300 - accuracy: 0.8023
Epoch 50/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5140 - accuracy: 0.8066
Epoch 51/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5302 - accuracy: 0.8005
Epoch 52/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5289 - accuracy: 0.8028
Epoch 53/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5320 - accuracy: 0.8023
Epoch 54/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5264 - accuracy: 0.8023
Epoch 55/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5199 - accuracy: 0.8041
Epoch 56/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.8036
Epoch 57/100
189/189 [==============================] - 1s 4ms/step - loss: 0.5212 - accuracy: 0.8036
Epoch 58/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5216 - accuracy: 0.8013
Epoch 59/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5225 - accuracy: 0.8017
Epoch 60/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5319 - accuracy: 0.8028
Epoch 61/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5280 - accuracy: 0.8015
Epoch 62/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5319 - accuracy: 0.8002
Epoch 63/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5200 - accuracy: 0.8073
Epoch 64/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5356 - accuracy: 0.7993
Epoch 65/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5285 - accuracy: 0.8038
Epoch 66/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5223 - accuracy: 0.8069
Epoch 67/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5250 - accuracy: 0.8051
Epoch 68/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5209 - accuracy: 0.8025
Epoch 69/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5288 - accuracy: 0.8041
Epoch 70/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5285 - accuracy: 0.7987
Epoch 71/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5179 - accuracy: 0.8026
Epoch 72/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5372 - accuracy: 0.8013
Epoch 73/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5318 - accuracy: 0.8040
Epoch 74/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5317 - accuracy: 0.7980
Epoch 75/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5287 - accuracy: 0.7988
Epoch 76/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5264 - accuracy: 0.8036
Epoch 77/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5225 - accuracy: 0.7985
Epoch 78/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5274 - accuracy: 0.8033
Epoch 79/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5231 - accuracy: 0.8015
Epoch 80/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5323 - accuracy: 0.7990
Epoch 81/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5274 - accuracy: 0.8025
Epoch 82/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5125 - accuracy: 0.8074
Epoch 83/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5293 - accuracy: 0.7974
Epoch 84/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5287 - accuracy: 0.7993
Epoch 85/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5226 - accuracy: 0.8041
Epoch 86/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5206 - accuracy: 0.8066
Epoch 87/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5189 - accuracy: 0.8048
Epoch 88/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5234 - accuracy: 0.8012
Epoch 89/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5233 - accuracy: 0.8071
Epoch 90/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5218 - accuracy: 0.8033
Epoch 91/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5250 - accuracy: 0.8030
Epoch 92/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5265 - accuracy: 0.7993
Epoch 93/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5237 - accuracy: 0.8048
Epoch 94/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5256 - accuracy: 0.8010
Epoch 95/100
189/189 [==============================] - 1s 6ms/step - loss: 0.5236 - accuracy: 0.8018
Epoch 96/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5219 - accuracy: 0.8030
Epoch 97/100
189/189 [==============================] - 1s 7ms/step - loss: 0.5274 - accuracy: 0.8002
Epoch 98/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5235 - accuracy: 0.8038
Epoch 99/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5195 - accuracy: 0.8012
Epoch 100/100
189/189 [==============================] - 1s 5ms/step - loss: 0.5187 - accuracy: 0.8028

In [ ]:
model_2005.save("/content/drive/MyDrive/FYP/Trained Models/2005.keras")

In [ ]:
accuracies = []

In [ ]:
# Loading saved model
model2005 = tf.keras.models.load_model("/content/drive/MyDrive/FYP/Trained Models/2005.keras")

In [ ]:
data = np.array([7752, 33.9786102913, 6.5336974015, 62.8065401418, 1, 0, 0, 0, 0])
data = data.reshape(1, -1)
scaled_data = sc.fit_transform(data)
scaled_data.ravel()

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
predictions = model2005(features_2005)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
predicted_labels[2]

0

In [ ]:
labels_2005[2]

0

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(labels_2005, predicted_labels)

In [ ]:
accuracy

0.8200264666960742

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.7941176470588235

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2005.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2006

### Stratified sampling

In [ ]:
kf = StratifiedKFold(n_splits=2)

In [ ]:
for train_index, val_index in kf.split(features_2006, labels_2006):
  x_train , x_val = features_2006[train_index], features_2006[val_index]
  y_train, y_val = labels_2006[train_index], labels_2006[val_index]

In [ ]:
for train_index, val_index in kf.split(x_val, y_val):
  X_val , X_test = x_val[train_index], x_val[val_index]
  Y_val, Y_test = y_val[train_index], y_val[val_index]

## Model Training 2006

In [ ]:
model_2006 = Sequential()
model_2006.add(Dense(units=1600, activation="tanh"))
model_2006.add(Dropout(0.5))
model_2006.add(Dense(units=1200, activation="tanh"))
model_2006.add(Dropout(0.5))
model_2006.add(Dense(units=800, activation="tanh"))
model_2006.add(Dropout(0.5))
model_2006.add(Dense(units=400, activation="tanh"))
model_2006.add(Dropout(0.5))
model_2006.add(Dense(units=200, activation="tanh"))
model_2006.add(Dropout(0.5))
model_2006.add(Dense(units=100, activation="tanh"))
model_2006.add(Dropout(0.5))
model_2006.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2006.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
history = model_2006.fit(x_train, y_train, epochs=100, validation_data=(X_val, Y_val))

Epoch 1/100
145/145 [==============================] - 18s 107ms/step - loss: 2.6360 - accuracy: 0.2231 - val_loss: 1.8821 - val_accuracy: 0.4150
Epoch 2/100
145/145 [==============================] - 13s 90ms/step - loss: 1.8869 - accuracy: 0.3874 - val_loss: 1.5302 - val_accuracy: 0.5165
Epoch 3/100
145/145 [==============================] - 13s 88ms/step - loss: 1.5402 - accuracy: 0.4862 - val_loss: 1.5976 - val_accuracy: 0.5147
Epoch 4/100
145/145 [==============================] - 12s 79ms/step - loss: 1.4239 - accuracy: 0.5209 - val_loss: 1.4711 - val_accuracy: 0.5416
Epoch 5/100
145/145 [==============================] - 13s 90ms/step - loss: 1.3148 - accuracy: 0.5480 - val_loss: 1.3850 - val_accuracy: 0.5763
Epoch 6/100
145/145 [==============================] - 13s 92ms/step - loss: 1.2461 - accuracy: 0.5723 - val_loss: 1.3657 - val_accuracy: 0.5893
Epoch 7/100
145/145 [==============================] - 12s 86ms/step - loss: 1.2031 - accuracy: 0.5831 - val_loss: 1.4226 - val_accuracy: 0.5711
Epoch 8/100
145/145 [==============================] - 11s 78ms/step - loss: 1.1698 - accuracy: 0.5959 - val_loss: 1.5123 - val_accuracy: 0.5746
Epoch 9/100
145/145 [==============================] - 12s 86ms/step - loss: 1.1384 - accuracy: 0.6009 - val_loss: 1.3241 - val_accuracy: 0.5837
Epoch 10/100
145/145 [==============================] - 12s 85ms/step - loss: 1.0948 - accuracy: 0.6115 - val_loss: 1.3122 - val_accuracy: 0.6041
Epoch 11/100
145/145 [==============================] - 12s 85ms/step - loss: 1.0903 - accuracy: 0.6094 - val_loss: 1.3734 - val_accuracy: 0.6084
Epoch 12/100
145/145 [==============================] - 11s 79ms/step - loss: 1.1263 - accuracy: 0.6035 - val_loss: 1.2850 - val_accuracy: 0.6136
Epoch 13/100
145/145 [==============================] - 13s 88ms/step - loss: 1.0520 - accuracy: 0.6310 - val_loss: 1.2563 - val_accuracy: 0.6154
Epoch 14/100
145/145 [==============================] - 13s 87ms/step - loss: 1.0191 - accuracy: 0.6410 - val_loss: 1.4585 - val_accuracy: 0.6036
Epoch 15/100
145/145 [==============================] - 12s 80ms/step - loss: 1.0423 - accuracy: 0.6341 - val_loss: 1.3904 - val_accuracy: 0.5993
Epoch 16/100
145/145 [==============================] - 12s 81ms/step - loss: 1.0034 - accuracy: 0.6432 - val_loss: 1.4175 - val_accuracy: 0.5976
Epoch 17/100
145/145 [==============================] - 13s 87ms/step - loss: 1.0323 - accuracy: 0.6332 - val_loss: 1.2760 - val_accuracy: 0.6271
Epoch 18/100
145/145 [==============================] - 13s 87ms/step - loss: 1.0065 - accuracy: 0.6410 - val_loss: 1.2817 - val_accuracy: 0.6227
Epoch 19/100
145/145 [==============================] - 12s 80ms/step - loss: 1.0329 - accuracy: 0.6313 - val_loss: 1.3558 - val_accuracy: 0.6158
Epoch 20/100
145/145 [==============================] - 12s 81ms/step - loss: 0.9722 - accuracy: 0.6519 - val_loss: 1.3087 - val_accuracy: 0.6271
Epoch 21/100
145/145 [==============================] - 13s 91ms/step - loss: 0.9867 - accuracy: 0.6497 - val_loss: 1.2611 - val_accuracy: 0.6158
Epoch 22/100
145/145 [==============================] - 13s 90ms/step - loss: 0.9670 - accuracy: 0.6592 - val_loss: 1.3650 - val_accuracy: 0.6071
Epoch 23/100
145/145 [==============================] - 14s 98ms/step - loss: 0.9619 - accuracy: 0.6679 - val_loss: 1.2199 - val_accuracy: 0.6422
Epoch 24/100
145/145 [==============================] - 12s 83ms/step - loss: 0.9659 - accuracy: 0.6558 - val_loss: 1.2798 - val_accuracy: 0.6240
Epoch 25/100
145/145 [==============================] - 13s 87ms/step - loss: 0.9600 - accuracy: 0.6575 - val_loss: 1.2288 - val_accuracy: 0.6336
Epoch 26/100
145/145 [==============================] - 13s 93ms/step - loss: 0.9584 - accuracy: 0.6612 - val_loss: 1.2521 - val_accuracy: 0.6318
Epoch 27/100
145/145 [==============================] - 13s 87ms/step - loss: 0.9643 - accuracy: 0.6532 - val_loss: 1.1846 - val_accuracy: 0.6370
Epoch 28/100
145/145 [==============================] - 11s 78ms/step - loss: 0.9624 - accuracy: 0.6590 - val_loss: 1.1823 - val_accuracy: 0.6340
Epoch 29/100
145/145 [==============================] - 14s 94ms/step - loss: 0.9709 - accuracy: 0.6553 - val_loss: 1.2571 - val_accuracy: 0.6184
Epoch 30/100
145/145 [==============================] - 13s 93ms/step - loss: 0.9723 - accuracy: 0.6566 - val_loss: 1.2435 - val_accuracy: 0.6240
Epoch 31/100
145/145 [==============================] - 13s 88ms/step - loss: 0.9365 - accuracy: 0.6659 - val_loss: 1.1828 - val_accuracy: 0.6401
Epoch 32/100
145/145 [==============================] - 12s 81ms/step - loss: 0.9180 - accuracy: 0.6740 - val_loss: 1.1759 - val_accuracy: 0.6379
Epoch 33/100
145/145 [==============================] - 13s 90ms/step - loss: 0.9181 - accuracy: 0.6685 - val_loss: 1.2128 - val_accuracy: 0.6344
Epoch 34/100
145/145 [==============================] - 13s 92ms/step - loss: 0.9215 - accuracy: 0.6753 - val_loss: 1.2092 - val_accuracy: 0.6362
Epoch 35/100
145/145 [==============================] - 13s 92ms/step - loss: 0.9341 - accuracy: 0.6644 - val_loss: 1.2600 - val_accuracy: 0.6357
Epoch 36/100
145/145 [==============================] - 12s 80ms/step - loss: 0.9074 - accuracy: 0.6763 - val_loss: 1.1809 - val_accuracy: 0.6470
Epoch 37/100
145/145 [==============================] - 12s 84ms/step - loss: 0.9278 - accuracy: 0.6672 - val_loss: 1.2374 - val_accuracy: 0.6448
Epoch 38/100
145/145 [==============================] - 12s 86ms/step - loss: 0.9575 - accuracy: 0.6573 - val_loss: 1.2289 - val_accuracy: 0.6349
Epoch 39/100
145/145 [==============================] - 12s 83ms/step - loss: 0.9023 - accuracy: 0.6757 - val_loss: 1.2292 - val_accuracy: 0.6266
Epoch 40/100
145/145 [==============================] - 11s 74ms/step - loss: 0.9036 - accuracy: 0.6800 - val_loss: 1.2225 - val_accuracy: 0.6396
Epoch 41/100
145/145 [==============================] - 13s 87ms/step - loss: 0.9112 - accuracy: 0.6692 - val_loss: 1.2337 - val_accuracy: 0.6509
Epoch 42/100
145/145 [==============================] - 13s 91ms/step - loss: 0.9026 - accuracy: 0.6763 - val_loss: 1.2500 - val_accuracy: 0.6453
Epoch 43/100
145/145 [==============================] - 12s 83ms/step - loss: 0.9362 - accuracy: 0.6729 - val_loss: 1.2151 - val_accuracy: 0.6418
Epoch 44/100
145/145 [==============================] - 12s 81ms/step - loss: 0.8933 - accuracy: 0.6783 - val_loss: 1.2426 - val_accuracy: 0.6466
Epoch 45/100
145/145 [==============================] - 16s 108ms/step - loss: 0.9181 - accuracy: 0.6631 - val_loss: 1.2549 - val_accuracy: 0.6435
Epoch 46/100
145/145 [==============================] - 12s 83ms/step - loss: 0.9009 - accuracy: 0.6731 - val_loss: 1.2312 - val_accuracy: 0.6340
Epoch 47/100
145/145 [==============================] - 11s 79ms/step - loss: 0.9091 - accuracy: 0.6668 - val_loss: 1.2634 - val_accuracy: 0.6301
Epoch 48/100
145/145 [==============================] - 13s 91ms/step - loss: 0.9068 - accuracy: 0.6792 - val_loss: 1.1839 - val_accuracy: 0.6500
Epoch 49/100
145/145 [==============================] - 13s 91ms/step - loss: 0.8973 - accuracy: 0.6826 - val_loss: 1.2358 - val_accuracy: 0.6375
Epoch 50/100
145/145 [==============================] - 12s 81ms/step - loss: 0.9074 - accuracy: 0.6768 - val_loss: 1.1649 - val_accuracy: 0.6505
Epoch 51/100
145/145 [==============================] - 12s 81ms/step - loss: 0.8955 - accuracy: 0.6755 - val_loss: 1.2585 - val_accuracy: 0.6427
Epoch 52/100
145/145 [==============================] - 13s 90ms/step - loss: 0.8985 - accuracy: 0.6826 - val_loss: 1.1303 - val_accuracy: 0.6474
Epoch 53/100
145/145 [==============================] - 13s 89ms/step - loss: 0.9145 - accuracy: 0.6750 - val_loss: 1.2193 - val_accuracy: 0.6474
Epoch 54/100
145/145 [==============================] - 11s 78ms/step - loss: 0.8921 - accuracy: 0.6796 - val_loss: 1.2019 - val_accuracy: 0.6470
Epoch 55/100
145/145 [==============================] - 12s 85ms/step - loss: 0.8893 - accuracy: 0.6781 - val_loss: 1.1611 - val_accuracy: 0.6401
Epoch 56/100
145/145 [==============================] - 14s 95ms/step - loss: 0.8999 - accuracy: 0.6759 - val_loss: 1.2030 - val_accuracy: 0.6531
Epoch 57/100
145/145 [==============================] - 12s 84ms/step - loss: 0.8925 - accuracy: 0.6863 - val_loss: 1.1339 - val_accuracy: 0.6665
Epoch 58/100
145/145 [==============================] - 11s 76ms/step - loss: 0.8838 - accuracy: 0.6874 - val_loss: 1.1812 - val_accuracy: 0.6574
Epoch 59/100
145/145 [==============================] - 13s 91ms/step - loss: 0.8763 - accuracy: 0.6837 - val_loss: 1.1849 - val_accuracy: 0.6557
Epoch 60/100
145/145 [==============================] - 14s 94ms/step - loss: 0.8867 - accuracy: 0.6748 - val_loss: 1.1997 - val_accuracy: 0.6461
Epoch 61/100
145/145 [==============================] - 14s 96ms/step - loss: 0.8694 - accuracy: 0.6950 - val_loss: 1.2423 - val_accuracy: 0.6500
Epoch 62/100
145/145 [==============================] - 12s 85ms/step - loss: 0.8724 - accuracy: 0.6883 - val_loss: 1.1912 - val_accuracy: 0.6466
Epoch 63/100
145/145 [==============================] - 12s 80ms/step - loss: 0.8855 - accuracy: 0.6839 - val_loss: 1.1933 - val_accuracy: 0.6483
Epoch 64/100
145/145 [==============================] - 13s 89ms/step - loss: 0.8510 - accuracy: 0.6937 - val_loss: 1.1920 - val_accuracy: 0.6596
Epoch 65/100
145/145 [==============================] - 13s 90ms/step - loss: 0.8896 - accuracy: 0.6809 - val_loss: 1.1754 - val_accuracy: 0.6479
Epoch 66/100
145/145 [==============================] - 13s 93ms/step - loss: 0.8684 - accuracy: 0.6783 - val_loss: 1.1989 - val_accuracy: 0.6539
Epoch 67/100
145/145 [==============================] - 13s 86ms/step - loss: 0.8911 - accuracy: 0.6813 - val_loss: 1.2289 - val_accuracy: 0.6392
Epoch 68/100
145/145 [==============================] - 13s 88ms/step - loss: 0.8777 - accuracy: 0.6839 - val_loss: 1.1831 - val_accuracy: 0.6505
Epoch 69/100
145/145 [==============================] - 14s 94ms/step - loss: 0.8771 - accuracy: 0.6848 - val_loss: 1.1645 - val_accuracy: 0.6496
Epoch 70/100
145/145 [==============================] - 11s 76ms/step - loss: 0.9076 - accuracy: 0.6779 - val_loss: 1.2234 - val_accuracy: 0.6375
Epoch 71/100
145/145 [==============================] - 13s 87ms/step - loss: 0.8938 - accuracy: 0.6824 - val_loss: 1.1795 - val_accuracy: 0.6578
Epoch 72/100
145/145 [==============================] - 13s 93ms/step - loss: 0.8527 - accuracy: 0.6874 - val_loss: 1.2055 - val_accuracy: 0.6435
Epoch 73/100
145/145 [==============================] - 13s 91ms/step - loss: 0.8788 - accuracy: 0.6792 - val_loss: 1.2436 - val_accuracy: 0.6370
Epoch 74/100
145/145 [==============================] - 12s 82ms/step - loss: 0.8766 - accuracy: 0.6850 - val_loss: 1.1891 - val_accuracy: 0.6500
Epoch 75/100
145/145 [==============================] - 13s 88ms/step - loss: 0.8859 - accuracy: 0.6707 - val_loss: 1.1388 - val_accuracy: 0.6631
Epoch 76/100
145/145 [==============================] - 13s 89ms/step - loss: 0.8831 - accuracy: 0.6928 - val_loss: 1.1786 - val_accuracy: 0.6500
Epoch 77/100
145/145 [==============================] - 14s 93ms/step - loss: 0.8652 - accuracy: 0.6911 - val_loss: 1.1721 - val_accuracy: 0.6513
Epoch 78/100
145/145 [==============================] - 11s 79ms/step - loss: 0.8773 - accuracy: 0.6896 - val_loss: 1.1391 - val_accuracy: 0.6561
Epoch 79/100
145/145 [==============================] - 12s 84ms/step - loss: 0.8538 - accuracy: 0.6941 - val_loss: 1.1855 - val_accuracy: 0.6565
Epoch 80/100
145/145 [==============================] - 14s 94ms/step - loss: 0.8437 - accuracy: 0.7013 - val_loss: 1.2112 - val_accuracy: 0.6496
Epoch 81/100
145/145 [==============================] - 13s 92ms/step - loss: 0.8501 - accuracy: 0.6904 - val_loss: 1.2129 - val_accuracy: 0.6487
Epoch 82/100
145/145 [==============================] - 12s 86ms/step - loss: 0.8569 - accuracy: 0.6939 - val_loss: 1.2285 - val_accuracy: 0.6518
Epoch 83/100
145/145 [==============================] - 12s 85ms/step - loss: 0.8544 - accuracy: 0.6865 - val_loss: 1.2461 - val_accuracy: 0.6552
Epoch 84/100
145/145 [==============================] - 18s 122ms/step - loss: 0.8455 - accuracy: 0.6920 - val_loss: 1.2962 - val_accuracy: 0.6440
Epoch 85/100
145/145 [==============================] - 24s 166ms/step - loss: 0.8937 - accuracy: 0.6766 - val_loss: 1.2258 - val_accuracy: 0.6461
Epoch 86/100
145/145 [==============================] - 13s 93ms/step - loss: 0.9023 - accuracy: 0.6796 - val_loss: 1.2218 - val_accuracy: 0.6496
Epoch 87/100
145/145 [==============================] - 14s 97ms/step - loss: 0.8805 - accuracy: 0.6846 - val_loss: 1.2497 - val_accuracy: 0.6505
Epoch 88/100
145/145 [==============================] - 16s 113ms/step - loss: 0.8687 - accuracy: 0.6943 - val_loss: 1.1476 - val_accuracy: 0.6557
Epoch 89/100
145/145 [==============================] - 13s 93ms/step - loss: 0.8463 - accuracy: 0.6959 - val_loss: 1.1578 - val_accuracy: 0.6513
Epoch 90/100
145/145 [==============================] - 13s 87ms/step - loss: 0.8478 - accuracy: 0.6924 - val_loss: 1.2068 - val_accuracy: 0.6548
Epoch 91/100
145/145 [==============================] - 12s 80ms/step - loss: 0.8760 - accuracy: 0.6894 - val_loss: 1.1878 - val_accuracy: 0.6592
Epoch 92/100
145/145 [==============================] - 14s 95ms/step - loss: 0.8770 - accuracy: 0.6848 - val_loss: 1.2183 - val_accuracy: 0.6474
Epoch 93/100
145/145 [==============================] - 14s 95ms/step - loss: 0.8684 - accuracy: 0.6846 - val_loss: 1.1665 - val_accuracy: 0.6578
Epoch 94/100
145/145 [==============================] - 13s 91ms/step - loss: 0.8546 - accuracy: 0.6937 - val_loss: 1.1761 - val_accuracy: 0.6609
Epoch 95/100
145/145 [==============================] - 13s 89ms/step - loss: 0.8659 - accuracy: 0.6926 - val_loss: 1.2673 - val_accuracy: 0.6392
Epoch 96/100
145/145 [==============================] - 12s 80ms/step - loss: 0.8776 - accuracy: 0.6868 - val_loss: 1.1815 - val_accuracy: 0.6487
Epoch 97/100
145/145 [==============================] - 13s 90ms/step - loss: 0.8354 - accuracy: 0.6937 - val_loss: 1.1713 - val_accuracy: 0.6535
Epoch 98/100
145/145 [==============================] - 13s 93ms/step - loss: 0.8586 - accuracy: 0.6956 - val_loss: 1.1698 - val_accuracy: 0.6618
Epoch 99/100
145/145 [==============================] - 14s 97ms/step - loss: 0.8370 - accuracy: 0.7008 - val_loss: 1.1901 - val_accuracy: 0.6552
Epoch 100/100
145/145 [==============================] - 12s 81ms/step - loss: 0.8441 - accuracy: 0.6943 - val_loss: 1.1668 - val_accuracy: 0.6600

In [ ]:
model_2006.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
history = model_2006.fit(x_train, y_train, epochs=100, validation_data=(X_val, Y_val))

Epoch 1/100
145/145 [==============================] - 16s 93ms/step - loss: 0.8258 - accuracy: 0.7037 - val_loss: 1.1386 - val_accuracy: 0.6665
Epoch 2/100
145/145 [==============================] - 14s 98ms/step - loss: 0.7963 - accuracy: 0.7128 - val_loss: 1.1376 - val_accuracy: 0.6696
Epoch 3/100
145/145 [==============================] - 12s 85ms/step - loss: 0.7825 - accuracy: 0.7128 - val_loss: 1.1411 - val_accuracy: 0.6670
Epoch 4/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7843 - accuracy: 0.7186 - val_loss: 1.1565 - val_accuracy: 0.6648
Epoch 5/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7729 - accuracy: 0.7256 - val_loss: 1.1363 - val_accuracy: 0.6700
Epoch 6/100
145/145 [==============================] - 11s 76ms/step - loss: 0.7857 - accuracy: 0.7162 - val_loss: 1.1317 - val_accuracy: 0.6670
Epoch 7/100
145/145 [==============================] - 12s 83ms/step - loss: 0.7916 - accuracy: 0.7234 - val_loss: 1.1349 - val_accuracy: 0.6704
Epoch 8/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7864 - accuracy: 0.7086 - val_loss: 1.1286 - val_accuracy: 0.6774
Epoch 9/100
145/145 [==============================] - 12s 86ms/step - loss: 0.7746 - accuracy: 0.7169 - val_loss: 1.1297 - val_accuracy: 0.6717
Epoch 10/100
145/145 [==============================] - 18s 125ms/step - loss: 0.7774 - accuracy: 0.7182 - val_loss: 1.1381 - val_accuracy: 0.6739
Epoch 11/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7651 - accuracy: 0.7206 - val_loss: 1.1350 - val_accuracy: 0.6730
Epoch 12/100
145/145 [==============================] - 13s 89ms/step - loss: 0.7539 - accuracy: 0.7282 - val_loss: 1.1316 - val_accuracy: 0.6704
Epoch 13/100
145/145 [==============================] - 13s 90ms/step - loss: 0.7781 - accuracy: 0.7188 - val_loss: 1.1379 - val_accuracy: 0.6752
Epoch 14/100
145/145 [==============================] - 13s 89ms/step - loss: 0.7706 - accuracy: 0.7204 - val_loss: 1.1434 - val_accuracy: 0.6739
Epoch 15/100
145/145 [==============================] - 13s 86ms/step - loss: 0.7429 - accuracy: 0.7303 - val_loss: 1.1454 - val_accuracy: 0.6709
Epoch 16/100
145/145 [==============================] - 12s 79ms/step - loss: 0.7831 - accuracy: 0.7147 - val_loss: 1.1455 - val_accuracy: 0.6717
Epoch 17/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7703 - accuracy: 0.7173 - val_loss: 1.1414 - val_accuracy: 0.6752
Epoch 18/100
145/145 [==============================] - 13s 90ms/step - loss: 0.7596 - accuracy: 0.7247 - val_loss: 1.1429 - val_accuracy: 0.6730
Epoch 19/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7549 - accuracy: 0.7303 - val_loss: 1.1342 - val_accuracy: 0.6743
Epoch 20/100
145/145 [==============================] - 14s 95ms/step - loss: 0.7647 - accuracy: 0.7186 - val_loss: 1.1471 - val_accuracy: 0.6739
Epoch 21/100
145/145 [==============================] - 12s 83ms/step - loss: 0.7583 - accuracy: 0.7238 - val_loss: 1.1483 - val_accuracy: 0.6748
Epoch 22/100
145/145 [==============================] - 12s 80ms/step - loss: 0.7398 - accuracy: 0.7334 - val_loss: 1.1498 - val_accuracy: 0.6774
Epoch 23/100
145/145 [==============================] - 14s 98ms/step - loss: 0.7552 - accuracy: 0.7336 - val_loss: 1.1489 - val_accuracy: 0.6782
Epoch 24/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7569 - accuracy: 0.7260 - val_loss: 1.1503 - val_accuracy: 0.6761
Epoch 25/100
145/145 [==============================] - 14s 96ms/step - loss: 0.7561 - accuracy: 0.7264 - val_loss: 1.1471 - val_accuracy: 0.6761
Epoch 26/100
145/145 [==============================] - 12s 83ms/step - loss: 0.7533 - accuracy: 0.7251 - val_loss: 1.1558 - val_accuracy: 0.6752
Epoch 27/100
145/145 [==============================] - 12s 80ms/step - loss: 0.7474 - accuracy: 0.7286 - val_loss: 1.1445 - val_accuracy: 0.6769
Epoch 28/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7569 - accuracy: 0.7275 - val_loss: 1.1540 - val_accuracy: 0.6726
Epoch 29/100
145/145 [==============================] - 13s 89ms/step - loss: 0.7470 - accuracy: 0.7312 - val_loss: 1.1422 - val_accuracy: 0.6769
Epoch 30/100
145/145 [==============================] - 13s 89ms/step - loss: 0.7486 - accuracy: 0.7305 - val_loss: 1.1426 - val_accuracy: 0.6748
Epoch 31/100
145/145 [==============================] - 11s 79ms/step - loss: 0.7515 - accuracy: 0.7297 - val_loss: 1.1401 - val_accuracy: 0.6769
Epoch 32/100
145/145 [==============================] - 12s 81ms/step - loss: 0.7334 - accuracy: 0.7407 - val_loss: 1.1533 - val_accuracy: 0.6743
Epoch 33/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7386 - accuracy: 0.7362 - val_loss: 1.1466 - val_accuracy: 0.6765
Epoch 34/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7363 - accuracy: 0.7312 - val_loss: 1.1486 - val_accuracy: 0.6717
Epoch 35/100
145/145 [==============================] - 12s 83ms/step - loss: 0.7413 - accuracy: 0.7286 - val_loss: 1.1505 - val_accuracy: 0.6700
Epoch 36/100
145/145 [==============================] - 11s 75ms/step - loss: 0.7491 - accuracy: 0.7219 - val_loss: 1.1502 - val_accuracy: 0.6752
Epoch 37/100
145/145 [==============================] - 12s 85ms/step - loss: 0.7385 - accuracy: 0.7290 - val_loss: 1.1610 - val_accuracy: 0.6713
Epoch 38/100
145/145 [==============================] - 13s 92ms/step - loss: 0.7248 - accuracy: 0.7355 - val_loss: 1.1518 - val_accuracy: 0.6726
Epoch 39/100
145/145 [==============================] - 13s 93ms/step - loss: 0.7344 - accuracy: 0.7314 - val_loss: 1.1581 - val_accuracy: 0.6730
Epoch 40/100
145/145 [==============================] - 12s 85ms/step - loss: 0.7238 - accuracy: 0.7394 - val_loss: 1.1512 - val_accuracy: 0.6769
Epoch 41/100
145/145 [==============================] - 11s 77ms/step - loss: 0.7380 - accuracy: 0.7383 - val_loss: 1.1677 - val_accuracy: 0.6691
Epoch 42/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7314 - accuracy: 0.7336 - val_loss: 1.1504 - val_accuracy: 0.6722
Epoch 43/100
145/145 [==============================] - 14s 94ms/step - loss: 0.7328 - accuracy: 0.7301 - val_loss: 1.1434 - val_accuracy: 0.6717
Epoch 44/100
145/145 [==============================] - 13s 92ms/step - loss: 0.7226 - accuracy: 0.7396 - val_loss: 1.1499 - val_accuracy: 0.6748
Epoch 45/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7295 - accuracy: 0.7379 - val_loss: 1.1510 - val_accuracy: 0.6726
Epoch 46/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7363 - accuracy: 0.7312 - val_loss: 1.1456 - val_accuracy: 0.6752
Epoch 47/100
145/145 [==============================] - 11s 75ms/step - loss: 0.7313 - accuracy: 0.7392 - val_loss: 1.1539 - val_accuracy: 0.6782
Epoch 48/100
145/145 [==============================] - 12s 81ms/step - loss: 0.7200 - accuracy: 0.7440 - val_loss: 1.1573 - val_accuracy: 0.6752
Epoch 49/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7473 - accuracy: 0.7299 - val_loss: 1.1608 - val_accuracy: 0.6739
Epoch 50/100
145/145 [==============================] - 12s 86ms/step - loss: 0.7467 - accuracy: 0.7388 - val_loss: 1.1627 - val_accuracy: 0.6726
Epoch 51/100
145/145 [==============================] - 12s 81ms/step - loss: 0.7249 - accuracy: 0.7401 - val_loss: 1.1574 - val_accuracy: 0.6765
Epoch 52/100
145/145 [==============================] - 12s 80ms/step - loss: 0.7163 - accuracy: 0.7438 - val_loss: 1.1560 - val_accuracy: 0.6726
Epoch 53/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7336 - accuracy: 0.7353 - val_loss: 1.1619 - val_accuracy: 0.6756
Epoch 54/100
145/145 [==============================] - 12s 81ms/step - loss: 0.7252 - accuracy: 0.7347 - val_loss: 1.1601 - val_accuracy: 0.6761
Epoch 55/100
145/145 [==============================] - 12s 82ms/step - loss: 0.7304 - accuracy: 0.7407 - val_loss: 1.1629 - val_accuracy: 0.6726
Epoch 56/100
145/145 [==============================] - 11s 76ms/step - loss: 0.7202 - accuracy: 0.7425 - val_loss: 1.1747 - val_accuracy: 0.6691
Epoch 57/100
145/145 [==============================] - 12s 82ms/step - loss: 0.7375 - accuracy: 0.7282 - val_loss: 1.1642 - val_accuracy: 0.6678
Epoch 58/100
145/145 [==============================] - 12s 85ms/step - loss: 0.7193 - accuracy: 0.7438 - val_loss: 1.1501 - val_accuracy: 0.6743
Epoch 59/100
145/145 [==============================] - 15s 103ms/step - loss: 0.7118 - accuracy: 0.7464 - val_loss: 1.1582 - val_accuracy: 0.6722
Epoch 60/100
145/145 [==============================] - 14s 95ms/step - loss: 0.7208 - accuracy: 0.7451 - val_loss: 1.1657 - val_accuracy: 0.6691
Epoch 61/100
145/145 [==============================] - 12s 85ms/step - loss: 0.7209 - accuracy: 0.7362 - val_loss: 1.1521 - val_accuracy: 0.6748
Epoch 62/100
145/145 [==============================] - 11s 78ms/step - loss: 0.7203 - accuracy: 0.7405 - val_loss: 1.1620 - val_accuracy: 0.6739
Epoch 63/100
145/145 [==============================] - 13s 86ms/step - loss: 0.7125 - accuracy: 0.7388 - val_loss: 1.1581 - val_accuracy: 0.6730
Epoch 64/100
145/145 [==============================] - 14s 99ms/step - loss: 0.7202 - accuracy: 0.7329 - val_loss: 1.1663 - val_accuracy: 0.6730
Epoch 65/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7211 - accuracy: 0.7470 - val_loss: 1.1511 - val_accuracy: 0.6791
Epoch 66/100
145/145 [==============================] - 12s 83ms/step - loss: 0.7226 - accuracy: 0.7433 - val_loss: 1.1587 - val_accuracy: 0.6787
Epoch 67/100
145/145 [==============================] - 11s 78ms/step - loss: 0.7223 - accuracy: 0.7375 - val_loss: 1.1513 - val_accuracy: 0.6804
Epoch 68/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7161 - accuracy: 0.7377 - val_loss: 1.1561 - val_accuracy: 0.6774
Epoch 69/100
145/145 [==============================] - 12s 86ms/step - loss: 0.7143 - accuracy: 0.7379 - val_loss: 1.1477 - val_accuracy: 0.6791
Epoch 70/100
145/145 [==============================] - 13s 91ms/step - loss: 0.7028 - accuracy: 0.7423 - val_loss: 1.1501 - val_accuracy: 0.6795
Epoch 71/100
145/145 [==============================] - 13s 89ms/step - loss: 0.7127 - accuracy: 0.7444 - val_loss: 1.1392 - val_accuracy: 0.6813
Epoch 72/100
145/145 [==============================] - 12s 82ms/step - loss: 0.7325 - accuracy: 0.7349 - val_loss: 1.1453 - val_accuracy: 0.6821
Epoch 73/100
145/145 [==============================] - 12s 81ms/step - loss: 0.7223 - accuracy: 0.7314 - val_loss: 1.1489 - val_accuracy: 0.6743
Epoch 74/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7194 - accuracy: 0.7399 - val_loss: 1.1445 - val_accuracy: 0.6717
Epoch 75/100
145/145 [==============================] - 13s 89ms/step - loss: 0.7286 - accuracy: 0.7329 - val_loss: 1.1516 - val_accuracy: 0.6769
Epoch 76/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7149 - accuracy: 0.7373 - val_loss: 1.1651 - val_accuracy: 0.6752
Epoch 77/100
145/145 [==============================] - 13s 92ms/step - loss: 0.7100 - accuracy: 0.7449 - val_loss: 1.1461 - val_accuracy: 0.6765
Epoch 78/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7229 - accuracy: 0.7438 - val_loss: 1.1540 - val_accuracy: 0.6791
Epoch 79/100
145/145 [==============================] - 11s 79ms/step - loss: 0.7007 - accuracy: 0.7496 - val_loss: 1.1457 - val_accuracy: 0.6752
Epoch 80/100
145/145 [==============================] - 12s 86ms/step - loss: 0.7025 - accuracy: 0.7407 - val_loss: 1.1580 - val_accuracy: 0.6752
Epoch 81/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7169 - accuracy: 0.7462 - val_loss: 1.1486 - val_accuracy: 0.6752
Epoch 82/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7099 - accuracy: 0.7386 - val_loss: 1.1347 - val_accuracy: 0.6769
Epoch 83/100
145/145 [==============================] - 12s 82ms/step - loss: 0.7095 - accuracy: 0.7429 - val_loss: 1.1549 - val_accuracy: 0.6782
Epoch 84/100
145/145 [==============================] - 11s 78ms/step - loss: 0.6957 - accuracy: 0.7451 - val_loss: 1.1593 - val_accuracy: 0.6709
Epoch 85/100
145/145 [==============================] - 14s 95ms/step - loss: 0.7050 - accuracy: 0.7501 - val_loss: 1.1446 - val_accuracy: 0.6782
Epoch 86/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7030 - accuracy: 0.7412 - val_loss: 1.1354 - val_accuracy: 0.6761
Epoch 87/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7105 - accuracy: 0.7396 - val_loss: 1.1432 - val_accuracy: 0.6787
Epoch 88/100
145/145 [==============================] - 12s 86ms/step - loss: 0.7014 - accuracy: 0.7429 - val_loss: 1.1511 - val_accuracy: 0.6765
Epoch 89/100
145/145 [==============================] - 12s 80ms/step - loss: 0.7205 - accuracy: 0.7351 - val_loss: 1.1410 - val_accuracy: 0.6769
Epoch 90/100
145/145 [==============================] - 12s 80ms/step - loss: 0.6976 - accuracy: 0.7472 - val_loss: 1.1388 - val_accuracy: 0.6769
Epoch 91/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7195 - accuracy: 0.7370 - val_loss: 1.1355 - val_accuracy: 0.6804
Epoch 92/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7019 - accuracy: 0.7457 - val_loss: 1.1416 - val_accuracy: 0.6756
Epoch 93/100
145/145 [==============================] - 12s 85ms/step - loss: 0.7032 - accuracy: 0.7485 - val_loss: 1.1429 - val_accuracy: 0.6808
Epoch 94/100
145/145 [==============================] - 13s 89ms/step - loss: 0.7226 - accuracy: 0.7414 - val_loss: 1.1308 - val_accuracy: 0.6804
Epoch 95/100
145/145 [==============================] - 12s 79ms/step - loss: 0.7066 - accuracy: 0.7457 - val_loss: 1.1425 - val_accuracy: 0.6800
Epoch 96/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7267 - accuracy: 0.7405 - val_loss: 1.1422 - val_accuracy: 0.6804
Epoch 97/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7076 - accuracy: 0.7494 - val_loss: 1.1413 - val_accuracy: 0.6769
Epoch 98/100
145/145 [==============================] - 13s 90ms/step - loss: 0.6953 - accuracy: 0.7483 - val_loss: 1.1498 - val_accuracy: 0.6782
Epoch 99/100
145/145 [==============================] - 13s 89ms/step - loss: 0.6955 - accuracy: 0.7514 - val_loss: 1.1365 - val_accuracy: 0.6800
Epoch 100/100
145/145 [==============================] - 12s 81ms/step - loss: 0.7021 - accuracy: 0.7516 - val_loss: 1.1415 - val_accuracy: 0.6869

In [ ]:
model_2006.compile(optimizer=tf.keras.optimizers.Adam(0.00001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
history = model_2006.fit(x_train, y_train, epochs=100, validation_data=(X_val, Y_val))

Epoch 1/100
145/145 [==============================] - 14s 87ms/step - loss: 0.6969 - accuracy: 0.7464 - val_loss: 1.1407 - val_accuracy: 0.6860
Epoch 2/100
145/145 [==============================] - 12s 81ms/step - loss: 0.7082 - accuracy: 0.7431 - val_loss: 1.1401 - val_accuracy: 0.6852
Epoch 3/100
145/145 [==============================] - 13s 91ms/step - loss: 0.6893 - accuracy: 0.7477 - val_loss: 1.1398 - val_accuracy: 0.6856
Epoch 4/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7043 - accuracy: 0.7429 - val_loss: 1.1388 - val_accuracy: 0.6852
Epoch 5/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6980 - accuracy: 0.7468 - val_loss: 1.1391 - val_accuracy: 0.6834
Epoch 6/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6961 - accuracy: 0.7509 - val_loss: 1.1400 - val_accuracy: 0.6834
Epoch 7/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7000 - accuracy: 0.7470 - val_loss: 1.1407 - val_accuracy: 0.6834
Epoch 8/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7030 - accuracy: 0.7414 - val_loss: 1.1381 - val_accuracy: 0.6834
Epoch 9/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6944 - accuracy: 0.7457 - val_loss: 1.1395 - val_accuracy: 0.6843
Epoch 10/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6966 - accuracy: 0.7492 - val_loss: 1.1388 - val_accuracy: 0.6834
Epoch 11/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6939 - accuracy: 0.7492 - val_loss: 1.1385 - val_accuracy: 0.6834
Epoch 12/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6833 - accuracy: 0.7531 - val_loss: 1.1390 - val_accuracy: 0.6821
Epoch 13/100
145/145 [==============================] - 12s 85ms/step - loss: 0.7007 - accuracy: 0.7496 - val_loss: 1.1387 - val_accuracy: 0.6826
Epoch 14/100
145/145 [==============================] - 11s 76ms/step - loss: 0.6916 - accuracy: 0.7444 - val_loss: 1.1399 - val_accuracy: 0.6813
Epoch 15/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6949 - accuracy: 0.7494 - val_loss: 1.1399 - val_accuracy: 0.6826
Epoch 16/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6917 - accuracy: 0.7518 - val_loss: 1.1382 - val_accuracy: 0.6821
Epoch 17/100
145/145 [==============================] - 13s 89ms/step - loss: 0.6914 - accuracy: 0.7509 - val_loss: 1.1390 - val_accuracy: 0.6826
Epoch 18/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6917 - accuracy: 0.7548 - val_loss: 1.1401 - val_accuracy: 0.6826
Epoch 19/100
145/145 [==============================] - 11s 78ms/step - loss: 0.6895 - accuracy: 0.7490 - val_loss: 1.1400 - val_accuracy: 0.6834
Epoch 20/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6895 - accuracy: 0.7587 - val_loss: 1.1394 - val_accuracy: 0.6826
Epoch 21/100
145/145 [==============================] - 12s 82ms/step - loss: 0.7091 - accuracy: 0.7436 - val_loss: 1.1406 - val_accuracy: 0.6834
Epoch 22/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6768 - accuracy: 0.7553 - val_loss: 1.1418 - val_accuracy: 0.6856
Epoch 23/100
145/145 [==============================] - 12s 86ms/step - loss: 0.7064 - accuracy: 0.7449 - val_loss: 1.1392 - val_accuracy: 0.6847
Epoch 24/100
145/145 [==============================] - 15s 101ms/step - loss: 0.7071 - accuracy: 0.7468 - val_loss: 1.1407 - val_accuracy: 0.6856
Epoch 25/100
145/145 [==============================] - 11s 73ms/step - loss: 0.6931 - accuracy: 0.7414 - val_loss: 1.1409 - val_accuracy: 0.6843
Epoch 26/100
145/145 [==============================] - 12s 81ms/step - loss: 0.7027 - accuracy: 0.7475 - val_loss: 1.1400 - val_accuracy: 0.6843
Epoch 27/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6825 - accuracy: 0.7527 - val_loss: 1.1394 - val_accuracy: 0.6843
Epoch 28/100
145/145 [==============================] - 11s 79ms/step - loss: 0.6997 - accuracy: 0.7449 - val_loss: 1.1409 - val_accuracy: 0.6847
Epoch 29/100
145/145 [==============================] - 11s 76ms/step - loss: 0.6761 - accuracy: 0.7516 - val_loss: 1.1419 - val_accuracy: 0.6843
Epoch 30/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6850 - accuracy: 0.7546 - val_loss: 1.1410 - val_accuracy: 0.6839
Epoch 31/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6944 - accuracy: 0.7544 - val_loss: 1.1419 - val_accuracy: 0.6860
Epoch 32/100
145/145 [==============================] - 12s 81ms/step - loss: 0.6856 - accuracy: 0.7446 - val_loss: 1.1399 - val_accuracy: 0.6856
Epoch 33/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7012 - accuracy: 0.7453 - val_loss: 1.1391 - val_accuracy: 0.6847
Epoch 34/100
145/145 [==============================] - 10s 70ms/step - loss: 0.7079 - accuracy: 0.7464 - val_loss: 1.1399 - val_accuracy: 0.6843
Epoch 35/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7003 - accuracy: 0.7479 - val_loss: 1.1387 - val_accuracy: 0.6843
Epoch 36/100
145/145 [==============================] - 12s 81ms/step - loss: 0.7047 - accuracy: 0.7462 - val_loss: 1.1389 - val_accuracy: 0.6847
Epoch 37/100
145/145 [==============================] - 12s 83ms/step - loss: 0.7017 - accuracy: 0.7503 - val_loss: 1.1401 - val_accuracy: 0.6856
Epoch 38/100
145/145 [==============================] - 11s 75ms/step - loss: 0.7071 - accuracy: 0.7405 - val_loss: 1.1381 - val_accuracy: 0.6852
Epoch 39/100
145/145 [==============================] - 12s 81ms/step - loss: 0.7000 - accuracy: 0.7468 - val_loss: 1.1382 - val_accuracy: 0.6847
Epoch 40/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6983 - accuracy: 0.7505 - val_loss: 1.1380 - val_accuracy: 0.6852
Epoch 41/100
145/145 [==============================] - 12s 83ms/step - loss: 0.7026 - accuracy: 0.7509 - val_loss: 1.1375 - val_accuracy: 0.6852
Epoch 42/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6834 - accuracy: 0.7531 - val_loss: 1.1373 - val_accuracy: 0.6839
Epoch 43/100
145/145 [==============================] - 11s 79ms/step - loss: 0.7014 - accuracy: 0.7472 - val_loss: 1.1367 - val_accuracy: 0.6843
Epoch 44/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6910 - accuracy: 0.7479 - val_loss: 1.1366 - val_accuracy: 0.6839
Epoch 45/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7038 - accuracy: 0.7416 - val_loss: 1.1354 - val_accuracy: 0.6834
Epoch 46/100
145/145 [==============================] - 13s 91ms/step - loss: 0.6980 - accuracy: 0.7483 - val_loss: 1.1353 - val_accuracy: 0.6843
Epoch 47/100
145/145 [==============================] - 12s 80ms/step - loss: 0.6915 - accuracy: 0.7501 - val_loss: 1.1360 - val_accuracy: 0.6830
Epoch 48/100
145/145 [==============================] - 11s 73ms/step - loss: 0.6964 - accuracy: 0.7511 - val_loss: 1.1367 - val_accuracy: 0.6843
Epoch 49/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6995 - accuracy: 0.7483 - val_loss: 1.1378 - val_accuracy: 0.6843
Epoch 50/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6822 - accuracy: 0.7537 - val_loss: 1.1385 - val_accuracy: 0.6847
Epoch 51/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6951 - accuracy: 0.7427 - val_loss: 1.1384 - val_accuracy: 0.6856
Epoch 52/100
145/145 [==============================] - 13s 92ms/step - loss: 0.6983 - accuracy: 0.7455 - val_loss: 1.1392 - val_accuracy: 0.6830
Epoch 53/100
145/145 [==============================] - 12s 81ms/step - loss: 0.6824 - accuracy: 0.7598 - val_loss: 1.1374 - val_accuracy: 0.6839
Epoch 54/100
145/145 [==============================] - 12s 81ms/step - loss: 0.6733 - accuracy: 0.7527 - val_loss: 1.1381 - val_accuracy: 0.6839
Epoch 55/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6863 - accuracy: 0.7451 - val_loss: 1.1373 - val_accuracy: 0.6852
Epoch 56/100
145/145 [==============================] - 13s 91ms/step - loss: 0.6941 - accuracy: 0.7490 - val_loss: 1.1367 - val_accuracy: 0.6860
Epoch 57/100
145/145 [==============================] - 13s 89ms/step - loss: 0.6941 - accuracy: 0.7492 - val_loss: 1.1354 - val_accuracy: 0.6847
Epoch 58/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6920 - accuracy: 0.7498 - val_loss: 1.1355 - val_accuracy: 0.6852
Epoch 59/100
145/145 [==============================] - 12s 80ms/step - loss: 0.6854 - accuracy: 0.7505 - val_loss: 1.1364 - val_accuracy: 0.6856
Epoch 60/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6991 - accuracy: 0.7520 - val_loss: 1.1359 - val_accuracy: 0.6852
Epoch 61/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6962 - accuracy: 0.7457 - val_loss: 1.1346 - val_accuracy: 0.6865
Epoch 62/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6906 - accuracy: 0.7449 - val_loss: 1.1356 - val_accuracy: 0.6865
Epoch 63/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6915 - accuracy: 0.7425 - val_loss: 1.1348 - val_accuracy: 0.6860
Epoch 64/100
145/145 [==============================] - 10s 72ms/step - loss: 0.6894 - accuracy: 0.7449 - val_loss: 1.1353 - val_accuracy: 0.6860
Epoch 65/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6860 - accuracy: 0.7436 - val_loss: 1.1368 - val_accuracy: 0.6865
Epoch 66/100
145/145 [==============================] - 14s 98ms/step - loss: 0.7008 - accuracy: 0.7468 - val_loss: 1.1377 - val_accuracy: 0.6860
Epoch 67/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6979 - accuracy: 0.7520 - val_loss: 1.1375 - val_accuracy: 0.6856
Epoch 68/100
145/145 [==============================] - 13s 90ms/step - loss: 0.7185 - accuracy: 0.7399 - val_loss: 1.1377 - val_accuracy: 0.6856
Epoch 69/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6963 - accuracy: 0.7498 - val_loss: 1.1382 - val_accuracy: 0.6843
Epoch 70/100
145/145 [==============================] - 11s 79ms/step - loss: 0.6886 - accuracy: 0.7527 - val_loss: 1.1403 - val_accuracy: 0.6860
Epoch 71/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6990 - accuracy: 0.7533 - val_loss: 1.1394 - val_accuracy: 0.6869
Epoch 72/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6932 - accuracy: 0.7466 - val_loss: 1.1395 - val_accuracy: 0.6860
Epoch 73/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6858 - accuracy: 0.7518 - val_loss: 1.1389 - val_accuracy: 0.6878
Epoch 74/100
145/145 [==============================] - 13s 90ms/step - loss: 0.6848 - accuracy: 0.7516 - val_loss: 1.1374 - val_accuracy: 0.6873
Epoch 75/100
145/145 [==============================] - 11s 73ms/step - loss: 0.7013 - accuracy: 0.7477 - val_loss: 1.1373 - val_accuracy: 0.6865
Epoch 76/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6909 - accuracy: 0.7464 - val_loss: 1.1365 - val_accuracy: 0.6860
Epoch 77/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6760 - accuracy: 0.7574 - val_loss: 1.1366 - val_accuracy: 0.6865
Epoch 78/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6926 - accuracy: 0.7457 - val_loss: 1.1363 - val_accuracy: 0.6873
Epoch 79/100
145/145 [==============================] - 12s 81ms/step - loss: 0.6808 - accuracy: 0.7570 - val_loss: 1.1356 - val_accuracy: 0.6843
Epoch 80/100
145/145 [==============================] - 11s 74ms/step - loss: 0.6964 - accuracy: 0.7442 - val_loss: 1.1366 - val_accuracy: 0.6860
Epoch 81/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6887 - accuracy: 0.7531 - val_loss: 1.1369 - val_accuracy: 0.6865
Epoch 82/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6894 - accuracy: 0.7433 - val_loss: 1.1359 - val_accuracy: 0.6860
Epoch 83/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6901 - accuracy: 0.7494 - val_loss: 1.1359 - val_accuracy: 0.6860
Epoch 84/100
145/145 [==============================] - 11s 78ms/step - loss: 0.6847 - accuracy: 0.7446 - val_loss: 1.1355 - val_accuracy: 0.6869
Epoch 85/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6867 - accuracy: 0.7507 - val_loss: 1.1362 - val_accuracy: 0.6873
Epoch 86/100
145/145 [==============================] - 13s 93ms/step - loss: 0.6895 - accuracy: 0.7490 - val_loss: 1.1357 - val_accuracy: 0.6869
Epoch 87/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6924 - accuracy: 0.7472 - val_loss: 1.1353 - val_accuracy: 0.6856
Epoch 88/100
145/145 [==============================] - 12s 82ms/step - loss: 0.7040 - accuracy: 0.7485 - val_loss: 1.1377 - val_accuracy: 0.6852
Epoch 89/100
145/145 [==============================] - 11s 76ms/step - loss: 0.6741 - accuracy: 0.7596 - val_loss: 1.1373 - val_accuracy: 0.6860
Epoch 90/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6859 - accuracy: 0.7537 - val_loss: 1.1366 - val_accuracy: 0.6869
Epoch 91/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6694 - accuracy: 0.7537 - val_loss: 1.1372 - val_accuracy: 0.6873
Epoch 92/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6811 - accuracy: 0.7533 - val_loss: 1.1384 - val_accuracy: 0.6856
Epoch 93/100
145/145 [==============================] - 13s 89ms/step - loss: 0.6751 - accuracy: 0.7490 - val_loss: 1.1377 - val_accuracy: 0.6865
Epoch 94/100
145/145 [==============================] - 11s 75ms/step - loss: 0.7024 - accuracy: 0.7488 - val_loss: 1.1393 - val_accuracy: 0.6865
Epoch 95/100
145/145 [==============================] - 11s 79ms/step - loss: 0.6949 - accuracy: 0.7507 - val_loss: 1.1396 - val_accuracy: 0.6865
Epoch 96/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6886 - accuracy: 0.7507 - val_loss: 1.1403 - val_accuracy: 0.6869
Epoch 97/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6977 - accuracy: 0.7438 - val_loss: 1.1399 - val_accuracy: 0.6878
Epoch 98/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6853 - accuracy: 0.7477 - val_loss: 1.1381 - val_accuracy: 0.6882
Epoch 99/100
145/145 [==============================] - 12s 79ms/step - loss: 0.7013 - accuracy: 0.7477 - val_loss: 1.1380 - val_accuracy: 0.6878
Epoch 100/100
145/145 [==============================] - 13s 91ms/step - loss: 0.7034 - accuracy: 0.7464 - val_loss: 1.1375 - val_accuracy: 0.6882

In [ ]:
model_2006.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
history = model_2006.fit(x_train, y_train, epochs=100, validation_data=(X_val, Y_val))

Epoch 1/100
145/145 [==============================] - 14s 85ms/step - loss: 0.6729 - accuracy: 0.7557 - val_loss: 1.1374 - val_accuracy: 0.6882
Epoch 2/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6925 - accuracy: 0.7579 - val_loss: 1.1375 - val_accuracy: 0.6882
Epoch 3/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6894 - accuracy: 0.7581 - val_loss: 1.1374 - val_accuracy: 0.6882
Epoch 4/100
145/145 [==============================] - 11s 74ms/step - loss: 0.6889 - accuracy: 0.7542 - val_loss: 1.1373 - val_accuracy: 0.6882
Epoch 5/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6935 - accuracy: 0.7449 - val_loss: 1.1373 - val_accuracy: 0.6882
Epoch 6/100
145/145 [==============================] - 13s 90ms/step - loss: 0.7035 - accuracy: 0.7479 - val_loss: 1.1373 - val_accuracy: 0.6882
Epoch 7/100
145/145 [==============================] - 13s 91ms/step - loss: 0.6781 - accuracy: 0.7563 - val_loss: 1.1373 - val_accuracy: 0.6882
Epoch 8/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6941 - accuracy: 0.7566 - val_loss: 1.1372 - val_accuracy: 0.6882
Epoch 9/100
145/145 [==============================] - 11s 75ms/step - loss: 0.6772 - accuracy: 0.7518 - val_loss: 1.1371 - val_accuracy: 0.6882
Epoch 10/100
145/145 [==============================] - 12s 80ms/step - loss: 0.6925 - accuracy: 0.7481 - val_loss: 1.1369 - val_accuracy: 0.6882
Epoch 11/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6941 - accuracy: 0.7511 - val_loss: 1.1369 - val_accuracy: 0.6882
Epoch 12/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6943 - accuracy: 0.7507 - val_loss: 1.1368 - val_accuracy: 0.6882
Epoch 13/100
145/145 [==============================] - 13s 93ms/step - loss: 0.6836 - accuracy: 0.7516 - val_loss: 1.1366 - val_accuracy: 0.6882
Epoch 14/100
145/145 [==============================] - 12s 80ms/step - loss: 0.6745 - accuracy: 0.7579 - val_loss: 1.1367 - val_accuracy: 0.6882
Epoch 15/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6740 - accuracy: 0.7559 - val_loss: 1.1366 - val_accuracy: 0.6882
Epoch 16/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6926 - accuracy: 0.7470 - val_loss: 1.1365 - val_accuracy: 0.6882
Epoch 17/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6859 - accuracy: 0.7507 - val_loss: 1.1365 - val_accuracy: 0.6882
Epoch 18/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6916 - accuracy: 0.7507 - val_loss: 1.1365 - val_accuracy: 0.6882
Epoch 19/100
145/145 [==============================] - 11s 76ms/step - loss: 0.6766 - accuracy: 0.7540 - val_loss: 1.1366 - val_accuracy: 0.6878
Epoch 20/100
145/145 [==============================] - 12s 85ms/step - loss: 0.7042 - accuracy: 0.7479 - val_loss: 1.1366 - val_accuracy: 0.6878
Epoch 21/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6884 - accuracy: 0.7483 - val_loss: 1.1366 - val_accuracy: 0.6882
Epoch 22/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6984 - accuracy: 0.7496 - val_loss: 1.1366 - val_accuracy: 0.6882
Epoch 23/100
145/145 [==============================] - 13s 86ms/step - loss: 0.6883 - accuracy: 0.7522 - val_loss: 1.1366 - val_accuracy: 0.6882
Epoch 24/100
145/145 [==============================] - 11s 75ms/step - loss: 0.6904 - accuracy: 0.7520 - val_loss: 1.1367 - val_accuracy: 0.6882
Epoch 25/100
145/145 [==============================] - 11s 79ms/step - loss: 0.6826 - accuracy: 0.7520 - val_loss: 1.1365 - val_accuracy: 0.6882
Epoch 26/100
145/145 [==============================] - 13s 88ms/step - loss: 0.7001 - accuracy: 0.7416 - val_loss: 1.1364 - val_accuracy: 0.6882
Epoch 27/100
145/145 [==============================] - 14s 99ms/step - loss: 0.6976 - accuracy: 0.7386 - val_loss: 1.1364 - val_accuracy: 0.6882
Epoch 28/100
145/145 [==============================] - 11s 75ms/step - loss: 0.6930 - accuracy: 0.7470 - val_loss: 1.1364 - val_accuracy: 0.6882
Epoch 29/100
145/145 [==============================] - 13s 87ms/step - loss: 0.7105 - accuracy: 0.7470 - val_loss: 1.1364 - val_accuracy: 0.6882
Epoch 30/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6743 - accuracy: 0.7587 - val_loss: 1.1365 - val_accuracy: 0.6882
Epoch 31/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6811 - accuracy: 0.7574 - val_loss: 1.1365 - val_accuracy: 0.6882
Epoch 32/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6932 - accuracy: 0.7453 - val_loss: 1.1366 - val_accuracy: 0.6882
Epoch 33/100
145/145 [==============================] - 13s 89ms/step - loss: 0.6765 - accuracy: 0.7533 - val_loss: 1.1366 - val_accuracy: 0.6882
Epoch 34/100
145/145 [==============================] - 13s 89ms/step - loss: 0.7033 - accuracy: 0.7442 - val_loss: 1.1366 - val_accuracy: 0.6882
Epoch 35/100
145/145 [==============================] - 12s 81ms/step - loss: 0.6893 - accuracy: 0.7505 - val_loss: 1.1367 - val_accuracy: 0.6882
Epoch 36/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6773 - accuracy: 0.7546 - val_loss: 1.1368 - val_accuracy: 0.6882
Epoch 37/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6825 - accuracy: 0.7566 - val_loss: 1.1367 - val_accuracy: 0.6882
Epoch 38/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6801 - accuracy: 0.7520 - val_loss: 1.1366 - val_accuracy: 0.6882
Epoch 39/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6864 - accuracy: 0.7535 - val_loss: 1.1365 - val_accuracy: 0.6882
Epoch 40/100
145/145 [==============================] - 11s 77ms/step - loss: 0.6870 - accuracy: 0.7470 - val_loss: 1.1366 - val_accuracy: 0.6882
Epoch 41/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6907 - accuracy: 0.7483 - val_loss: 1.1367 - val_accuracy: 0.6882
Epoch 42/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6949 - accuracy: 0.7483 - val_loss: 1.1368 - val_accuracy: 0.6882
Epoch 43/100
145/145 [==============================] - 13s 88ms/step - loss: 0.6888 - accuracy: 0.7496 - val_loss: 1.1368 - val_accuracy: 0.6882
Epoch 44/100
145/145 [==============================] - 12s 80ms/step - loss: 0.6908 - accuracy: 0.7494 - val_loss: 1.1369 - val_accuracy: 0.6882
Epoch 45/100
145/145 [==============================] - 11s 76ms/step - loss: 0.6905 - accuracy: 0.7535 - val_loss: 1.1370 - val_accuracy: 0.6882
Epoch 46/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6836 - accuracy: 0.7583 - val_loss: 1.1369 - val_accuracy: 0.6882
Epoch 47/100
145/145 [==============================] - 14s 96ms/step - loss: 0.7036 - accuracy: 0.7416 - val_loss: 1.1369 - val_accuracy: 0.6882
Epoch 48/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6913 - accuracy: 0.7533 - val_loss: 1.1369 - val_accuracy: 0.6882
Epoch 49/100
145/145 [==============================] - 13s 89ms/step - loss: 0.6896 - accuracy: 0.7594 - val_loss: 1.1368 - val_accuracy: 0.6882
Epoch 50/100
145/145 [==============================] - 11s 79ms/step - loss: 0.6972 - accuracy: 0.7490 - val_loss: 1.1367 - val_accuracy: 0.6878
Epoch 51/100
145/145 [==============================] - 13s 86ms/step - loss: 0.6838 - accuracy: 0.7483 - val_loss: 1.1367 - val_accuracy: 0.6882
Epoch 52/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6773 - accuracy: 0.7505 - val_loss: 1.1368 - val_accuracy: 0.6882
Epoch 53/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6850 - accuracy: 0.7516 - val_loss: 1.1367 - val_accuracy: 0.6878
Epoch 54/100
145/145 [==============================] - 13s 86ms/step - loss: 0.6863 - accuracy: 0.7464 - val_loss: 1.1367 - val_accuracy: 0.6878
Epoch 55/100
145/145 [==============================] - 11s 75ms/step - loss: 0.6936 - accuracy: 0.7501 - val_loss: 1.1368 - val_accuracy: 0.6878
Epoch 56/100
145/145 [==============================] - 12s 83ms/step - loss: 0.7139 - accuracy: 0.7403 - val_loss: 1.1369 - val_accuracy: 0.6878
Epoch 57/100
145/145 [==============================] - 11s 79ms/step - loss: 0.6860 - accuracy: 0.7507 - val_loss: 1.1369 - val_accuracy: 0.6878
Epoch 58/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6885 - accuracy: 0.7483 - val_loss: 1.1370 - val_accuracy: 0.6878
Epoch 59/100
145/145 [==============================] - 11s 73ms/step - loss: 0.6872 - accuracy: 0.7475 - val_loss: 1.1370 - val_accuracy: 0.6878
Epoch 60/100
145/145 [==============================] - 11s 76ms/step - loss: 0.6816 - accuracy: 0.7488 - val_loss: 1.1370 - val_accuracy: 0.6873
Epoch 61/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6974 - accuracy: 0.7509 - val_loss: 1.1371 - val_accuracy: 0.6873
Epoch 62/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6730 - accuracy: 0.7613 - val_loss: 1.1372 - val_accuracy: 0.6873
Epoch 63/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6850 - accuracy: 0.7568 - val_loss: 1.1372 - val_accuracy: 0.6873
Epoch 64/100
145/145 [==============================] - 11s 77ms/step - loss: 0.6962 - accuracy: 0.7498 - val_loss: 1.1371 - val_accuracy: 0.6869
Epoch 65/100
145/145 [==============================] - 12s 83ms/step - loss: 0.7041 - accuracy: 0.7377 - val_loss: 1.1370 - val_accuracy: 0.6873
Epoch 66/100
145/145 [==============================] - 12s 80ms/step - loss: 0.6932 - accuracy: 0.7466 - val_loss: 1.1369 - val_accuracy: 0.6878
Epoch 67/100
145/145 [==============================] - 14s 97ms/step - loss: 0.6745 - accuracy: 0.7522 - val_loss: 1.1368 - val_accuracy: 0.6882
Epoch 68/100
145/145 [==============================] - 11s 77ms/step - loss: 0.6739 - accuracy: 0.7559 - val_loss: 1.1369 - val_accuracy: 0.6878
Epoch 69/100
145/145 [==============================] - 11s 78ms/step - loss: 0.6881 - accuracy: 0.7566 - val_loss: 1.1370 - val_accuracy: 0.6873
Epoch 70/100
145/145 [==============================] - 12s 84ms/step - loss: 0.7021 - accuracy: 0.7455 - val_loss: 1.1372 - val_accuracy: 0.6873
Epoch 71/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6957 - accuracy: 0.7427 - val_loss: 1.1374 - val_accuracy: 0.6873
Epoch 72/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6813 - accuracy: 0.7557 - val_loss: 1.1373 - val_accuracy: 0.6873
Epoch 73/100
145/145 [==============================] - 11s 74ms/step - loss: 0.6874 - accuracy: 0.7559 - val_loss: 1.1374 - val_accuracy: 0.6873
Epoch 74/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6812 - accuracy: 0.7520 - val_loss: 1.1374 - val_accuracy: 0.6869
Epoch 75/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6644 - accuracy: 0.7535 - val_loss: 1.1374 - val_accuracy: 0.6865
Epoch 76/100
145/145 [==============================] - 12s 82ms/step - loss: 0.7089 - accuracy: 0.7433 - val_loss: 1.1374 - val_accuracy: 0.6865
Epoch 77/100
145/145 [==============================] - 13s 86ms/step - loss: 0.6859 - accuracy: 0.7481 - val_loss: 1.1375 - val_accuracy: 0.6865
Epoch 78/100
145/145 [==============================] - 11s 76ms/step - loss: 0.6790 - accuracy: 0.7540 - val_loss: 1.1374 - val_accuracy: 0.6865
Epoch 79/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6727 - accuracy: 0.7611 - val_loss: 1.1376 - val_accuracy: 0.6869
Epoch 80/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6824 - accuracy: 0.7488 - val_loss: 1.1376 - val_accuracy: 0.6869
Epoch 81/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6872 - accuracy: 0.7483 - val_loss: 1.1375 - val_accuracy: 0.6869
Epoch 82/100
145/145 [==============================] - 11s 78ms/step - loss: 0.6999 - accuracy: 0.7462 - val_loss: 1.1374 - val_accuracy: 0.6869
Epoch 83/100
145/145 [==============================] - 12s 81ms/step - loss: 0.6811 - accuracy: 0.7548 - val_loss: 1.1374 - val_accuracy: 0.6869
Epoch 84/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6731 - accuracy: 0.7574 - val_loss: 1.1375 - val_accuracy: 0.6865
Epoch 85/100
145/145 [==============================] - 12s 85ms/step - loss: 0.6871 - accuracy: 0.7516 - val_loss: 1.1376 - val_accuracy: 0.6865
Epoch 86/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6873 - accuracy: 0.7494 - val_loss: 1.1377 - val_accuracy: 0.6865
Epoch 87/100
145/145 [==============================] - 13s 89ms/step - loss: 0.6936 - accuracy: 0.7472 - val_loss: 1.1377 - val_accuracy: 0.6865
Epoch 88/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6917 - accuracy: 0.7472 - val_loss: 1.1377 - val_accuracy: 0.6865
Epoch 89/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6940 - accuracy: 0.7481 - val_loss: 1.1377 - val_accuracy: 0.6869
Epoch 90/100
145/145 [==============================] - 11s 79ms/step - loss: 0.6878 - accuracy: 0.7596 - val_loss: 1.1376 - val_accuracy: 0.6869
Epoch 91/100
145/145 [==============================] - 11s 79ms/step - loss: 0.6868 - accuracy: 0.7496 - val_loss: 1.1377 - val_accuracy: 0.6869
Epoch 92/100
145/145 [==============================] - 13s 87ms/step - loss: 0.6912 - accuracy: 0.7563 - val_loss: 1.1376 - val_accuracy: 0.6869
Epoch 93/100
145/145 [==============================] - 12s 82ms/step - loss: 0.6830 - accuracy: 0.7468 - val_loss: 1.1377 - val_accuracy: 0.6869
Epoch 94/100
145/145 [==============================] - 13s 90ms/step - loss: 0.6813 - accuracy: 0.7466 - val_loss: 1.1375 - val_accuracy: 0.6873
Epoch 95/100
145/145 [==============================] - 13s 90ms/step - loss: 0.6783 - accuracy: 0.7540 - val_loss: 1.1375 - val_accuracy: 0.6869
Epoch 96/100
145/145 [==============================] - 11s 74ms/step - loss: 0.6923 - accuracy: 0.7507 - val_loss: 1.1377 - val_accuracy: 0.6869
Epoch 97/100
145/145 [==============================] - 12s 84ms/step - loss: 0.6908 - accuracy: 0.7477 - val_loss: 1.1378 - val_accuracy: 0.6869
Epoch 98/100
145/145 [==============================] - 12s 86ms/step - loss: 0.6864 - accuracy: 0.7481 - val_loss: 1.1378 - val_accuracy: 0.6869
Epoch 99/100
145/145 [==============================] - 12s 83ms/step - loss: 0.6938 - accuracy: 0.7488 - val_loss: 1.1378 - val_accuracy: 0.6865
Epoch 100/100
145/145 [==============================] - 11s 78ms/step - loss: 0.6918 - accuracy: 0.7488 - val_loss: 1.1378 - val_accuracy: 0.6865

In [ ]:
# model_2006.save("/content/drive/MyDrive/FYP/Trained Models/2006.keras")
loaded_model = load_model("/content/drive/MyDrive/FYP/Trained Models/2006.keras")

In [ ]:
val_loss, val_accuracy = loaded_model.evaluate(x_train, y_train)
print(f"Final Train Loss: {val_loss:.4f}")
print(f"Final Train Accuracy: {val_accuracy:.4f}")

145/145 [==============================] - 1s 3ms/step - loss: 0.5078 - accuracy: 0.8019
Final Train Loss: 0.5078
Final Train Accuracy: 0.8019

In [ ]:
val_loss, val_accuracy = loaded_model.evaluate(X_val, Y_val)
print(f"Final Validation Loss: {val_loss:.4f}")
print(f"Final Validation Accuracy: {val_accuracy:.4f}")

73/73 [==============================] - 1s 7ms/step - loss: 0.4038 - accuracy: 0.8439
Final Validation Loss: 0.4038
Final Validation Accuracy: 0.8439

In [ ]:
test_loss, test_accuracy = loaded_model.evaluate(X_test, Y_test)
print(f"Final Test Loss: {test_loss:.4f}")
print(f"Final Test Accuracy: {test_accuracy:.4f}")

73/73 [==============================] - 1s 7ms/step - loss: 0.4526 - accuracy: 0.8114
Final Test Loss: 0.4526
Final Test Accuracy: 0.8114

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(x_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.7851257588898526

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2006.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2007

### Stratified sampling

In [ ]:
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2007, labels_2007):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2007)

numpy.ndarray

In [ ]:
fold1[0]

array([ 149,  150,  151, ..., 9665, 9666, 9667])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2007[x]
    y_train = labels_2007[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2007[x]))
    y_train = np.vstack((y_train, labels_2007[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2007[x]
    y_test = labels_2007[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2007[x]))
    y_test = np.vstack((y_test, labels_2007[x]))

In [ ]:
# Second iteration of Stratified KFold for test set
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2007[x]
    y_train = labels_2007[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2007[x]))
    y_train = np.vstack((y_train, labels_2007[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2007[x]
    y_test = labels_2007[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2007[x]))
    y_test = np.vstack((y_test, labels_2007[x]))

In [ ]:
# Third iteration of Stratified KFold for training test and cross validation set
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2007[x]
    y_train = labels_2007[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2007[x]))
    y_train = np.vstack((y_train, labels_2007[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2007[x]
    y_test = labels_2007[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2007[x]))
    y_test = np.vstack((y_test, labels_2007[x]))

In [ ]:
y_train.shape

(6445, 1)

## Model Training 2007

In [ ]:
model_2007 = Sequential()

In [ ]:
model_2007.add(Dense(units=520, activation="relu"))
model_2007.add(Dropout(0.2))
model_2007.add(Dense(units=250, activation="relu"))
model_2007.add(Dropout(0.2))
model_2007.add(Dense(units=128, activation="relu"))
model_2007.add(Dropout(0.2))
model_2007.add(Dense(units=64, activation="relu"))
model_2007.add(Dropout(0.2))
model_2007.add(Dense(units=45, activation="relu"))
model_2007.add(Dropout(0.2))
model_2007.add(Dense(units=28, activation="relu"))
model_2007.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2007.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2007.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
202/202 [==============================] - 3s 5ms/step - loss: 2.4641 - accuracy: 0.1947
Epoch 2/100
202/202 [==============================] - 1s 5ms/step - loss: 1.6962 - accuracy: 0.4014
Epoch 3/100
202/202 [==============================] - 1s 5ms/step - loss: 1.4068 - accuracy: 0.4855
Epoch 4/100
202/202 [==============================] - 1s 5ms/step - loss: 1.2539 - accuracy: 0.5310
Epoch 5/100
202/202 [==============================] - 1s 5ms/step - loss: 1.1981 - accuracy: 0.5553
Epoch 6/100
202/202 [==============================] - 1s 5ms/step - loss: 1.1527 - accuracy: 0.5747
Epoch 7/100
202/202 [==============================] - 1s 6ms/step - loss: 1.0808 - accuracy: 0.5946
Epoch 8/100
202/202 [==============================] - 1s 6ms/step - loss: 1.0518 - accuracy: 0.6109
Epoch 9/100
202/202 [==============================] - 1s 6ms/step - loss: 1.0142 - accuracy: 0.6230
Epoch 10/100
202/202 [==============================] - 1s 6ms/step - loss: 0.9989 - accuracy: 0.6273
Epoch 11/100
202/202 [==============================] - 1s 6ms/step - loss: 0.9700 - accuracy: 0.6382
Epoch 12/100
202/202 [==============================] - 1s 5ms/step - loss: 0.9368 - accuracy: 0.6456
Epoch 13/100
202/202 [==============================] - 1s 5ms/step - loss: 0.9343 - accuracy: 0.6512
Epoch 14/100
202/202 [==============================] - 1s 5ms/step - loss: 0.9094 - accuracy: 0.6571
Epoch 15/100
202/202 [==============================] - 1s 5ms/step - loss: 0.9118 - accuracy: 0.6607
Epoch 16/100
202/202 [==============================] - 1s 5ms/step - loss: 0.9056 - accuracy: 0.6559
Epoch 17/100
202/202 [==============================] - 1s 5ms/step - loss: 0.8893 - accuracy: 0.6753
Epoch 18/100
202/202 [==============================] - 1s 5ms/step - loss: 0.8717 - accuracy: 0.6723
Epoch 19/100
202/202 [==============================] - 1s 4ms/step - loss: 0.8688 - accuracy: 0.6737
Epoch 20/100
202/202 [==============================] - 1s 5ms/step - loss: 0.8862 - accuracy: 0.6666
Epoch 21/100
202/202 [==============================] - 1s 5ms/step - loss: 0.8399 - accuracy: 0.6846
Epoch 22/100
202/202 [==============================] - 1s 6ms/step - loss: 0.8366 - accuracy: 0.6915
Epoch 23/100
202/202 [==============================] - 1s 6ms/step - loss: 0.8374 - accuracy: 0.6853
Epoch 24/100
202/202 [==============================] - 1s 7ms/step - loss: 0.8259 - accuracy: 0.6877
Epoch 25/100
202/202 [==============================] - 1s 7ms/step - loss: 0.8160 - accuracy: 0.7002
Epoch 26/100
202/202 [==============================] - 1s 5ms/step - loss: 0.8108 - accuracy: 0.6988
Epoch 27/100
202/202 [==============================] - 1s 5ms/step - loss: 0.8164 - accuracy: 0.6940
Epoch 28/100
202/202 [==============================] - 1s 5ms/step - loss: 0.8072 - accuracy: 0.6957
Epoch 29/100
202/202 [==============================] - 1s 5ms/step - loss: 0.8042 - accuracy: 0.6996
Epoch 30/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7905 - accuracy: 0.7054
Epoch 31/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7975 - accuracy: 0.6971
Epoch 32/100
202/202 [==============================] - 1s 5ms/step - loss: 0.8041 - accuracy: 0.7019
Epoch 33/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7874 - accuracy: 0.7061
Epoch 34/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7783 - accuracy: 0.7043
Epoch 35/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7722 - accuracy: 0.7072
Epoch 36/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7854 - accuracy: 0.7072
Epoch 37/100
202/202 [==============================] - 1s 6ms/step - loss: 0.7829 - accuracy: 0.7047
Epoch 38/100
202/202 [==============================] - 1s 6ms/step - loss: 0.7804 - accuracy: 0.7067
Epoch 39/100
202/202 [==============================] - 1s 6ms/step - loss: 0.7535 - accuracy: 0.7157
Epoch 40/100
202/202 [==============================] - 1s 7ms/step - loss: 0.7553 - accuracy: 0.7162
Epoch 41/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7767 - accuracy: 0.7054
Epoch 42/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7705 - accuracy: 0.7119
Epoch 43/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7537 - accuracy: 0.7168
Epoch 44/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7473 - accuracy: 0.7184
Epoch 45/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7454 - accuracy: 0.7167
Epoch 46/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7484 - accuracy: 0.7159
Epoch 47/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7310 - accuracy: 0.7202
Epoch 48/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7250 - accuracy: 0.7342
Epoch 49/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7378 - accuracy: 0.7196
Epoch 50/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7351 - accuracy: 0.7260
Epoch 51/100
202/202 [==============================] - 1s 6ms/step - loss: 0.7403 - accuracy: 0.7216
Epoch 52/100
202/202 [==============================] - 1s 6ms/step - loss: 0.7403 - accuracy: 0.7204
Epoch 53/100
202/202 [==============================] - 1s 6ms/step - loss: 0.7545 - accuracy: 0.7140
Epoch 54/100
202/202 [==============================] - 1s 6ms/step - loss: 0.7252 - accuracy: 0.7257
Epoch 55/100
202/202 [==============================] - 1s 6ms/step - loss: 0.7289 - accuracy: 0.7268
Epoch 56/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7244 - accuracy: 0.7182
Epoch 57/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7182 - accuracy: 0.7251
Epoch 58/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7224 - accuracy: 0.7241
Epoch 59/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7166 - accuracy: 0.7227
Epoch 60/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7062 - accuracy: 0.7345
Epoch 61/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7122 - accuracy: 0.7330
Epoch 62/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7046 - accuracy: 0.7348
Epoch 63/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7053 - accuracy: 0.7344
Epoch 64/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6959 - accuracy: 0.7353
Epoch 65/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7066 - accuracy: 0.7314
Epoch 66/100
202/202 [==============================] - 1s 6ms/step - loss: 0.7083 - accuracy: 0.7339
Epoch 67/100
202/202 [==============================] - 1s 6ms/step - loss: 0.7201 - accuracy: 0.7302
Epoch 68/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6967 - accuracy: 0.7348
Epoch 69/100
202/202 [==============================] - 1s 7ms/step - loss: 0.6846 - accuracy: 0.7421
Epoch 70/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7090 - accuracy: 0.7306
Epoch 71/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7100 - accuracy: 0.7333
Epoch 72/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6915 - accuracy: 0.7319
Epoch 73/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7013 - accuracy: 0.7292
Epoch 74/100
202/202 [==============================] - 1s 5ms/step - loss: 0.7079 - accuracy: 0.7297
Epoch 75/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6938 - accuracy: 0.7413
Epoch 76/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6822 - accuracy: 0.7432
Epoch 77/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6945 - accuracy: 0.7437
Epoch 78/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6936 - accuracy: 0.7378
Epoch 79/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6868 - accuracy: 0.7409
Epoch 80/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6936 - accuracy: 0.7413
Epoch 81/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6804 - accuracy: 0.7423
Epoch 82/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6973 - accuracy: 0.7303
Epoch 83/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6811 - accuracy: 0.7412
Epoch 84/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6875 - accuracy: 0.7410
Epoch 85/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6857 - accuracy: 0.7429
Epoch 86/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6785 - accuracy: 0.7432
Epoch 87/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6846 - accuracy: 0.7420
Epoch 88/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6710 - accuracy: 0.7452
Epoch 89/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6618 - accuracy: 0.7449
Epoch 90/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6967 - accuracy: 0.7351
Epoch 91/100
202/202 [==============================] - 1s 4ms/step - loss: 0.6757 - accuracy: 0.7427
Epoch 92/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6815 - accuracy: 0.7424
Epoch 93/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6778 - accuracy: 0.7469
Epoch 94/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6655 - accuracy: 0.7458
Epoch 95/100
202/202 [==============================] - 1s 7ms/step - loss: 0.6713 - accuracy: 0.7465
Epoch 96/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6549 - accuracy: 0.7519
Epoch 97/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6825 - accuracy: 0.7392
Epoch 98/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6798 - accuracy: 0.7448
Epoch 99/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6649 - accuracy: 0.7531
Epoch 100/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6651 - accuracy: 0.7508

In [ ]:
model_2007.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2007.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
202/202 [==============================] - 3s 5ms/step - loss: 0.6323 - accuracy: 0.7589
Epoch 2/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6217 - accuracy: 0.7642
Epoch 3/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6231 - accuracy: 0.7583
Epoch 4/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6037 - accuracy: 0.7704
Epoch 5/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6178 - accuracy: 0.7631
Epoch 6/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6117 - accuracy: 0.7666
Epoch 7/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6193 - accuracy: 0.7629
Epoch 8/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6131 - accuracy: 0.7652
Epoch 9/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6126 - accuracy: 0.7631
Epoch 10/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5992 - accuracy: 0.7732
Epoch 11/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5996 - accuracy: 0.7728
Epoch 12/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6090 - accuracy: 0.7752
Epoch 13/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6130 - accuracy: 0.7674
Epoch 14/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6061 - accuracy: 0.7693
Epoch 15/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6053 - accuracy: 0.7722
Epoch 16/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5930 - accuracy: 0.7725
Epoch 17/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6016 - accuracy: 0.7732
Epoch 18/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5977 - accuracy: 0.7760
Epoch 19/100
202/202 [==============================] - 1s 5ms/step - loss: 0.6027 - accuracy: 0.7707
Epoch 20/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5993 - accuracy: 0.7724
Epoch 21/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6017 - accuracy: 0.7668
Epoch 22/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5934 - accuracy: 0.7730
Epoch 23/100
202/202 [==============================] - 1s 6ms/step - loss: 0.6005 - accuracy: 0.7646
Epoch 24/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5959 - accuracy: 0.7761
Epoch 25/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5808 - accuracy: 0.7773
Epoch 26/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5951 - accuracy: 0.7766
Epoch 27/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5888 - accuracy: 0.7722
Epoch 28/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5900 - accuracy: 0.7770
Epoch 29/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5848 - accuracy: 0.7770
Epoch 30/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5793 - accuracy: 0.7770
Epoch 31/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5774 - accuracy: 0.7791
Epoch 32/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5943 - accuracy: 0.7764
Epoch 33/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5912 - accuracy: 0.7718
Epoch 34/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5870 - accuracy: 0.7761
Epoch 35/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5907 - accuracy: 0.7746
Epoch 36/100
202/202 [==============================] - 1s 7ms/step - loss: 0.5940 - accuracy: 0.7733
Epoch 37/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5819 - accuracy: 0.7772
Epoch 38/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5796 - accuracy: 0.7797
Epoch 39/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5837 - accuracy: 0.7775
Epoch 40/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5779 - accuracy: 0.7820
Epoch 41/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5854 - accuracy: 0.7822
Epoch 42/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5804 - accuracy: 0.7800
Epoch 43/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5722 - accuracy: 0.7842
Epoch 44/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5779 - accuracy: 0.7747
Epoch 45/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5845 - accuracy: 0.7794
Epoch 46/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5791 - accuracy: 0.7791
Epoch 47/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5751 - accuracy: 0.7834
Epoch 48/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5736 - accuracy: 0.7826
Epoch 49/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5675 - accuracy: 0.7812
Epoch 50/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5724 - accuracy: 0.7804
Epoch 51/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5785 - accuracy: 0.7794
Epoch 52/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5605 - accuracy: 0.7822
Epoch 53/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5825 - accuracy: 0.7747
Epoch 54/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5721 - accuracy: 0.7777
Epoch 55/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5758 - accuracy: 0.7775
Epoch 56/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5642 - accuracy: 0.7859
Epoch 57/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5657 - accuracy: 0.7811
Epoch 58/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5808 - accuracy: 0.7755
Epoch 59/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5720 - accuracy: 0.7803
Epoch 60/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5718 - accuracy: 0.7820
Epoch 61/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5732 - accuracy: 0.7836
Epoch 62/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5751 - accuracy: 0.7797
Epoch 63/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5700 - accuracy: 0.7848
Epoch 64/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5680 - accuracy: 0.7828
Epoch 65/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5739 - accuracy: 0.7783
Epoch 66/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5829 - accuracy: 0.7767
Epoch 67/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5710 - accuracy: 0.7804
Epoch 68/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5769 - accuracy: 0.7800
Epoch 69/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5701 - accuracy: 0.7792
Epoch 70/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5653 - accuracy: 0.7834
Epoch 71/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5754 - accuracy: 0.7820
Epoch 72/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5668 - accuracy: 0.7843
Epoch 73/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5707 - accuracy: 0.7842
Epoch 74/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5555 - accuracy: 0.7873
Epoch 75/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5677 - accuracy: 0.7820
Epoch 76/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5658 - accuracy: 0.7773
Epoch 77/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5643 - accuracy: 0.7848
Epoch 78/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5602 - accuracy: 0.7867
Epoch 79/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5682 - accuracy: 0.7846
Epoch 80/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5665 - accuracy: 0.7876
Epoch 81/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5584 - accuracy: 0.7905
Epoch 82/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5707 - accuracy: 0.7803
Epoch 83/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5644 - accuracy: 0.7877
Epoch 84/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5593 - accuracy: 0.7823
Epoch 85/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5762 - accuracy: 0.7772
Epoch 86/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5634 - accuracy: 0.7891
Epoch 87/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5801 - accuracy: 0.7822
Epoch 88/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5630 - accuracy: 0.7834
Epoch 89/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5722 - accuracy: 0.7832
Epoch 90/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5485 - accuracy: 0.7879
Epoch 91/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5523 - accuracy: 0.7924
Epoch 92/100
202/202 [==============================] - 1s 7ms/step - loss: 0.5615 - accuracy: 0.7870
Epoch 93/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5595 - accuracy: 0.7893
Epoch 94/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5522 - accuracy: 0.7867
Epoch 95/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5571 - accuracy: 0.7836
Epoch 96/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5572 - accuracy: 0.7896
Epoch 97/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5445 - accuracy: 0.7938
Epoch 98/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5584 - accuracy: 0.7856
Epoch 99/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5646 - accuracy: 0.7828
Epoch 100/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5408 - accuracy: 0.7908

In [ ]:
model_2007.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2007.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
202/202 [==============================] - 3s 6ms/step - loss: 0.5343 - accuracy: 0.7984
Epoch 2/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5218 - accuracy: 0.7992
Epoch 3/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5211 - accuracy: 0.7983
Epoch 4/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5228 - accuracy: 0.8000
Epoch 5/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5175 - accuracy: 0.8051
Epoch 6/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5090 - accuracy: 0.8043
Epoch 7/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5176 - accuracy: 0.8029
Epoch 8/100
202/202 [==============================] - 1s 4ms/step - loss: 0.5170 - accuracy: 0.8002
Epoch 9/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5178 - accuracy: 0.8023
Epoch 10/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5126 - accuracy: 0.8016
Epoch 11/100
202/202 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7986
Epoch 12/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5081 - accuracy: 0.8026
Epoch 13/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5180 - accuracy: 0.8036
Epoch 14/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5100 - accuracy: 0.8051
Epoch 15/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5146 - accuracy: 0.8026
Epoch 16/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5060 - accuracy: 0.8073
Epoch 17/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5087 - accuracy: 0.8099
Epoch 18/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5035 - accuracy: 0.8101
Epoch 19/100
202/202 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.8045
Epoch 20/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5105 - accuracy: 0.8025
Epoch 21/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5025 - accuracy: 0.8093
Epoch 22/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5083 - accuracy: 0.8061
Epoch 23/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4951 - accuracy: 0.8112
Epoch 24/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5095 - accuracy: 0.8026
Epoch 25/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5086 - accuracy: 0.8073
Epoch 26/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5092 - accuracy: 0.8037
Epoch 27/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5018 - accuracy: 0.8051
Epoch 28/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5053 - accuracy: 0.8042
Epoch 29/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4947 - accuracy: 0.8092
Epoch 30/100
202/202 [==============================] - 1s 7ms/step - loss: 0.4997 - accuracy: 0.8093
Epoch 31/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5064 - accuracy: 0.8107
Epoch 32/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5050 - accuracy: 0.8074
Epoch 33/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5076 - accuracy: 0.8051
Epoch 34/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5050 - accuracy: 0.8056
Epoch 35/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5014 - accuracy: 0.8053
Epoch 36/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5096 - accuracy: 0.8042
Epoch 37/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5014 - accuracy: 0.8057
Epoch 38/100
202/202 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.8034
Epoch 39/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5043 - accuracy: 0.8081
Epoch 40/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5068 - accuracy: 0.8047
Epoch 41/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5020 - accuracy: 0.8101
Epoch 42/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5068 - accuracy: 0.8039
Epoch 43/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5020 - accuracy: 0.8088
Epoch 44/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5088 - accuracy: 0.8070
Epoch 45/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5078 - accuracy: 0.8020
Epoch 46/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5016 - accuracy: 0.8047
Epoch 47/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4968 - accuracy: 0.8102
Epoch 48/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5026 - accuracy: 0.8101
Epoch 49/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5056 - accuracy: 0.8109
Epoch 50/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4929 - accuracy: 0.8098
Epoch 51/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4991 - accuracy: 0.8116
Epoch 52/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5001 - accuracy: 0.8123
Epoch 53/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5090 - accuracy: 0.8054
Epoch 54/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4912 - accuracy: 0.8143
Epoch 55/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4866 - accuracy: 0.8115
Epoch 56/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5031 - accuracy: 0.8009
Epoch 57/100
202/202 [==============================] - 1s 6ms/step - loss: 0.5010 - accuracy: 0.8067
Epoch 58/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4994 - accuracy: 0.8099
Epoch 59/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4928 - accuracy: 0.8073
Epoch 60/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5010 - accuracy: 0.8062
Epoch 61/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5050 - accuracy: 0.8073
Epoch 62/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5000 - accuracy: 0.8095
Epoch 63/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5083 - accuracy: 0.8078
Epoch 64/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4996 - accuracy: 0.8078
Epoch 65/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4964 - accuracy: 0.8088
Epoch 66/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5058 - accuracy: 0.8090
Epoch 67/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4974 - accuracy: 0.8123
Epoch 68/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4990 - accuracy: 0.8095
Epoch 69/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4953 - accuracy: 0.8081
Epoch 70/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4937 - accuracy: 0.8109
Epoch 71/100
202/202 [==============================] - 1s 7ms/step - loss: 0.4921 - accuracy: 0.8161
Epoch 72/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4988 - accuracy: 0.8078
Epoch 73/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5018 - accuracy: 0.8078
Epoch 74/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4947 - accuracy: 0.8067
Epoch 75/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4943 - accuracy: 0.8081
Epoch 76/100
202/202 [==============================] - 1s 5ms/step - loss: 0.5013 - accuracy: 0.8095
Epoch 77/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4950 - accuracy: 0.8082
Epoch 78/100
202/202 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.8116
Epoch 79/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4926 - accuracy: 0.8132
Epoch 80/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4988 - accuracy: 0.8107
Epoch 81/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4912 - accuracy: 0.8110
Epoch 82/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4941 - accuracy: 0.8129
Epoch 83/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4995 - accuracy: 0.8053
Epoch 84/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4963 - accuracy: 0.8106
Epoch 85/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4926 - accuracy: 0.8116
Epoch 86/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4884 - accuracy: 0.8143
Epoch 87/100
202/202 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.8123
Epoch 88/100
202/202 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.8096
Epoch 89/100
202/202 [==============================] - 1s 4ms/step - loss: 0.4946 - accuracy: 0.8099
Epoch 90/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4890 - accuracy: 0.8118
Epoch 91/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4969 - accuracy: 0.8116
Epoch 92/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4966 - accuracy: 0.8138
Epoch 93/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4882 - accuracy: 0.8133
Epoch 94/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4999 - accuracy: 0.8102
Epoch 95/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4886 - accuracy: 0.8062
Epoch 96/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4807 - accuracy: 0.8076
Epoch 97/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4960 - accuracy: 0.8053
Epoch 98/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4920 - accuracy: 0.8155
Epoch 99/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4896 - accuracy: 0.8116
Epoch 100/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4975 - accuracy: 0.8034

In [ ]:
model_2007.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2007.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
202/202 [==============================] - 3s 5ms/step - loss: 0.4887 - accuracy: 0.8137
Epoch 2/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4903 - accuracy: 0.8138
Epoch 3/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4928 - accuracy: 0.8119
Epoch 4/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4892 - accuracy: 0.8116
Epoch 5/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4851 - accuracy: 0.8119
Epoch 6/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4783 - accuracy: 0.8155
Epoch 7/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4882 - accuracy: 0.8144
Epoch 8/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4778 - accuracy: 0.8169
Epoch 9/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4812 - accuracy: 0.8132
Epoch 10/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4800 - accuracy: 0.8144
Epoch 11/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4804 - accuracy: 0.8132
Epoch 12/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4813 - accuracy: 0.8152
Epoch 13/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4888 - accuracy: 0.8137
Epoch 14/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4792 - accuracy: 0.8174
Epoch 15/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4908 - accuracy: 0.8118
Epoch 16/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4799 - accuracy: 0.8172
Epoch 17/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4785 - accuracy: 0.8166
Epoch 18/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4872 - accuracy: 0.8180
Epoch 19/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4877 - accuracy: 0.8141
Epoch 20/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4823 - accuracy: 0.8081
Epoch 21/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4909 - accuracy: 0.8144
Epoch 22/100
202/202 [==============================] - 1s 7ms/step - loss: 0.4874 - accuracy: 0.8140
Epoch 23/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4891 - accuracy: 0.8110
Epoch 24/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4805 - accuracy: 0.8141
Epoch 25/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4965 - accuracy: 0.8070
Epoch 26/100
202/202 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.8084
Epoch 27/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4746 - accuracy: 0.8200
Epoch 28/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4829 - accuracy: 0.8126
Epoch 29/100
202/202 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.8149
Epoch 30/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4871 - accuracy: 0.8095
Epoch 31/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4741 - accuracy: 0.8178
Epoch 32/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4853 - accuracy: 0.8166
Epoch 33/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4853 - accuracy: 0.8164
Epoch 34/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4804 - accuracy: 0.8141
Epoch 35/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4812 - accuracy: 0.8143
Epoch 36/100
202/202 [==============================] - 1s 7ms/step - loss: 0.4835 - accuracy: 0.8135
Epoch 37/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4917 - accuracy: 0.8095
Epoch 38/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4752 - accuracy: 0.8140
Epoch 39/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4827 - accuracy: 0.8127
Epoch 40/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4831 - accuracy: 0.8160
Epoch 41/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4768 - accuracy: 0.8166
Epoch 42/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4819 - accuracy: 0.8200
Epoch 43/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4841 - accuracy: 0.8133
Epoch 44/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4867 - accuracy: 0.8118
Epoch 45/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4828 - accuracy: 0.8160
Epoch 46/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4830 - accuracy: 0.8149
Epoch 47/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4866 - accuracy: 0.8132
Epoch 48/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4903 - accuracy: 0.8121
Epoch 49/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4848 - accuracy: 0.8175
Epoch 50/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4849 - accuracy: 0.8200
Epoch 51/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4874 - accuracy: 0.8098
Epoch 52/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4879 - accuracy: 0.8183
Epoch 53/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4797 - accuracy: 0.8171
Epoch 54/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4763 - accuracy: 0.8163
Epoch 55/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4786 - accuracy: 0.8133
Epoch 56/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4845 - accuracy: 0.8146
Epoch 57/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4924 - accuracy: 0.8146
Epoch 58/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4889 - accuracy: 0.8118
Epoch 59/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4785 - accuracy: 0.8109
Epoch 60/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4751 - accuracy: 0.8112
Epoch 61/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4801 - accuracy: 0.8140
Epoch 62/100
202/202 [==============================] - 1s 7ms/step - loss: 0.4867 - accuracy: 0.8113
Epoch 63/100
202/202 [==============================] - 1s 7ms/step - loss: 0.4838 - accuracy: 0.8135
Epoch 64/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4855 - accuracy: 0.8116
Epoch 65/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4775 - accuracy: 0.8161
Epoch 66/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4869 - accuracy: 0.8115
Epoch 67/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4784 - accuracy: 0.8186
Epoch 68/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4863 - accuracy: 0.8149
Epoch 69/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4792 - accuracy: 0.8157
Epoch 70/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4776 - accuracy: 0.8174
Epoch 71/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4870 - accuracy: 0.8088
Epoch 72/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4805 - accuracy: 0.8144
Epoch 73/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4921 - accuracy: 0.8112
Epoch 74/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4831 - accuracy: 0.8123
Epoch 75/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4867 - accuracy: 0.8101
Epoch 76/100
202/202 [==============================] - 1s 7ms/step - loss: 0.4790 - accuracy: 0.8152
Epoch 77/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4768 - accuracy: 0.8147
Epoch 78/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4800 - accuracy: 0.8174
Epoch 79/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4837 - accuracy: 0.8140
Epoch 80/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4835 - accuracy: 0.8144
Epoch 81/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4785 - accuracy: 0.8152
Epoch 82/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4844 - accuracy: 0.8149
Epoch 83/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4754 - accuracy: 0.8160
Epoch 84/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4773 - accuracy: 0.8186
Epoch 85/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4853 - accuracy: 0.8169
Epoch 86/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4847 - accuracy: 0.8113
Epoch 87/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4786 - accuracy: 0.8203
Epoch 88/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4863 - accuracy: 0.8095
Epoch 89/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4839 - accuracy: 0.8140
Epoch 90/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4935 - accuracy: 0.8113
Epoch 91/100
202/202 [==============================] - 1s 7ms/step - loss: 0.4838 - accuracy: 0.8112
Epoch 92/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4827 - accuracy: 0.8154
Epoch 93/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4737 - accuracy: 0.8172
Epoch 94/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4826 - accuracy: 0.8158
Epoch 95/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4792 - accuracy: 0.8172
Epoch 96/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4811 - accuracy: 0.8133
Epoch 97/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4849 - accuracy: 0.8099
Epoch 98/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4782 - accuracy: 0.8196
Epoch 99/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4835 - accuracy: 0.8189
Epoch 100/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4752 - accuracy: 0.8185

In [ ]:
model_2007.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2007.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
202/202 [==============================] - 4s 6ms/step - loss: 0.4786 - accuracy: 0.8126
Epoch 2/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4717 - accuracy: 0.8140
Epoch 3/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4691 - accuracy: 0.8158
Epoch 4/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4734 - accuracy: 0.8183
Epoch 5/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4694 - accuracy: 0.8209
Epoch 6/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4745 - accuracy: 0.8158
Epoch 7/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4758 - accuracy: 0.8185
Epoch 8/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4750 - accuracy: 0.8168
Epoch 9/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4774 - accuracy: 0.8166
Epoch 10/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4736 - accuracy: 0.8200
Epoch 11/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4716 - accuracy: 0.8171
Epoch 12/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4803 - accuracy: 0.8161
Epoch 13/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4804 - accuracy: 0.8202
Epoch 14/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4762 - accuracy: 0.8211
Epoch 15/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4766 - accuracy: 0.8157
Epoch 16/100
202/202 [==============================] - 1s 7ms/step - loss: 0.4710 - accuracy: 0.8197
Epoch 17/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4736 - accuracy: 0.8194
Epoch 18/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4814 - accuracy: 0.8160
Epoch 19/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4760 - accuracy: 0.8214
Epoch 20/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4827 - accuracy: 0.8127
Epoch 21/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4746 - accuracy: 0.8186
Epoch 22/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4734 - accuracy: 0.8191
Epoch 23/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4725 - accuracy: 0.8163
Epoch 24/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4770 - accuracy: 0.8151
Epoch 25/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4744 - accuracy: 0.8166
Epoch 26/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4757 - accuracy: 0.8154
Epoch 27/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4800 - accuracy: 0.8168
Epoch 28/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4705 - accuracy: 0.8192
Epoch 29/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4716 - accuracy: 0.8197
Epoch 30/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4704 - accuracy: 0.8154
Epoch 31/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4735 - accuracy: 0.8205
Epoch 32/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4808 - accuracy: 0.8194
Epoch 33/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4822 - accuracy: 0.8146
Epoch 34/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4772 - accuracy: 0.8197
Epoch 35/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4734 - accuracy: 0.8155
Epoch 36/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4823 - accuracy: 0.8115
Epoch 37/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4776 - accuracy: 0.8168
Epoch 38/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4704 - accuracy: 0.8185
Epoch 39/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4756 - accuracy: 0.8197
Epoch 40/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4823 - accuracy: 0.8180
Epoch 41/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4762 - accuracy: 0.8171
Epoch 42/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4686 - accuracy: 0.8231
Epoch 43/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4710 - accuracy: 0.8172
Epoch 44/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4823 - accuracy: 0.8149
Epoch 45/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4731 - accuracy: 0.8174
Epoch 46/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4890 - accuracy: 0.8140
Epoch 47/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4710 - accuracy: 0.8177
Epoch 48/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4745 - accuracy: 0.8209
Epoch 49/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4739 - accuracy: 0.8200
Epoch 50/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4989 - accuracy: 0.8146
Epoch 51/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4720 - accuracy: 0.8191
Epoch 52/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4899 - accuracy: 0.8099
Epoch 53/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4862 - accuracy: 0.8186
Epoch 54/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4844 - accuracy: 0.8137
Epoch 55/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4638 - accuracy: 0.8236
Epoch 56/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4765 - accuracy: 0.8223
Epoch 57/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4694 - accuracy: 0.8185
Epoch 58/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4718 - accuracy: 0.8191
Epoch 59/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4702 - accuracy: 0.8247
Epoch 60/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4739 - accuracy: 0.8146
Epoch 61/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4821 - accuracy: 0.8132
Epoch 62/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4720 - accuracy: 0.8197
Epoch 63/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4716 - accuracy: 0.8191
Epoch 64/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4730 - accuracy: 0.8152
Epoch 65/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4676 - accuracy: 0.8185
Epoch 66/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4709 - accuracy: 0.8171
Epoch 67/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4745 - accuracy: 0.8192
Epoch 68/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4770 - accuracy: 0.8161
Epoch 69/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4667 - accuracy: 0.8163
Epoch 70/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4754 - accuracy: 0.8177
Epoch 71/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4712 - accuracy: 0.8205
Epoch 72/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4713 - accuracy: 0.8169
Epoch 73/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4740 - accuracy: 0.8222
Epoch 74/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4851 - accuracy: 0.8168
Epoch 75/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4673 - accuracy: 0.8182
Epoch 76/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4822 - accuracy: 0.8110
Epoch 77/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4698 - accuracy: 0.8211
Epoch 78/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4762 - accuracy: 0.8158
Epoch 79/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4789 - accuracy: 0.8133
Epoch 80/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4772 - accuracy: 0.8178
Epoch 81/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4747 - accuracy: 0.8211
Epoch 82/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4804 - accuracy: 0.8175
Epoch 83/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4767 - accuracy: 0.8172
Epoch 84/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4677 - accuracy: 0.8211
Epoch 85/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4652 - accuracy: 0.8197
Epoch 86/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4777 - accuracy: 0.8133
Epoch 87/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4780 - accuracy: 0.8138
Epoch 88/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4792 - accuracy: 0.8147
Epoch 89/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4766 - accuracy: 0.8197
Epoch 90/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4688 - accuracy: 0.8192
Epoch 91/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4766 - accuracy: 0.8196
Epoch 92/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4780 - accuracy: 0.8177
Epoch 93/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4757 - accuracy: 0.8177
Epoch 94/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4688 - accuracy: 0.8194
Epoch 95/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4707 - accuracy: 0.8152
Epoch 96/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4742 - accuracy: 0.8234
Epoch 97/100
202/202 [==============================] - 1s 6ms/step - loss: 0.4763 - accuracy: 0.8191
Epoch 98/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4746 - accuracy: 0.8151
Epoch 99/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4716 - accuracy: 0.8175
Epoch 100/100
202/202 [==============================] - 1s 5ms/step - loss: 0.4661 - accuracy: 0.8227

In [ ]:
model_2007.save("/content/drive/MyDrive/FYP/Trained Models/2007.keras")

In [ ]:
predictions = model_2007(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

0

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.8079429103319888

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.8087597571552472

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2007.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2008

### Stratified sampling

In [ ]:
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2008, labels_2008):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2008)

numpy.ndarray

In [ ]:
fold1[0]

array([ 148,  149,  150, ..., 9529, 9530, 9531])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2008[x]
    y_train = labels_2008[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2008[x]))
    y_train = np.vstack((y_train, labels_2008[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2008[x]
    y_test = labels_2008[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2008[x]))
    y_test = np.vstack((y_test, labels_2008[x]))

In [ ]:
# Second iteration of Stratified KFold for test set
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2008[x]
    y_train = labels_2008[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2008[x]))
    y_train = np.vstack((y_train, labels_2008[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2008[x]
    y_test = labels_2008[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2008[x]))
    y_test = np.vstack((y_test, labels_2008[x]))

In [ ]:
# Third iteration of Stratified KFold for training test and cross validation set
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2008[x]
    y_train = labels_2008[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2008[x]))
    y_train = np.vstack((y_train, labels_2008[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2008[x]
    y_test = labels_2008[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2008[x]))
    y_test = np.vstack((y_test, labels_2008[x]))

In [ ]:
y_train.shape

(6354, 1)

## Model Training 2008

In [ ]:
model_2008 = Sequential()

In [ ]:
model_2008.add(Dense(units=520, activation="relu"))
model_2008.add(Dropout(0.2))
model_2008.add(Dense(units=250, activation="relu"))
model_2008.add(Dropout(0.2))
model_2008.add(Dense(units=128, activation="relu"))
model_2008.add(Dropout(0.2))
model_2008.add(Dense(units=64, activation="relu"))
model_2008.add(Dropout(0.2))
model_2008.add(Dense(units=45, activation="relu"))
model_2008.add(Dropout(0.2))
model_2008.add(Dense(units=28, activation="relu"))
model_2008.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2008.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2008.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
199/199 [==============================] - 3s 5ms/step - loss: 2.5390 - accuracy: 0.1805
Epoch 2/100
199/199 [==============================] - 1s 4ms/step - loss: 1.8637 - accuracy: 0.3366
Epoch 3/100
199/199 [==============================] - 1s 5ms/step - loss: 1.5222 - accuracy: 0.4424
Epoch 4/100
199/199 [==============================] - 1s 5ms/step - loss: 1.3562 - accuracy: 0.4954
Epoch 5/100
199/199 [==============================] - 1s 6ms/step - loss: 1.2669 - accuracy: 0.5206
Epoch 6/100
199/199 [==============================] - 1s 6ms/step - loss: 1.2134 - accuracy: 0.5442
Epoch 7/100
199/199 [==============================] - 1s 6ms/step - loss: 1.1669 - accuracy: 0.5655
Epoch 8/100
199/199 [==============================] - 1s 5ms/step - loss: 1.1174 - accuracy: 0.5839
Epoch 9/100
199/199 [==============================] - 1s 5ms/step - loss: 1.0914 - accuracy: 0.5990
Epoch 10/100
199/199 [==============================] - 1s 5ms/step - loss: 1.0371 - accuracy: 0.6228
Epoch 11/100
199/199 [==============================] - 1s 5ms/step - loss: 1.0048 - accuracy: 0.6330
Epoch 12/100
199/199 [==============================] - 1s 5ms/step - loss: 0.9905 - accuracy: 0.6300
Epoch 13/100
199/199 [==============================] - 1s 5ms/step - loss: 0.9738 - accuracy: 0.6394
Epoch 14/100
199/199 [==============================] - 1s 5ms/step - loss: 0.9523 - accuracy: 0.6404
Epoch 15/100
199/199 [==============================] - 1s 4ms/step - loss: 0.9346 - accuracy: 0.6630
Epoch 16/100
199/199 [==============================] - 1s 5ms/step - loss: 0.9283 - accuracy: 0.6568
Epoch 17/100
199/199 [==============================] - 1s 4ms/step - loss: 0.9205 - accuracy: 0.6568
Epoch 18/100
199/199 [==============================] - 1s 5ms/step - loss: 0.9092 - accuracy: 0.6571
Epoch 19/100
199/199 [==============================] - 1s 6ms/step - loss: 0.9157 - accuracy: 0.6553
Epoch 20/100
199/199 [==============================] - 1s 6ms/step - loss: 0.9133 - accuracy: 0.6601
Epoch 21/100
199/199 [==============================] - 1s 6ms/step - loss: 0.8648 - accuracy: 0.6723
Epoch 22/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8779 - accuracy: 0.6763
Epoch 23/100
199/199 [==============================] - 1s 4ms/step - loss: 0.8827 - accuracy: 0.6766
Epoch 24/100
199/199 [==============================] - 1s 4ms/step - loss: 0.8558 - accuracy: 0.6760
Epoch 25/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8597 - accuracy: 0.6764
Epoch 26/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8624 - accuracy: 0.6832
Epoch 27/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8554 - accuracy: 0.6755
Epoch 28/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8572 - accuracy: 0.6785
Epoch 29/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8302 - accuracy: 0.6909
Epoch 30/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8334 - accuracy: 0.6923
Epoch 31/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8247 - accuracy: 0.6865
Epoch 32/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8173 - accuracy: 0.6933
Epoch 33/100
199/199 [==============================] - 1s 6ms/step - loss: 0.8246 - accuracy: 0.6907
Epoch 34/100
199/199 [==============================] - 1s 6ms/step - loss: 0.8210 - accuracy: 0.6970
Epoch 35/100
199/199 [==============================] - 1s 6ms/step - loss: 0.8022 - accuracy: 0.6972
Epoch 36/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8104 - accuracy: 0.7002
Epoch 37/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8081 - accuracy: 0.7011
Epoch 38/100
199/199 [==============================] - 1s 5ms/step - loss: 0.8127 - accuracy: 0.6906
Epoch 39/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7878 - accuracy: 0.7068
Epoch 40/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7886 - accuracy: 0.7016
Epoch 41/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7961 - accuracy: 0.7077
Epoch 42/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7922 - accuracy: 0.6948
Epoch 43/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7898 - accuracy: 0.7000
Epoch 44/100
199/199 [==============================] - 1s 4ms/step - loss: 0.7827 - accuracy: 0.7073
Epoch 45/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7806 - accuracy: 0.7052
Epoch 46/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7611 - accuracy: 0.7169
Epoch 47/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7722 - accuracy: 0.7076
Epoch 48/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7629 - accuracy: 0.7114
Epoch 49/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7603 - accuracy: 0.7117
Epoch 50/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7604 - accuracy: 0.7103
Epoch 51/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7463 - accuracy: 0.7199
Epoch 52/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7479 - accuracy: 0.7172
Epoch 53/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7538 - accuracy: 0.7129
Epoch 54/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7408 - accuracy: 0.7251
Epoch 55/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7517 - accuracy: 0.7251
Epoch 56/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7651 - accuracy: 0.7095
Epoch 57/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7461 - accuracy: 0.7169
Epoch 58/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7527 - accuracy: 0.7148
Epoch 59/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7501 - accuracy: 0.7156
Epoch 60/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7285 - accuracy: 0.7295
Epoch 61/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7326 - accuracy: 0.7287
Epoch 62/100
199/199 [==============================] - 1s 7ms/step - loss: 0.7327 - accuracy: 0.7249
Epoch 63/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7301 - accuracy: 0.7265
Epoch 64/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7393 - accuracy: 0.7238
Epoch 65/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7409 - accuracy: 0.7328
Epoch 66/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7233 - accuracy: 0.7284
Epoch 67/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7254 - accuracy: 0.7247
Epoch 68/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7195 - accuracy: 0.7353
Epoch 69/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7221 - accuracy: 0.7293
Epoch 70/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7202 - accuracy: 0.7290
Epoch 71/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7107 - accuracy: 0.7325
Epoch 72/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7086 - accuracy: 0.7380
Epoch 73/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7197 - accuracy: 0.7232
Epoch 74/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7124 - accuracy: 0.7293
Epoch 75/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7031 - accuracy: 0.7391
Epoch 76/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7089 - accuracy: 0.7347
Epoch 77/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7167 - accuracy: 0.7326
Epoch 78/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7072 - accuracy: 0.7317
Epoch 79/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7032 - accuracy: 0.7340
Epoch 80/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7020 - accuracy: 0.7285
Epoch 81/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7007 - accuracy: 0.7331
Epoch 82/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7063 - accuracy: 0.7381
Epoch 83/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7091 - accuracy: 0.7342
Epoch 84/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7237 - accuracy: 0.7326
Epoch 85/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6899 - accuracy: 0.7361
Epoch 86/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7026 - accuracy: 0.7334
Epoch 87/100
199/199 [==============================] - 1s 5ms/step - loss: 0.7067 - accuracy: 0.7326
Epoch 88/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6895 - accuracy: 0.7405
Epoch 89/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7023 - accuracy: 0.7391
Epoch 90/100
199/199 [==============================] - 1s 6ms/step - loss: 0.6899 - accuracy: 0.7343
Epoch 91/100
199/199 [==============================] - 1s 6ms/step - loss: 0.7055 - accuracy: 0.7351
Epoch 92/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6804 - accuracy: 0.7398
Epoch 93/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6874 - accuracy: 0.7411
Epoch 94/100
199/199 [==============================] - 1s 4ms/step - loss: 0.6991 - accuracy: 0.7417
Epoch 95/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6799 - accuracy: 0.7455
Epoch 96/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6949 - accuracy: 0.7372
Epoch 97/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6956 - accuracy: 0.7395
Epoch 98/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6916 - accuracy: 0.7350
Epoch 99/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6830 - accuracy: 0.7428
Epoch 100/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6676 - accuracy: 0.7490

In [ ]:
model_2008.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2008.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
199/199 [==============================] - 3s 5ms/step - loss: 0.6473 - accuracy: 0.7534
Epoch 2/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6363 - accuracy: 0.7565
Epoch 3/100
199/199 [==============================] - 1s 4ms/step - loss: 0.6356 - accuracy: 0.7546
Epoch 4/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6255 - accuracy: 0.7611
Epoch 5/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6370 - accuracy: 0.7557
Epoch 6/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6228 - accuracy: 0.7619
Epoch 7/100
199/199 [==============================] - 1s 6ms/step - loss: 0.6314 - accuracy: 0.7658
Epoch 8/100
199/199 [==============================] - 1s 7ms/step - loss: 0.6185 - accuracy: 0.7624
Epoch 9/100
199/199 [==============================] - 1s 7ms/step - loss: 0.6229 - accuracy: 0.7649
Epoch 10/100
199/199 [==============================] - 1s 7ms/step - loss: 0.6239 - accuracy: 0.7642
Epoch 11/100
199/199 [==============================] - 1s 6ms/step - loss: 0.6082 - accuracy: 0.7669
Epoch 12/100
199/199 [==============================] - 1s 6ms/step - loss: 0.6159 - accuracy: 0.7650
Epoch 13/100
199/199 [==============================] - 1s 4ms/step - loss: 0.6134 - accuracy: 0.7614
Epoch 14/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6117 - accuracy: 0.7663
Epoch 15/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6201 - accuracy: 0.7663
Epoch 16/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6231 - accuracy: 0.7605
Epoch 17/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6174 - accuracy: 0.7661
Epoch 18/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6183 - accuracy: 0.7631
Epoch 19/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6153 - accuracy: 0.7696
Epoch 20/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6163 - accuracy: 0.7693
Epoch 21/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6176 - accuracy: 0.7620
Epoch 22/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6162 - accuracy: 0.7698
Epoch 23/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6057 - accuracy: 0.7696
Epoch 24/100
199/199 [==============================] - 1s 6ms/step - loss: 0.6081 - accuracy: 0.7702
Epoch 25/100
199/199 [==============================] - 1s 6ms/step - loss: 0.6089 - accuracy: 0.7674
Epoch 26/100
199/199 [==============================] - 1s 6ms/step - loss: 0.6178 - accuracy: 0.7614
Epoch 27/100
199/199 [==============================] - 1s 4ms/step - loss: 0.6138 - accuracy: 0.7661
Epoch 28/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6096 - accuracy: 0.7674
Epoch 29/100
199/199 [==============================] - 1s 4ms/step - loss: 0.6141 - accuracy: 0.7694
Epoch 30/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6134 - accuracy: 0.7679
Epoch 31/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6110 - accuracy: 0.7664
Epoch 32/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6105 - accuracy: 0.7680
Epoch 33/100
199/199 [==============================] - 1s 4ms/step - loss: 0.6089 - accuracy: 0.7767
Epoch 34/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6045 - accuracy: 0.7701
Epoch 35/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5992 - accuracy: 0.7727
Epoch 36/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5960 - accuracy: 0.7734
Epoch 37/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5921 - accuracy: 0.7699
Epoch 38/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5931 - accuracy: 0.7748
Epoch 39/100
199/199 [==============================] - 1s 6ms/step - loss: 0.6000 - accuracy: 0.7731
Epoch 40/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5977 - accuracy: 0.7675
Epoch 41/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6039 - accuracy: 0.7735
Epoch 42/100
199/199 [==============================] - 1s 4ms/step - loss: 0.6108 - accuracy: 0.7669
Epoch 43/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6038 - accuracy: 0.7726
Epoch 44/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6081 - accuracy: 0.7655
Epoch 45/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6064 - accuracy: 0.7699
Epoch 46/100
199/199 [==============================] - 1s 4ms/step - loss: 0.6024 - accuracy: 0.7704
Epoch 47/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5914 - accuracy: 0.7698
Epoch 48/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5957 - accuracy: 0.7724
Epoch 49/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5967 - accuracy: 0.7721
Epoch 50/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5980 - accuracy: 0.7657
Epoch 51/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5954 - accuracy: 0.7716
Epoch 52/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5880 - accuracy: 0.7724
Epoch 53/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5942 - accuracy: 0.7701
Epoch 54/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5954 - accuracy: 0.7768
Epoch 55/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5960 - accuracy: 0.7715
Epoch 56/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5849 - accuracy: 0.7721
Epoch 57/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5878 - accuracy: 0.7798
Epoch 58/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5930 - accuracy: 0.7768
Epoch 59/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5882 - accuracy: 0.7753
Epoch 60/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6020 - accuracy: 0.7696
Epoch 61/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5875 - accuracy: 0.7768
Epoch 62/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5999 - accuracy: 0.7775
Epoch 63/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5848 - accuracy: 0.7775
Epoch 64/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5795 - accuracy: 0.7778
Epoch 65/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5909 - accuracy: 0.7771
Epoch 66/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5837 - accuracy: 0.7779
Epoch 67/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5933 - accuracy: 0.7756
Epoch 68/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5861 - accuracy: 0.7723
Epoch 69/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5854 - accuracy: 0.7727
Epoch 70/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5879 - accuracy: 0.7768
Epoch 71/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5822 - accuracy: 0.7798
Epoch 72/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5868 - accuracy: 0.7735
Epoch 73/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5962 - accuracy: 0.7743
Epoch 74/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5734 - accuracy: 0.7808
Epoch 75/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5755 - accuracy: 0.7833
Epoch 76/100
199/199 [==============================] - 1s 5ms/step - loss: 0.6001 - accuracy: 0.7691
Epoch 77/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5800 - accuracy: 0.7737
Epoch 78/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5853 - accuracy: 0.7765
Epoch 79/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5727 - accuracy: 0.7830
Epoch 80/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5853 - accuracy: 0.7745
Epoch 81/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5783 - accuracy: 0.7778
Epoch 82/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5867 - accuracy: 0.7748
Epoch 83/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5789 - accuracy: 0.7778
Epoch 84/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5706 - accuracy: 0.7803
Epoch 85/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5701 - accuracy: 0.7754
Epoch 86/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5751 - accuracy: 0.7814
Epoch 87/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5709 - accuracy: 0.7803
Epoch 88/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5776 - accuracy: 0.7856
Epoch 89/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5764 - accuracy: 0.7794
Epoch 90/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5870 - accuracy: 0.7776
Epoch 91/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5801 - accuracy: 0.7775
Epoch 92/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5873 - accuracy: 0.7812
Epoch 93/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5802 - accuracy: 0.7794
Epoch 94/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5727 - accuracy: 0.7803
Epoch 95/100
199/199 [==============================] - 1s 7ms/step - loss: 0.5893 - accuracy: 0.7737
Epoch 96/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5787 - accuracy: 0.7825
Epoch 97/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5739 - accuracy: 0.7779
Epoch 98/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5755 - accuracy: 0.7847
Epoch 99/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5641 - accuracy: 0.7834
Epoch 100/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5847 - accuracy: 0.7806

In [ ]:
model_2008.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2008.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
199/199 [==============================] - 3s 5ms/step - loss: 0.5493 - accuracy: 0.7871
Epoch 2/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5264 - accuracy: 0.8023
Epoch 3/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5266 - accuracy: 0.7968
Epoch 4/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5222 - accuracy: 0.7984
Epoch 5/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5244 - accuracy: 0.7989
Epoch 6/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5311 - accuracy: 0.7921
Epoch 7/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7978
Epoch 8/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5289 - accuracy: 0.7986
Epoch 9/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.8023
Epoch 10/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7992
Epoch 11/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7995
Epoch 12/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5265 - accuracy: 0.8014
Epoch 13/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5178 - accuracy: 0.7986
Epoch 14/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7952
Epoch 15/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7984
Epoch 16/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5233 - accuracy: 0.7949
Epoch 17/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.7984
Epoch 18/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5181 - accuracy: 0.7997
Epoch 19/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5148 - accuracy: 0.8004
Epoch 20/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5226 - accuracy: 0.7989
Epoch 21/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5166 - accuracy: 0.8000
Epoch 22/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5151 - accuracy: 0.7987
Epoch 23/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5163 - accuracy: 0.7970
Epoch 24/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5171 - accuracy: 0.7970
Epoch 25/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.8033
Epoch 26/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.8004
Epoch 27/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5120 - accuracy: 0.8047
Epoch 28/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5161 - accuracy: 0.8003
Epoch 29/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.8003
Epoch 30/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5204 - accuracy: 0.7959
Epoch 31/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.8026
Epoch 32/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5097 - accuracy: 0.7987
Epoch 33/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.7984
Epoch 34/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5143 - accuracy: 0.8037
Epoch 35/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5097 - accuracy: 0.8011
Epoch 36/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5094 - accuracy: 0.8048
Epoch 37/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5179 - accuracy: 0.7984
Epoch 38/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5092 - accuracy: 0.8045
Epoch 39/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5127 - accuracy: 0.8028
Epoch 40/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5094 - accuracy: 0.8014
Epoch 41/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5022 - accuracy: 0.8003
Epoch 42/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5135 - accuracy: 0.8004
Epoch 43/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5169 - accuracy: 0.7970
Epoch 44/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.8036
Epoch 45/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.7978
Epoch 46/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.8063
Epoch 47/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.8009
Epoch 48/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5141 - accuracy: 0.7990
Epoch 49/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5146 - accuracy: 0.8059
Epoch 50/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5142 - accuracy: 0.8037
Epoch 51/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5063 - accuracy: 0.8009
Epoch 52/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5134 - accuracy: 0.7998
Epoch 53/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5128 - accuracy: 0.8033
Epoch 54/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5064 - accuracy: 0.8004
Epoch 55/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5088 - accuracy: 0.7993
Epoch 56/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5219 - accuracy: 0.7998
Epoch 57/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.8075
Epoch 58/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5172 - accuracy: 0.7997
Epoch 59/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5028 - accuracy: 0.8039
Epoch 60/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5185 - accuracy: 0.7986
Epoch 61/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.8048
Epoch 62/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5053 - accuracy: 0.8056
Epoch 63/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.8006
Epoch 64/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5014 - accuracy: 0.8000
Epoch 65/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.8008
Epoch 66/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.8023
Epoch 67/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.8044
Epoch 68/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5080 - accuracy: 0.8025
Epoch 69/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5104 - accuracy: 0.8006
Epoch 70/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5059 - accuracy: 0.7968
Epoch 71/100
199/199 [==============================] - 1s 6ms/step - loss: 0.5086 - accuracy: 0.8014
Epoch 72/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.8071
Epoch 73/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.8045
Epoch 74/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5050 - accuracy: 0.8061
Epoch 75/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5090 - accuracy: 0.8036
Epoch 76/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.8022
Epoch 77/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4982 - accuracy: 0.8071
Epoch 78/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7993
Epoch 79/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4992 - accuracy: 0.8052
Epoch 80/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.8044
Epoch 81/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.8075
Epoch 82/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.8020
Epoch 83/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.8056
Epoch 84/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5086 - accuracy: 0.7984
Epoch 85/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4975 - accuracy: 0.8067
Epoch 86/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5132 - accuracy: 0.7963
Epoch 87/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4988 - accuracy: 0.8061
Epoch 88/100
199/199 [==============================] - 1s 5ms/step - loss: 0.5062 - accuracy: 0.8034
Epoch 89/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4954 - accuracy: 0.8075
Epoch 90/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.8078
Epoch 91/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.8017
Epoch 92/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.7957
Epoch 93/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.8089
Epoch 94/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.8044
Epoch 95/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.8050
Epoch 96/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.7997
Epoch 97/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.7976
Epoch 98/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.8034
Epoch 99/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.8053
Epoch 100/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.8042

In [ ]:
model_2008.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2008.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
199/199 [==============================] - 3s 4ms/step - loss: 0.5028 - accuracy: 0.8075
Epoch 2/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4999 - accuracy: 0.8053
Epoch 3/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.8105
Epoch 4/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4859 - accuracy: 0.8053
Epoch 5/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.8037
Epoch 6/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.8102
Epoch 7/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4997 - accuracy: 0.8042
Epoch 8/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.8044
Epoch 9/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.8082
Epoch 10/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4910 - accuracy: 0.8105
Epoch 11/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4892 - accuracy: 0.8118
Epoch 12/100
199/199 [==============================] - 1s 6ms/step - loss: 0.4974 - accuracy: 0.8044
Epoch 13/100
199/199 [==============================] - 1s 6ms/step - loss: 0.4934 - accuracy: 0.8096
Epoch 14/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4939 - accuracy: 0.8105
Epoch 15/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4950 - accuracy: 0.8059
Epoch 16/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4984 - accuracy: 0.8069
Epoch 17/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.8088
Epoch 18/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.8044
Epoch 19/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.8108
Epoch 20/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4956 - accuracy: 0.8066
Epoch 21/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.8094
Epoch 22/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.8108
Epoch 23/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4964 - accuracy: 0.8050
Epoch 24/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.8053
Epoch 25/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4892 - accuracy: 0.8104
Epoch 26/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.8078
Epoch 27/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4968 - accuracy: 0.8082
Epoch 28/100
199/199 [==============================] - 1s 6ms/step - loss: 0.4884 - accuracy: 0.8083
Epoch 29/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4925 - accuracy: 0.8100
Epoch 30/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4952 - accuracy: 0.8088
Epoch 31/100
199/199 [==============================] - 1s 6ms/step - loss: 0.4820 - accuracy: 0.8116
Epoch 32/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.8091
Epoch 33/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.8078
Epoch 34/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4969 - accuracy: 0.8036
Epoch 35/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.8047
Epoch 36/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.8104
Epoch 37/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.8072
Epoch 38/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.8093
Epoch 39/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.8099
Epoch 40/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.8129
Epoch 41/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.8100
Epoch 42/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.8058
Epoch 43/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.8137
Epoch 44/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4997 - accuracy: 0.8056
Epoch 45/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4910 - accuracy: 0.8116
Epoch 46/100
199/199 [==============================] - 1s 6ms/step - loss: 0.4795 - accuracy: 0.8105
Epoch 47/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4953 - accuracy: 0.8132
Epoch 48/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4980 - accuracy: 0.8067
Epoch 49/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.8064
Epoch 50/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.8080
Epoch 51/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.8116
Epoch 52/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4922 - accuracy: 0.8086
Epoch 53/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.8100
Epoch 54/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4942 - accuracy: 0.8050
Epoch 55/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.8118
Epoch 56/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.8099
Epoch 57/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5000 - accuracy: 0.8063
Epoch 58/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.8059
Epoch 59/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.8100
Epoch 60/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.8110
Epoch 61/100
199/199 [==============================] - 1s 6ms/step - loss: 0.4931 - accuracy: 0.8066
Epoch 62/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4914 - accuracy: 0.8082
Epoch 63/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4936 - accuracy: 0.8067
Epoch 64/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4868 - accuracy: 0.8077
Epoch 65/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4938 - accuracy: 0.8138
Epoch 66/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.8072
Epoch 67/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.8096
Epoch 68/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.8009
Epoch 69/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4971 - accuracy: 0.8094
Epoch 70/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5013 - accuracy: 0.8059
Epoch 71/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.8107
Epoch 72/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4864 - accuracy: 0.8080
Epoch 73/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.8085
Epoch 74/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.8094
Epoch 75/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4863 - accuracy: 0.8064
Epoch 76/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.8102
Epoch 77/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.8085
Epoch 78/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4945 - accuracy: 0.8088
Epoch 79/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4879 - accuracy: 0.8074
Epoch 80/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4872 - accuracy: 0.8110
Epoch 81/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4939 - accuracy: 0.8072
Epoch 82/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.8105
Epoch 83/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4869 - accuracy: 0.8091
Epoch 84/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.8080
Epoch 85/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4854 - accuracy: 0.8074
Epoch 86/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4896 - accuracy: 0.8108
Epoch 87/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4930 - accuracy: 0.8077
Epoch 88/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.8058
Epoch 89/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.8124
Epoch 90/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.8059
Epoch 91/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4819 - accuracy: 0.8122
Epoch 92/100
199/199 [==============================] - 1s 4ms/step - loss: 0.5021 - accuracy: 0.8012
Epoch 93/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4883 - accuracy: 0.8067
Epoch 94/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4909 - accuracy: 0.8074
Epoch 95/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4898 - accuracy: 0.8099
Epoch 96/100
199/199 [==============================] - 1s 6ms/step - loss: 0.4925 - accuracy: 0.8072
Epoch 97/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4933 - accuracy: 0.8075
Epoch 98/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4882 - accuracy: 0.8102
Epoch 99/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4914 - accuracy: 0.8071
Epoch 100/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4858 - accuracy: 0.8071

In [ ]:
model_2008.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2008.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
199/199 [==============================] - 3s 4ms/step - loss: 0.4860 - accuracy: 0.8138
Epoch 2/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.8124
Epoch 3/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4851 - accuracy: 0.8108
Epoch 4/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.8105
Epoch 5/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.8080
Epoch 6/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.8143
Epoch 7/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.8110
Epoch 8/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.8165
Epoch 9/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4850 - accuracy: 0.8121
Epoch 10/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4890 - accuracy: 0.8102
Epoch 11/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4762 - accuracy: 0.8144
Epoch 12/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4881 - accuracy: 0.8124
Epoch 13/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4829 - accuracy: 0.8140
Epoch 14/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4917 - accuracy: 0.8078
Epoch 15/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.8124
Epoch 16/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.8100
Epoch 17/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.8097
Epoch 18/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4887 - accuracy: 0.8124
Epoch 19/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.8115
Epoch 20/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.8102
Epoch 21/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4893 - accuracy: 0.8066
Epoch 22/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.8119
Epoch 23/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4875 - accuracy: 0.8094
Epoch 24/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.8096
Epoch 25/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4862 - accuracy: 0.8104
Epoch 26/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4845 - accuracy: 0.8091
Epoch 27/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4919 - accuracy: 0.8108
Epoch 28/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.8111
Epoch 29/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4853 - accuracy: 0.8107
Epoch 30/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4799 - accuracy: 0.8143
Epoch 31/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.8113
Epoch 32/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.8124
Epoch 33/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4777 - accuracy: 0.8100
Epoch 34/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.8107
Epoch 35/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4809 - accuracy: 0.8121
Epoch 36/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.8099
Epoch 37/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4814 - accuracy: 0.8110
Epoch 38/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.8121
Epoch 39/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.8069
Epoch 40/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4795 - accuracy: 0.8113
Epoch 41/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4797 - accuracy: 0.8132
Epoch 42/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4843 - accuracy: 0.8105
Epoch 43/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4870 - accuracy: 0.8135
Epoch 44/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.8111
Epoch 45/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.8116
Epoch 46/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4843 - accuracy: 0.8129
Epoch 47/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4879 - accuracy: 0.8072
Epoch 48/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.8129
Epoch 49/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4827 - accuracy: 0.8111
Epoch 50/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4721 - accuracy: 0.8155
Epoch 51/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4763 - accuracy: 0.8189
Epoch 52/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4766 - accuracy: 0.8141
Epoch 53/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4724 - accuracy: 0.8157
Epoch 54/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4838 - accuracy: 0.8130
Epoch 55/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4842 - accuracy: 0.8099
Epoch 56/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4906 - accuracy: 0.8061
Epoch 57/100
199/199 [==============================] - 1s 6ms/step - loss: 0.4734 - accuracy: 0.8140
Epoch 58/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4811 - accuracy: 0.8129
Epoch 59/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4806 - accuracy: 0.8100
Epoch 60/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.8082
Epoch 61/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4847 - accuracy: 0.8110
Epoch 62/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.8108
Epoch 63/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.8129
Epoch 64/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4806 - accuracy: 0.8119
Epoch 65/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.8086
Epoch 66/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4889 - accuracy: 0.8088
Epoch 67/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.8080
Epoch 68/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.8170
Epoch 69/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.8080
Epoch 70/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4836 - accuracy: 0.8096
Epoch 71/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.8102
Epoch 72/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4856 - accuracy: 0.8108
Epoch 73/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4785 - accuracy: 0.8118
Epoch 74/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4893 - accuracy: 0.8137
Epoch 75/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4784 - accuracy: 0.8137
Epoch 76/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4849 - accuracy: 0.8082
Epoch 77/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.8144
Epoch 78/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.8121
Epoch 79/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.8105
Epoch 80/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.8165
Epoch 81/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.8141
Epoch 82/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4811 - accuracy: 0.8126
Epoch 83/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.8108
Epoch 84/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4850 - accuracy: 0.8111
Epoch 85/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.8129
Epoch 86/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.8119
Epoch 87/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4852 - accuracy: 0.8089
Epoch 88/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4839 - accuracy: 0.8140
Epoch 89/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4851 - accuracy: 0.8104
Epoch 90/100
199/199 [==============================] - 1s 5ms/step - loss: 0.4794 - accuracy: 0.8129
Epoch 91/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.8140
Epoch 92/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4872 - accuracy: 0.8115
Epoch 93/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4855 - accuracy: 0.8121
Epoch 94/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4885 - accuracy: 0.8077
Epoch 95/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.8091
Epoch 96/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4805 - accuracy: 0.8097
Epoch 97/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4899 - accuracy: 0.8108
Epoch 98/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.8086
Epoch 99/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4831 - accuracy: 0.8152
Epoch 100/100
199/199 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.8102

In [ ]:
model_2008.save("/content/drive/MyDrive/FYP/Trained Models/2008.keras")

In [ ]:
predictions = model_2008(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

0

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.7879169288860919

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.8091934084995663

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2008.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2009

### Stratified sampling

In [ ]:
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2009, labels_2009):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2009)

numpy.ndarray

In [ ]:
fold1[0]

array([ 152,  153,  154, ..., 9267, 9268, 9269])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2009[x]
    y_train = labels_2009[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2009[x]))
    y_train = np.vstack((y_train, labels_2009[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2009[x]
    y_test = labels_2009[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2009[x]))
    y_test = np.vstack((y_test, labels_2009[x]))

In [ ]:
# Second iteration of Stratified KFold for test set
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2009[x]
    y_train = labels_2009[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2009[x]))
    y_train = np.vstack((y_train, labels_2009[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2009[x]
    y_test = labels_2009[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2009[x]))
    y_test = np.vstack((y_test, labels_2009[x]))

In [ ]:
# Third iteration of Stratified KFold for training test and cross validation set
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2009[x]
    y_train = labels_2009[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2009[x]))
    y_train = np.vstack((y_train, labels_2009[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2009[x]
    y_test = labels_2009[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2009[x]))
    y_test = np.vstack((y_test, labels_2009[x]))

In [ ]:
y_train.shape

(6180, 1)

## Model Training 2009

In [ ]:
model_2009 = Sequential()

In [ ]:
model_2009.add(Dense(units=520, activation="relu"))
model_2009.add(Dropout(0.2))
model_2009.add(Dense(units=250, activation="relu"))
model_2009.add(Dropout(0.2))
model_2009.add(Dense(units=128, activation="relu"))
model_2009.add(Dropout(0.2))
model_2009.add(Dense(units=64, activation="relu"))
model_2009.add(Dropout(0.2))
model_2009.add(Dense(units=45, activation="relu"))
model_2009.add(Dropout(0.2))
model_2009.add(Dense(units=28, activation="relu"))
model_2009.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2009.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2009.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
194/194 [==============================] - 4s 6ms/step - loss: 2.5641 - accuracy: 0.1859
Epoch 2/100
194/194 [==============================] - 1s 6ms/step - loss: 1.7763 - accuracy: 0.3786
Epoch 3/100
194/194 [==============================] - 1s 6ms/step - loss: 1.4895 - accuracy: 0.4555
Epoch 4/100
194/194 [==============================] - 1s 5ms/step - loss: 1.3587 - accuracy: 0.5005
Epoch 5/100
194/194 [==============================] - 1s 5ms/step - loss: 1.2860 - accuracy: 0.5104
Epoch 6/100
194/194 [==============================] - 1s 5ms/step - loss: 1.2498 - accuracy: 0.5301
Epoch 7/100
194/194 [==============================] - 1s 5ms/step - loss: 1.2000 - accuracy: 0.5422
Epoch 8/100
194/194 [==============================] - 1s 4ms/step - loss: 1.1640 - accuracy: 0.5620
Epoch 9/100
194/194 [==============================] - 1s 5ms/step - loss: 1.1369 - accuracy: 0.5728
Epoch 10/100
194/194 [==============================] - 1s 5ms/step - loss: 1.1088 - accuracy: 0.5780
Epoch 11/100
194/194 [==============================] - 1s 5ms/step - loss: 1.0965 - accuracy: 0.5854
Epoch 12/100
194/194 [==============================] - 1s 4ms/step - loss: 1.0743 - accuracy: 0.6045
Epoch 13/100
194/194 [==============================] - 1s 5ms/step - loss: 1.0475 - accuracy: 0.6095
Epoch 14/100
194/194 [==============================] - 1s 5ms/step - loss: 1.0190 - accuracy: 0.6146
Epoch 15/100
194/194 [==============================] - 1s 6ms/step - loss: 1.0041 - accuracy: 0.6223
Epoch 16/100
194/194 [==============================] - 1s 6ms/step - loss: 1.0051 - accuracy: 0.6243
Epoch 17/100
194/194 [==============================] - 1s 6ms/step - loss: 1.0040 - accuracy: 0.6259
Epoch 18/100
194/194 [==============================] - 1s 5ms/step - loss: 0.9843 - accuracy: 0.6332
Epoch 19/100
194/194 [==============================] - 1s 5ms/step - loss: 0.9656 - accuracy: 0.6409
Epoch 20/100
194/194 [==============================] - 1s 4ms/step - loss: 0.9619 - accuracy: 0.6421
Epoch 21/100
194/194 [==============================] - 1s 4ms/step - loss: 0.9303 - accuracy: 0.6489
Epoch 22/100
194/194 [==============================] - 1s 4ms/step - loss: 0.9351 - accuracy: 0.6492
Epoch 23/100
194/194 [==============================] - 1s 4ms/step - loss: 0.9323 - accuracy: 0.6531
Epoch 24/100
194/194 [==============================] - 1s 5ms/step - loss: 0.9104 - accuracy: 0.6600
Epoch 25/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8916 - accuracy: 0.6657
Epoch 26/100
194/194 [==============================] - 1s 5ms/step - loss: 0.9013 - accuracy: 0.6565
Epoch 27/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8873 - accuracy: 0.6667
Epoch 28/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8959 - accuracy: 0.6681
Epoch 29/100
194/194 [==============================] - 1s 6ms/step - loss: 0.8704 - accuracy: 0.6762
Epoch 30/100
194/194 [==============================] - 1s 6ms/step - loss: 0.8712 - accuracy: 0.6756
Epoch 31/100
194/194 [==============================] - 1s 6ms/step - loss: 0.8780 - accuracy: 0.6681
Epoch 32/100
194/194 [==============================] - 1s 6ms/step - loss: 0.8497 - accuracy: 0.6820
Epoch 33/100
194/194 [==============================] - 1s 4ms/step - loss: 0.8622 - accuracy: 0.6762
Epoch 34/100
194/194 [==============================] - 1s 4ms/step - loss: 0.8559 - accuracy: 0.6764
Epoch 35/100
194/194 [==============================] - 1s 4ms/step - loss: 0.8591 - accuracy: 0.6788
Epoch 36/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8539 - accuracy: 0.6764
Epoch 37/100
194/194 [==============================] - 1s 4ms/step - loss: 0.8477 - accuracy: 0.6785
Epoch 38/100
194/194 [==============================] - 1s 4ms/step - loss: 0.8189 - accuracy: 0.6927
Epoch 39/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8323 - accuracy: 0.6867
Epoch 40/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8317 - accuracy: 0.6903
Epoch 41/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8303 - accuracy: 0.6903
Epoch 42/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8141 - accuracy: 0.6917
Epoch 43/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8202 - accuracy: 0.6888
Epoch 44/100
194/194 [==============================] - 1s 6ms/step - loss: 0.8134 - accuracy: 0.6932
Epoch 45/100
194/194 [==============================] - 1s 6ms/step - loss: 0.8056 - accuracy: 0.7023
Epoch 46/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7983 - accuracy: 0.6939
Epoch 47/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7927 - accuracy: 0.7057
Epoch 48/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8032 - accuracy: 0.6945
Epoch 49/100
194/194 [==============================] - 1s 5ms/step - loss: 0.8200 - accuracy: 0.6937
Epoch 50/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7995 - accuracy: 0.7021
Epoch 51/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7874 - accuracy: 0.7052
Epoch 52/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7994 - accuracy: 0.7003
Epoch 53/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7833 - accuracy: 0.7058
Epoch 54/100
194/194 [==============================] - 1s 4ms/step - loss: 0.7873 - accuracy: 0.7015
Epoch 55/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7847 - accuracy: 0.7070
Epoch 56/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7706 - accuracy: 0.7112
Epoch 57/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7908 - accuracy: 0.7018
Epoch 58/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7857 - accuracy: 0.7042
Epoch 59/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7689 - accuracy: 0.7092
Epoch 60/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7762 - accuracy: 0.7128
Epoch 61/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7679 - accuracy: 0.7066
Epoch 62/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7676 - accuracy: 0.7183
Epoch 63/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7663 - accuracy: 0.7099
Epoch 64/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7551 - accuracy: 0.7126
Epoch 65/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7643 - accuracy: 0.7060
Epoch 66/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7599 - accuracy: 0.7117
Epoch 67/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7598 - accuracy: 0.7138
Epoch 68/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7340 - accuracy: 0.7167
Epoch 69/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7623 - accuracy: 0.7157
Epoch 70/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7434 - accuracy: 0.7199
Epoch 71/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7490 - accuracy: 0.7214
Epoch 72/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7553 - accuracy: 0.7129
Epoch 73/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7444 - accuracy: 0.7186
Epoch 74/100
194/194 [==============================] - 1s 7ms/step - loss: 0.7456 - accuracy: 0.7141
Epoch 75/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7254 - accuracy: 0.7294
Epoch 76/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7430 - accuracy: 0.7144
Epoch 77/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7426 - accuracy: 0.7172
Epoch 78/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7243 - accuracy: 0.7228
Epoch 79/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7283 - accuracy: 0.7209
Epoch 80/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7247 - accuracy: 0.7262
Epoch 81/100
194/194 [==============================] - 1s 4ms/step - loss: 0.7447 - accuracy: 0.7160
Epoch 82/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7476 - accuracy: 0.7129
Epoch 83/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7212 - accuracy: 0.7282
Epoch 84/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7294 - accuracy: 0.7210
Epoch 85/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7271 - accuracy: 0.7220
Epoch 86/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7224 - accuracy: 0.7320
Epoch 87/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7244 - accuracy: 0.7214
Epoch 88/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7160 - accuracy: 0.7270
Epoch 89/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7111 - accuracy: 0.7277
Epoch 90/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7328 - accuracy: 0.7267
Epoch 91/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7111 - accuracy: 0.7273
Epoch 92/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7102 - accuracy: 0.7256
Epoch 93/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7285 - accuracy: 0.7248
Epoch 94/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7083 - accuracy: 0.7312
Epoch 95/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7062 - accuracy: 0.7267
Epoch 96/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7071 - accuracy: 0.7272
Epoch 97/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7390 - accuracy: 0.7254
Epoch 98/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7223 - accuracy: 0.7299
Epoch 99/100
194/194 [==============================] - 1s 5ms/step - loss: 0.7091 - accuracy: 0.7283
Epoch 100/100
194/194 [==============================] - 1s 6ms/step - loss: 0.7298 - accuracy: 0.7231

In [ ]:
model_2009.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2009.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
194/194 [==============================] - 4s 5ms/step - loss: 0.6745 - accuracy: 0.7414
Epoch 2/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6720 - accuracy: 0.7482
Epoch 3/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6637 - accuracy: 0.7495
Epoch 4/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6506 - accuracy: 0.7447
Epoch 5/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6601 - accuracy: 0.7490
Epoch 6/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6583 - accuracy: 0.7450
Epoch 7/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6455 - accuracy: 0.7553
Epoch 8/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6571 - accuracy: 0.7492
Epoch 9/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6453 - accuracy: 0.7526
Epoch 10/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6447 - accuracy: 0.7528
Epoch 11/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6519 - accuracy: 0.7519
Epoch 12/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6396 - accuracy: 0.7500
Epoch 13/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6353 - accuracy: 0.7532
Epoch 14/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6405 - accuracy: 0.7528
Epoch 15/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6569 - accuracy: 0.7429
Epoch 16/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6376 - accuracy: 0.7552
Epoch 17/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6333 - accuracy: 0.7534
Epoch 18/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6443 - accuracy: 0.7492
Epoch 19/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6430 - accuracy: 0.7519
Epoch 20/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6366 - accuracy: 0.7545
Epoch 21/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6335 - accuracy: 0.7584
Epoch 22/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6300 - accuracy: 0.7542
Epoch 23/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6355 - accuracy: 0.7505
Epoch 24/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6318 - accuracy: 0.7570
Epoch 25/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6175 - accuracy: 0.7625
Epoch 26/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6239 - accuracy: 0.7604
Epoch 27/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6352 - accuracy: 0.7553
Epoch 28/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6191 - accuracy: 0.7574
Epoch 29/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6214 - accuracy: 0.7662
Epoch 30/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6303 - accuracy: 0.7505
Epoch 31/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6212 - accuracy: 0.7642
Epoch 32/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6348 - accuracy: 0.7589
Epoch 33/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6212 - accuracy: 0.7639
Epoch 34/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6237 - accuracy: 0.7583
Epoch 35/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6243 - accuracy: 0.7570
Epoch 36/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6299 - accuracy: 0.7568
Epoch 37/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6225 - accuracy: 0.7547
Epoch 38/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6276 - accuracy: 0.7529
Epoch 39/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6189 - accuracy: 0.7607
Epoch 40/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6199 - accuracy: 0.7650
Epoch 41/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6323 - accuracy: 0.7595
Epoch 42/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6197 - accuracy: 0.7583
Epoch 43/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6263 - accuracy: 0.7578
Epoch 44/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6188 - accuracy: 0.7584
Epoch 45/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6100 - accuracy: 0.7642
Epoch 46/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6080 - accuracy: 0.7668
Epoch 47/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6039 - accuracy: 0.7701
Epoch 48/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6142 - accuracy: 0.7629
Epoch 49/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6224 - accuracy: 0.7608
Epoch 50/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6102 - accuracy: 0.7676
Epoch 51/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6123 - accuracy: 0.7655
Epoch 52/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6039 - accuracy: 0.7667
Epoch 53/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6198 - accuracy: 0.7586
Epoch 54/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6223 - accuracy: 0.7647
Epoch 55/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6215 - accuracy: 0.7633
Epoch 56/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6156 - accuracy: 0.7667
Epoch 57/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6117 - accuracy: 0.7621
Epoch 58/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6078 - accuracy: 0.7641
Epoch 59/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5949 - accuracy: 0.7706
Epoch 60/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6028 - accuracy: 0.7667
Epoch 61/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6023 - accuracy: 0.7696
Epoch 62/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6187 - accuracy: 0.7531
Epoch 63/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6134 - accuracy: 0.7663
Epoch 64/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6031 - accuracy: 0.7607
Epoch 65/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6124 - accuracy: 0.7629
Epoch 66/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6063 - accuracy: 0.7676
Epoch 67/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6052 - accuracy: 0.7659
Epoch 68/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6062 - accuracy: 0.7693
Epoch 69/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6030 - accuracy: 0.7668
Epoch 70/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6060 - accuracy: 0.7604
Epoch 71/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5972 - accuracy: 0.7686
Epoch 72/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6127 - accuracy: 0.7659
Epoch 73/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5996 - accuracy: 0.7684
Epoch 74/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5910 - accuracy: 0.7727
Epoch 75/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5960 - accuracy: 0.7759
Epoch 76/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5973 - accuracy: 0.7694
Epoch 77/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6057 - accuracy: 0.7718
Epoch 78/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6159 - accuracy: 0.7650
Epoch 79/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5953 - accuracy: 0.7662
Epoch 80/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5911 - accuracy: 0.7684
Epoch 81/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5990 - accuracy: 0.7697
Epoch 82/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5951 - accuracy: 0.7722
Epoch 83/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6002 - accuracy: 0.7691
Epoch 84/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6035 - accuracy: 0.7665
Epoch 85/100
194/194 [==============================] - 1s 5ms/step - loss: 0.6034 - accuracy: 0.7636
Epoch 86/100
194/194 [==============================] - 1s 6ms/step - loss: 0.6035 - accuracy: 0.7710
Epoch 87/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5951 - accuracy: 0.7706
Epoch 88/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5969 - accuracy: 0.7744
Epoch 89/100
194/194 [==============================] - 1s 4ms/step - loss: 0.6069 - accuracy: 0.7629
Epoch 90/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5946 - accuracy: 0.7715
Epoch 91/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5890 - accuracy: 0.7706
Epoch 92/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5936 - accuracy: 0.7717
Epoch 93/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5869 - accuracy: 0.7660
Epoch 94/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5849 - accuracy: 0.7739
Epoch 95/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5745 - accuracy: 0.7778
Epoch 96/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5981 - accuracy: 0.7723
Epoch 97/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5999 - accuracy: 0.7628
Epoch 98/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5977 - accuracy: 0.7641
Epoch 99/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5831 - accuracy: 0.7796
Epoch 100/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5891 - accuracy: 0.7715

In [ ]:
model_2009.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2009.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
194/194 [==============================] - 3s 5ms/step - loss: 0.5769 - accuracy: 0.7751
Epoch 2/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5648 - accuracy: 0.7783
Epoch 3/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5544 - accuracy: 0.7875
Epoch 4/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5507 - accuracy: 0.7885
Epoch 5/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5604 - accuracy: 0.7840
Epoch 6/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5447 - accuracy: 0.7861
Epoch 7/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5537 - accuracy: 0.7809
Epoch 8/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5576 - accuracy: 0.7845
Epoch 9/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5390 - accuracy: 0.7840
Epoch 10/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5495 - accuracy: 0.7895
Epoch 11/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5373 - accuracy: 0.7856
Epoch 12/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5404 - accuracy: 0.7917
Epoch 13/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5346 - accuracy: 0.7964
Epoch 14/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5439 - accuracy: 0.7887
Epoch 15/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5485 - accuracy: 0.7841
Epoch 16/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7909
Epoch 17/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5437 - accuracy: 0.7859
Epoch 18/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5415 - accuracy: 0.7909
Epoch 19/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5386 - accuracy: 0.7960
Epoch 20/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5481 - accuracy: 0.7845
Epoch 21/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5388 - accuracy: 0.7883
Epoch 22/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5364 - accuracy: 0.7903
Epoch 23/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5314 - accuracy: 0.7906
Epoch 24/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5275 - accuracy: 0.7911
Epoch 25/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5334 - accuracy: 0.7900
Epoch 26/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5435 - accuracy: 0.7896
Epoch 27/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5476 - accuracy: 0.7880
Epoch 28/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5248 - accuracy: 0.7977
Epoch 29/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5326 - accuracy: 0.7932
Epoch 30/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5424 - accuracy: 0.7827
Epoch 31/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5442 - accuracy: 0.7898
Epoch 32/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5393 - accuracy: 0.7887
Epoch 33/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5324 - accuracy: 0.7900
Epoch 34/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5331 - accuracy: 0.7926
Epoch 35/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5335 - accuracy: 0.7883
Epoch 36/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5381 - accuracy: 0.7937
Epoch 37/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5354 - accuracy: 0.7895
Epoch 38/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5240 - accuracy: 0.7968
Epoch 39/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5302 - accuracy: 0.7911
Epoch 40/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5321 - accuracy: 0.7927
Epoch 41/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5301 - accuracy: 0.7953
Epoch 42/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5346 - accuracy: 0.7914
Epoch 43/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5337 - accuracy: 0.7890
Epoch 44/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5464 - accuracy: 0.7838
Epoch 45/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5347 - accuracy: 0.7927
Epoch 46/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5399 - accuracy: 0.7851
Epoch 47/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5274 - accuracy: 0.7924
Epoch 48/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5350 - accuracy: 0.7947
Epoch 49/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5361 - accuracy: 0.7916
Epoch 50/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5340 - accuracy: 0.7880
Epoch 51/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5306 - accuracy: 0.7950
Epoch 52/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5321 - accuracy: 0.7930
Epoch 53/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5336 - accuracy: 0.7924
Epoch 54/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5423 - accuracy: 0.7935
Epoch 55/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5360 - accuracy: 0.7888
Epoch 56/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5291 - accuracy: 0.7971
Epoch 57/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5351 - accuracy: 0.7932
Epoch 58/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7977
Epoch 59/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7939
Epoch 60/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7919
Epoch 61/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5282 - accuracy: 0.7964
Epoch 62/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5407 - accuracy: 0.7900
Epoch 63/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5278 - accuracy: 0.7916
Epoch 64/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5282 - accuracy: 0.7966
Epoch 65/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5283 - accuracy: 0.7900
Epoch 66/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5208 - accuracy: 0.7937
Epoch 67/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7934
Epoch 68/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5392 - accuracy: 0.7877
Epoch 69/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5267 - accuracy: 0.7942
Epoch 70/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5229 - accuracy: 0.7929
Epoch 71/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5362 - accuracy: 0.7929
Epoch 72/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5371 - accuracy: 0.7901
Epoch 73/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5341 - accuracy: 0.7890
Epoch 74/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5233 - accuracy: 0.7984
Epoch 75/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5303 - accuracy: 0.7974
Epoch 76/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5306 - accuracy: 0.7906
Epoch 77/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5240 - accuracy: 0.7994
Epoch 78/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5268 - accuracy: 0.7982
Epoch 79/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5264 - accuracy: 0.7953
Epoch 80/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5258 - accuracy: 0.7951
Epoch 81/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5243 - accuracy: 0.7945
Epoch 82/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5268 - accuracy: 0.7982
Epoch 83/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5263 - accuracy: 0.7956
Epoch 84/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5171 - accuracy: 0.7968
Epoch 85/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.8010
Epoch 86/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5323 - accuracy: 0.7892
Epoch 87/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5219 - accuracy: 0.7977
Epoch 88/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5243 - accuracy: 0.7968
Epoch 89/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5307 - accuracy: 0.7909
Epoch 90/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5246 - accuracy: 0.7906
Epoch 91/100
194/194 [==============================] - 1s 7ms/step - loss: 0.5157 - accuracy: 0.8000
Epoch 92/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5257 - accuracy: 0.7968
Epoch 93/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5157 - accuracy: 0.8003
Epoch 94/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5045 - accuracy: 0.8015
Epoch 95/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5338 - accuracy: 0.7905
Epoch 96/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5243 - accuracy: 0.7985
Epoch 97/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5348 - accuracy: 0.7922
Epoch 98/100
194/194 [==============================] - 1s 7ms/step - loss: 0.5282 - accuracy: 0.7908
Epoch 99/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5219 - accuracy: 0.7939
Epoch 100/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.7990

In [ ]:
model_2009.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2009.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
194/194 [==============================] - 3s 6ms/step - loss: 0.5216 - accuracy: 0.7953
Epoch 2/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5221 - accuracy: 0.8026
Epoch 3/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5124 - accuracy: 0.7994
Epoch 4/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5141 - accuracy: 0.7989
Epoch 5/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5159 - accuracy: 0.7995
Epoch 6/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5178 - accuracy: 0.7913
Epoch 7/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5150 - accuracy: 0.8008
Epoch 8/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5174 - accuracy: 0.8008
Epoch 9/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5209 - accuracy: 0.7960
Epoch 10/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5252 - accuracy: 0.7943
Epoch 11/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5142 - accuracy: 0.8011
Epoch 12/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5140 - accuracy: 0.7963
Epoch 13/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5163 - accuracy: 0.7943
Epoch 14/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5145 - accuracy: 0.7997
Epoch 15/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5142 - accuracy: 0.7989
Epoch 16/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5092 - accuracy: 0.8015
Epoch 17/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5229 - accuracy: 0.7935
Epoch 18/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5008 - accuracy: 0.8049
Epoch 19/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5128 - accuracy: 0.7974
Epoch 20/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5114 - accuracy: 0.8006
Epoch 21/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5151 - accuracy: 0.7935
Epoch 22/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5160 - accuracy: 0.7998
Epoch 23/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5191 - accuracy: 0.7956
Epoch 24/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5102 - accuracy: 0.8021
Epoch 25/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5175 - accuracy: 0.8003
Epoch 26/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.8024
Epoch 27/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5156 - accuracy: 0.7976
Epoch 28/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5137 - accuracy: 0.8000
Epoch 29/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5238 - accuracy: 0.7964
Epoch 30/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5094 - accuracy: 0.8047
Epoch 31/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5165 - accuracy: 0.7969
Epoch 32/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5188 - accuracy: 0.8003
Epoch 33/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5053 - accuracy: 0.7998
Epoch 34/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4999 - accuracy: 0.8042
Epoch 35/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5188 - accuracy: 0.7992
Epoch 36/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5057 - accuracy: 0.8024
Epoch 37/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5060 - accuracy: 0.8013
Epoch 38/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5063 - accuracy: 0.8002
Epoch 39/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5109 - accuracy: 0.8026
Epoch 40/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5078 - accuracy: 0.8000
Epoch 41/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5181 - accuracy: 0.7958
Epoch 42/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5097 - accuracy: 0.7989
Epoch 43/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5150 - accuracy: 0.7974
Epoch 44/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5127 - accuracy: 0.7997
Epoch 45/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5041 - accuracy: 0.8047
Epoch 46/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5118 - accuracy: 0.8006
Epoch 47/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5011 - accuracy: 0.8076
Epoch 48/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5161 - accuracy: 0.8026
Epoch 49/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5141 - accuracy: 0.7977
Epoch 50/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5157 - accuracy: 0.7934
Epoch 51/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5090 - accuracy: 0.7958
Epoch 52/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5177 - accuracy: 0.8032
Epoch 53/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5161 - accuracy: 0.7963
Epoch 54/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.8053
Epoch 55/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5092 - accuracy: 0.8000
Epoch 56/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7998
Epoch 57/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5080 - accuracy: 0.8034
Epoch 58/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5119 - accuracy: 0.7951
Epoch 59/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5151 - accuracy: 0.7992
Epoch 60/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5091 - accuracy: 0.7990
Epoch 61/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5069 - accuracy: 0.8044
Epoch 62/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5111 - accuracy: 0.8021
Epoch 63/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5125 - accuracy: 0.7971
Epoch 64/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5202 - accuracy: 0.7943
Epoch 65/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5139 - accuracy: 0.7981
Epoch 66/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5096 - accuracy: 0.8040
Epoch 67/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5128 - accuracy: 0.7987
Epoch 68/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5150 - accuracy: 0.7927
Epoch 69/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5100 - accuracy: 0.8006
Epoch 70/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5174 - accuracy: 0.7998
Epoch 71/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5015 - accuracy: 0.8083
Epoch 72/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5133 - accuracy: 0.7976
Epoch 73/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5031 - accuracy: 0.8055
Epoch 74/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5112 - accuracy: 0.7984
Epoch 75/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5105 - accuracy: 0.8021
Epoch 76/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5141 - accuracy: 0.7961
Epoch 77/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5189 - accuracy: 0.7981
Epoch 78/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5078 - accuracy: 0.7995
Epoch 79/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5087 - accuracy: 0.7972
Epoch 80/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5008 - accuracy: 0.8010
Epoch 81/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.8021
Epoch 82/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7966
Epoch 83/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.8036
Epoch 84/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5062 - accuracy: 0.8013
Epoch 85/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5154 - accuracy: 0.7992
Epoch 86/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.7981
Epoch 87/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5144 - accuracy: 0.7942
Epoch 88/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5186 - accuracy: 0.7939
Epoch 89/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5077 - accuracy: 0.7997
Epoch 90/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5148 - accuracy: 0.7963
Epoch 91/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4972 - accuracy: 0.8039
Epoch 92/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5042 - accuracy: 0.8024
Epoch 93/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5145 - accuracy: 0.8021
Epoch 94/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.8010
Epoch 95/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5077 - accuracy: 0.8008
Epoch 96/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.8023
Epoch 97/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5080 - accuracy: 0.8010
Epoch 98/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5101 - accuracy: 0.7960
Epoch 99/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5013 - accuracy: 0.8044
Epoch 100/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5129 - accuracy: 0.8019

In [ ]:
model_2009.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2009.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
194/194 [==============================] - 4s 6ms/step - loss: 0.5079 - accuracy: 0.8047
Epoch 2/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5059 - accuracy: 0.8011
Epoch 3/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5066 - accuracy: 0.7977
Epoch 4/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5126 - accuracy: 0.8040
Epoch 5/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5057 - accuracy: 0.7977
Epoch 6/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5004 - accuracy: 0.8042
Epoch 7/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.7964
Epoch 8/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5111 - accuracy: 0.8002
Epoch 9/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4980 - accuracy: 0.8055
Epoch 10/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5084 - accuracy: 0.8008
Epoch 11/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4977 - accuracy: 0.8095
Epoch 12/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5021 - accuracy: 0.8008
Epoch 13/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4990 - accuracy: 0.8011
Epoch 14/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5008 - accuracy: 0.8008
Epoch 15/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5001 - accuracy: 0.7979
Epoch 16/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5015 - accuracy: 0.8008
Epoch 17/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5057 - accuracy: 0.8039
Epoch 18/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5060 - accuracy: 0.8003
Epoch 19/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5074 - accuracy: 0.8060
Epoch 20/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5073 - accuracy: 0.8066
Epoch 21/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4955 - accuracy: 0.8058
Epoch 22/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5024 - accuracy: 0.8079
Epoch 23/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5051 - accuracy: 0.7994
Epoch 24/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5138 - accuracy: 0.7971
Epoch 25/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5033 - accuracy: 0.8044
Epoch 26/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5132 - accuracy: 0.8003
Epoch 27/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5124 - accuracy: 0.7974
Epoch 28/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5025 - accuracy: 0.8029
Epoch 29/100
194/194 [==============================] - 1s 6ms/step - loss: 0.4994 - accuracy: 0.8060
Epoch 30/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5061 - accuracy: 0.7998
Epoch 31/100
194/194 [==============================] - 1s 6ms/step - loss: 0.4938 - accuracy: 0.8008
Epoch 32/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5055 - accuracy: 0.8023
Epoch 33/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5008 - accuracy: 0.8053
Epoch 34/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4976 - accuracy: 0.8047
Epoch 35/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5076 - accuracy: 0.8000
Epoch 36/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4964 - accuracy: 0.8040
Epoch 37/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5003 - accuracy: 0.8060
Epoch 38/100
194/194 [==============================] - 1s 4ms/step - loss: 0.4970 - accuracy: 0.8092
Epoch 39/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5039 - accuracy: 0.8024
Epoch 40/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4990 - accuracy: 0.8065
Epoch 41/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5095 - accuracy: 0.8055
Epoch 42/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.8018
Epoch 43/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5006 - accuracy: 0.8060
Epoch 44/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5021 - accuracy: 0.8042
Epoch 45/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5130 - accuracy: 0.7963
Epoch 46/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5002 - accuracy: 0.8042
Epoch 47/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7976
Epoch 48/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5075 - accuracy: 0.8026
Epoch 49/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5117 - accuracy: 0.8005
Epoch 50/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5103 - accuracy: 0.7997
Epoch 51/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5036 - accuracy: 0.8055
Epoch 52/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5044 - accuracy: 0.8024
Epoch 53/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5102 - accuracy: 0.8068
Epoch 54/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5097 - accuracy: 0.8042
Epoch 55/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5121 - accuracy: 0.8013
Epoch 56/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5052 - accuracy: 0.8052
Epoch 57/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5042 - accuracy: 0.8071
Epoch 58/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5056 - accuracy: 0.7953
Epoch 59/100
194/194 [==============================] - 1s 6ms/step - loss: 0.4989 - accuracy: 0.8008
Epoch 60/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5021 - accuracy: 0.7976
Epoch 61/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5010 - accuracy: 0.8010
Epoch 62/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5035 - accuracy: 0.8019
Epoch 63/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5094 - accuracy: 0.8019
Epoch 64/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5132 - accuracy: 0.8037
Epoch 65/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5126 - accuracy: 0.7929
Epoch 66/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5096 - accuracy: 0.8016
Epoch 67/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5014 - accuracy: 0.8019
Epoch 68/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5105 - accuracy: 0.8026
Epoch 69/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5188 - accuracy: 0.7953
Epoch 70/100
194/194 [==============================] - 1s 4ms/step - loss: 0.4980 - accuracy: 0.8058
Epoch 71/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5067 - accuracy: 0.8003
Epoch 72/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5013 - accuracy: 0.8039
Epoch 73/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5050 - accuracy: 0.8015
Epoch 74/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5002 - accuracy: 0.8070
Epoch 75/100
194/194 [==============================] - 1s 6ms/step - loss: 0.4996 - accuracy: 0.8040
Epoch 76/100
194/194 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.8023
Epoch 77/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4995 - accuracy: 0.8065
Epoch 78/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7964
Epoch 79/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7995
Epoch 80/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4981 - accuracy: 0.8053
Epoch 81/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.7987
Epoch 82/100
194/194 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.8026
Epoch 83/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5012 - accuracy: 0.8011
Epoch 84/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5065 - accuracy: 0.7992
Epoch 85/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5077 - accuracy: 0.7989
Epoch 86/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4976 - accuracy: 0.8104
Epoch 87/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5005 - accuracy: 0.8095
Epoch 88/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5110 - accuracy: 0.7987
Epoch 89/100
194/194 [==============================] - 1s 6ms/step - loss: 0.5107 - accuracy: 0.8023
Epoch 90/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4981 - accuracy: 0.7992
Epoch 91/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5056 - accuracy: 0.8031
Epoch 92/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5036 - accuracy: 0.8045
Epoch 93/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4985 - accuracy: 0.8050
Epoch 94/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5005 - accuracy: 0.8031
Epoch 95/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5203 - accuracy: 0.7976
Epoch 96/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5113 - accuracy: 0.7984
Epoch 97/100
194/194 [==============================] - 1s 5ms/step - loss: 0.4966 - accuracy: 0.8034
Epoch 98/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5070 - accuracy: 0.7985
Epoch 99/100
194/194 [==============================] - 1s 5ms/step - loss: 0.5113 - accuracy: 0.8015
Epoch 100/100
194/194 [==============================] - 1s 4ms/step - loss: 0.4967 - accuracy: 0.8049

In [ ]:
model_2009.save("/content/drive/MyDrive/FYP/Trained Models/2009.keras")

In [ ]:
predictions = model_2009(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

0

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.7944983818770227

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.8098438855160451

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2009.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2010

#### Random sampling

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features_2010, labels_2010, test_size=0.2)

In [ ]:
y_train = y_train.astype(int)

In [ ]:
X_train.shape, y_train.shape

((7588, 8), (7588,))

In [ ]:
y_train[:5]

array([14, 14, 13,  5,  8])

### Stratified sampling

In [ ]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2010, labels_2010):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
features_2010[0]

array([0.72486041, 0.54320369, 0.14061741, 0.        , 1.        ,
       0.        , 0.        , 0.        ])

In [ ]:
fold1[0]

array([ 161,  162,  163, ..., 9482, 9483, 9484])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2010[x]
    y_train = labels_2010[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2010[x]))
    y_train = np.vstack((y_train, labels_2010[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2010[x]
    y_test = labels_2010[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2010[x]))
    y_test = np.vstack((y_test, labels_2010[x]))

In [ ]:
# Second iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2010[x]
    y_train = labels_2010[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2010[x]))
    y_train = np.vstack((y_train, labels_2010[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2010[x]
    y_test = labels_2010[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2010[x]))
    y_test = np.vstack((y_test, labels_2010[x]))

In [ ]:
# Third iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2010[x]
    y_train = labels_2010[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2010[x]))
    y_train = np.vstack((y_train, labels_2010[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2010[x]
    y_test = labels_2010[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2010[x]))
    y_test = np.vstack((y_test, labels_2010[x]))

In [ ]:
y_train.shape

(6323, 1)

## Model Training 2010

In [ ]:
model_2010 = Sequential()

In [ ]:
model_2010.add(Dense(units=520, activation="relu"))
model_2010.add(Dropout(0.5))
model_2010.add(Dense(units=250, activation="relu"))
model_2010.add(Dropout(0.3))
model_2010.add(Dense(units=128, activation="relu"))
model_2010.add(Dropout(0.3))
model_2010.add(Dense(units=64, activation="relu"))
model_2010.add(Dropout(0.3))
model_2010.add(Dense(units=45, activation="relu"))
model_2010.add(Dropout(0.2))
model_2010.add(Dense(units=28, activation="relu"))
model_2010.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2010.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2010.fit(X_train, y_train, epochs=200)
except Exception as ex:
  print(ex)

Epoch 1/200
198/198 [==============================] - 8s 6ms/step - loss: 2.6019 - accuracy: 0.1648
Epoch 2/200
198/198 [==============================] - 1s 7ms/step - loss: 2.0300 - accuracy: 0.2772
Epoch 3/200
198/198 [==============================] - 2s 8ms/step - loss: 1.7335 - accuracy: 0.3851
Epoch 4/200
198/198 [==============================] - 1s 7ms/step - loss: 1.5385 - accuracy: 0.4460
Epoch 5/200
198/198 [==============================] - 1s 7ms/step - loss: 1.4036 - accuracy: 0.4866
Epoch 6/200
198/198 [==============================] - 2s 8ms/step - loss: 1.3357 - accuracy: 0.5093
Epoch 7/200
198/198 [==============================] - 1s 6ms/step - loss: 1.2618 - accuracy: 0.5316
Epoch 8/200
198/198 [==============================] - 1s 6ms/step - loss: 1.2286 - accuracy: 0.5474
Epoch 9/200
198/198 [==============================] - 1s 6ms/step - loss: 1.1862 - accuracy: 0.5754
Epoch 10/200
198/198 [==============================] - 1s 6ms/step - loss: 1.1545 - accuracy: 0.5701
Epoch 11/200
198/198 [==============================] - 1s 6ms/step - loss: 1.1160 - accuracy: 0.5896
Epoch 12/200
198/198 [==============================] - 1s 6ms/step - loss: 1.1009 - accuracy: 0.5959
Epoch 13/200
198/198 [==============================] - 1s 6ms/step - loss: 1.0694 - accuracy: 0.6032
Epoch 14/200
198/198 [==============================] - 1s 6ms/step - loss: 1.0613 - accuracy: 0.6078
Epoch 15/200
198/198 [==============================] - 2s 8ms/step - loss: 1.0276 - accuracy: 0.6201
Epoch 16/200
198/198 [==============================] - 2s 9ms/step - loss: 1.0221 - accuracy: 0.6231
Epoch 17/200
198/198 [==============================] - 2s 8ms/step - loss: 1.0010 - accuracy: 0.6366
Epoch 18/200
198/198 [==============================] - 1s 7ms/step - loss: 1.0006 - accuracy: 0.6320
Epoch 19/200
198/198 [==============================] - 1s 6ms/step - loss: 0.9948 - accuracy: 0.6318
Epoch 20/200
198/198 [==============================] - 1s 6ms/step - loss: 0.9714 - accuracy: 0.6446
Epoch 21/200
198/198 [==============================] - 1s 6ms/step - loss: 0.9731 - accuracy: 0.6459
Epoch 22/200
198/198 [==============================] - 1s 6ms/step - loss: 0.9459 - accuracy: 0.6533
Epoch 23/200
198/198 [==============================] - 1s 6ms/step - loss: 0.9514 - accuracy: 0.6473
Epoch 24/200
198/198 [==============================] - 1s 6ms/step - loss: 0.9269 - accuracy: 0.6595
Epoch 25/200
198/198 [==============================] - 1s 6ms/step - loss: 0.9134 - accuracy: 0.6655
Epoch 26/200
198/198 [==============================] - 1s 6ms/step - loss: 0.9096 - accuracy: 0.6606
Epoch 27/200
198/198 [==============================] - 1s 7ms/step - loss: 0.9377 - accuracy: 0.6532
Epoch 28/200
198/198 [==============================] - 2s 8ms/step - loss: 0.8983 - accuracy: 0.6676
Epoch 29/200
198/198 [==============================] - 1s 7ms/step - loss: 0.9111 - accuracy: 0.6536
Epoch 30/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8965 - accuracy: 0.6691
Epoch 31/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8899 - accuracy: 0.6684
Epoch 32/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8819 - accuracy: 0.6736
Epoch 33/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8921 - accuracy: 0.6706
Epoch 34/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8799 - accuracy: 0.6703
Epoch 35/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8675 - accuracy: 0.6789
Epoch 36/200
198/198 [==============================] - 1s 5ms/step - loss: 0.8852 - accuracy: 0.6755
Epoch 37/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8819 - accuracy: 0.6734
Epoch 38/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8657 - accuracy: 0.6823
Epoch 39/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8527 - accuracy: 0.6808
Epoch 40/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8503 - accuracy: 0.6878
Epoch 41/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8664 - accuracy: 0.6769
Epoch 42/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8595 - accuracy: 0.6808
Epoch 43/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8533 - accuracy: 0.6884
Epoch 44/200
198/198 [==============================] - 1s 5ms/step - loss: 0.8292 - accuracy: 0.6875
Epoch 45/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8443 - accuracy: 0.6820
Epoch 46/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8449 - accuracy: 0.6845
Epoch 47/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8270 - accuracy: 0.6910
Epoch 48/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8140 - accuracy: 0.6937
Epoch 49/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8259 - accuracy: 0.6891
Epoch 50/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8217 - accuracy: 0.6943
Epoch 51/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8253 - accuracy: 0.6941
Epoch 52/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8280 - accuracy: 0.6888
Epoch 53/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8072 - accuracy: 0.6987
Epoch 54/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8218 - accuracy: 0.6845
Epoch 55/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8009 - accuracy: 0.7006
Epoch 56/200
198/198 [==============================] - 1s 5ms/step - loss: 0.8117 - accuracy: 0.6944
Epoch 57/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8188 - accuracy: 0.6919
Epoch 58/200
198/198 [==============================] - 1s 5ms/step - loss: 0.8074 - accuracy: 0.6970
Epoch 59/200
198/198 [==============================] - 1s 6ms/step - loss: 0.8305 - accuracy: 0.6929
Epoch 60/200
198/198 [==============================] - 1s 5ms/step - loss: 0.8044 - accuracy: 0.6872
Epoch 61/200
198/198 [==============================] - 1s 4ms/step - loss: 0.8097 - accuracy: 0.6943
Epoch 62/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7915 - accuracy: 0.7041
Epoch 63/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7876 - accuracy: 0.7087
Epoch 64/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7955 - accuracy: 0.7073
Epoch 65/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7940 - accuracy: 0.7006
Epoch 66/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7844 - accuracy: 0.7092
Epoch 67/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7802 - accuracy: 0.7109
Epoch 68/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7963 - accuracy: 0.7066
Epoch 69/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7996 - accuracy: 0.7006
Epoch 70/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7623 - accuracy: 0.7147
Epoch 71/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7915 - accuracy: 0.7096
Epoch 72/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7740 - accuracy: 0.7106
Epoch 73/200
198/198 [==============================] - 1s 5ms/step - loss: 0.7776 - accuracy: 0.7104
Epoch 74/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7868 - accuracy: 0.7057
Epoch 75/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7657 - accuracy: 0.7141
Epoch 76/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7906 - accuracy: 0.7093
Epoch 77/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7728 - accuracy: 0.7137
Epoch 78/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7681 - accuracy: 0.7087
Epoch 79/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7880 - accuracy: 0.7043
Epoch 80/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7572 - accuracy: 0.7144
Epoch 81/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7488 - accuracy: 0.7142
Epoch 82/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7803 - accuracy: 0.7131
Epoch 83/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7617 - accuracy: 0.7172
Epoch 84/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7561 - accuracy: 0.7183
Epoch 85/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7669 - accuracy: 0.7095
Epoch 86/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7695 - accuracy: 0.7156
Epoch 87/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7567 - accuracy: 0.7158
Epoch 88/200
198/198 [==============================] - 1s 5ms/step - loss: 0.7453 - accuracy: 0.7174
Epoch 89/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7764 - accuracy: 0.7103
Epoch 90/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7517 - accuracy: 0.7210
Epoch 91/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7489 - accuracy: 0.7209
Epoch 92/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7564 - accuracy: 0.7212
Epoch 93/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7544 - accuracy: 0.7149
Epoch 94/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7686 - accuracy: 0.7137
Epoch 95/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7583 - accuracy: 0.7150
Epoch 96/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7378 - accuracy: 0.7228
Epoch 97/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7564 - accuracy: 0.7188
Epoch 98/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7736 - accuracy: 0.7158
Epoch 99/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7516 - accuracy: 0.7247
Epoch 100/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7535 - accuracy: 0.7171
Epoch 101/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7644 - accuracy: 0.7155
Epoch 102/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7498 - accuracy: 0.7144
Epoch 103/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7406 - accuracy: 0.7191
Epoch 104/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7504 - accuracy: 0.7155
Epoch 105/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7523 - accuracy: 0.7149
Epoch 106/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7474 - accuracy: 0.7152
Epoch 107/200
198/198 [==============================] - 1s 5ms/step - loss: 0.7464 - accuracy: 0.7198
Epoch 108/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7483 - accuracy: 0.7161
Epoch 109/200
198/198 [==============================] - 1s 5ms/step - loss: 0.7365 - accuracy: 0.7235
Epoch 110/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7354 - accuracy: 0.7190
Epoch 111/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7587 - accuracy: 0.7217
Epoch 112/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7313 - accuracy: 0.7334
Epoch 113/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7280 - accuracy: 0.7266
Epoch 114/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7290 - accuracy: 0.7303
Epoch 115/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7343 - accuracy: 0.7259
Epoch 116/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7471 - accuracy: 0.7205
Epoch 117/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7358 - accuracy: 0.7213
Epoch 118/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7348 - accuracy: 0.7251
Epoch 119/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7283 - accuracy: 0.7272
Epoch 120/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7433 - accuracy: 0.7234
Epoch 121/200
198/198 [==============================] - 1s 5ms/step - loss: 0.7319 - accuracy: 0.7190
Epoch 122/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7195 - accuracy: 0.7294
Epoch 123/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7370 - accuracy: 0.7223
Epoch 124/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7210 - accuracy: 0.7269
Epoch 125/200
198/198 [==============================] - 1s 5ms/step - loss: 0.7149 - accuracy: 0.7248
Epoch 126/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7155 - accuracy: 0.7341
Epoch 127/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7357 - accuracy: 0.7223
Epoch 128/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7356 - accuracy: 0.7242
Epoch 129/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7188 - accuracy: 0.7307
Epoch 130/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7300 - accuracy: 0.7264
Epoch 131/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7269 - accuracy: 0.7283
Epoch 132/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7307 - accuracy: 0.7239
Epoch 133/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7277 - accuracy: 0.7264
Epoch 134/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7207 - accuracy: 0.7296
Epoch 135/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7168 - accuracy: 0.7338
Epoch 136/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7046 - accuracy: 0.7365
Epoch 137/200
198/198 [==============================] - 1s 5ms/step - loss: 0.7265 - accuracy: 0.7231
Epoch 138/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7159 - accuracy: 0.7318
Epoch 139/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7078 - accuracy: 0.7334
Epoch 140/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7150 - accuracy: 0.7261
Epoch 141/200
198/198 [==============================] - 1s 5ms/step - loss: 0.7136 - accuracy: 0.7318
Epoch 142/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7274 - accuracy: 0.7307
Epoch 143/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7283 - accuracy: 0.7264
Epoch 144/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6955 - accuracy: 0.7411
Epoch 145/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7324 - accuracy: 0.7267
Epoch 146/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7119 - accuracy: 0.7335
Epoch 147/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6996 - accuracy: 0.7364
Epoch 148/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7126 - accuracy: 0.7376
Epoch 149/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7024 - accuracy: 0.7368
Epoch 150/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7217 - accuracy: 0.7311
Epoch 151/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7232 - accuracy: 0.7326
Epoch 152/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7131 - accuracy: 0.7322
Epoch 153/200
198/198 [==============================] - 1s 5ms/step - loss: 0.7155 - accuracy: 0.7288
Epoch 154/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7006 - accuracy: 0.7376
Epoch 155/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7103 - accuracy: 0.7345
Epoch 156/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7109 - accuracy: 0.7367
Epoch 157/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7226 - accuracy: 0.7277
Epoch 158/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7182 - accuracy: 0.7292
Epoch 159/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7024 - accuracy: 0.7375
Epoch 160/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7198 - accuracy: 0.7294
Epoch 161/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7078 - accuracy: 0.7337
Epoch 162/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6936 - accuracy: 0.7392
Epoch 163/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7031 - accuracy: 0.7349
Epoch 164/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7202 - accuracy: 0.7267
Epoch 165/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6994 - accuracy: 0.7387
Epoch 166/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7155 - accuracy: 0.7334
Epoch 167/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7081 - accuracy: 0.7335
Epoch 168/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6977 - accuracy: 0.7414
Epoch 169/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7066 - accuracy: 0.7364
Epoch 170/200
198/198 [==============================] - 1s 6ms/step - loss: 0.6922 - accuracy: 0.7446
Epoch 171/200
198/198 [==============================] - 1s 6ms/step - loss: 0.6983 - accuracy: 0.7408
Epoch 172/200
198/198 [==============================] - 1s 6ms/step - loss: 0.6861 - accuracy: 0.7446
Epoch 173/200
198/198 [==============================] - 1s 6ms/step - loss: 0.6867 - accuracy: 0.7409
Epoch 174/200
198/198 [==============================] - 1s 5ms/step - loss: 0.7036 - accuracy: 0.7340
Epoch 175/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6776 - accuracy: 0.7440
Epoch 176/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6968 - accuracy: 0.7395
Epoch 177/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6892 - accuracy: 0.7356
Epoch 178/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7002 - accuracy: 0.7411
Epoch 179/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6932 - accuracy: 0.7387
Epoch 180/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6928 - accuracy: 0.7422
Epoch 181/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7051 - accuracy: 0.7387
Epoch 182/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6939 - accuracy: 0.7370
Epoch 183/200
198/198 [==============================] - 1s 4ms/step - loss: 0.7092 - accuracy: 0.7326
Epoch 184/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6958 - accuracy: 0.7360
Epoch 185/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6942 - accuracy: 0.7406
Epoch 186/200
198/198 [==============================] - 1s 6ms/step - loss: 0.6974 - accuracy: 0.7416
Epoch 187/200
198/198 [==============================] - 2s 9ms/step - loss: 0.6908 - accuracy: 0.7384
Epoch 188/200
198/198 [==============================] - 1s 6ms/step - loss: 0.7048 - accuracy: 0.7452
Epoch 189/200
198/198 [==============================] - 1s 6ms/step - loss: 0.6887 - accuracy: 0.7378
Epoch 190/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6932 - accuracy: 0.7392
Epoch 191/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6946 - accuracy: 0.7381
Epoch 192/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6922 - accuracy: 0.7357
Epoch 193/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6825 - accuracy: 0.7485
Epoch 194/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6938 - accuracy: 0.7405
Epoch 195/200
198/198 [==============================] - 1s 4ms/step - loss: 0.6895 - accuracy: 0.7451
Epoch 196/200

In [ ]:
model_2010.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2010.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
198/198 [==============================] - 3s 4ms/step - loss: 0.6534 - accuracy: 0.7552
Epoch 2/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6586 - accuracy: 0.7552
Epoch 3/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6495 - accuracy: 0.7585
Epoch 4/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6388 - accuracy: 0.7585
Epoch 5/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6316 - accuracy: 0.7569
Epoch 6/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6409 - accuracy: 0.7590
Epoch 7/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6367 - accuracy: 0.7590
Epoch 8/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6460 - accuracy: 0.7526
Epoch 9/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6402 - accuracy: 0.7604
Epoch 10/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6431 - accuracy: 0.7613
Epoch 11/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6336 - accuracy: 0.7651
Epoch 12/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6243 - accuracy: 0.7663
Epoch 13/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6446 - accuracy: 0.7564
Epoch 14/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6324 - accuracy: 0.7620
Epoch 15/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6360 - accuracy: 0.7594
Epoch 16/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6424 - accuracy: 0.7583
Epoch 17/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6228 - accuracy: 0.7637
Epoch 18/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6188 - accuracy: 0.7594
Epoch 19/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6238 - accuracy: 0.7606
Epoch 20/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6255 - accuracy: 0.7610
Epoch 21/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6250 - accuracy: 0.7640
Epoch 22/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6235 - accuracy: 0.7664
Epoch 23/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6242 - accuracy: 0.7585
Epoch 24/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6315 - accuracy: 0.7572
Epoch 25/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6192 - accuracy: 0.7609
Epoch 26/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6229 - accuracy: 0.7648
Epoch 27/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6148 - accuracy: 0.7683
Epoch 28/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6179 - accuracy: 0.7667
Epoch 29/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6324 - accuracy: 0.7585
Epoch 30/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6174 - accuracy: 0.7623
Epoch 31/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6190 - accuracy: 0.7651
Epoch 32/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6308 - accuracy: 0.7612
Epoch 33/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6251 - accuracy: 0.7629
Epoch 34/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6267 - accuracy: 0.7604
Epoch 35/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6104 - accuracy: 0.7680
Epoch 36/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6170 - accuracy: 0.7623
Epoch 37/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6135 - accuracy: 0.7658
Epoch 38/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6178 - accuracy: 0.7669
Epoch 39/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6160 - accuracy: 0.7637
Epoch 40/100
198/198 [==============================] - 2s 9ms/step - loss: 0.6213 - accuracy: 0.7629
Epoch 41/100
198/198 [==============================] - 1s 7ms/step - loss: 0.6245 - accuracy: 0.7587
Epoch 42/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6140 - accuracy: 0.7689
Epoch 43/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6053 - accuracy: 0.7666
Epoch 44/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6136 - accuracy: 0.7680
Epoch 45/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6193 - accuracy: 0.7577
Epoch 46/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6492 - accuracy: 0.7663
Epoch 47/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6304 - accuracy: 0.7583
Epoch 48/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6160 - accuracy: 0.7669
Epoch 49/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6146 - accuracy: 0.7667
Epoch 50/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6143 - accuracy: 0.7670
Epoch 51/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6188 - accuracy: 0.7658
Epoch 52/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6164 - accuracy: 0.7678
Epoch 53/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6181 - accuracy: 0.7615
Epoch 54/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6220 - accuracy: 0.7640
Epoch 55/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6104 - accuracy: 0.7688
Epoch 56/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6152 - accuracy: 0.7640
Epoch 57/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6105 - accuracy: 0.7685
Epoch 58/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6174 - accuracy: 0.7642
Epoch 59/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6175 - accuracy: 0.7658
Epoch 60/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6007 - accuracy: 0.7693
Epoch 61/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6108 - accuracy: 0.7664
Epoch 62/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5969 - accuracy: 0.7772
Epoch 63/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6216 - accuracy: 0.7651
Epoch 64/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6094 - accuracy: 0.7700
Epoch 65/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6142 - accuracy: 0.7669
Epoch 66/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6097 - accuracy: 0.7697
Epoch 67/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6015 - accuracy: 0.7743
Epoch 68/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6167 - accuracy: 0.7688
Epoch 69/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6046 - accuracy: 0.7723
Epoch 70/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6159 - accuracy: 0.7691
Epoch 71/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6103 - accuracy: 0.7683
Epoch 72/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6086 - accuracy: 0.7710
Epoch 73/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6145 - accuracy: 0.7697
Epoch 74/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5998 - accuracy: 0.7699
Epoch 75/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6072 - accuracy: 0.7651
Epoch 76/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6163 - accuracy: 0.7686
Epoch 77/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6153 - accuracy: 0.7681
Epoch 78/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6075 - accuracy: 0.7693
Epoch 79/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5948 - accuracy: 0.7753
Epoch 80/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5999 - accuracy: 0.7669
Epoch 81/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6004 - accuracy: 0.7745
Epoch 82/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6026 - accuracy: 0.7678
Epoch 83/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6021 - accuracy: 0.7650
Epoch 84/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6016 - accuracy: 0.7702
Epoch 85/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6182 - accuracy: 0.7672
Epoch 86/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6048 - accuracy: 0.7740
Epoch 87/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5963 - accuracy: 0.7753
Epoch 88/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5997 - accuracy: 0.7691
Epoch 89/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6093 - accuracy: 0.7732
Epoch 90/100
198/198 [==============================] - 1s 5ms/step - loss: 0.6078 - accuracy: 0.7680
Epoch 91/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5973 - accuracy: 0.7705
Epoch 92/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5958 - accuracy: 0.7678
Epoch 93/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6073 - accuracy: 0.7705
Epoch 94/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6170 - accuracy: 0.7696
Epoch 95/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6116 - accuracy: 0.7694
Epoch 96/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5934 - accuracy: 0.7748
Epoch 97/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6086 - accuracy: 0.7721
Epoch 98/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6049 - accuracy: 0.7756
Epoch 99/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6072 - accuracy: 0.7678
Epoch 100/100
198/198 [==============================] - 1s 4ms/step - loss: 0.6100 - accuracy: 0.7677

In [ ]:
model_2010.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2010.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
198/198 [==============================] - 3s 4ms/step - loss: 0.5813 - accuracy: 0.7784
Epoch 2/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5833 - accuracy: 0.7817
Epoch 3/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5864 - accuracy: 0.7756
Epoch 4/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5733 - accuracy: 0.7822
Epoch 5/100
198/198 [==============================] - 1s 6ms/step - loss: 0.6012 - accuracy: 0.7794
Epoch 6/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5707 - accuracy: 0.7836
Epoch 7/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5779 - accuracy: 0.7794
Epoch 8/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5725 - accuracy: 0.7819
Epoch 9/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5754 - accuracy: 0.7817
Epoch 10/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5593 - accuracy: 0.7854
Epoch 11/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5614 - accuracy: 0.7827
Epoch 12/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5647 - accuracy: 0.7832
Epoch 13/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5667 - accuracy: 0.7854
Epoch 14/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5773 - accuracy: 0.7789
Epoch 15/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5694 - accuracy: 0.7776
Epoch 16/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5600 - accuracy: 0.7849
Epoch 17/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5659 - accuracy: 0.7770
Epoch 18/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5675 - accuracy: 0.7876
Epoch 19/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5635 - accuracy: 0.7854
Epoch 20/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5608 - accuracy: 0.7857
Epoch 21/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5772 - accuracy: 0.7780
Epoch 22/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5543 - accuracy: 0.7835
Epoch 23/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5649 - accuracy: 0.7830
Epoch 24/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5531 - accuracy: 0.7849
Epoch 25/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5534 - accuracy: 0.7889
Epoch 26/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5590 - accuracy: 0.7878
Epoch 27/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5479 - accuracy: 0.7878
Epoch 28/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5580 - accuracy: 0.7857
Epoch 29/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5560 - accuracy: 0.7852
Epoch 30/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5537 - accuracy: 0.7895
Epoch 31/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5615 - accuracy: 0.7868
Epoch 32/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5619 - accuracy: 0.7825
Epoch 33/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5581 - accuracy: 0.7890
Epoch 34/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5546 - accuracy: 0.7840
Epoch 35/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5575 - accuracy: 0.7925
Epoch 36/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5572 - accuracy: 0.7879
Epoch 37/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5661 - accuracy: 0.7841
Epoch 38/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5439 - accuracy: 0.7889
Epoch 39/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5655 - accuracy: 0.7840
Epoch 40/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5507 - accuracy: 0.7892
Epoch 41/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5484 - accuracy: 0.7897
Epoch 42/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5630 - accuracy: 0.7822
Epoch 43/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7876
Epoch 44/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5491 - accuracy: 0.7890
Epoch 45/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5591 - accuracy: 0.7882
Epoch 46/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5638 - accuracy: 0.7868
Epoch 47/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5455 - accuracy: 0.7863
Epoch 48/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7930
Epoch 49/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5528 - accuracy: 0.7906
Epoch 50/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5504 - accuracy: 0.7878
Epoch 51/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5446 - accuracy: 0.7933
Epoch 52/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5537 - accuracy: 0.7870
Epoch 53/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5444 - accuracy: 0.7923
Epoch 54/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5476 - accuracy: 0.7849
Epoch 55/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5454 - accuracy: 0.7871
Epoch 56/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7879
Epoch 57/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5557 - accuracy: 0.7882
Epoch 58/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5433 - accuracy: 0.7849
Epoch 59/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5527 - accuracy: 0.7867
Epoch 60/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5586 - accuracy: 0.7808
Epoch 61/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5595 - accuracy: 0.7848
Epoch 62/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5536 - accuracy: 0.7892
Epoch 63/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5544 - accuracy: 0.7892
Epoch 64/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5382 - accuracy: 0.7927
Epoch 65/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5415 - accuracy: 0.7892
Epoch 66/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5521 - accuracy: 0.7895
Epoch 67/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5606 - accuracy: 0.7833
Epoch 68/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5641 - accuracy: 0.7849
Epoch 69/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5514 - accuracy: 0.7868
Epoch 70/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7903
Epoch 71/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5469 - accuracy: 0.7911
Epoch 72/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7871
Epoch 73/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7876
Epoch 74/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5508 - accuracy: 0.7859
Epoch 75/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5464 - accuracy: 0.7912
Epoch 76/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5464 - accuracy: 0.7914
Epoch 77/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5420 - accuracy: 0.7920
Epoch 78/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5557 - accuracy: 0.7833
Epoch 79/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5661 - accuracy: 0.7904
Epoch 80/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5457 - accuracy: 0.7947
Epoch 81/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5553 - accuracy: 0.7870
Epoch 82/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5562 - accuracy: 0.7892
Epoch 83/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5620 - accuracy: 0.7827
Epoch 84/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5428 - accuracy: 0.7906
Epoch 85/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5556 - accuracy: 0.7881
Epoch 86/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5526 - accuracy: 0.7867
Epoch 87/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5437 - accuracy: 0.7892
Epoch 88/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5462 - accuracy: 0.7944
Epoch 89/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5516 - accuracy: 0.7855
Epoch 90/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5405 - accuracy: 0.7941
Epoch 91/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5444 - accuracy: 0.7909
Epoch 92/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5436 - accuracy: 0.7895
Epoch 93/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5461 - accuracy: 0.7900
Epoch 94/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5364 - accuracy: 0.7952
Epoch 95/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7887
Epoch 96/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7917
Epoch 97/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5418 - accuracy: 0.7901
Epoch 98/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5450 - accuracy: 0.7889
Epoch 99/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5412 - accuracy: 0.7941
Epoch 100/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5559 - accuracy: 0.7887

In [ ]:
model_2010.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2010.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
198/198 [==============================] - 3s 5ms/step - loss: 0.5423 - accuracy: 0.7928
Epoch 2/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7928
Epoch 3/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5392 - accuracy: 0.7971
Epoch 4/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5387 - accuracy: 0.7917
Epoch 5/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5453 - accuracy: 0.7912
Epoch 6/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5401 - accuracy: 0.7944
Epoch 7/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5297 - accuracy: 0.7972
Epoch 8/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7885
Epoch 9/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5376 - accuracy: 0.7919
Epoch 10/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5391 - accuracy: 0.7909
Epoch 11/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5592 - accuracy: 0.7985
Epoch 12/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5388 - accuracy: 0.7933
Epoch 13/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5482 - accuracy: 0.7941
Epoch 14/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5377 - accuracy: 0.7969
Epoch 15/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5347 - accuracy: 0.7925
Epoch 16/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5367 - accuracy: 0.7963
Epoch 17/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5426 - accuracy: 0.7876
Epoch 18/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5328 - accuracy: 0.7947
Epoch 19/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5303 - accuracy: 0.7974
Epoch 20/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5426 - accuracy: 0.7893
Epoch 21/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5376 - accuracy: 0.7908
Epoch 22/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5369 - accuracy: 0.7923
Epoch 23/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5441 - accuracy: 0.7931
Epoch 24/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5374 - accuracy: 0.7954
Epoch 25/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7941
Epoch 26/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5305 - accuracy: 0.7920
Epoch 27/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5407 - accuracy: 0.7961
Epoch 28/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5475 - accuracy: 0.7920
Epoch 29/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5354 - accuracy: 0.7933
Epoch 30/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5495 - accuracy: 0.7923
Epoch 31/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7863
Epoch 32/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5359 - accuracy: 0.7925
Epoch 33/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7961
Epoch 34/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7976
Epoch 35/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5371 - accuracy: 0.7944
Epoch 36/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7968
Epoch 37/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7946
Epoch 38/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7961
Epoch 39/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7922
Epoch 40/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7930
Epoch 41/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7974
Epoch 42/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5316 - accuracy: 0.7969
Epoch 43/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5322 - accuracy: 0.7916
Epoch 44/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5324 - accuracy: 0.7942
Epoch 45/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5318 - accuracy: 0.7952
Epoch 46/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5423 - accuracy: 0.7898
Epoch 47/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5353 - accuracy: 0.7952
Epoch 48/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5395 - accuracy: 0.7936
Epoch 49/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5375 - accuracy: 0.7917
Epoch 50/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.8003
Epoch 51/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5389 - accuracy: 0.7906
Epoch 52/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5398 - accuracy: 0.7972
Epoch 53/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7904
Epoch 54/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7931
Epoch 55/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5437 - accuracy: 0.7925
Epoch 56/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5390 - accuracy: 0.7960
Epoch 57/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7999
Epoch 58/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5347 - accuracy: 0.7920
Epoch 59/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5338 - accuracy: 0.7922
Epoch 60/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5374 - accuracy: 0.7960
Epoch 61/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5261 - accuracy: 0.8012
Epoch 62/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5393 - accuracy: 0.7906
Epoch 63/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5331 - accuracy: 0.7963
Epoch 64/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5421 - accuracy: 0.7892
Epoch 65/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5296 - accuracy: 0.7960
Epoch 66/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7950
Epoch 67/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5396 - accuracy: 0.7912
Epoch 68/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5409 - accuracy: 0.7938
Epoch 69/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7936
Epoch 70/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5268 - accuracy: 0.7952
Epoch 71/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7984
Epoch 72/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5370 - accuracy: 0.7935
Epoch 73/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5364 - accuracy: 0.7961
Epoch 74/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5372 - accuracy: 0.7942
Epoch 75/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5297 - accuracy: 0.7946
Epoch 76/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5294 - accuracy: 0.7960
Epoch 77/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5357 - accuracy: 0.7944
Epoch 78/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5327 - accuracy: 0.7919
Epoch 79/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5264 - accuracy: 0.8003
Epoch 80/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5319 - accuracy: 0.7949
Epoch 81/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5447 - accuracy: 0.7942
Epoch 82/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5397 - accuracy: 0.7938
Epoch 83/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5413 - accuracy: 0.7931
Epoch 84/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5405 - accuracy: 0.7928
Epoch 85/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5486 - accuracy: 0.7885
Epoch 86/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5352 - accuracy: 0.7936
Epoch 87/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5248 - accuracy: 0.7941
Epoch 88/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5234 - accuracy: 0.8004
Epoch 89/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5372 - accuracy: 0.7979
Epoch 90/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5374 - accuracy: 0.7963
Epoch 91/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5282 - accuracy: 0.7939
Epoch 92/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5434 - accuracy: 0.7904
Epoch 93/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5388 - accuracy: 0.7898
Epoch 94/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5355 - accuracy: 0.7957
Epoch 95/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5310 - accuracy: 0.7976
Epoch 96/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5304 - accuracy: 0.7949
Epoch 97/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5325 - accuracy: 0.7961
Epoch 98/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5375 - accuracy: 0.7988
Epoch 99/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5320 - accuracy: 0.7936
Epoch 100/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5323 - accuracy: 0.7949

In [ ]:
model_2010.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2010.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
198/198 [==============================] - 3s 4ms/step - loss: 0.5323 - accuracy: 0.7971
Epoch 2/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5312 - accuracy: 0.7963
Epoch 3/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5286 - accuracy: 0.7965
Epoch 4/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5319 - accuracy: 0.7963
Epoch 5/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5286 - accuracy: 0.7977
Epoch 6/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5372 - accuracy: 0.7998
Epoch 7/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5417 - accuracy: 0.7955
Epoch 8/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.7977
Epoch 9/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5173 - accuracy: 0.8014
Epoch 10/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5267 - accuracy: 0.7974
Epoch 11/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5292 - accuracy: 0.7961
Epoch 12/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5318 - accuracy: 0.7963
Epoch 13/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.8015
Epoch 14/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5373 - accuracy: 0.7931
Epoch 15/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5306 - accuracy: 0.7960
Epoch 16/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7998
Epoch 17/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7930
Epoch 18/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5321 - accuracy: 0.7920
Epoch 19/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5286 - accuracy: 0.7979
Epoch 20/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5399 - accuracy: 0.7908
Epoch 21/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5344 - accuracy: 0.7942
Epoch 22/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5276 - accuracy: 0.7960
Epoch 23/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5308 - accuracy: 0.7928
Epoch 24/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5299 - accuracy: 0.7963
Epoch 25/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7991
Epoch 26/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7919
Epoch 27/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7969
Epoch 28/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7912
Epoch 29/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.7930
Epoch 30/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5341 - accuracy: 0.7912
Epoch 31/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7968
Epoch 32/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5245 - accuracy: 0.7977
Epoch 33/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5419 - accuracy: 0.7985
Epoch 34/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7976
Epoch 35/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5314 - accuracy: 0.7958
Epoch 36/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5257 - accuracy: 0.7984
Epoch 37/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5244 - accuracy: 0.7982
Epoch 38/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5381 - accuracy: 0.7984
Epoch 39/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5293 - accuracy: 0.7968
Epoch 40/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5222 - accuracy: 0.7984
Epoch 41/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5329 - accuracy: 0.7960
Epoch 42/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5278 - accuracy: 0.7914
Epoch 43/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5307 - accuracy: 0.7996
Epoch 44/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5378 - accuracy: 0.7947
Epoch 45/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5220 - accuracy: 0.7969
Epoch 46/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5242 - accuracy: 0.7936
Epoch 47/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5315 - accuracy: 0.7942
Epoch 48/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5339 - accuracy: 0.8006
Epoch 49/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5282 - accuracy: 0.7991
Epoch 50/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5221 - accuracy: 0.8007
Epoch 51/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5332 - accuracy: 0.7977
Epoch 52/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5285 - accuracy: 0.7995
Epoch 53/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5314 - accuracy: 0.7963
Epoch 54/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5275 - accuracy: 0.7984
Epoch 55/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5225 - accuracy: 0.7987
Epoch 56/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5344 - accuracy: 0.7946
Epoch 57/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5323 - accuracy: 0.7930
Epoch 58/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5338 - accuracy: 0.7873
Epoch 59/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5366 - accuracy: 0.7963
Epoch 60/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5368 - accuracy: 0.7971
Epoch 61/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5252 - accuracy: 0.7974
Epoch 62/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5337 - accuracy: 0.7988
Epoch 63/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5213 - accuracy: 0.7961
Epoch 64/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5375 - accuracy: 0.7925
Epoch 65/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5225 - accuracy: 0.7958
Epoch 66/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5234 - accuracy: 0.7988
Epoch 67/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5432 - accuracy: 0.7906
Epoch 68/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5277 - accuracy: 0.7954
Epoch 69/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5266 - accuracy: 0.7977
Epoch 70/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5326 - accuracy: 0.7965
Epoch 71/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5245 - accuracy: 0.7988
Epoch 72/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5351 - accuracy: 0.7982
Epoch 73/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5319 - accuracy: 0.7969
Epoch 74/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5322 - accuracy: 0.7933
Epoch 75/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5228 - accuracy: 0.7984
Epoch 76/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5237 - accuracy: 0.7947
Epoch 77/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5201 - accuracy: 0.7988
Epoch 78/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5269 - accuracy: 0.7941
Epoch 79/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5300 - accuracy: 0.7995
Epoch 80/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5438 - accuracy: 0.7919
Epoch 81/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5418 - accuracy: 0.7958
Epoch 82/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7933
Epoch 83/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5245 - accuracy: 0.7990
Epoch 84/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5325 - accuracy: 0.7982
Epoch 85/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5338 - accuracy: 0.8004
Epoch 86/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5294 - accuracy: 0.7950
Epoch 87/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5291 - accuracy: 0.7980
Epoch 88/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5402 - accuracy: 0.7931
Epoch 89/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5258 - accuracy: 0.7955
Epoch 90/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5308 - accuracy: 0.7976
Epoch 91/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5324 - accuracy: 0.7960
Epoch 92/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.7938
Epoch 93/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5390 - accuracy: 0.7995
Epoch 94/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5236 - accuracy: 0.8034
Epoch 95/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5250 - accuracy: 0.7935
Epoch 96/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5287 - accuracy: 0.7982
Epoch 97/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5246 - accuracy: 0.8010
Epoch 98/100
198/198 [==============================] - 1s 4ms/step - loss: 0.5254 - accuracy: 0.7927
Epoch 99/100
198/198 [==============================] - 1s 5ms/step - loss: 0.5352 - accuracy: 0.7873
Epoch 100/100
198/198 [==============================] - 1s 6ms/step - loss: 0.5223 - accuracy: 0.7968

In [ ]:
model_2010.save("/content/drive/MyDrive/FYP/Trained Models/2010.keras")

In [ ]:
accuracies = []

In [ ]:
predictions = model_2010(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.7890575585072739

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.8029054640069384

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2010.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2011

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features_2011, labels_2011, test_size=0.2)

In [ ]:
y_train = y_train.astype(int)

In [ ]:
X_train.shape, y_train.shape

((7332, 8), (7332,))

In [ ]:
y_train[:5]

array([ 8, 16,  0,  9, 10])

## Model Training 2011

In [ ]:
model_2011 = Sequential()

In [ ]:
model_2011.add(Dense(units=520, activation="relu"))
model_2011.add(Dropout(0.2))
model_2011.add(Dense(units=250, activation="relu"))
model_2011.add(Dropout(0.2))
model_2011.add(Dense(units=128, activation="relu"))
model_2011.add(Dropout(0.2))
model_2011.add(Dense(units=64, activation="relu"))
model_2011.add(Dropout(0.2))
model_2011.add(Dense(units=45, activation="relu"))
model_2011.add(Dropout(0.2))
model_2011.add(Dense(units=28, activation="relu"))
model_2011.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2011.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2011.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
230/230 [==============================] - 3s 5ms/step - loss: 2.4382 - accuracy: 0.2053
Epoch 2/100
230/230 [==============================] - 1s 4ms/step - loss: 1.8062 - accuracy: 0.3733
Epoch 3/100
230/230 [==============================] - 1s 5ms/step - loss: 1.4661 - accuracy: 0.4752
Epoch 4/100
230/230 [==============================] - 1s 5ms/step - loss: 1.2924 - accuracy: 0.5303
Epoch 5/100
230/230 [==============================] - 1s 6ms/step - loss: 1.2207 - accuracy: 0.5513
Epoch 6/100
230/230 [==============================] - 1s 6ms/step - loss: 1.1446 - accuracy: 0.5719
Epoch 7/100
230/230 [==============================] - 1s 4ms/step - loss: 1.1067 - accuracy: 0.5899
Epoch 8/100
230/230 [==============================] - 1s 4ms/step - loss: 1.0658 - accuracy: 0.6071
Epoch 9/100
230/230 [==============================] - 1s 4ms/step - loss: 1.0308 - accuracy: 0.6200
Epoch 10/100
230/230 [==============================] - 1s 4ms/step - loss: 1.0001 - accuracy: 0.6255
Epoch 11/100
230/230 [==============================] - 1s 4ms/step - loss: 0.9747 - accuracy: 0.6387
Epoch 12/100
230/230 [==============================] - 1s 4ms/step - loss: 0.9454 - accuracy: 0.6469
Epoch 13/100
230/230 [==============================] - 1s 4ms/step - loss: 0.9532 - accuracy: 0.6470
Epoch 14/100
230/230 [==============================] - 1s 4ms/step - loss: 0.9419 - accuracy: 0.6495
Epoch 15/100
230/230 [==============================] - 1s 4ms/step - loss: 0.9309 - accuracy: 0.6567
Epoch 16/100
230/230 [==============================] - 1s 4ms/step - loss: 0.9170 - accuracy: 0.6616
Epoch 17/100
230/230 [==============================] - 1s 5ms/step - loss: 0.8946 - accuracy: 0.6607
Epoch 18/100
230/230 [==============================] - 1s 6ms/step - loss: 0.8835 - accuracy: 0.6720
Epoch 19/100
230/230 [==============================] - 1s 6ms/step - loss: 0.8819 - accuracy: 0.6718
Epoch 20/100
230/230 [==============================] - 1s 6ms/step - loss: 0.8508 - accuracy: 0.6814
Epoch 21/100
230/230 [==============================] - 1s 4ms/step - loss: 0.8454 - accuracy: 0.6824
Epoch 22/100
230/230 [==============================] - 1s 4ms/step - loss: 0.8582 - accuracy: 0.6829
Epoch 23/100
230/230 [==============================] - 1s 4ms/step - loss: 0.8498 - accuracy: 0.6819
Epoch 24/100
230/230 [==============================] - 1s 4ms/step - loss: 0.8409 - accuracy: 0.6826
Epoch 25/100
230/230 [==============================] - 1s 4ms/step - loss: 0.8420 - accuracy: 0.6878
Epoch 26/100
230/230 [==============================] - 1s 4ms/step - loss: 0.8389 - accuracy: 0.6877
Epoch 27/100
230/230 [==============================] - 1s 4ms/step - loss: 0.8245 - accuracy: 0.6911
Epoch 28/100
230/230 [==============================] - 1s 4ms/step - loss: 0.8211 - accuracy: 0.6935
Epoch 29/100
230/230 [==============================] - 1s 4ms/step - loss: 0.8083 - accuracy: 0.6930
Epoch 30/100
230/230 [==============================] - 1s 4ms/step - loss: 0.8294 - accuracy: 0.6878
Epoch 31/100
230/230 [==============================] - 1s 5ms/step - loss: 0.8099 - accuracy: 0.6874
Epoch 32/100
230/230 [==============================] - 1s 6ms/step - loss: 0.8221 - accuracy: 0.6904
Epoch 33/100
230/230 [==============================] - 1s 5ms/step - loss: 0.8035 - accuracy: 0.6939
Epoch 34/100
230/230 [==============================] - 1s 6ms/step - loss: 0.7936 - accuracy: 0.7001
Epoch 35/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7876 - accuracy: 0.7032
Epoch 36/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7843 - accuracy: 0.7080
Epoch 37/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7922 - accuracy: 0.7054
Epoch 38/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7905 - accuracy: 0.7065
Epoch 39/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7789 - accuracy: 0.7062
Epoch 40/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7779 - accuracy: 0.7057
Epoch 41/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7727 - accuracy: 0.7114
Epoch 42/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7687 - accuracy: 0.7167
Epoch 43/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7547 - accuracy: 0.7125
Epoch 44/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7674 - accuracy: 0.7158
Epoch 45/100
230/230 [==============================] - 1s 5ms/step - loss: 0.7693 - accuracy: 0.7121
Epoch 46/100
230/230 [==============================] - 1s 6ms/step - loss: 0.7672 - accuracy: 0.7089
Epoch 47/100
230/230 [==============================] - 1s 6ms/step - loss: 0.7405 - accuracy: 0.7215
Epoch 48/100
230/230 [==============================] - 1s 6ms/step - loss: 0.7550 - accuracy: 0.7184
Epoch 49/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7499 - accuracy: 0.7154
Epoch 50/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7627 - accuracy: 0.7119
Epoch 51/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7446 - accuracy: 0.7237
Epoch 52/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7479 - accuracy: 0.7264
Epoch 53/100
230/230 [==============================] - 1s 5ms/step - loss: 0.7341 - accuracy: 0.7278
Epoch 54/100
230/230 [==============================] - 1s 5ms/step - loss: 0.7502 - accuracy: 0.7190
Epoch 55/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7344 - accuracy: 0.7282
Epoch 56/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7429 - accuracy: 0.7219
Epoch 57/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7359 - accuracy: 0.7229
Epoch 58/100
230/230 [==============================] - 1s 5ms/step - loss: 0.7379 - accuracy: 0.7215
Epoch 59/100
230/230 [==============================] - 1s 6ms/step - loss: 0.7195 - accuracy: 0.7244
Epoch 60/100
230/230 [==============================] - 1s 6ms/step - loss: 0.7331 - accuracy: 0.7264
Epoch 61/100
230/230 [==============================] - 1s 6ms/step - loss: 0.7427 - accuracy: 0.7152
Epoch 62/100
230/230 [==============================] - 1s 5ms/step - loss: 0.7358 - accuracy: 0.7231
Epoch 63/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7151 - accuracy: 0.7293
Epoch 64/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7185 - accuracy: 0.7265
Epoch 65/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7060 - accuracy: 0.7293
Epoch 66/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7154 - accuracy: 0.7321
Epoch 67/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7202 - accuracy: 0.7304
Epoch 68/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7220 - accuracy: 0.7271
Epoch 69/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7101 - accuracy: 0.7343
Epoch 70/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7120 - accuracy: 0.7380
Epoch 71/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7119 - accuracy: 0.7315
Epoch 72/100
230/230 [==============================] - 1s 5ms/step - loss: 0.7306 - accuracy: 0.7274
Epoch 73/100
230/230 [==============================] - 1s 6ms/step - loss: 0.7255 - accuracy: 0.7308
Epoch 74/100
230/230 [==============================] - 1s 6ms/step - loss: 0.7096 - accuracy: 0.7339
Epoch 75/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6992 - accuracy: 0.7413
Epoch 76/100
230/230 [==============================] - 1s 5ms/step - loss: 0.7145 - accuracy: 0.7289
Epoch 77/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6964 - accuracy: 0.7405
Epoch 78/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7134 - accuracy: 0.7268
Epoch 79/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7058 - accuracy: 0.7331
Epoch 80/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6971 - accuracy: 0.7368
Epoch 81/100
230/230 [==============================] - 1s 4ms/step - loss: 0.7104 - accuracy: 0.7381
Epoch 82/100
230/230 [==============================] - 1s 5ms/step - loss: 0.7071 - accuracy: 0.7357
Epoch 83/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6834 - accuracy: 0.7373
Epoch 84/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6937 - accuracy: 0.7385
Epoch 85/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6808 - accuracy: 0.7432
Epoch 86/100
230/230 [==============================] - 1s 5ms/step - loss: 0.6770 - accuracy: 0.7458
Epoch 87/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6869 - accuracy: 0.7456
Epoch 88/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6812 - accuracy: 0.7466
Epoch 89/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6990 - accuracy: 0.7399
Epoch 90/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6946 - accuracy: 0.7381
Epoch 91/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6948 - accuracy: 0.7345
Epoch 92/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6862 - accuracy: 0.7399
Epoch 93/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6795 - accuracy: 0.7411
Epoch 94/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6853 - accuracy: 0.7429
Epoch 95/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6872 - accuracy: 0.7407
Epoch 96/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6780 - accuracy: 0.7448
Epoch 97/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6848 - accuracy: 0.7463
Epoch 98/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6898 - accuracy: 0.7383
Epoch 99/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6859 - accuracy: 0.7460
Epoch 100/100
230/230 [==============================] - 1s 5ms/step - loss: 0.6848 - accuracy: 0.7443

In [ ]:
model_2011.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2011.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
230/230 [==============================] - 3s 4ms/step - loss: 0.6439 - accuracy: 0.7598
Epoch 2/100
230/230 [==============================] - 1s 5ms/step - loss: 0.6263 - accuracy: 0.7636
Epoch 3/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6270 - accuracy: 0.7651
Epoch 4/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6275 - accuracy: 0.7609
Epoch 5/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6208 - accuracy: 0.7638
Epoch 6/100
230/230 [==============================] - 1s 5ms/step - loss: 0.6283 - accuracy: 0.7623
Epoch 7/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6290 - accuracy: 0.7597
Epoch 8/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6293 - accuracy: 0.7546
Epoch 9/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6148 - accuracy: 0.7653
Epoch 10/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6136 - accuracy: 0.7602
Epoch 11/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5978 - accuracy: 0.7707
Epoch 12/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6257 - accuracy: 0.7600
Epoch 13/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6201 - accuracy: 0.7660
Epoch 14/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6179 - accuracy: 0.7662
Epoch 15/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6144 - accuracy: 0.7699
Epoch 16/100
230/230 [==============================] - 1s 5ms/step - loss: 0.6117 - accuracy: 0.7672
Epoch 17/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6142 - accuracy: 0.7640
Epoch 18/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6154 - accuracy: 0.7642
Epoch 19/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6091 - accuracy: 0.7628
Epoch 20/100
230/230 [==============================] - 1s 5ms/step - loss: 0.6220 - accuracy: 0.7654
Epoch 21/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6210 - accuracy: 0.7597
Epoch 22/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6071 - accuracy: 0.7680
Epoch 23/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6192 - accuracy: 0.7610
Epoch 24/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6065 - accuracy: 0.7722
Epoch 25/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6069 - accuracy: 0.7694
Epoch 26/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6049 - accuracy: 0.7695
Epoch 27/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6060 - accuracy: 0.7679
Epoch 28/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6133 - accuracy: 0.7680
Epoch 29/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6035 - accuracy: 0.7651
Epoch 30/100
230/230 [==============================] - 1s 5ms/step - loss: 0.6030 - accuracy: 0.7679
Epoch 31/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6100 - accuracy: 0.7647
Epoch 32/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6175 - accuracy: 0.7672
Epoch 33/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6054 - accuracy: 0.7665
Epoch 34/100
230/230 [==============================] - 1s 5ms/step - loss: 0.6045 - accuracy: 0.7681
Epoch 35/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5960 - accuracy: 0.7714
Epoch 36/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5974 - accuracy: 0.7690
Epoch 37/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6075 - accuracy: 0.7709
Epoch 38/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5974 - accuracy: 0.7696
Epoch 39/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6032 - accuracy: 0.7673
Epoch 40/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5902 - accuracy: 0.7754
Epoch 41/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6004 - accuracy: 0.7684
Epoch 42/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5892 - accuracy: 0.7792
Epoch 43/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5886 - accuracy: 0.7759
Epoch 44/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5887 - accuracy: 0.7739
Epoch 45/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5961 - accuracy: 0.7720
Epoch 46/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6073 - accuracy: 0.7640
Epoch 47/100
230/230 [==============================] - 1s 6ms/step - loss: 0.6062 - accuracy: 0.7694
Epoch 48/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5943 - accuracy: 0.7683
Epoch 49/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5928 - accuracy: 0.7724
Epoch 50/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5872 - accuracy: 0.7769
Epoch 51/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6004 - accuracy: 0.7730
Epoch 52/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5971 - accuracy: 0.7711
Epoch 53/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5837 - accuracy: 0.7756
Epoch 54/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5958 - accuracy: 0.7685
Epoch 55/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5891 - accuracy: 0.7758
Epoch 56/100
230/230 [==============================] - 1s 4ms/step - loss: 0.6001 - accuracy: 0.7711
Epoch 57/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5937 - accuracy: 0.7705
Epoch 58/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5953 - accuracy: 0.7735
Epoch 59/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5926 - accuracy: 0.7743
Epoch 60/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5805 - accuracy: 0.7728
Epoch 61/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5818 - accuracy: 0.7724
Epoch 62/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5841 - accuracy: 0.7776
Epoch 63/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5907 - accuracy: 0.7755
Epoch 64/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5892 - accuracy: 0.7741
Epoch 65/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5902 - accuracy: 0.7793
Epoch 66/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5813 - accuracy: 0.7767
Epoch 67/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5831 - accuracy: 0.7761
Epoch 68/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5807 - accuracy: 0.7782
Epoch 69/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5912 - accuracy: 0.7692
Epoch 70/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5912 - accuracy: 0.7756
Epoch 71/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5857 - accuracy: 0.7740
Epoch 72/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5841 - accuracy: 0.7776
Epoch 73/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5865 - accuracy: 0.7722
Epoch 74/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5867 - accuracy: 0.7763
Epoch 75/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5784 - accuracy: 0.7718
Epoch 76/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5873 - accuracy: 0.7725
Epoch 77/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5789 - accuracy: 0.7780
Epoch 78/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5697 - accuracy: 0.7808
Epoch 79/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5870 - accuracy: 0.7735
Epoch 80/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5770 - accuracy: 0.7793
Epoch 81/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5802 - accuracy: 0.7724
Epoch 82/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5871 - accuracy: 0.7771
Epoch 83/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5815 - accuracy: 0.7755
Epoch 84/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5817 - accuracy: 0.7741
Epoch 85/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5716 - accuracy: 0.7776
Epoch 86/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5750 - accuracy: 0.7765
Epoch 87/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5886 - accuracy: 0.7679
Epoch 88/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5933 - accuracy: 0.7766
Epoch 89/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5682 - accuracy: 0.7827
Epoch 90/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5808 - accuracy: 0.7797
Epoch 91/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5730 - accuracy: 0.7766
Epoch 92/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5912 - accuracy: 0.7699
Epoch 93/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5728 - accuracy: 0.7745
Epoch 94/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5818 - accuracy: 0.7771
Epoch 95/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5749 - accuracy: 0.7799
Epoch 96/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5722 - accuracy: 0.7754
Epoch 97/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5711 - accuracy: 0.7797
Epoch 98/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5659 - accuracy: 0.7765
Epoch 99/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5754 - accuracy: 0.7765
Epoch 100/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5665 - accuracy: 0.7776

In [ ]:
model_2011.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2011.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
230/230 [==============================] - 4s 5ms/step - loss: 0.5560 - accuracy: 0.7823
Epoch 2/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5415 - accuracy: 0.7891
Epoch 3/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5467 - accuracy: 0.7878
Epoch 4/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5425 - accuracy: 0.7868
Epoch 5/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5475 - accuracy: 0.7893
Epoch 6/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5439 - accuracy: 0.7868
Epoch 7/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5383 - accuracy: 0.7942
Epoch 8/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5271 - accuracy: 0.7968
Epoch 9/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5389 - accuracy: 0.7926
Epoch 10/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7902
Epoch 11/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5387 - accuracy: 0.7919
Epoch 12/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5186 - accuracy: 0.7973
Epoch 13/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5263 - accuracy: 0.7965
Epoch 14/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5298 - accuracy: 0.7941
Epoch 15/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5276 - accuracy: 0.7981
Epoch 16/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5239 - accuracy: 0.7927
Epoch 17/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5294 - accuracy: 0.7949
Epoch 18/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5200 - accuracy: 0.7987
Epoch 19/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7991
Epoch 20/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5284 - accuracy: 0.7966
Epoch 21/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7958
Epoch 22/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5342 - accuracy: 0.7896
Epoch 23/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5247 - accuracy: 0.7920
Epoch 24/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5295 - accuracy: 0.7908
Epoch 25/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5226 - accuracy: 0.7969
Epoch 26/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5297 - accuracy: 0.7905
Epoch 27/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5202 - accuracy: 0.7917
Epoch 28/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5214 - accuracy: 0.7979
Epoch 29/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7943
Epoch 30/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5233 - accuracy: 0.7964
Epoch 31/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5264 - accuracy: 0.7990
Epoch 32/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5233 - accuracy: 0.7943
Epoch 33/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5131 - accuracy: 0.8006
Epoch 34/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.8005
Epoch 35/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5188 - accuracy: 0.7992
Epoch 36/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5270 - accuracy: 0.7947
Epoch 37/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5288 - accuracy: 0.7950
Epoch 38/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5219 - accuracy: 0.7958
Epoch 39/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5228 - accuracy: 0.7947
Epoch 40/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5242 - accuracy: 0.7969
Epoch 41/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5190 - accuracy: 0.8011
Epoch 42/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5284 - accuracy: 0.7928
Epoch 43/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5272 - accuracy: 0.7969
Epoch 44/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5160 - accuracy: 0.7990
Epoch 45/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5202 - accuracy: 0.7983
Epoch 46/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5229 - accuracy: 0.7919
Epoch 47/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5260 - accuracy: 0.7971
Epoch 48/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5084 - accuracy: 0.8081
Epoch 49/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.7992
Epoch 50/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7883
Epoch 51/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5335 - accuracy: 0.7920
Epoch 52/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5245 - accuracy: 0.7939
Epoch 53/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5252 - accuracy: 0.7953
Epoch 54/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5177 - accuracy: 0.8020
Epoch 55/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5090 - accuracy: 0.8010
Epoch 56/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5187 - accuracy: 0.8006
Epoch 57/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5166 - accuracy: 0.7961
Epoch 58/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5241 - accuracy: 0.7923
Epoch 59/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.7971
Epoch 60/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.8029
Epoch 61/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5191 - accuracy: 0.7962
Epoch 62/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5130 - accuracy: 0.8033
Epoch 63/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5197 - accuracy: 0.7986
Epoch 64/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5205 - accuracy: 0.7961
Epoch 65/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5195 - accuracy: 0.7949
Epoch 66/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5244 - accuracy: 0.7953
Epoch 67/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5186 - accuracy: 0.7946
Epoch 68/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5234 - accuracy: 0.7931
Epoch 69/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5182 - accuracy: 0.7991
Epoch 70/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5136 - accuracy: 0.7979
Epoch 71/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5106 - accuracy: 0.8001
Epoch 72/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5052 - accuracy: 0.8043
Epoch 73/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5141 - accuracy: 0.8017
Epoch 74/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5145 - accuracy: 0.7965
Epoch 75/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5281 - accuracy: 0.7935
Epoch 76/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5248 - accuracy: 0.7923
Epoch 77/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5223 - accuracy: 0.7935
Epoch 78/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5140 - accuracy: 0.8001
Epoch 79/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5145 - accuracy: 0.8010
Epoch 80/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5179 - accuracy: 0.7984
Epoch 81/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5170 - accuracy: 0.7999
Epoch 82/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5181 - accuracy: 0.7966
Epoch 83/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5136 - accuracy: 0.7992
Epoch 84/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5129 - accuracy: 0.8014
Epoch 85/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5113 - accuracy: 0.8001
Epoch 86/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5086 - accuracy: 0.7988
Epoch 87/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7958
Epoch 88/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5098 - accuracy: 0.8020
Epoch 89/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5159 - accuracy: 0.8010
Epoch 90/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5199 - accuracy: 0.7971
Epoch 91/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5147 - accuracy: 0.8028
Epoch 92/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5116 - accuracy: 0.8050
Epoch 93/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5129 - accuracy: 0.7976
Epoch 94/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5164 - accuracy: 0.7973
Epoch 95/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5101 - accuracy: 0.8020
Epoch 96/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5083 - accuracy: 0.8024
Epoch 97/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5039 - accuracy: 0.7999
Epoch 98/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7999
Epoch 99/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5099 - accuracy: 0.8001
Epoch 100/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5164 - accuracy: 0.7924

In [ ]:
model_2011.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2011.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
230/230 [==============================] - 4s 6ms/step - loss: 0.5111 - accuracy: 0.8007
Epoch 2/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5031 - accuracy: 0.8046
Epoch 3/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7991
Epoch 4/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5082 - accuracy: 0.8011
Epoch 5/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5118 - accuracy: 0.8024
Epoch 6/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5108 - accuracy: 0.8041
Epoch 7/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.8091
Epoch 8/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7971
Epoch 9/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.7958
Epoch 10/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5088 - accuracy: 0.8003
Epoch 11/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5081 - accuracy: 0.7992
Epoch 12/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5035 - accuracy: 0.8014
Epoch 13/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5088 - accuracy: 0.8002
Epoch 14/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5072 - accuracy: 0.8018
Epoch 15/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5067 - accuracy: 0.8011
Epoch 16/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.8003
Epoch 17/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5066 - accuracy: 0.8022
Epoch 18/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.8062
Epoch 19/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5091 - accuracy: 0.8024
Epoch 20/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4987 - accuracy: 0.8051
Epoch 21/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5096 - accuracy: 0.7988
Epoch 22/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.8028
Epoch 23/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5115 - accuracy: 0.7991
Epoch 24/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5024 - accuracy: 0.8039
Epoch 25/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5109 - accuracy: 0.7998
Epoch 26/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5018 - accuracy: 0.8044
Epoch 27/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5056 - accuracy: 0.7998
Epoch 28/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5097 - accuracy: 0.7995
Epoch 29/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5034 - accuracy: 0.8044
Epoch 30/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5072 - accuracy: 0.7998
Epoch 31/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5047 - accuracy: 0.8039
Epoch 32/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5132 - accuracy: 0.8044
Epoch 33/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.8050
Epoch 34/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7991
Epoch 35/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.8024
Epoch 36/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5019 - accuracy: 0.8066
Epoch 37/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5111 - accuracy: 0.8010
Epoch 38/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5112 - accuracy: 0.7998
Epoch 39/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5037 - accuracy: 0.8022
Epoch 40/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5033 - accuracy: 0.8074
Epoch 41/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5040 - accuracy: 0.8026
Epoch 42/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5086 - accuracy: 0.7979
Epoch 43/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5009 - accuracy: 0.8017
Epoch 44/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.8061
Epoch 45/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.8082
Epoch 46/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.8059
Epoch 47/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.8025
Epoch 48/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5058 - accuracy: 0.7991
Epoch 49/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5001 - accuracy: 0.8055
Epoch 50/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.8041
Epoch 51/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5020 - accuracy: 0.8056
Epoch 52/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5022 - accuracy: 0.8014
Epoch 53/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5102 - accuracy: 0.7994
Epoch 54/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4994 - accuracy: 0.8041
Epoch 55/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4976 - accuracy: 0.8033
Epoch 56/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5081 - accuracy: 0.8014
Epoch 57/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5023 - accuracy: 0.8059
Epoch 58/100
230/230 [==============================] - 1s 5ms/step - loss: 0.4998 - accuracy: 0.8058
Epoch 59/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5087 - accuracy: 0.7979
Epoch 60/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5078 - accuracy: 0.8047
Epoch 61/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5079 - accuracy: 0.8011
Epoch 62/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.8054
Epoch 63/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5003 - accuracy: 0.8024
Epoch 64/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.8040
Epoch 65/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.8006
Epoch 66/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4939 - accuracy: 0.8062
Epoch 67/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4970 - accuracy: 0.8092
Epoch 68/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5068 - accuracy: 0.7995
Epoch 69/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5013 - accuracy: 0.8036
Epoch 70/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5054 - accuracy: 0.7965
Epoch 71/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5095 - accuracy: 0.8006
Epoch 72/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5016 - accuracy: 0.7991
Epoch 73/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5059 - accuracy: 0.8055
Epoch 74/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4993 - accuracy: 0.8020
Epoch 75/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.8052
Epoch 76/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.8086
Epoch 77/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.8039
Epoch 78/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5006 - accuracy: 0.8033
Epoch 79/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5084 - accuracy: 0.7983
Epoch 80/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5012 - accuracy: 0.8017
Epoch 81/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5056 - accuracy: 0.8040
Epoch 82/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5011 - accuracy: 0.7998
Epoch 83/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5040 - accuracy: 0.8028
Epoch 84/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5025 - accuracy: 0.7995
Epoch 85/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4998 - accuracy: 0.8044
Epoch 86/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4916 - accuracy: 0.8046
Epoch 87/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5029 - accuracy: 0.7969
Epoch 88/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.8065
Epoch 89/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5100 - accuracy: 0.8022
Epoch 90/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5027 - accuracy: 0.8058
Epoch 91/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.8036
Epoch 92/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5041 - accuracy: 0.7992
Epoch 93/100
230/230 [==============================] - 1s 5ms/step - loss: 0.4991 - accuracy: 0.8039
Epoch 94/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4989 - accuracy: 0.8052
Epoch 95/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4954 - accuracy: 0.8021
Epoch 96/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4911 - accuracy: 0.8099
Epoch 97/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5026 - accuracy: 0.8050
Epoch 98/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.8076
Epoch 99/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5050 - accuracy: 0.8046
Epoch 100/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4934 - accuracy: 0.8050

In [ ]:
model_2011.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2011.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
230/230 [==============================] - 3s 6ms/step - loss: 0.4979 - accuracy: 0.8046
Epoch 2/100
230/230 [==============================] - 2s 7ms/step - loss: 0.4994 - accuracy: 0.8066
Epoch 3/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5003 - accuracy: 0.8001
Epoch 4/100
230/230 [==============================] - 1s 5ms/step - loss: 0.4842 - accuracy: 0.8089
Epoch 5/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.8039
Epoch 6/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4994 - accuracy: 0.8018
Epoch 7/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4949 - accuracy: 0.8029
Epoch 8/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.8048
Epoch 9/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5017 - accuracy: 0.8056
Epoch 10/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4973 - accuracy: 0.8036
Epoch 11/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.8063
Epoch 12/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5007 - accuracy: 0.8076
Epoch 13/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.8063
Epoch 14/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5043 - accuracy: 0.8020
Epoch 15/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4995 - accuracy: 0.8041
Epoch 16/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4903 - accuracy: 0.8086
Epoch 17/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4957 - accuracy: 0.8032
Epoch 18/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5005 - accuracy: 0.8059
Epoch 19/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4974 - accuracy: 0.8003
Epoch 20/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.8035
Epoch 21/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.8065
Epoch 22/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.8076
Epoch 23/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4933 - accuracy: 0.8065
Epoch 24/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5008 - accuracy: 0.8013
Epoch 25/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.8037
Epoch 26/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5020 - accuracy: 0.8077
Epoch 27/100
230/230 [==============================] - 1s 5ms/step - loss: 0.4894 - accuracy: 0.8069
Epoch 28/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4998 - accuracy: 0.8044
Epoch 29/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4979 - accuracy: 0.8063
Epoch 30/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4966 - accuracy: 0.8039
Epoch 31/100
230/230 [==============================] - 1s 5ms/step - loss: 0.4931 - accuracy: 0.8081
Epoch 32/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.8081
Epoch 33/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4981 - accuracy: 0.8077
Epoch 34/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4937 - accuracy: 0.8046
Epoch 35/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.8058
Epoch 36/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.8026
Epoch 37/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.8059
Epoch 38/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4924 - accuracy: 0.8084
Epoch 39/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.7981
Epoch 40/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4901 - accuracy: 0.8093
Epoch 41/100
230/230 [==============================] - 1s 5ms/step - loss: 0.4996 - accuracy: 0.8069
Epoch 42/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4967 - accuracy: 0.8029
Epoch 43/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4936 - accuracy: 0.8078
Epoch 44/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4923 - accuracy: 0.8029
Epoch 45/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5010 - accuracy: 0.8035
Epoch 46/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4966 - accuracy: 0.8073
Epoch 47/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4921 - accuracy: 0.8066
Epoch 48/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4904 - accuracy: 0.8084
Epoch 49/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5046 - accuracy: 0.8032
Epoch 50/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5144 - accuracy: 0.8033
Epoch 51/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4945 - accuracy: 0.8018
Epoch 52/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5037 - accuracy: 0.8046
Epoch 53/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.8059
Epoch 54/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5011 - accuracy: 0.8041
Epoch 55/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4980 - accuracy: 0.8025
Epoch 56/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4938 - accuracy: 0.8065
Epoch 57/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4896 - accuracy: 0.8076
Epoch 58/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5033 - accuracy: 0.8028
Epoch 59/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.8061
Epoch 60/100
230/230 [==============================] - 1s 5ms/step - loss: 0.4964 - accuracy: 0.8039
Epoch 61/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.8052
Epoch 62/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4965 - accuracy: 0.8026
Epoch 63/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.8047
Epoch 64/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.8066
Epoch 65/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4913 - accuracy: 0.8066
Epoch 66/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4962 - accuracy: 0.8081
Epoch 67/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4929 - accuracy: 0.8052
Epoch 68/100
230/230 [==============================] - 1s 5ms/step - loss: 0.4939 - accuracy: 0.8052
Epoch 69/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4892 - accuracy: 0.8084
Epoch 70/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4942 - accuracy: 0.8059
Epoch 71/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4947 - accuracy: 0.8036
Epoch 72/100
230/230 [==============================] - 1s 5ms/step - loss: 0.4952 - accuracy: 0.8011
Epoch 73/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5093 - accuracy: 0.7998
Epoch 74/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4909 - accuracy: 0.8052
Epoch 75/100
230/230 [==============================] - 1s 5ms/step - loss: 0.5000 - accuracy: 0.8086
Epoch 76/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4960 - accuracy: 0.8051
Epoch 77/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.8066
Epoch 78/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5023 - accuracy: 0.8032
Epoch 79/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5032 - accuracy: 0.7984
Epoch 80/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4925 - accuracy: 0.8059
Epoch 81/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.8089
Epoch 82/100
230/230 [==============================] - 1s 5ms/step - loss: 0.4902 - accuracy: 0.8067
Epoch 83/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4890 - accuracy: 0.8078
Epoch 84/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4943 - accuracy: 0.8043
Epoch 85/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5023 - accuracy: 0.8056
Epoch 86/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4979 - accuracy: 0.8063
Epoch 87/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4952 - accuracy: 0.8025
Epoch 88/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4935 - accuracy: 0.8055
Epoch 89/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.8054
Epoch 90/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4940 - accuracy: 0.8081
Epoch 91/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4975 - accuracy: 0.8014
Epoch 92/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4920 - accuracy: 0.8032
Epoch 93/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4877 - accuracy: 0.8070
Epoch 94/100
230/230 [==============================] - 1s 4ms/step - loss: 0.5006 - accuracy: 0.8076
Epoch 95/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.8088
Epoch 96/100
230/230 [==============================] - 1s 6ms/step - loss: 0.5003 - accuracy: 0.8043
Epoch 97/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4913 - accuracy: 0.8065
Epoch 98/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4941 - accuracy: 0.8069
Epoch 99/100
230/230 [==============================] - 1s 6ms/step - loss: 0.4960 - accuracy: 0.8052
Epoch 100/100
230/230 [==============================] - 1s 4ms/step - loss: 0.4996 - accuracy: 0.8037

In [ ]:
model_2011.save("/content/drive/MyDrive/FYP/Trained Models/2011.keras")

In [ ]:
predictions = model_2011(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

8

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.8015267175572519

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.8068083261058109

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2011.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2012

### Stratified sampling

In [ ]:
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2012, labels_2012):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2012)

numpy.ndarray

In [ ]:
fold1[0]

array([ 144,  145,  146, ..., 8668, 8669, 8670])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2012[x]
    y_train = labels_2012[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2012[x]))
    y_train = np.vstack((y_train, labels_2012[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2012[x]
    y_test = labels_2012[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2012[x]))
    y_test = np.vstack((y_test, labels_2012[x]))

In [ ]:
# Second iteration of Stratified KFold for test set
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2012[x]
    y_train = labels_2012[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2012[x]))
    y_train = np.vstack((y_train, labels_2012[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2012[x]
    y_test = labels_2012[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2012[x]))
    y_test = np.vstack((y_test, labels_2012[x]))

In [ ]:
# Third iteration of Stratified KFold for training test and cross validation set
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2012[x]
    y_train = labels_2012[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2012[x]))
    y_train = np.vstack((y_train, labels_2012[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2012[x]
    y_test = labels_2012[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2012[x]))
    y_test = np.vstack((y_test, labels_2012[x]))

In [ ]:
y_train.shape

(5780, 1)

## Model Training 2012

In [ ]:
model_2012 = Sequential()

In [ ]:
model_2012.add(Dense(units=520, activation="relu"))
model_2012.add(Dropout(0.2))
model_2012.add(Dense(units=250, activation="relu"))
model_2012.add(Dropout(0.2))
model_2012.add(Dense(units=128, activation="relu"))
model_2012.add(Dropout(0.2))
model_2012.add(Dense(units=64, activation="relu"))
model_2012.add(Dropout(0.2))
model_2012.add(Dense(units=45, activation="relu"))
model_2012.add(Dropout(0.2))
model_2012.add(Dense(units=28, activation="relu"))
model_2012.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2012.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2012.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
181/181 [==============================] - 3s 5ms/step - loss: 2.5338 - accuracy: 0.1889
Epoch 2/100
181/181 [==============================] - 1s 4ms/step - loss: 1.7913 - accuracy: 0.3728
Epoch 3/100
181/181 [==============================] - 1s 4ms/step - loss: 1.4731 - accuracy: 0.4696
Epoch 4/100
181/181 [==============================] - 1s 4ms/step - loss: 1.3117 - accuracy: 0.5202
Epoch 5/100
181/181 [==============================] - 1s 4ms/step - loss: 1.2299 - accuracy: 0.5429
Epoch 6/100
181/181 [==============================] - 1s 4ms/step - loss: 1.1842 - accuracy: 0.5600
Epoch 7/100
181/181 [==============================] - 1s 4ms/step - loss: 1.1494 - accuracy: 0.5723
Epoch 8/100
181/181 [==============================] - 1s 6ms/step - loss: 1.1080 - accuracy: 0.5931
Epoch 9/100
181/181 [==============================] - 1s 6ms/step - loss: 1.0742 - accuracy: 0.5967
Epoch 10/100
181/181 [==============================] - 1s 6ms/step - loss: 1.0512 - accuracy: 0.6073
Epoch 11/100
181/181 [==============================] - 1s 6ms/step - loss: 1.0173 - accuracy: 0.6216
Epoch 12/100
181/181 [==============================] - 1s 5ms/step - loss: 0.9744 - accuracy: 0.6388
Epoch 13/100
181/181 [==============================] - 1s 4ms/step - loss: 0.9629 - accuracy: 0.6441
Epoch 14/100
181/181 [==============================] - 1s 4ms/step - loss: 0.9657 - accuracy: 0.6471
Epoch 15/100
181/181 [==============================] - 1s 4ms/step - loss: 0.9456 - accuracy: 0.6554
Epoch 16/100
181/181 [==============================] - 1s 4ms/step - loss: 0.9069 - accuracy: 0.6670
Epoch 17/100
181/181 [==============================] - 1s 4ms/step - loss: 0.9112 - accuracy: 0.6638
Epoch 18/100
181/181 [==============================] - 1s 4ms/step - loss: 0.9028 - accuracy: 0.6680
Epoch 19/100
181/181 [==============================] - 1s 4ms/step - loss: 0.8821 - accuracy: 0.6779
Epoch 20/100
181/181 [==============================] - 1s 4ms/step - loss: 0.8635 - accuracy: 0.6863
Epoch 21/100
181/181 [==============================] - 1s 4ms/step - loss: 0.8767 - accuracy: 0.6784
Epoch 22/100
181/181 [==============================] - 1s 4ms/step - loss: 0.8657 - accuracy: 0.6853
Epoch 23/100
181/181 [==============================] - 1s 4ms/step - loss: 0.8430 - accuracy: 0.6870
Epoch 24/100
181/181 [==============================] - 1s 4ms/step - loss: 0.8370 - accuracy: 0.6948
Epoch 25/100
181/181 [==============================] - 1s 5ms/step - loss: 0.8328 - accuracy: 0.6893
Epoch 26/100
181/181 [==============================] - 1s 6ms/step - loss: 0.8307 - accuracy: 0.6943
Epoch 27/100
181/181 [==============================] - 1s 6ms/step - loss: 0.8270 - accuracy: 0.6997
Epoch 28/100
181/181 [==============================] - 1s 6ms/step - loss: 0.8134 - accuracy: 0.7019
Epoch 29/100
181/181 [==============================] - 1s 6ms/step - loss: 0.8065 - accuracy: 0.7048
Epoch 30/100
181/181 [==============================] - 1s 4ms/step - loss: 0.8171 - accuracy: 0.7014
Epoch 31/100
181/181 [==============================] - 1s 4ms/step - loss: 0.8054 - accuracy: 0.7012
Epoch 32/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7981 - accuracy: 0.7040
Epoch 33/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7998 - accuracy: 0.7087
Epoch 34/100
181/181 [==============================] - 1s 4ms/step - loss: 0.8015 - accuracy: 0.7012
Epoch 35/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7931 - accuracy: 0.7031
Epoch 36/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7652 - accuracy: 0.7137
Epoch 37/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7941 - accuracy: 0.7090
Epoch 38/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7823 - accuracy: 0.7102
Epoch 39/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7651 - accuracy: 0.7209
Epoch 40/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7571 - accuracy: 0.7206
Epoch 41/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7563 - accuracy: 0.7234
Epoch 42/100
181/181 [==============================] - 1s 5ms/step - loss: 0.7554 - accuracy: 0.7273
Epoch 43/100
181/181 [==============================] - 1s 6ms/step - loss: 0.7461 - accuracy: 0.7218
Epoch 44/100
181/181 [==============================] - 1s 6ms/step - loss: 0.7351 - accuracy: 0.7249
Epoch 45/100
181/181 [==============================] - 1s 6ms/step - loss: 0.7566 - accuracy: 0.7204
Epoch 46/100
181/181 [==============================] - 1s 6ms/step - loss: 0.7567 - accuracy: 0.7192
Epoch 47/100
181/181 [==============================] - 1s 5ms/step - loss: 0.7374 - accuracy: 0.7289
Epoch 48/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7316 - accuracy: 0.7273
Epoch 49/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7312 - accuracy: 0.7325
Epoch 50/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7452 - accuracy: 0.7303
Epoch 51/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7254 - accuracy: 0.7329
Epoch 52/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7376 - accuracy: 0.7308
Epoch 53/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7104 - accuracy: 0.7355
Epoch 54/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7246 - accuracy: 0.7303
Epoch 55/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7336 - accuracy: 0.7301
Epoch 56/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7244 - accuracy: 0.7337
Epoch 57/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7232 - accuracy: 0.7311
Epoch 58/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6976 - accuracy: 0.7419
Epoch 59/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7264 - accuracy: 0.7311
Epoch 60/100
181/181 [==============================] - 1s 5ms/step - loss: 0.7055 - accuracy: 0.7396
Epoch 61/100
181/181 [==============================] - 1s 6ms/step - loss: 0.7184 - accuracy: 0.7393
Epoch 62/100
181/181 [==============================] - 1s 6ms/step - loss: 0.7121 - accuracy: 0.7343
Epoch 63/100
181/181 [==============================] - 1s 6ms/step - loss: 0.7040 - accuracy: 0.7369
Epoch 64/100
181/181 [==============================] - 1s 6ms/step - loss: 0.6988 - accuracy: 0.7438
Epoch 65/100
181/181 [==============================] - 1s 5ms/step - loss: 0.7090 - accuracy: 0.7389
Epoch 66/100
181/181 [==============================] - 1s 4ms/step - loss: 0.7037 - accuracy: 0.7427
Epoch 67/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6984 - accuracy: 0.7401
Epoch 68/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6827 - accuracy: 0.7464
Epoch 69/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6792 - accuracy: 0.7535
Epoch 70/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6911 - accuracy: 0.7450
Epoch 71/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6882 - accuracy: 0.7445
Epoch 72/100
181/181 [==============================] - 1s 5ms/step - loss: 0.6925 - accuracy: 0.7462
Epoch 73/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6985 - accuracy: 0.7379
Epoch 74/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6774 - accuracy: 0.7465
Epoch 75/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6722 - accuracy: 0.7512
Epoch 76/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6656 - accuracy: 0.7555
Epoch 77/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6729 - accuracy: 0.7455
Epoch 78/100
181/181 [==============================] - 1s 6ms/step - loss: 0.6900 - accuracy: 0.7417
Epoch 79/100
181/181 [==============================] - 1s 6ms/step - loss: 0.6851 - accuracy: 0.7464
Epoch 80/100
181/181 [==============================] - 1s 6ms/step - loss: 0.6774 - accuracy: 0.7507
Epoch 81/100
181/181 [==============================] - 1s 6ms/step - loss: 0.6975 - accuracy: 0.7448
Epoch 82/100
181/181 [==============================] - 1s 6ms/step - loss: 0.6752 - accuracy: 0.7510
Epoch 83/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6608 - accuracy: 0.7547
Epoch 84/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6694 - accuracy: 0.7567
Epoch 85/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6657 - accuracy: 0.7528
Epoch 86/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6745 - accuracy: 0.7500
Epoch 87/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6562 - accuracy: 0.7585
Epoch 88/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6548 - accuracy: 0.7633
Epoch 89/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6681 - accuracy: 0.7517
Epoch 90/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6584 - accuracy: 0.7597
Epoch 91/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6617 - accuracy: 0.7573
Epoch 92/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6648 - accuracy: 0.7540
Epoch 93/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6597 - accuracy: 0.7567
Epoch 94/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6645 - accuracy: 0.7510
Epoch 95/100
181/181 [==============================] - 1s 5ms/step - loss: 0.6504 - accuracy: 0.7638
Epoch 96/100
181/181 [==============================] - 1s 6ms/step - loss: 0.6429 - accuracy: 0.7637
Epoch 97/100
181/181 [==============================] - 1s 6ms/step - loss: 0.6623 - accuracy: 0.7561
Epoch 98/100
181/181 [==============================] - 1s 6ms/step - loss: 0.6711 - accuracy: 0.7529
Epoch 99/100
181/181 [==============================] - 1s 6ms/step - loss: 0.6390 - accuracy: 0.7638
Epoch 100/100
181/181 [==============================] - 1s 5ms/step - loss: 0.6620 - accuracy: 0.7503

In [ ]:
model_2012.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2012.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
181/181 [==============================] - 3s 4ms/step - loss: 0.6174 - accuracy: 0.7706
Epoch 2/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6006 - accuracy: 0.7721
Epoch 3/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6019 - accuracy: 0.7782
Epoch 4/100
181/181 [==============================] - 1s 4ms/step - loss: 0.6016 - accuracy: 0.7777
Epoch 5/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5947 - accuracy: 0.7789
Epoch 6/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5930 - accuracy: 0.7782
Epoch 7/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5964 - accuracy: 0.7815
Epoch 8/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5878 - accuracy: 0.7766
Epoch 9/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5915 - accuracy: 0.7746
Epoch 10/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5932 - accuracy: 0.7813
Epoch 11/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5842 - accuracy: 0.7768
Epoch 12/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5864 - accuracy: 0.7765
Epoch 13/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5876 - accuracy: 0.7817
Epoch 14/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5909 - accuracy: 0.7779
Epoch 15/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5805 - accuracy: 0.7825
Epoch 16/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5894 - accuracy: 0.7849
Epoch 17/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5802 - accuracy: 0.7810
Epoch 18/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5875 - accuracy: 0.7751
Epoch 19/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5790 - accuracy: 0.7832
Epoch 20/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5636 - accuracy: 0.7903
Epoch 21/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5796 - accuracy: 0.7808
Epoch 22/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5757 - accuracy: 0.7855
Epoch 23/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5662 - accuracy: 0.7844
Epoch 24/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5804 - accuracy: 0.7832
Epoch 25/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5706 - accuracy: 0.7844
Epoch 26/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5596 - accuracy: 0.7851
Epoch 27/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5745 - accuracy: 0.7865
Epoch 28/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5763 - accuracy: 0.7891
Epoch 29/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5780 - accuracy: 0.7891
Epoch 30/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5697 - accuracy: 0.7872
Epoch 31/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5776 - accuracy: 0.7862
Epoch 32/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5650 - accuracy: 0.7894
Epoch 33/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5821 - accuracy: 0.7815
Epoch 34/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5764 - accuracy: 0.7849
Epoch 35/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5793 - accuracy: 0.7837
Epoch 36/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5728 - accuracy: 0.7827
Epoch 37/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5586 - accuracy: 0.7931
Epoch 38/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5597 - accuracy: 0.7896
Epoch 39/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5778 - accuracy: 0.7817
Epoch 40/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5669 - accuracy: 0.7929
Epoch 41/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5692 - accuracy: 0.7877
Epoch 42/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5653 - accuracy: 0.7907
Epoch 43/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5721 - accuracy: 0.7848
Epoch 44/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5588 - accuracy: 0.7898
Epoch 45/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5682 - accuracy: 0.7855
Epoch 46/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5742 - accuracy: 0.7884
Epoch 47/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5503 - accuracy: 0.7967
Epoch 48/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5620 - accuracy: 0.7858
Epoch 49/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5576 - accuracy: 0.7913
Epoch 50/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5595 - accuracy: 0.7924
Epoch 51/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5614 - accuracy: 0.7913
Epoch 52/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5545 - accuracy: 0.7822
Epoch 53/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5602 - accuracy: 0.7922
Epoch 54/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5536 - accuracy: 0.7924
Epoch 55/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5560 - accuracy: 0.7955
Epoch 56/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5560 - accuracy: 0.7941
Epoch 57/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5664 - accuracy: 0.7832
Epoch 58/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5601 - accuracy: 0.7910
Epoch 59/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5549 - accuracy: 0.7881
Epoch 60/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5574 - accuracy: 0.7952
Epoch 61/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5550 - accuracy: 0.7905
Epoch 62/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5614 - accuracy: 0.7896
Epoch 63/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5524 - accuracy: 0.7926
Epoch 64/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5654 - accuracy: 0.7888
Epoch 65/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5593 - accuracy: 0.7908
Epoch 66/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5505 - accuracy: 0.7882
Epoch 67/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5452 - accuracy: 0.7934
Epoch 68/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5519 - accuracy: 0.7882
Epoch 69/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5538 - accuracy: 0.7936
Epoch 70/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5549 - accuracy: 0.7939
Epoch 71/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5535 - accuracy: 0.7917
Epoch 72/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5655 - accuracy: 0.7865
Epoch 73/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5518 - accuracy: 0.7898
Epoch 74/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5460 - accuracy: 0.7915
Epoch 75/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5387 - accuracy: 0.7950
Epoch 76/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5501 - accuracy: 0.7941
Epoch 77/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5512 - accuracy: 0.7931
Epoch 78/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5657 - accuracy: 0.7941
Epoch 79/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5482 - accuracy: 0.7941
Epoch 80/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5499 - accuracy: 0.7905
Epoch 81/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5592 - accuracy: 0.7958
Epoch 82/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5386 - accuracy: 0.7960
Epoch 83/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5504 - accuracy: 0.8016
Epoch 84/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5432 - accuracy: 0.7962
Epoch 85/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5478 - accuracy: 0.7953
Epoch 86/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5411 - accuracy: 0.7972
Epoch 87/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5529 - accuracy: 0.7929
Epoch 88/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5392 - accuracy: 0.7958
Epoch 89/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5503 - accuracy: 0.7952
Epoch 90/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5402 - accuracy: 0.7900
Epoch 91/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5517 - accuracy: 0.7986
Epoch 92/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5495 - accuracy: 0.7934
Epoch 93/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5434 - accuracy: 0.7900
Epoch 94/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7905
Epoch 95/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5455 - accuracy: 0.7943
Epoch 96/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5370 - accuracy: 0.8016
Epoch 97/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5435 - accuracy: 0.7969
Epoch 98/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5442 - accuracy: 0.7952
Epoch 99/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5415 - accuracy: 0.7927
Epoch 100/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5514 - accuracy: 0.7943

In [ ]:
model_2012.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2012.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
181/181 [==============================] - 3s 4ms/step - loss: 0.5279 - accuracy: 0.7955
Epoch 2/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5193 - accuracy: 0.8040
Epoch 3/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5158 - accuracy: 0.8043
Epoch 4/100
181/181 [==============================] - 1s 5ms/step - loss: 0.5084 - accuracy: 0.8064
Epoch 5/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4973 - accuracy: 0.8147
Epoch 6/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4990 - accuracy: 0.8106
Epoch 7/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.8090
Epoch 8/100
181/181 [==============================] - 1s 4ms/step - loss: 0.5018 - accuracy: 0.8066
Epoch 9/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4977 - accuracy: 0.8131
Epoch 10/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.8100
Epoch 11/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4952 - accuracy: 0.8076
Epoch 12/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4977 - accuracy: 0.8104
Epoch 13/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5049 - accuracy: 0.8161
Epoch 14/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4880 - accuracy: 0.8133
Epoch 15/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4937 - accuracy: 0.8121
Epoch 16/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4915 - accuracy: 0.8093
Epoch 17/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4978 - accuracy: 0.8123
Epoch 18/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4951 - accuracy: 0.8097
Epoch 19/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4950 - accuracy: 0.8152
Epoch 20/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4959 - accuracy: 0.8171
Epoch 21/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4898 - accuracy: 0.8116
Epoch 22/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.8197
Epoch 23/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4943 - accuracy: 0.8164
Epoch 24/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4932 - accuracy: 0.8114
Epoch 25/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4882 - accuracy: 0.8149
Epoch 26/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4813 - accuracy: 0.8163
Epoch 27/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4888 - accuracy: 0.8138
Epoch 28/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4904 - accuracy: 0.8149
Epoch 29/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4903 - accuracy: 0.8164
Epoch 30/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4802 - accuracy: 0.8154
Epoch 31/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4853 - accuracy: 0.8119
Epoch 32/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4952 - accuracy: 0.8095
Epoch 33/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4853 - accuracy: 0.8152
Epoch 34/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4818 - accuracy: 0.8218
Epoch 35/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4905 - accuracy: 0.8170
Epoch 36/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4822 - accuracy: 0.8145
Epoch 37/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4783 - accuracy: 0.8151
Epoch 38/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4884 - accuracy: 0.8137
Epoch 39/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4865 - accuracy: 0.8163
Epoch 40/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4791 - accuracy: 0.8170
Epoch 41/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.8185
Epoch 42/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.8099
Epoch 43/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.8185
Epoch 44/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4928 - accuracy: 0.8090
Epoch 45/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4790 - accuracy: 0.8138
Epoch 46/100
181/181 [==============================] - 1s 6ms/step - loss: 0.5034 - accuracy: 0.8095
Epoch 47/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4867 - accuracy: 0.8140
Epoch 48/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4817 - accuracy: 0.8163
Epoch 49/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4871 - accuracy: 0.8170
Epoch 50/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4808 - accuracy: 0.8211
Epoch 51/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4771 - accuracy: 0.8163
Epoch 52/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4894 - accuracy: 0.8116
Epoch 53/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4820 - accuracy: 0.8173
Epoch 54/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.8199
Epoch 55/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.8168
Epoch 56/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4789 - accuracy: 0.8147
Epoch 57/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4818 - accuracy: 0.8208
Epoch 58/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4840 - accuracy: 0.8168
Epoch 59/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4839 - accuracy: 0.8171
Epoch 60/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.8133
Epoch 61/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4776 - accuracy: 0.8192
Epoch 62/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4835 - accuracy: 0.8126
Epoch 63/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4838 - accuracy: 0.8163
Epoch 64/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4859 - accuracy: 0.8161
Epoch 65/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4816 - accuracy: 0.8154
Epoch 66/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4868 - accuracy: 0.8137
Epoch 67/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4813 - accuracy: 0.8204
Epoch 68/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4772 - accuracy: 0.8178
Epoch 69/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4757 - accuracy: 0.8202
Epoch 70/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4833 - accuracy: 0.8125
Epoch 71/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.8126
Epoch 72/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4774 - accuracy: 0.8163
Epoch 73/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.8170
Epoch 74/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4769 - accuracy: 0.8213
Epoch 75/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.8178
Epoch 76/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4764 - accuracy: 0.8144
Epoch 77/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4873 - accuracy: 0.8125
Epoch 78/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4870 - accuracy: 0.8116
Epoch 79/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4816 - accuracy: 0.8151
Epoch 80/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4808 - accuracy: 0.8152
Epoch 81/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4822 - accuracy: 0.8126
Epoch 82/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4832 - accuracy: 0.8128
Epoch 83/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4763 - accuracy: 0.8182
Epoch 84/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4848 - accuracy: 0.8170
Epoch 85/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4748 - accuracy: 0.8189
Epoch 86/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4828 - accuracy: 0.8166
Epoch 87/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4826 - accuracy: 0.8176
Epoch 88/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4775 - accuracy: 0.8228
Epoch 89/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.8144
Epoch 90/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4793 - accuracy: 0.8182
Epoch 91/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4757 - accuracy: 0.8227
Epoch 92/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.8208
Epoch 93/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.8163
Epoch 94/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.8171
Epoch 95/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4823 - accuracy: 0.8159
Epoch 96/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4802 - accuracy: 0.8194
Epoch 97/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4718 - accuracy: 0.8190
Epoch 98/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4806 - accuracy: 0.8171
Epoch 99/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4834 - accuracy: 0.8178
Epoch 100/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4708 - accuracy: 0.8164

In [ ]:
model_2012.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2012.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
181/181 [==============================] - 3s 4ms/step - loss: 0.4698 - accuracy: 0.8208
Epoch 2/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4735 - accuracy: 0.8206
Epoch 3/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4731 - accuracy: 0.8185
Epoch 4/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4684 - accuracy: 0.8220
Epoch 5/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.8223
Epoch 6/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4717 - accuracy: 0.8211
Epoch 7/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4635 - accuracy: 0.8215
Epoch 8/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4647 - accuracy: 0.8194
Epoch 9/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4728 - accuracy: 0.8230
Epoch 10/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4717 - accuracy: 0.8221
Epoch 11/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4742 - accuracy: 0.8170
Epoch 12/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4721 - accuracy: 0.8196
Epoch 13/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.8154
Epoch 14/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4671 - accuracy: 0.8277
Epoch 15/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.8260
Epoch 16/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4729 - accuracy: 0.8247
Epoch 17/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.8223
Epoch 18/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4734 - accuracy: 0.8147
Epoch 19/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4738 - accuracy: 0.8244
Epoch 20/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4767 - accuracy: 0.8221
Epoch 21/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4727 - accuracy: 0.8209
Epoch 22/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.8253
Epoch 23/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4711 - accuracy: 0.8206
Epoch 24/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.8225
Epoch 25/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4767 - accuracy: 0.8159
Epoch 26/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4690 - accuracy: 0.8270
Epoch 27/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4575 - accuracy: 0.8237
Epoch 28/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4738 - accuracy: 0.8199
Epoch 29/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4714 - accuracy: 0.8235
Epoch 30/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4658 - accuracy: 0.8218
Epoch 31/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4768 - accuracy: 0.8197
Epoch 32/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.8225
Epoch 33/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.8256
Epoch 34/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4701 - accuracy: 0.8201
Epoch 35/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.8227
Epoch 36/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4713 - accuracy: 0.8227
Epoch 37/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.8182
Epoch 38/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4749 - accuracy: 0.8175
Epoch 39/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4684 - accuracy: 0.8202
Epoch 40/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.8258
Epoch 41/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.8208
Epoch 42/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4727 - accuracy: 0.8246
Epoch 43/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4607 - accuracy: 0.8218
Epoch 44/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4588 - accuracy: 0.8244
Epoch 45/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4757 - accuracy: 0.8197
Epoch 46/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4703 - accuracy: 0.8183
Epoch 47/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.8192
Epoch 48/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4629 - accuracy: 0.8251
Epoch 49/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4571 - accuracy: 0.8261
Epoch 50/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.8235
Epoch 51/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4656 - accuracy: 0.8204
Epoch 52/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.8266
Epoch 53/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4645 - accuracy: 0.8251
Epoch 54/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.8204
Epoch 55/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4645 - accuracy: 0.8190
Epoch 56/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.8194
Epoch 57/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4722 - accuracy: 0.8175
Epoch 58/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4612 - accuracy: 0.8273
Epoch 59/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4685 - accuracy: 0.8221
Epoch 60/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4655 - accuracy: 0.8221
Epoch 61/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4773 - accuracy: 0.8204
Epoch 62/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4703 - accuracy: 0.8189
Epoch 63/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4582 - accuracy: 0.8268
Epoch 64/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4651 - accuracy: 0.8230
Epoch 65/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4640 - accuracy: 0.8208
Epoch 66/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.8285
Epoch 67/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4602 - accuracy: 0.8199
Epoch 68/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4614 - accuracy: 0.8220
Epoch 69/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4723 - accuracy: 0.8197
Epoch 70/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.8183
Epoch 71/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4661 - accuracy: 0.8185
Epoch 72/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.8258
Epoch 73/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4698 - accuracy: 0.8209
Epoch 74/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4585 - accuracy: 0.8266
Epoch 75/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4731 - accuracy: 0.8215
Epoch 76/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4725 - accuracy: 0.8221
Epoch 77/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4548 - accuracy: 0.8258
Epoch 78/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4605 - accuracy: 0.8256
Epoch 79/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4696 - accuracy: 0.8196
Epoch 80/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4654 - accuracy: 0.8211
Epoch 81/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4703 - accuracy: 0.8213
Epoch 82/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.8208
Epoch 83/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4617 - accuracy: 0.8253
Epoch 84/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.8164
Epoch 85/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.8254
Epoch 86/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4619 - accuracy: 0.8237
Epoch 87/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4657 - accuracy: 0.8237
Epoch 88/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4650 - accuracy: 0.8204
Epoch 89/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4615 - accuracy: 0.8221
Epoch 90/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4652 - accuracy: 0.8228
Epoch 91/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4832 - accuracy: 0.8176
Epoch 92/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4586 - accuracy: 0.8215
Epoch 93/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4592 - accuracy: 0.8211
Epoch 94/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4682 - accuracy: 0.8221
Epoch 95/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4620 - accuracy: 0.8266
Epoch 96/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4635 - accuracy: 0.8202
Epoch 97/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4636 - accuracy: 0.8261
Epoch 98/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4669 - accuracy: 0.8171
Epoch 99/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.8199
Epoch 100/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4617 - accuracy: 0.8239

In [ ]:
model_2012.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2012.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
181/181 [==============================] - 3s 4ms/step - loss: 0.4670 - accuracy: 0.8202
Epoch 2/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.8206
Epoch 3/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.8209
Epoch 4/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4590 - accuracy: 0.8227
Epoch 5/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4567 - accuracy: 0.8273
Epoch 6/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4659 - accuracy: 0.8242
Epoch 7/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4672 - accuracy: 0.8215
Epoch 8/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4622 - accuracy: 0.8223
Epoch 9/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4592 - accuracy: 0.8230
Epoch 10/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4594 - accuracy: 0.8256
Epoch 11/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.8225
Epoch 12/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4550 - accuracy: 0.8225
Epoch 13/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4671 - accuracy: 0.8227
Epoch 14/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4663 - accuracy: 0.8206
Epoch 15/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4528 - accuracy: 0.8298
Epoch 16/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4686 - accuracy: 0.8211
Epoch 17/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.8234
Epoch 18/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4641 - accuracy: 0.8199
Epoch 19/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4584 - accuracy: 0.8260
Epoch 20/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4655 - accuracy: 0.8251
Epoch 21/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4581 - accuracy: 0.8223
Epoch 22/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4568 - accuracy: 0.8251
Epoch 23/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4634 - accuracy: 0.8246
Epoch 24/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4632 - accuracy: 0.8234
Epoch 25/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4514 - accuracy: 0.8296
Epoch 26/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4520 - accuracy: 0.8279
Epoch 27/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4597 - accuracy: 0.8280
Epoch 28/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.8228
Epoch 29/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4556 - accuracy: 0.8230
Epoch 30/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4581 - accuracy: 0.8263
Epoch 31/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.8266
Epoch 32/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4556 - accuracy: 0.8260
Epoch 33/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4589 - accuracy: 0.8268
Epoch 34/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4637 - accuracy: 0.8199
Epoch 35/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4645 - accuracy: 0.8272
Epoch 36/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4599 - accuracy: 0.8285
Epoch 37/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4604 - accuracy: 0.8183
Epoch 38/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4552 - accuracy: 0.8253
Epoch 39/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4569 - accuracy: 0.8242
Epoch 40/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4628 - accuracy: 0.8228
Epoch 41/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4578 - accuracy: 0.8213
Epoch 42/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4627 - accuracy: 0.8206
Epoch 43/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4538 - accuracy: 0.8211
Epoch 44/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4506 - accuracy: 0.8272
Epoch 45/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.8256
Epoch 46/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4623 - accuracy: 0.8234
Epoch 47/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4526 - accuracy: 0.8261
Epoch 48/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4630 - accuracy: 0.8220
Epoch 49/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.8261
Epoch 50/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4633 - accuracy: 0.8197
Epoch 51/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4561 - accuracy: 0.8234
Epoch 52/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4652 - accuracy: 0.8237
Epoch 53/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.8242
Epoch 54/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4548 - accuracy: 0.8275
Epoch 55/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4535 - accuracy: 0.8275
Epoch 56/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4544 - accuracy: 0.8240
Epoch 57/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4517 - accuracy: 0.8215
Epoch 58/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4578 - accuracy: 0.8260
Epoch 59/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4573 - accuracy: 0.8260
Epoch 60/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4651 - accuracy: 0.8239
Epoch 61/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4573 - accuracy: 0.8225
Epoch 62/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4546 - accuracy: 0.8291
Epoch 63/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.8244
Epoch 64/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4613 - accuracy: 0.8284
Epoch 65/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4544 - accuracy: 0.8268
Epoch 66/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4570 - accuracy: 0.8249
Epoch 67/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4614 - accuracy: 0.8251
Epoch 68/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4568 - accuracy: 0.8277
Epoch 69/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4553 - accuracy: 0.8242
Epoch 70/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4464 - accuracy: 0.8280
Epoch 71/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4598 - accuracy: 0.8287
Epoch 72/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4526 - accuracy: 0.8303
Epoch 73/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4676 - accuracy: 0.8164
Epoch 74/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4725 - accuracy: 0.8208
Epoch 75/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4585 - accuracy: 0.8282
Epoch 76/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4541 - accuracy: 0.8270
Epoch 77/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4440 - accuracy: 0.8296
Epoch 78/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4669 - accuracy: 0.8178
Epoch 79/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4522 - accuracy: 0.8279
Epoch 80/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.8223
Epoch 81/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4468 - accuracy: 0.8266
Epoch 82/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4445 - accuracy: 0.8320
Epoch 83/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4576 - accuracy: 0.8253
Epoch 84/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4564 - accuracy: 0.8294
Epoch 85/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4601 - accuracy: 0.8204
Epoch 86/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4532 - accuracy: 0.8254
Epoch 87/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4549 - accuracy: 0.8213
Epoch 88/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4539 - accuracy: 0.8211
Epoch 89/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4620 - accuracy: 0.8228
Epoch 90/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4593 - accuracy: 0.8284
Epoch 91/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4588 - accuracy: 0.8228
Epoch 92/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4620 - accuracy: 0.8246
Epoch 93/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4597 - accuracy: 0.8266
Epoch 94/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4460 - accuracy: 0.8265
Epoch 95/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4547 - accuracy: 0.8263
Epoch 96/100
181/181 [==============================] - 1s 6ms/step - loss: 0.4611 - accuracy: 0.8230
Epoch 97/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4665 - accuracy: 0.8230
Epoch 98/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4598 - accuracy: 0.8268
Epoch 99/100
181/181 [==============================] - 1s 4ms/step - loss: 0.4583 - accuracy: 0.8298
Epoch 100/100
181/181 [==============================] - 1s 5ms/step - loss: 0.4617 - accuracy: 0.8209

In [ ]:
model_2012.save("/content/drive/MyDrive/FYP/Trained Models/2012.keras")

In [ ]:
model_2012 = tf.keras.models.load_model("/content/drive/MyDrive/FYP/Trained Models/2012.keras")

In [ ]:
predictions = model_2012(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
np.argmax(predictions[0])

0

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.7928052576962988

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.8061578490893322

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2012.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2013

#### Random sampling

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features_2013, labels_2013, test_size=0.2)

In [ ]:
y_train = y_train.astype(int)

In [ ]:
X_train.shape, y_train.shape

((6873, 8), (6873,))

In [ ]:
y_train[:5]

array([ 0, 14,  7,  1,  5])

### Stratified sampling

In [ ]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2013, labels_2013):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2013)

numpy.ndarray

In [ ]:
fold1[0]

array([ 131,  132,  133, ..., 8589, 8590, 8591])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2013[x]
    y_train = labels_2013[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2013[x]))
    y_train = np.vstack((y_train, labels_2013[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2013[x]
    y_test = labels_2013[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2013[x]))
    y_test = np.vstack((y_test, labels_2013[x]))

In [ ]:
# Second iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2013[x]
    y_train = labels_2013[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2013[x]))
    y_train = np.vstack((y_train, labels_2013[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2013[x]
    y_test = labels_2013[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2013[x]))
    y_test = np.vstack((y_test, labels_2013[x]))

In [ ]:
# Third iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2013[x]
    y_train = labels_2013[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2013[x]))
    y_train = np.vstack((y_train, labels_2013[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2013[x]
    y_test = labels_2013[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2013[x]))
    y_test = np.vstack((y_test, labels_2013[x]))

In [ ]:
y_train.shape

(5728, 1)

## Model Training 2013

In [ ]:
model_2013 = Sequential()

In [ ]:
model_2013.add(Dense(units=900, activation="relu"))
model_2013.add(Dropout(0.3))
model_2013.add(Dense(units=700, activation="relu"))
model_2013.add(Dropout(0.3))
model_2013.add(Dense(units=250, activation="relu"))
model_2013.add(Dropout(0.2))
model_2013.add(Dense(units=128, activation="relu"))
model_2013.add(Dropout(0.2))
model_2013.add(Dense(units=64, activation="relu"))
model_2013.add(Dropout(0.2))
model_2013.add(Dense(units=32, activation="relu"))
model_2013.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2013.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2013.fit(X_train, y_train, epochs=200)
except Exception as ex:
  print(ex)

Epoch 1/200
179/179 [==============================] - 5s 6ms/step - loss: 2.3036 - accuracy: 0.2530
Epoch 2/200
179/179 [==============================] - 1s 6ms/step - loss: 1.4992 - accuracy: 0.4633
Epoch 3/200
179/179 [==============================] - 1s 6ms/step - loss: 1.2985 - accuracy: 0.5222
Epoch 4/200
179/179 [==============================] - 1s 6ms/step - loss: 1.1749 - accuracy: 0.5756
Epoch 5/200
179/179 [==============================] - 1s 6ms/step - loss: 1.1052 - accuracy: 0.5965
Epoch 6/200
179/179 [==============================] - 1s 7ms/step - loss: 1.0355 - accuracy: 0.6175
Epoch 7/200
179/179 [==============================] - 1s 8ms/step - loss: 1.0190 - accuracy: 0.6234
Epoch 8/200
179/179 [==============================] - 1s 7ms/step - loss: 0.9684 - accuracy: 0.6517
Epoch 9/200
179/179 [==============================] - 1s 7ms/step - loss: 0.9232 - accuracy: 0.6566
Epoch 10/200
179/179 [==============================] - 1s 6ms/step - loss: 0.9090 - accuracy: 0.6650
Epoch 11/200
179/179 [==============================] - 1s 5ms/step - loss: 0.8939 - accuracy: 0.6662
Epoch 12/200
179/179 [==============================] - 1s 6ms/step - loss: 0.8949 - accuracy: 0.6737
Epoch 13/200
179/179 [==============================] - 1s 5ms/step - loss: 0.8585 - accuracy: 0.6791
Epoch 14/200
179/179 [==============================] - 1s 6ms/step - loss: 0.8615 - accuracy: 0.6775
Epoch 15/200
179/179 [==============================] - 1s 5ms/step - loss: 0.8349 - accuracy: 0.6920
Epoch 16/200
179/179 [==============================] - 1s 6ms/step - loss: 0.8214 - accuracy: 0.6906
Epoch 17/200
179/179 [==============================] - 1s 5ms/step - loss: 0.8447 - accuracy: 0.6805
Epoch 18/200
179/179 [==============================] - 1s 5ms/step - loss: 0.8376 - accuracy: 0.6833
Epoch 19/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7981 - accuracy: 0.7004
Epoch 20/200
179/179 [==============================] - 1s 8ms/step - loss: 0.7963 - accuracy: 0.6990
Epoch 21/200
179/179 [==============================] - 1s 7ms/step - loss: 0.8106 - accuracy: 0.6929
Epoch 22/200
179/179 [==============================] - 1s 8ms/step - loss: 0.7856 - accuracy: 0.7039
Epoch 23/200
179/179 [==============================] - 1s 8ms/step - loss: 0.7816 - accuracy: 0.6987
Epoch 24/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7646 - accuracy: 0.7069
Epoch 25/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7704 - accuracy: 0.7065
Epoch 26/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7654 - accuracy: 0.7137
Epoch 27/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7436 - accuracy: 0.7214
Epoch 28/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7556 - accuracy: 0.7142
Epoch 29/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7555 - accuracy: 0.7128
Epoch 30/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7527 - accuracy: 0.7144
Epoch 31/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7475 - accuracy: 0.7181
Epoch 32/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7499 - accuracy: 0.7219
Epoch 33/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7242 - accuracy: 0.7254
Epoch 34/200
179/179 [==============================] - 1s 8ms/step - loss: 0.7159 - accuracy: 0.7278
Epoch 35/200
179/179 [==============================] - 1s 7ms/step - loss: 0.7314 - accuracy: 0.7250
Epoch 36/200
179/179 [==============================] - 1s 8ms/step - loss: 0.7361 - accuracy: 0.7235
Epoch 37/200
179/179 [==============================] - 1s 7ms/step - loss: 0.7252 - accuracy: 0.7291
Epoch 38/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7140 - accuracy: 0.7322
Epoch 39/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7004 - accuracy: 0.7296
Epoch 40/200
179/179 [==============================] - 1s 5ms/step - loss: 0.7207 - accuracy: 0.7303
Epoch 41/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7026 - accuracy: 0.7311
Epoch 42/200
179/179 [==============================] - 1s 6ms/step - loss: 0.6958 - accuracy: 0.7352
Epoch 43/200
179/179 [==============================] - 1s 6ms/step - loss: 0.6848 - accuracy: 0.7346
Epoch 44/200
179/179 [==============================] - 1s 6ms/step - loss: 0.7132 - accuracy: 0.7284
Epoch 45/200
179/179 [==============================] - 1s 6ms/step - loss: 0.6995 - accuracy: 0.7334
Epoch 46/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6841 - accuracy: 0.7414
Epoch 47/200
179/179 [==============================] - 1s 6ms/step - loss: 0.6887 - accuracy: 0.7374
Epoch 48/200
179/179 [==============================] - 1s 8ms/step - loss: 0.6805 - accuracy: 0.7467
Epoch 49/200
179/179 [==============================] - 1s 8ms/step - loss: 0.6785 - accuracy: 0.7404
Epoch 50/200
179/179 [==============================] - 1s 7ms/step - loss: 0.6811 - accuracy: 0.7380
Epoch 51/200
179/179 [==============================] - 1s 8ms/step - loss: 0.6921 - accuracy: 0.7402
Epoch 52/200
179/179 [==============================] - 1s 6ms/step - loss: 0.6929 - accuracy: 0.7338
Epoch 53/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6811 - accuracy: 0.7413
Epoch 54/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6862 - accuracy: 0.7378
Epoch 55/200
179/179 [==============================] - 1s 6ms/step - loss: 0.6647 - accuracy: 0.7470
Epoch 56/200
179/179 [==============================] - 1s 6ms/step - loss: 0.6665 - accuracy: 0.7477
Epoch 57/200
179/179 [==============================] - 1s 6ms/step - loss: 0.6746 - accuracy: 0.7400
Epoch 58/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6621 - accuracy: 0.7430
Epoch 59/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6663 - accuracy: 0.7449
Epoch 60/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6639 - accuracy: 0.7437
Epoch 61/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6535 - accuracy: 0.7540
Epoch 62/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6827 - accuracy: 0.7367
Epoch 63/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6484 - accuracy: 0.7476
Epoch 64/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6621 - accuracy: 0.7497
Epoch 65/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6593 - accuracy: 0.7407
Epoch 66/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6544 - accuracy: 0.7497
Epoch 67/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6368 - accuracy: 0.7556
Epoch 68/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6528 - accuracy: 0.7500
Epoch 69/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6514 - accuracy: 0.7500
Epoch 70/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6426 - accuracy: 0.7517
Epoch 71/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6303 - accuracy: 0.7610
Epoch 72/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6328 - accuracy: 0.7600
Epoch 73/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6356 - accuracy: 0.7570
Epoch 74/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6331 - accuracy: 0.7551
Epoch 75/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6434 - accuracy: 0.7535
Epoch 76/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6270 - accuracy: 0.7622
Epoch 77/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6212 - accuracy: 0.7573
Epoch 78/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6250 - accuracy: 0.7570
Epoch 79/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6261 - accuracy: 0.7570
Epoch 80/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6476 - accuracy: 0.7481
Epoch 81/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6308 - accuracy: 0.7586
Epoch 82/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6398 - accuracy: 0.7558
Epoch 83/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6122 - accuracy: 0.7570
Epoch 84/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6368 - accuracy: 0.7531
Epoch 85/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6164 - accuracy: 0.7624
Epoch 86/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6269 - accuracy: 0.7577
Epoch 87/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6376 - accuracy: 0.7558
Epoch 88/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6326 - accuracy: 0.7612
Epoch 89/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6234 - accuracy: 0.7593
Epoch 90/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6286 - accuracy: 0.7533
Epoch 91/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6547 - accuracy: 0.7552
Epoch 92/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6145 - accuracy: 0.7626
Epoch 93/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6333 - accuracy: 0.7547
Epoch 94/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6281 - accuracy: 0.7603
Epoch 95/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6245 - accuracy: 0.7573
Epoch 96/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6104 - accuracy: 0.7664
Epoch 97/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6197 - accuracy: 0.7586
Epoch 98/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6180 - accuracy: 0.7624
Epoch 99/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6192 - accuracy: 0.7627
Epoch 100/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5997 - accuracy: 0.7647
Epoch 101/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6297 - accuracy: 0.7493
Epoch 102/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6129 - accuracy: 0.7676
Epoch 103/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6281 - accuracy: 0.7579
Epoch 104/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6230 - accuracy: 0.7596
Epoch 105/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5961 - accuracy: 0.7673
Epoch 106/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6138 - accuracy: 0.7631
Epoch 107/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6005 - accuracy: 0.7669
Epoch 108/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6082 - accuracy: 0.7652
Epoch 109/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6060 - accuracy: 0.7708
Epoch 110/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6020 - accuracy: 0.7666
Epoch 111/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6057 - accuracy: 0.7680
Epoch 112/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6049 - accuracy: 0.7706
Epoch 113/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6132 - accuracy: 0.7678
Epoch 114/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6029 - accuracy: 0.7631
Epoch 115/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5966 - accuracy: 0.7671
Epoch 116/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5854 - accuracy: 0.7715
Epoch 117/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6095 - accuracy: 0.7605
Epoch 118/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6007 - accuracy: 0.7659
Epoch 119/200
179/179 [==============================] - 1s 6ms/step - loss: 0.6145 - accuracy: 0.7633
Epoch 120/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5869 - accuracy: 0.7718
Epoch 121/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5962 - accuracy: 0.7732
Epoch 122/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6050 - accuracy: 0.7650
Epoch 123/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5826 - accuracy: 0.7666
Epoch 124/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5865 - accuracy: 0.7771
Epoch 125/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5846 - accuracy: 0.7776
Epoch 126/200
179/179 [==============================] - 1s 4ms/step - loss: 0.6108 - accuracy: 0.7631
Epoch 127/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5988 - accuracy: 0.7627
Epoch 128/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5849 - accuracy: 0.7715
Epoch 129/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5997 - accuracy: 0.7671
Epoch 130/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5899 - accuracy: 0.7680
Epoch 131/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5865 - accuracy: 0.7706
Epoch 132/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5923 - accuracy: 0.7675
Epoch 133/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5746 - accuracy: 0.7764
Epoch 134/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5877 - accuracy: 0.7741
Epoch 135/200
179/179 [==============================] - 1s 5ms/step - loss: 0.6009 - accuracy: 0.7645
Epoch 136/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5963 - accuracy: 0.7682
Epoch 137/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5794 - accuracy: 0.7718
Epoch 138/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5882 - accuracy: 0.7671
Epoch 139/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5776 - accuracy: 0.7734
Epoch 140/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5783 - accuracy: 0.7762
Epoch 141/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5679 - accuracy: 0.7762
Epoch 142/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5855 - accuracy: 0.7778
Epoch 143/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5832 - accuracy: 0.7732
Epoch 144/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5736 - accuracy: 0.7800
Epoch 145/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5907 - accuracy: 0.7765
Epoch 146/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5819 - accuracy: 0.7715
Epoch 147/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5680 - accuracy: 0.7760
Epoch 148/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5778 - accuracy: 0.7786
Epoch 149/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5897 - accuracy: 0.7730
Epoch 150/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5630 - accuracy: 0.7781
Epoch 151/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5827 - accuracy: 0.7753
Epoch 152/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5804 - accuracy: 0.7774
Epoch 153/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5830 - accuracy: 0.7795
Epoch 154/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5640 - accuracy: 0.7762
Epoch 155/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5746 - accuracy: 0.7758
Epoch 156/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5719 - accuracy: 0.7793
Epoch 157/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5565 - accuracy: 0.7776
Epoch 158/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5947 - accuracy: 0.7697
Epoch 159/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5699 - accuracy: 0.7792
Epoch 160/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5733 - accuracy: 0.7762
Epoch 161/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5947 - accuracy: 0.7720
Epoch 162/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5694 - accuracy: 0.7814
Epoch 163/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5520 - accuracy: 0.7825
Epoch 164/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5583 - accuracy: 0.7828
Epoch 165/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5743 - accuracy: 0.7799
Epoch 166/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5775 - accuracy: 0.7788
Epoch 167/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5504 - accuracy: 0.7744
Epoch 168/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5719 - accuracy: 0.7758
Epoch 169/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5655 - accuracy: 0.7790
Epoch 170/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5674 - accuracy: 0.7781
Epoch 171/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5814 - accuracy: 0.7811
Epoch 172/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5758 - accuracy: 0.7786
Epoch 173/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5616 - accuracy: 0.7779
Epoch 174/200
179/179 [==============================] - 1s 6ms/step - loss: 0.5715 - accuracy: 0.7764
Epoch 175/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5729 - accuracy: 0.7760
Epoch 176/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5680 - accuracy: 0.7748
Epoch 177/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5645 - accuracy: 0.7795
Epoch 178/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5806 - accuracy: 0.7748
Epoch 179/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5826 - accuracy: 0.7730
Epoch 180/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5673 - accuracy: 0.7765
Epoch 181/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5571 - accuracy: 0.7826
Epoch 182/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5476 - accuracy: 0.7874
Epoch 183/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5624 - accuracy: 0.7839
Epoch 184/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5618 - accuracy: 0.7778
Epoch 185/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5548 - accuracy: 0.7776
Epoch 186/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5647 - accuracy: 0.7807
Epoch 187/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5654 - accuracy: 0.7732
Epoch 188/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5491 - accuracy: 0.7785
Epoch 189/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5474 - accuracy: 0.7806
Epoch 190/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5611 - accuracy: 0.7741
Epoch 191/200
179/179 [==============================] - 1s 5ms/step - loss: 0.5685 - accuracy: 0.7816
Epoch 192/200
179/179 [==============================] - 1s 6ms/step - loss: 0.5636 - accuracy: 0.7800
Epoch 193/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5681 - accuracy: 0.7779
Epoch 194/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5529 - accuracy: 0.7812
Epoch 195/200
179/179 [==============================] - 1s 4ms/step - loss: 0.5533 - accuracy: 0.7856
Epoch 196/200

In [ ]:
model_2013.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2013.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
179/179 [==============================] - 3s 4ms/step - loss: 0.5254 - accuracy: 0.7907
Epoch 2/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4975 - accuracy: 0.8038
Epoch 3/100
179/179 [==============================] - 1s 5ms/step - loss: 0.5095 - accuracy: 0.8024
Epoch 4/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4943 - accuracy: 0.8010
Epoch 5/100
179/179 [==============================] - 1s 6ms/step - loss: 0.5017 - accuracy: 0.7992
Epoch 6/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4991 - accuracy: 0.7989
Epoch 7/100
179/179 [==============================] - 1s 4ms/step - loss: 0.5155 - accuracy: 0.8005
Epoch 8/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4936 - accuracy: 0.8038
Epoch 9/100
179/179 [==============================] - 1s 4ms/step - loss: 0.5030 - accuracy: 0.8001
Epoch 10/100
179/179 [==============================] - 1s 4ms/step - loss: 0.5042 - accuracy: 0.8036
Epoch 11/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4876 - accuracy: 0.8010
Epoch 12/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4908 - accuracy: 0.8012
Epoch 13/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4837 - accuracy: 0.8022
Epoch 14/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4919 - accuracy: 0.8057
Epoch 15/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4903 - accuracy: 0.8053
Epoch 16/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4947 - accuracy: 0.8045
Epoch 17/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4868 - accuracy: 0.8081
Epoch 18/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.8029
Epoch 19/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.8052
Epoch 20/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4825 - accuracy: 0.8078
Epoch 21/100
179/179 [==============================] - 1s 6ms/step - loss: 0.4923 - accuracy: 0.8053
Epoch 22/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4834 - accuracy: 0.8064
Epoch 23/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4862 - accuracy: 0.8071
Epoch 24/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4705 - accuracy: 0.8099
Epoch 25/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.8052
Epoch 26/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4856 - accuracy: 0.8059
Epoch 27/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4845 - accuracy: 0.8090
Epoch 28/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.8019
Epoch 29/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4782 - accuracy: 0.8095
Epoch 30/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.8045
Epoch 31/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4906 - accuracy: 0.8071
Epoch 32/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4923 - accuracy: 0.7991
Epoch 33/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4812 - accuracy: 0.8092
Epoch 34/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.8097
Epoch 35/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4744 - accuracy: 0.8048
Epoch 36/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4807 - accuracy: 0.8071
Epoch 37/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.8172
Epoch 38/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4801 - accuracy: 0.8104
Epoch 39/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4830 - accuracy: 0.8102
Epoch 40/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4807 - accuracy: 0.8076
Epoch 41/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4710 - accuracy: 0.8162
Epoch 42/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4747 - accuracy: 0.8078
Epoch 43/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4727 - accuracy: 0.8123
Epoch 44/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4628 - accuracy: 0.8165
Epoch 45/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4660 - accuracy: 0.8141
Epoch 46/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.8109
Epoch 47/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4697 - accuracy: 0.8074
Epoch 48/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4608 - accuracy: 0.8148
Epoch 49/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.8074
Epoch 50/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4720 - accuracy: 0.8106
Epoch 51/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.8066
Epoch 52/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4797 - accuracy: 0.8059
Epoch 53/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4696 - accuracy: 0.8087
Epoch 54/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4712 - accuracy: 0.8141
Epoch 55/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4680 - accuracy: 0.8073
Epoch 56/100
179/179 [==============================] - 1s 6ms/step - loss: 0.4566 - accuracy: 0.8169
Epoch 57/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4671 - accuracy: 0.8094
Epoch 58/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4644 - accuracy: 0.8135
Epoch 59/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4743 - accuracy: 0.8046
Epoch 60/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.8148
Epoch 61/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4739 - accuracy: 0.8073
Epoch 62/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4653 - accuracy: 0.8149
Epoch 63/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.8090
Epoch 64/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4674 - accuracy: 0.8142
Epoch 65/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4596 - accuracy: 0.8132
Epoch 66/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4642 - accuracy: 0.8160
Epoch 67/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4756 - accuracy: 0.8024
Epoch 68/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4521 - accuracy: 0.8191
Epoch 69/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4664 - accuracy: 0.8055
Epoch 70/100
179/179 [==============================] - 1s 4ms/step - loss: 0.5118 - accuracy: 0.8071
Epoch 71/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4767 - accuracy: 0.8123
Epoch 72/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4704 - accuracy: 0.8059
Epoch 73/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4645 - accuracy: 0.8128
Epoch 74/100
179/179 [==============================] - 1s 6ms/step - loss: 0.4671 - accuracy: 0.8118
Epoch 75/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4547 - accuracy: 0.8141
Epoch 76/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4547 - accuracy: 0.8165
Epoch 77/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4634 - accuracy: 0.8127
Epoch 78/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4646 - accuracy: 0.8130
Epoch 79/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4625 - accuracy: 0.8120
Epoch 80/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4567 - accuracy: 0.8130
Epoch 81/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4741 - accuracy: 0.8090
Epoch 82/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4679 - accuracy: 0.8106
Epoch 83/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4699 - accuracy: 0.8104
Epoch 84/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4709 - accuracy: 0.8088
Epoch 85/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4678 - accuracy: 0.8115
Epoch 86/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4555 - accuracy: 0.8183
Epoch 87/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4465 - accuracy: 0.8167
Epoch 88/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4772 - accuracy: 0.8115
Epoch 89/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4708 - accuracy: 0.8085
Epoch 90/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4605 - accuracy: 0.8176
Epoch 91/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4692 - accuracy: 0.8116
Epoch 92/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4615 - accuracy: 0.8135
Epoch 93/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4428 - accuracy: 0.8179
Epoch 94/100
179/179 [==============================] - 1s 6ms/step - loss: 0.4536 - accuracy: 0.8183
Epoch 95/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4643 - accuracy: 0.8169
Epoch 96/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4609 - accuracy: 0.8130
Epoch 97/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4418 - accuracy: 0.8198
Epoch 98/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4618 - accuracy: 0.8148
Epoch 99/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4654 - accuracy: 0.8088
Epoch 100/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4508 - accuracy: 0.8190

In [ ]:
model_2013.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2013.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
179/179 [==============================] - 3s 4ms/step - loss: 0.4286 - accuracy: 0.8256
Epoch 2/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4177 - accuracy: 0.8291
Epoch 3/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4144 - accuracy: 0.8301
Epoch 4/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4143 - accuracy: 0.8280
Epoch 5/100
179/179 [==============================] - 1s 6ms/step - loss: 0.4164 - accuracy: 0.8294
Epoch 6/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4170 - accuracy: 0.8315
Epoch 7/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4188 - accuracy: 0.8287
Epoch 8/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4145 - accuracy: 0.8277
Epoch 9/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4220 - accuracy: 0.8265
Epoch 10/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4156 - accuracy: 0.8298
Epoch 11/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4086 - accuracy: 0.8308
Epoch 12/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4130 - accuracy: 0.8319
Epoch 13/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4048 - accuracy: 0.8355
Epoch 14/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4072 - accuracy: 0.8298
Epoch 15/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4144 - accuracy: 0.8293
Epoch 16/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4039 - accuracy: 0.8357
Epoch 17/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4011 - accuracy: 0.8334
Epoch 18/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4098 - accuracy: 0.8317
Epoch 19/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4164 - accuracy: 0.8296
Epoch 20/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4072 - accuracy: 0.8298
Epoch 21/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4070 - accuracy: 0.8408
Epoch 22/100
179/179 [==============================] - 1s 6ms/step - loss: 0.4011 - accuracy: 0.8345
Epoch 23/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4008 - accuracy: 0.8333
Epoch 24/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4071 - accuracy: 0.8338
Epoch 25/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4091 - accuracy: 0.8348
Epoch 26/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4054 - accuracy: 0.8348
Epoch 27/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4018 - accuracy: 0.8338
Epoch 28/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4090 - accuracy: 0.8328
Epoch 29/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4051 - accuracy: 0.8314
Epoch 30/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4061 - accuracy: 0.8348
Epoch 31/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4042 - accuracy: 0.8413
Epoch 32/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4014 - accuracy: 0.8352
Epoch 33/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3985 - accuracy: 0.8347
Epoch 34/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3975 - accuracy: 0.8340
Epoch 35/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3939 - accuracy: 0.8399
Epoch 36/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3995 - accuracy: 0.8385
Epoch 37/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4008 - accuracy: 0.8387
Epoch 38/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3938 - accuracy: 0.8389
Epoch 39/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4058 - accuracy: 0.8359
Epoch 40/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3971 - accuracy: 0.8359
Epoch 41/100
179/179 [==============================] - 1s 5ms/step - loss: 0.4070 - accuracy: 0.8326
Epoch 42/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3912 - accuracy: 0.8418
Epoch 43/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3997 - accuracy: 0.8399
Epoch 44/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4023 - accuracy: 0.8350
Epoch 45/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3988 - accuracy: 0.8340
Epoch 46/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4056 - accuracy: 0.8375
Epoch 47/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4016 - accuracy: 0.8305
Epoch 48/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3981 - accuracy: 0.8350
Epoch 49/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4050 - accuracy: 0.8347
Epoch 50/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4035 - accuracy: 0.8378
Epoch 51/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3962 - accuracy: 0.8368
Epoch 52/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4043 - accuracy: 0.8385
Epoch 53/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3948 - accuracy: 0.8378
Epoch 54/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3941 - accuracy: 0.8396
Epoch 55/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3932 - accuracy: 0.8427
Epoch 56/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3856 - accuracy: 0.8382
Epoch 57/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3953 - accuracy: 0.8396
Epoch 58/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3973 - accuracy: 0.8375
Epoch 59/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3977 - accuracy: 0.8362
Epoch 60/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4017 - accuracy: 0.8378
Epoch 61/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3947 - accuracy: 0.8403
Epoch 62/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3928 - accuracy: 0.8340
Epoch 63/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3901 - accuracy: 0.8420
Epoch 64/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4000 - accuracy: 0.8376
Epoch 65/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3961 - accuracy: 0.8411
Epoch 66/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3932 - accuracy: 0.8392
Epoch 67/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3995 - accuracy: 0.8359
Epoch 68/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3983 - accuracy: 0.8376
Epoch 69/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4031 - accuracy: 0.8364
Epoch 70/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4078 - accuracy: 0.8373
Epoch 71/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3954 - accuracy: 0.8382
Epoch 72/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3897 - accuracy: 0.8410
Epoch 73/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4059 - accuracy: 0.8347
Epoch 74/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3928 - accuracy: 0.8382
Epoch 75/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3898 - accuracy: 0.8396
Epoch 76/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3889 - accuracy: 0.8387
Epoch 77/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3900 - accuracy: 0.8343
Epoch 78/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3874 - accuracy: 0.8392
Epoch 79/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3976 - accuracy: 0.8362
Epoch 80/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3942 - accuracy: 0.8389
Epoch 81/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3916 - accuracy: 0.8408
Epoch 82/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3961 - accuracy: 0.8364
Epoch 83/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3936 - accuracy: 0.8444
Epoch 84/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3873 - accuracy: 0.8394
Epoch 85/100
179/179 [==============================] - 1s 4ms/step - loss: 0.4000 - accuracy: 0.8345
Epoch 86/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3897 - accuracy: 0.8387
Epoch 87/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3800 - accuracy: 0.8443
Epoch 88/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3892 - accuracy: 0.8434
Epoch 89/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3850 - accuracy: 0.8382
Epoch 90/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3910 - accuracy: 0.8411
Epoch 91/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3803 - accuracy: 0.8450
Epoch 92/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3835 - accuracy: 0.8465
Epoch 93/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3913 - accuracy: 0.8362
Epoch 94/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3895 - accuracy: 0.8382
Epoch 95/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3806 - accuracy: 0.8415
Epoch 96/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3835 - accuracy: 0.8460
Epoch 97/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3848 - accuracy: 0.8462
Epoch 98/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3946 - accuracy: 0.8399
Epoch 99/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3906 - accuracy: 0.8399
Epoch 100/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3874 - accuracy: 0.8401

In [ ]:
model_2013.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2013.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
179/179 [==============================] - 3s 4ms/step - loss: 0.3912 - accuracy: 0.8389
Epoch 2/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3933 - accuracy: 0.8413
Epoch 3/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3835 - accuracy: 0.8390
Epoch 4/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3942 - accuracy: 0.8380
Epoch 5/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3797 - accuracy: 0.8451
Epoch 6/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3847 - accuracy: 0.8422
Epoch 7/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3837 - accuracy: 0.8460
Epoch 8/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3761 - accuracy: 0.8476
Epoch 9/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3850 - accuracy: 0.8431
Epoch 10/100
179/179 [==============================] - 1s 6ms/step - loss: 0.3827 - accuracy: 0.8425
Epoch 11/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3847 - accuracy: 0.8406
Epoch 12/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3811 - accuracy: 0.8389
Epoch 13/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3769 - accuracy: 0.8465
Epoch 14/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3839 - accuracy: 0.8420
Epoch 15/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3721 - accuracy: 0.8479
Epoch 16/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3768 - accuracy: 0.8434
Epoch 17/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3760 - accuracy: 0.8464
Epoch 18/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3891 - accuracy: 0.8396
Epoch 19/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3797 - accuracy: 0.8432
Epoch 20/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3879 - accuracy: 0.8378
Epoch 21/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3843 - accuracy: 0.8462
Epoch 22/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3763 - accuracy: 0.8464
Epoch 23/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3766 - accuracy: 0.8483
Epoch 24/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3810 - accuracy: 0.8427
Epoch 25/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3810 - accuracy: 0.8401
Epoch 26/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3747 - accuracy: 0.8450
Epoch 27/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3883 - accuracy: 0.8399
Epoch 28/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3782 - accuracy: 0.8471
Epoch 29/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3817 - accuracy: 0.8436
Epoch 30/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3709 - accuracy: 0.8418
Epoch 31/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3810 - accuracy: 0.8422
Epoch 32/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3813 - accuracy: 0.8450
Epoch 33/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3841 - accuracy: 0.8453
Epoch 34/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3773 - accuracy: 0.8425
Epoch 35/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3838 - accuracy: 0.8396
Epoch 36/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3778 - accuracy: 0.8467
Epoch 37/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3818 - accuracy: 0.8411
Epoch 38/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3833 - accuracy: 0.8390
Epoch 39/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3805 - accuracy: 0.8436
Epoch 40/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3748 - accuracy: 0.8431
Epoch 41/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3825 - accuracy: 0.8453
Epoch 42/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3820 - accuracy: 0.8411
Epoch 43/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3842 - accuracy: 0.8448
Epoch 44/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3831 - accuracy: 0.8429
Epoch 45/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3782 - accuracy: 0.8448
Epoch 46/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3799 - accuracy: 0.8431
Epoch 47/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3824 - accuracy: 0.8438
Epoch 48/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3750 - accuracy: 0.8432
Epoch 49/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3797 - accuracy: 0.8455
Epoch 50/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3714 - accuracy: 0.8453
Epoch 51/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3780 - accuracy: 0.8436
Epoch 52/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3817 - accuracy: 0.8411
Epoch 53/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3792 - accuracy: 0.8417
Epoch 54/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3774 - accuracy: 0.8460
Epoch 55/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3810 - accuracy: 0.8438
Epoch 56/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3791 - accuracy: 0.8383
Epoch 57/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3779 - accuracy: 0.8444
Epoch 58/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3813 - accuracy: 0.8460
Epoch 59/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3805 - accuracy: 0.8390
Epoch 60/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3727 - accuracy: 0.8481
Epoch 61/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3738 - accuracy: 0.8469
Epoch 62/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3787 - accuracy: 0.8438
Epoch 63/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3707 - accuracy: 0.8446
Epoch 64/100
179/179 [==============================] - 1s 6ms/step - loss: 0.3761 - accuracy: 0.8436
Epoch 65/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3747 - accuracy: 0.8439
Epoch 66/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3899 - accuracy: 0.8429
Epoch 67/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3780 - accuracy: 0.8371
Epoch 68/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3822 - accuracy: 0.8404
Epoch 69/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3757 - accuracy: 0.8404
Epoch 70/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3821 - accuracy: 0.8460
Epoch 71/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3863 - accuracy: 0.8453
Epoch 72/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3767 - accuracy: 0.8471
Epoch 73/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3761 - accuracy: 0.8439
Epoch 74/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3776 - accuracy: 0.8422
Epoch 75/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3734 - accuracy: 0.8465
Epoch 76/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3739 - accuracy: 0.8443
Epoch 77/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3792 - accuracy: 0.8413
Epoch 78/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3807 - accuracy: 0.8490
Epoch 79/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3727 - accuracy: 0.8453
Epoch 80/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3810 - accuracy: 0.8438
Epoch 81/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3759 - accuracy: 0.8451
Epoch 82/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3729 - accuracy: 0.8479
Epoch 83/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3721 - accuracy: 0.8458
Epoch 84/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3763 - accuracy: 0.8441
Epoch 85/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3741 - accuracy: 0.8465
Epoch 86/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3769 - accuracy: 0.8438
Epoch 87/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3775 - accuracy: 0.8441
Epoch 88/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3811 - accuracy: 0.8417
Epoch 89/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3792 - accuracy: 0.8432
Epoch 90/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3789 - accuracy: 0.8432
Epoch 91/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3679 - accuracy: 0.8439
Epoch 92/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3778 - accuracy: 0.8424
Epoch 93/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3823 - accuracy: 0.8438
Epoch 94/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3732 - accuracy: 0.8427
Epoch 95/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3744 - accuracy: 0.8424
Epoch 96/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3750 - accuracy: 0.8478
Epoch 97/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3825 - accuracy: 0.8455
Epoch 98/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3777 - accuracy: 0.8441
Epoch 99/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3801 - accuracy: 0.8401
Epoch 100/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3753 - accuracy: 0.8460

In [ ]:
model_2013.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2013.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
179/179 [==============================] - 3s 4ms/step - loss: 0.3708 - accuracy: 0.8483
Epoch 2/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3688 - accuracy: 0.8495
Epoch 3/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3736 - accuracy: 0.8465
Epoch 4/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3649 - accuracy: 0.8469
Epoch 5/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3792 - accuracy: 0.8472
Epoch 6/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3714 - accuracy: 0.8450
Epoch 7/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3688 - accuracy: 0.8492
Epoch 8/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3747 - accuracy: 0.8464
Epoch 9/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3647 - accuracy: 0.8469
Epoch 10/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3720 - accuracy: 0.8479
Epoch 11/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3715 - accuracy: 0.8441
Epoch 12/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3696 - accuracy: 0.8474
Epoch 13/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3699 - accuracy: 0.8497
Epoch 14/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3709 - accuracy: 0.8438
Epoch 15/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3764 - accuracy: 0.8443
Epoch 16/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3762 - accuracy: 0.8472
Epoch 17/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3667 - accuracy: 0.8485
Epoch 18/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3678 - accuracy: 0.8471
Epoch 19/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3680 - accuracy: 0.8509
Epoch 20/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3750 - accuracy: 0.8439
Epoch 21/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3717 - accuracy: 0.8469
Epoch 22/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3859 - accuracy: 0.8458
Epoch 23/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3697 - accuracy: 0.8444
Epoch 24/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3600 - accuracy: 0.8541
Epoch 25/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3714 - accuracy: 0.8438
Epoch 26/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3699 - accuracy: 0.8434
Epoch 27/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3691 - accuracy: 0.8471
Epoch 28/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3725 - accuracy: 0.8488
Epoch 29/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3808 - accuracy: 0.8418
Epoch 30/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3695 - accuracy: 0.8495
Epoch 31/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3796 - accuracy: 0.8472
Epoch 32/100
179/179 [==============================] - 1s 6ms/step - loss: 0.3703 - accuracy: 0.8523
Epoch 33/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3761 - accuracy: 0.8450
Epoch 34/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3714 - accuracy: 0.8495
Epoch 35/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3725 - accuracy: 0.8516
Epoch 36/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3746 - accuracy: 0.8434
Epoch 37/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3610 - accuracy: 0.8518
Epoch 38/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3647 - accuracy: 0.8497
Epoch 39/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3719 - accuracy: 0.8509
Epoch 40/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3687 - accuracy: 0.8462
Epoch 41/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3772 - accuracy: 0.8436
Epoch 42/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3709 - accuracy: 0.8432
Epoch 43/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3691 - accuracy: 0.8527
Epoch 44/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3691 - accuracy: 0.8448
Epoch 45/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3729 - accuracy: 0.8465
Epoch 46/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3779 - accuracy: 0.8472
Epoch 47/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3779 - accuracy: 0.8464
Epoch 48/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3642 - accuracy: 0.8443
Epoch 49/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3739 - accuracy: 0.8500
Epoch 50/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3748 - accuracy: 0.8418
Epoch 51/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3670 - accuracy: 0.8467
Epoch 52/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3741 - accuracy: 0.8478
Epoch 53/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3656 - accuracy: 0.8506
Epoch 54/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3697 - accuracy: 0.8513
Epoch 55/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3636 - accuracy: 0.8500
Epoch 56/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3759 - accuracy: 0.8485
Epoch 57/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3625 - accuracy: 0.8490
Epoch 58/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3805 - accuracy: 0.8460
Epoch 59/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3767 - accuracy: 0.8469
Epoch 60/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3729 - accuracy: 0.8460
Epoch 61/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3652 - accuracy: 0.8481
Epoch 62/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3677 - accuracy: 0.8471
Epoch 63/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3667 - accuracy: 0.8497
Epoch 64/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3748 - accuracy: 0.8469
Epoch 65/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3709 - accuracy: 0.8478
Epoch 66/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3689 - accuracy: 0.8472
Epoch 67/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3735 - accuracy: 0.8453
Epoch 68/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3726 - accuracy: 0.8490
Epoch 69/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3678 - accuracy: 0.8474
Epoch 70/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3717 - accuracy: 0.8422
Epoch 71/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3750 - accuracy: 0.8429
Epoch 72/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3791 - accuracy: 0.8431
Epoch 73/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3664 - accuracy: 0.8479
Epoch 74/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3767 - accuracy: 0.8469
Epoch 75/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3753 - accuracy: 0.8458
Epoch 76/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3653 - accuracy: 0.8518
Epoch 77/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3769 - accuracy: 0.8460
Epoch 78/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3733 - accuracy: 0.8485
Epoch 79/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3712 - accuracy: 0.8460
Epoch 80/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3741 - accuracy: 0.8448
Epoch 81/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3677 - accuracy: 0.8453
Epoch 82/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3748 - accuracy: 0.8469
Epoch 83/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3744 - accuracy: 0.8485
Epoch 84/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3661 - accuracy: 0.8513
Epoch 85/100
179/179 [==============================] - 1s 5ms/step - loss: 0.3591 - accuracy: 0.8504
Epoch 86/100
179/179 [==============================] - 1s 6ms/step - loss: 0.3761 - accuracy: 0.8408
Epoch 87/100
179/179 [==============================] - 1s 6ms/step - loss: 0.3682 - accuracy: 0.8511
Epoch 88/100
179/179 [==============================] - 1s 6ms/step - loss: 0.3782 - accuracy: 0.8453
Epoch 89/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3649 - accuracy: 0.8485
Epoch 90/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3714 - accuracy: 0.8465
Epoch 91/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3689 - accuracy: 0.8513
Epoch 92/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3591 - accuracy: 0.8532
Epoch 93/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3697 - accuracy: 0.8457
Epoch 94/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3613 - accuracy: 0.8495
Epoch 95/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3644 - accuracy: 0.8476
Epoch 96/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3743 - accuracy: 0.8460
Epoch 97/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3675 - accuracy: 0.8481
Epoch 98/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3686 - accuracy: 0.8436
Epoch 99/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3857 - accuracy: 0.8441
Epoch 100/100
179/179 [==============================] - 1s 4ms/step - loss: 0.3597 - accuracy: 0.8509

In [ ]:
model_2013.save("/content/drive/MyDrive/FYP/Trained Models/2013.keras")

In [ ]:
accuracies = []

In [ ]:
X_test.shape

(2864, 8)

In [ ]:
predictions = model_2013(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.7636173184357542

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.7985689505637468

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2013.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2014

#### Random sampling

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features_2014, labels_2014, test_size=0.2)

In [ ]:
y_train = y_train.astype(int)

In [ ]:
X_train.shape, y_train.shape

((5569, 8), (5569,))

In [ ]:
y_train[:5]

array([ 8, 13,  5,  7,  3])

### Stratified sampling

In [ ]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2014, labels_2014):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2014)

numpy.ndarray

In [ ]:
fold1[0]

array([ 105,  106,  107, ..., 6959, 6960, 6961])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2014[x]
    y_train = labels_2014[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2014[x]))
    y_train = np.vstack((y_train, labels_2014[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2014[x]
    y_test = labels_2014[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2014[x]))
    y_test = np.vstack((y_test, labels_2014[x]))

In [ ]:
# Second iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2014[x]
    y_train = labels_2014[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2014[x]))
    y_train = np.vstack((y_train, labels_2014[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2014[x]
    y_test = labels_2014[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2014[x]))
    y_test = np.vstack((y_test, labels_2014[x]))

In [ ]:
# Third iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2014[x]
    y_train = labels_2014[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2014[x]))
    y_train = np.vstack((y_train, labels_2014[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2014[x]
    y_test = labels_2014[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2014[x]))
    y_test = np.vstack((y_test, labels_2014[x]))

In [ ]:
y_train.shape

(4641, 1)

## Model Training 2014

In [ ]:
early_stopping_callback = tf.keras.callbacks.EarlyStopping(
    monitor="loss",
    min_delta=0.001,
    patience=3,
    verbose=1,
    mode="min",
    baseline=None,
    restore_best_weights=True,
    start_from_epoch=0,
)

In [ ]:
model_2014 = Sequential()

In [ ]:
model_2014.add(Dense(units=520, activation="relu"))
model_2014.add(Dropout(0.5))
model_2014.add(Dense(units=250, activation="relu"))
model_2014.add(Dropout(0.3))
model_2014.add(Dense(units=128, activation="relu"))
model_2014.add(Dropout(0.3))
model_2014.add(Dense(units=64, activation="relu"))
model_2014.add(Dropout(0.3))
model_2014.add(Dense(units=45, activation="relu"))
model_2014.add(Dropout(0.2))
model_2014.add(Dense(units=28, activation="relu"))
model_2014.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2014.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
try:
  model_2014.fit(X_train, y_train, epochs=200)
except Exception as ex:
  print(ex)

Epoch 1/200
146/146 [==============================] - 3s 5ms/step - loss: 2.6926 - accuracy: 0.1487
Epoch 2/200
146/146 [==============================] - 1s 4ms/step - loss: 2.1648 - accuracy: 0.2549
Epoch 3/200
146/146 [==============================] - 1s 4ms/step - loss: 1.8373 - accuracy: 0.3422
Epoch 4/200
146/146 [==============================] - 1s 4ms/step - loss: 1.6267 - accuracy: 0.4092
Epoch 5/200
146/146 [==============================] - 1s 4ms/step - loss: 1.5095 - accuracy: 0.4445
Epoch 6/200
146/146 [==============================] - 1s 4ms/step - loss: 1.4587 - accuracy: 0.4562
Epoch 7/200
146/146 [==============================] - 1s 4ms/step - loss: 1.3522 - accuracy: 0.4943
Epoch 8/200
146/146 [==============================] - 1s 4ms/step - loss: 1.3037 - accuracy: 0.5109
Epoch 9/200
146/146 [==============================] - 1s 5ms/step - loss: 1.2886 - accuracy: 0.5279
Epoch 10/200
146/146 [==============================] - 1s 6ms/step - loss: 1.2496 - accuracy: 0.5342
Epoch 11/200
146/146 [==============================] - 1s 6ms/step - loss: 1.2169 - accuracy: 0.5385
Epoch 12/200
146/146 [==============================] - 1s 6ms/step - loss: 1.2059 - accuracy: 0.5566
Epoch 13/200
146/146 [==============================] - 1s 6ms/step - loss: 1.1695 - accuracy: 0.5602
Epoch 14/200
146/146 [==============================] - 1s 6ms/step - loss: 1.1632 - accuracy: 0.5566
Epoch 15/200
146/146 [==============================] - 1s 5ms/step - loss: 1.1377 - accuracy: 0.5695
Epoch 16/200
146/146 [==============================] - 1s 4ms/step - loss: 1.1141 - accuracy: 0.5772
Epoch 17/200
146/146 [==============================] - 1s 4ms/step - loss: 1.1003 - accuracy: 0.5869
Epoch 18/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0986 - accuracy: 0.5813
Epoch 19/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0827 - accuracy: 0.5908
Epoch 20/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0810 - accuracy: 0.5906
Epoch 21/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0551 - accuracy: 0.6066
Epoch 22/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0628 - accuracy: 0.6087
Epoch 23/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0450 - accuracy: 0.6126
Epoch 24/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0443 - accuracy: 0.6113
Epoch 25/200
146/146 [==============================] - 1s 5ms/step - loss: 1.0305 - accuracy: 0.6147
Epoch 26/200
146/146 [==============================] - 1s 5ms/step - loss: 1.0090 - accuracy: 0.6197
Epoch 27/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0028 - accuracy: 0.6300
Epoch 28/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0043 - accuracy: 0.6292
Epoch 29/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9738 - accuracy: 0.6341
Epoch 30/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0122 - accuracy: 0.6234
Epoch 31/200
146/146 [==============================] - 1s 6ms/step - loss: 1.0065 - accuracy: 0.6272
Epoch 32/200
146/146 [==============================] - 1s 6ms/step - loss: 0.9662 - accuracy: 0.6451
Epoch 33/200
146/146 [==============================] - 1s 6ms/step - loss: 0.9694 - accuracy: 0.6309
Epoch 34/200
146/146 [==============================] - 1s 6ms/step - loss: 0.9775 - accuracy: 0.6365
Epoch 35/200
146/146 [==============================] - 1s 6ms/step - loss: 0.9943 - accuracy: 0.6208
Epoch 36/200
146/146 [==============================] - 1s 6ms/step - loss: 0.9575 - accuracy: 0.6423
Epoch 37/200
146/146 [==============================] - 1s 4ms/step - loss: 1.0056 - accuracy: 0.6315
Epoch 38/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9840 - accuracy: 0.6374
Epoch 39/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9522 - accuracy: 0.6490
Epoch 40/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9441 - accuracy: 0.6580
Epoch 41/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9301 - accuracy: 0.6423
Epoch 42/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9106 - accuracy: 0.6619
Epoch 43/200
146/146 [==============================] - 1s 5ms/step - loss: 0.9593 - accuracy: 0.6458
Epoch 44/200
146/146 [==============================] - 1s 5ms/step - loss: 0.9141 - accuracy: 0.6680
Epoch 45/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9141 - accuracy: 0.6496
Epoch 46/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9370 - accuracy: 0.6557
Epoch 47/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9093 - accuracy: 0.6673
Epoch 48/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9356 - accuracy: 0.6572
Epoch 49/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8965 - accuracy: 0.6658
Epoch 50/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9102 - accuracy: 0.6701
Epoch 51/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9169 - accuracy: 0.6630
Epoch 52/200
146/146 [==============================] - 1s 5ms/step - loss: 0.9281 - accuracy: 0.6604
Epoch 53/200
146/146 [==============================] - 1s 6ms/step - loss: 0.9105 - accuracy: 0.6699
Epoch 54/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8917 - accuracy: 0.6693
Epoch 55/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8767 - accuracy: 0.6761
Epoch 56/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8886 - accuracy: 0.6716
Epoch 57/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8681 - accuracy: 0.6805
Epoch 58/200
146/146 [==============================] - 1s 5ms/step - loss: 0.9005 - accuracy: 0.6624
Epoch 59/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8836 - accuracy: 0.6727
Epoch 60/200
146/146 [==============================] - 1s 4ms/step - loss: 0.9058 - accuracy: 0.6639
Epoch 61/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8884 - accuracy: 0.6684
Epoch 62/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8688 - accuracy: 0.6811
Epoch 63/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8712 - accuracy: 0.6753
Epoch 64/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8607 - accuracy: 0.6830
Epoch 65/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8605 - accuracy: 0.6792
Epoch 66/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8965 - accuracy: 0.6673
Epoch 67/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8679 - accuracy: 0.6789
Epoch 68/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8658 - accuracy: 0.6798
Epoch 69/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8523 - accuracy: 0.6899
Epoch 70/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8652 - accuracy: 0.6779
Epoch 71/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8700 - accuracy: 0.6839
Epoch 72/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8814 - accuracy: 0.6774
Epoch 73/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8814 - accuracy: 0.6826
Epoch 74/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8565 - accuracy: 0.6796
Epoch 75/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8634 - accuracy: 0.6757
Epoch 76/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8501 - accuracy: 0.6858
Epoch 77/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8470 - accuracy: 0.6955
Epoch 78/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8319 - accuracy: 0.6889
Epoch 79/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8417 - accuracy: 0.6889
Epoch 80/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8478 - accuracy: 0.6824
Epoch 81/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8309 - accuracy: 0.6891
Epoch 82/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8816 - accuracy: 0.6800
Epoch 83/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8278 - accuracy: 0.6891
Epoch 84/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8262 - accuracy: 0.6942
Epoch 85/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8381 - accuracy: 0.6983
Epoch 86/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8502 - accuracy: 0.6815
Epoch 87/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8182 - accuracy: 0.7001
Epoch 88/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8356 - accuracy: 0.6964
Epoch 89/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8132 - accuracy: 0.7018
Epoch 90/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8207 - accuracy: 0.6958
Epoch 91/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8301 - accuracy: 0.6904
Epoch 92/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8231 - accuracy: 0.6998
Epoch 93/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8321 - accuracy: 0.6876
Epoch 94/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8207 - accuracy: 0.6899
Epoch 95/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8131 - accuracy: 0.7020
Epoch 96/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8004 - accuracy: 0.7033
Epoch 97/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8134 - accuracy: 0.7007
Epoch 98/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8117 - accuracy: 0.6996
Epoch 99/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8136 - accuracy: 0.7031
Epoch 100/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8185 - accuracy: 0.6975
Epoch 101/200
146/146 [==============================] - 1s 5ms/step - loss: 0.7943 - accuracy: 0.7070
Epoch 102/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8287 - accuracy: 0.6921
Epoch 103/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8138 - accuracy: 0.6932
Epoch 104/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7914 - accuracy: 0.7087
Epoch 105/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8221 - accuracy: 0.6983
Epoch 106/200
146/146 [==============================] - 1s 5ms/step - loss: 0.8359 - accuracy: 0.6925
Epoch 107/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8123 - accuracy: 0.6986
Epoch 108/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7839 - accuracy: 0.7117
Epoch 109/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8175 - accuracy: 0.7042
Epoch 110/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8279 - accuracy: 0.6936
Epoch 111/200
146/146 [==============================] - 1s 4ms/step - loss: 0.8108 - accuracy: 0.6986
Epoch 112/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7966 - accuracy: 0.7078
Epoch 113/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7982 - accuracy: 0.7007
Epoch 114/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7888 - accuracy: 0.7022
Epoch 115/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7870 - accuracy: 0.7078
Epoch 116/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7851 - accuracy: 0.7091
Epoch 117/200
146/146 [==============================] - 1s 5ms/step - loss: 0.7751 - accuracy: 0.7083
Epoch 118/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7861 - accuracy: 0.7089
Epoch 119/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8090 - accuracy: 0.7039
Epoch 120/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8132 - accuracy: 0.7074
Epoch 121/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7660 - accuracy: 0.7197
Epoch 122/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7951 - accuracy: 0.7089
Epoch 123/200
146/146 [==============================] - 1s 5ms/step - loss: 0.7923 - accuracy: 0.7115
Epoch 124/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7914 - accuracy: 0.7095
Epoch 125/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7864 - accuracy: 0.7117
Epoch 126/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7992 - accuracy: 0.7070
Epoch 127/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7893 - accuracy: 0.7100
Epoch 128/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7862 - accuracy: 0.7100
Epoch 129/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7841 - accuracy: 0.7072
Epoch 130/200
146/146 [==============================] - 1s 5ms/step - loss: 0.7685 - accuracy: 0.7115
Epoch 131/200
146/146 [==============================] - 1s 5ms/step - loss: 0.7884 - accuracy: 0.7130
Epoch 132/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7838 - accuracy: 0.7070
Epoch 133/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7859 - accuracy: 0.7121
Epoch 134/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7898 - accuracy: 0.7022
Epoch 135/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7813 - accuracy: 0.7162
Epoch 136/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7919 - accuracy: 0.7052
Epoch 137/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7819 - accuracy: 0.7102
Epoch 138/200
146/146 [==============================] - 1s 5ms/step - loss: 0.7696 - accuracy: 0.7186
Epoch 139/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7762 - accuracy: 0.7115
Epoch 140/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7878 - accuracy: 0.7059
Epoch 141/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7633 - accuracy: 0.7102
Epoch 142/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7706 - accuracy: 0.7177
Epoch 143/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7700 - accuracy: 0.7132
Epoch 144/200
146/146 [==============================] - 1s 5ms/step - loss: 0.7731 - accuracy: 0.7171
Epoch 145/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7873 - accuracy: 0.7128
Epoch 146/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7858 - accuracy: 0.7072
Epoch 147/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7746 - accuracy: 0.7136
Epoch 148/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7588 - accuracy: 0.7128
Epoch 149/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7809 - accuracy: 0.7149
Epoch 150/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7681 - accuracy: 0.7205
Epoch 151/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7657 - accuracy: 0.7207
Epoch 152/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7616 - accuracy: 0.7223
Epoch 153/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7772 - accuracy: 0.7074
Epoch 154/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7827 - accuracy: 0.7143
Epoch 155/200
146/146 [==============================] - 1s 5ms/step - loss: 0.7569 - accuracy: 0.7115
Epoch 156/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7601 - accuracy: 0.7175
Epoch 157/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7661 - accuracy: 0.7158
Epoch 158/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7732 - accuracy: 0.7074
Epoch 159/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7630 - accuracy: 0.7177
Epoch 160/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7675 - accuracy: 0.7151
Epoch 161/200
146/146 [==============================] - 1s 6ms/step - loss: 0.8005 - accuracy: 0.7042
Epoch 162/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7690 - accuracy: 0.7123
Epoch 163/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7793 - accuracy: 0.7031
Epoch 164/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7782 - accuracy: 0.7173
Epoch 165/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7426 - accuracy: 0.7279
Epoch 166/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7965 - accuracy: 0.7037
Epoch 167/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7971 - accuracy: 0.7057
Epoch 168/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7723 - accuracy: 0.7139
Epoch 169/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7540 - accuracy: 0.7192
Epoch 170/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7851 - accuracy: 0.7136
Epoch 171/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7757 - accuracy: 0.7145
Epoch 172/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7550 - accuracy: 0.7218
Epoch 173/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7371 - accuracy: 0.7285
Epoch 174/200
146/146 [==============================] - 1s 5ms/step - loss: 0.7476 - accuracy: 0.7218
Epoch 175/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7415 - accuracy: 0.7259
Epoch 176/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7489 - accuracy: 0.7197
Epoch 177/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7568 - accuracy: 0.7207
Epoch 178/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7559 - accuracy: 0.7190
Epoch 179/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7349 - accuracy: 0.7253
Epoch 180/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7445 - accuracy: 0.7266
Epoch 181/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7695 - accuracy: 0.7203
Epoch 182/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7279 - accuracy: 0.7274
Epoch 183/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7521 - accuracy: 0.7147
Epoch 184/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7467 - accuracy: 0.7231
Epoch 185/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7514 - accuracy: 0.7238
Epoch 186/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7174 - accuracy: 0.7350
Epoch 187/200
146/146 [==============================] - 1s 6ms/step - loss: 0.7612 - accuracy: 0.7177
Epoch 188/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7495 - accuracy: 0.7248
Epoch 189/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7401 - accuracy: 0.7201
Epoch 190/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7452 - accuracy: 0.7167
Epoch 191/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7348 - accuracy: 0.7313
Epoch 192/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7579 - accuracy: 0.7173
Epoch 193/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7575 - accuracy: 0.7173
Epoch 194/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7586 - accuracy: 0.7126
Epoch 195/200
146/146 [==============================] - 1s 4ms/step - loss: 0.7469 - accuracy: 0.7179
Epoch 196/200

In [ ]:
model_2014.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2014.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
146/146 [==============================] - 4s 6ms/step - loss: 0.7056 - accuracy: 0.7384
Epoch 2/100
146/146 [==============================] - 1s 5ms/step - loss: 0.7044 - accuracy: 0.7388
Epoch 3/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6982 - accuracy: 0.7410
Epoch 4/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6957 - accuracy: 0.7442
Epoch 5/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6881 - accuracy: 0.7401
Epoch 6/100
146/146 [==============================] - 1s 4ms/step - loss: 0.7031 - accuracy: 0.7320
Epoch 7/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6715 - accuracy: 0.7496
Epoch 8/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6833 - accuracy: 0.7464
Epoch 9/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6818 - accuracy: 0.7490
Epoch 10/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6759 - accuracy: 0.7466
Epoch 11/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6843 - accuracy: 0.7423
Epoch 12/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6816 - accuracy: 0.7468
Epoch 13/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6856 - accuracy: 0.7520
Epoch 14/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6708 - accuracy: 0.7462
Epoch 15/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6726 - accuracy: 0.7449
Epoch 16/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6784 - accuracy: 0.7436
Epoch 17/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6796 - accuracy: 0.7434
Epoch 18/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6785 - accuracy: 0.7490
Epoch 19/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6838 - accuracy: 0.7380
Epoch 20/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6811 - accuracy: 0.7485
Epoch 21/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6827 - accuracy: 0.7479
Epoch 22/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6659 - accuracy: 0.7503
Epoch 23/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6668 - accuracy: 0.7466
Epoch 24/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6615 - accuracy: 0.7539
Epoch 25/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6658 - accuracy: 0.7507
Epoch 26/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6579 - accuracy: 0.7544
Epoch 27/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6709 - accuracy: 0.7455
Epoch 28/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6809 - accuracy: 0.7449
Epoch 29/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6768 - accuracy: 0.7464
Epoch 30/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6560 - accuracy: 0.7554
Epoch 31/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6644 - accuracy: 0.7533
Epoch 32/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6592 - accuracy: 0.7524
Epoch 33/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6507 - accuracy: 0.7533
Epoch 34/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6785 - accuracy: 0.7455
Epoch 35/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6738 - accuracy: 0.7498
Epoch 36/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6611 - accuracy: 0.7546
Epoch 37/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6673 - accuracy: 0.7546
Epoch 38/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6639 - accuracy: 0.7462
Epoch 39/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6650 - accuracy: 0.7520
Epoch 40/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6650 - accuracy: 0.7561
Epoch 41/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6764 - accuracy: 0.7511
Epoch 42/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6769 - accuracy: 0.7481
Epoch 43/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6547 - accuracy: 0.7546
Epoch 44/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6638 - accuracy: 0.7479
Epoch 45/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6589 - accuracy: 0.7498
Epoch 46/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6559 - accuracy: 0.7541
Epoch 47/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6490 - accuracy: 0.7544
Epoch 48/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6557 - accuracy: 0.7541
Epoch 49/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6692 - accuracy: 0.7498
Epoch 50/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6607 - accuracy: 0.7457
Epoch 51/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6593 - accuracy: 0.7535
Epoch 52/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6648 - accuracy: 0.7492
Epoch 53/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6633 - accuracy: 0.7569
Epoch 54/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6609 - accuracy: 0.7479
Epoch 55/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6625 - accuracy: 0.7559
Epoch 56/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6464 - accuracy: 0.7595
Epoch 57/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6823 - accuracy: 0.7410
Epoch 58/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6515 - accuracy: 0.7565
Epoch 59/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6498 - accuracy: 0.7563
Epoch 60/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6517 - accuracy: 0.7524
Epoch 61/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6651 - accuracy: 0.7522
Epoch 62/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6594 - accuracy: 0.7513
Epoch 63/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6658 - accuracy: 0.7537
Epoch 64/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6562 - accuracy: 0.7550
Epoch 65/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6435 - accuracy: 0.7651
Epoch 66/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6433 - accuracy: 0.7563
Epoch 67/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6674 - accuracy: 0.7552
Epoch 68/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6661 - accuracy: 0.7539
Epoch 69/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6494 - accuracy: 0.7604
Epoch 70/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6563 - accuracy: 0.7535
Epoch 71/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6467 - accuracy: 0.7593
Epoch 72/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6705 - accuracy: 0.7479
Epoch 73/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6550 - accuracy: 0.7524
Epoch 74/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6548 - accuracy: 0.7544
Epoch 75/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6617 - accuracy: 0.7507
Epoch 76/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6430 - accuracy: 0.7548
Epoch 77/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6409 - accuracy: 0.7606
Epoch 78/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6480 - accuracy: 0.7600
Epoch 79/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6425 - accuracy: 0.7576
Epoch 80/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6463 - accuracy: 0.7623
Epoch 81/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6650 - accuracy: 0.7572
Epoch 82/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6254 - accuracy: 0.7610
Epoch 83/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6411 - accuracy: 0.7636
Epoch 84/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6428 - accuracy: 0.7660
Epoch 85/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6506 - accuracy: 0.7578
Epoch 86/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6444 - accuracy: 0.7541
Epoch 87/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6645 - accuracy: 0.7561
Epoch 88/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6585 - accuracy: 0.7520
Epoch 89/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6457 - accuracy: 0.7576
Epoch 90/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6475 - accuracy: 0.7576
Epoch 91/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6461 - accuracy: 0.7531
Epoch 92/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6510 - accuracy: 0.7511
Epoch 93/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6555 - accuracy: 0.7569
Epoch 94/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6463 - accuracy: 0.7585
Epoch 95/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6474 - accuracy: 0.7576
Epoch 96/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6418 - accuracy: 0.7589
Epoch 97/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6500 - accuracy: 0.7561
Epoch 98/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6362 - accuracy: 0.7643
Epoch 99/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6611 - accuracy: 0.7550
Epoch 100/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6491 - accuracy: 0.7587

In [ ]:
model_2014.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2014.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
146/146 [==============================] - 3s 5ms/step - loss: 0.6331 - accuracy: 0.7610
Epoch 2/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6176 - accuracy: 0.7673
Epoch 3/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6110 - accuracy: 0.7735
Epoch 4/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6044 - accuracy: 0.7636
Epoch 5/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6127 - accuracy: 0.7716
Epoch 6/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6180 - accuracy: 0.7677
Epoch 7/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6185 - accuracy: 0.7692
Epoch 8/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6277 - accuracy: 0.7626
Epoch 9/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6070 - accuracy: 0.7697
Epoch 10/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6049 - accuracy: 0.7729
Epoch 11/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5985 - accuracy: 0.7783
Epoch 12/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5993 - accuracy: 0.7729
Epoch 13/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6082 - accuracy: 0.7720
Epoch 14/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6018 - accuracy: 0.7712
Epoch 15/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6129 - accuracy: 0.7656
Epoch 16/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6125 - accuracy: 0.7742
Epoch 17/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6162 - accuracy: 0.7727
Epoch 18/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5993 - accuracy: 0.7718
Epoch 19/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5892 - accuracy: 0.7819
Epoch 20/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5870 - accuracy: 0.7789
Epoch 21/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6054 - accuracy: 0.7692
Epoch 22/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5965 - accuracy: 0.7701
Epoch 23/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5995 - accuracy: 0.7759
Epoch 24/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6010 - accuracy: 0.7697
Epoch 25/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6043 - accuracy: 0.7692
Epoch 26/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5943 - accuracy: 0.7759
Epoch 27/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6063 - accuracy: 0.7692
Epoch 28/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6012 - accuracy: 0.7785
Epoch 29/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5938 - accuracy: 0.7783
Epoch 30/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5832 - accuracy: 0.7742
Epoch 31/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5991 - accuracy: 0.7686
Epoch 32/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5970 - accuracy: 0.7716
Epoch 33/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5947 - accuracy: 0.7742
Epoch 34/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5990 - accuracy: 0.7774
Epoch 35/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5965 - accuracy: 0.7718
Epoch 36/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5925 - accuracy: 0.7781
Epoch 37/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5867 - accuracy: 0.7725
Epoch 38/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5832 - accuracy: 0.7766
Epoch 39/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5852 - accuracy: 0.7757
Epoch 40/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5881 - accuracy: 0.7839
Epoch 41/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5841 - accuracy: 0.7811
Epoch 42/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5893 - accuracy: 0.7785
Epoch 43/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5956 - accuracy: 0.7759
Epoch 44/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5896 - accuracy: 0.7705
Epoch 45/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5891 - accuracy: 0.7828
Epoch 46/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6030 - accuracy: 0.7671
Epoch 47/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5842 - accuracy: 0.7841
Epoch 48/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5968 - accuracy: 0.7781
Epoch 49/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5972 - accuracy: 0.7746
Epoch 50/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5984 - accuracy: 0.7744
Epoch 51/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5870 - accuracy: 0.7802
Epoch 52/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5835 - accuracy: 0.7770
Epoch 53/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5834 - accuracy: 0.7809
Epoch 54/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5859 - accuracy: 0.7785
Epoch 55/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5917 - accuracy: 0.7757
Epoch 56/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5922 - accuracy: 0.7742
Epoch 57/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5863 - accuracy: 0.7746
Epoch 58/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5830 - accuracy: 0.7787
Epoch 59/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5971 - accuracy: 0.7774
Epoch 60/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5875 - accuracy: 0.7791
Epoch 61/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5817 - accuracy: 0.7798
Epoch 62/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5819 - accuracy: 0.7725
Epoch 63/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5791 - accuracy: 0.7742
Epoch 64/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5785 - accuracy: 0.7832
Epoch 65/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5876 - accuracy: 0.7763
Epoch 66/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5746 - accuracy: 0.7768
Epoch 67/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5805 - accuracy: 0.7746
Epoch 68/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5829 - accuracy: 0.7817
Epoch 69/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5833 - accuracy: 0.7796
Epoch 70/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5708 - accuracy: 0.7830
Epoch 71/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5756 - accuracy: 0.7809
Epoch 72/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6017 - accuracy: 0.7750
Epoch 73/100
146/146 [==============================] - 1s 5ms/step - loss: 0.6110 - accuracy: 0.7753
Epoch 74/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5894 - accuracy: 0.7757
Epoch 75/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5731 - accuracy: 0.7854
Epoch 76/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5763 - accuracy: 0.7822
Epoch 77/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5812 - accuracy: 0.7766
Epoch 78/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5879 - accuracy: 0.7802
Epoch 79/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5867 - accuracy: 0.7731
Epoch 80/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5962 - accuracy: 0.7731
Epoch 81/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5936 - accuracy: 0.7761
Epoch 82/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5895 - accuracy: 0.7778
Epoch 83/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5960 - accuracy: 0.7766
Epoch 84/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5852 - accuracy: 0.7811
Epoch 85/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5866 - accuracy: 0.7809
Epoch 86/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5963 - accuracy: 0.7761
Epoch 87/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5835 - accuracy: 0.7809
Epoch 88/100
146/146 [==============================] - 1s 4ms/step - loss: 0.6023 - accuracy: 0.7746
Epoch 89/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5766 - accuracy: 0.7856
Epoch 90/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5775 - accuracy: 0.7847
Epoch 91/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5841 - accuracy: 0.7770
Epoch 92/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5942 - accuracy: 0.7757
Epoch 93/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5683 - accuracy: 0.7807
Epoch 94/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5781 - accuracy: 0.7824
Epoch 95/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5774 - accuracy: 0.7798
Epoch 96/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5686 - accuracy: 0.7871
Epoch 97/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5893 - accuracy: 0.7718
Epoch 98/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5776 - accuracy: 0.7847
Epoch 99/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5813 - accuracy: 0.7757
Epoch 100/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5843 - accuracy: 0.7837

In [ ]:
model_2014.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2014.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
146/146 [==============================] - 2s 4ms/step - loss: 0.5823 - accuracy: 0.7809
Epoch 2/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5908 - accuracy: 0.7725
Epoch 3/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5924 - accuracy: 0.7772
Epoch 4/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5882 - accuracy: 0.7796
Epoch 5/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5781 - accuracy: 0.7830
Epoch 6/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5814 - accuracy: 0.7802
Epoch 7/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5601 - accuracy: 0.7878
Epoch 8/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5830 - accuracy: 0.7804
Epoch 9/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5773 - accuracy: 0.7832
Epoch 10/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5757 - accuracy: 0.7794
Epoch 11/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5780 - accuracy: 0.7748
Epoch 12/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5716 - accuracy: 0.7828
Epoch 13/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5781 - accuracy: 0.7813
Epoch 14/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5741 - accuracy: 0.7824
Epoch 15/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5742 - accuracy: 0.7891
Epoch 16/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5810 - accuracy: 0.7800
Epoch 17/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5746 - accuracy: 0.7832
Epoch 18/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5828 - accuracy: 0.7753
Epoch 19/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5673 - accuracy: 0.7852
Epoch 20/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5670 - accuracy: 0.7819
Epoch 21/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5715 - accuracy: 0.7841
Epoch 22/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5798 - accuracy: 0.7863
Epoch 23/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5653 - accuracy: 0.7878
Epoch 24/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5760 - accuracy: 0.7858
Epoch 25/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5707 - accuracy: 0.7826
Epoch 26/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5943 - accuracy: 0.7757
Epoch 27/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5614 - accuracy: 0.7899
Epoch 28/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5915 - accuracy: 0.7772
Epoch 29/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5670 - accuracy: 0.7802
Epoch 30/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5587 - accuracy: 0.7895
Epoch 31/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5794 - accuracy: 0.7837
Epoch 32/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5619 - accuracy: 0.7856
Epoch 33/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5781 - accuracy: 0.7813
Epoch 34/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5739 - accuracy: 0.7817
Epoch 35/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5792 - accuracy: 0.7742
Epoch 36/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5723 - accuracy: 0.7794
Epoch 37/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5759 - accuracy: 0.7899
Epoch 38/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5688 - accuracy: 0.7856
Epoch 39/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5724 - accuracy: 0.7837
Epoch 40/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5771 - accuracy: 0.7753
Epoch 41/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5799 - accuracy: 0.7813
Epoch 42/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5739 - accuracy: 0.7830
Epoch 43/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5745 - accuracy: 0.7828
Epoch 44/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5754 - accuracy: 0.7817
Epoch 45/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5778 - accuracy: 0.7802
Epoch 46/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5703 - accuracy: 0.7796
Epoch 47/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5700 - accuracy: 0.7841
Epoch 48/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5710 - accuracy: 0.7895
Epoch 49/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5691 - accuracy: 0.7804
Epoch 50/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5752 - accuracy: 0.7794
Epoch 51/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5623 - accuracy: 0.7880
Epoch 52/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5620 - accuracy: 0.7886
Epoch 53/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5660 - accuracy: 0.7863
Epoch 54/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5743 - accuracy: 0.7863
Epoch 55/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5722 - accuracy: 0.7860
Epoch 56/100
146/146 [==============================] - 1s 6ms/step - loss: 0.6229 - accuracy: 0.7843
Epoch 57/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5763 - accuracy: 0.7789
Epoch 58/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5772 - accuracy: 0.7875
Epoch 59/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5741 - accuracy: 0.7828
Epoch 60/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5804 - accuracy: 0.7796
Epoch 61/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5757 - accuracy: 0.7852
Epoch 62/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5660 - accuracy: 0.7888
Epoch 63/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5652 - accuracy: 0.7843
Epoch 64/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5752 - accuracy: 0.7763
Epoch 65/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5755 - accuracy: 0.7785
Epoch 66/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5631 - accuracy: 0.7895
Epoch 67/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5770 - accuracy: 0.7830
Epoch 68/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5697 - accuracy: 0.7811
Epoch 69/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5683 - accuracy: 0.7817
Epoch 70/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5845 - accuracy: 0.7815
Epoch 71/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5709 - accuracy: 0.7830
Epoch 72/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5759 - accuracy: 0.7839
Epoch 73/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5699 - accuracy: 0.7832
Epoch 74/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5712 - accuracy: 0.7787
Epoch 75/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5551 - accuracy: 0.7884
Epoch 76/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5771 - accuracy: 0.7791
Epoch 77/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5625 - accuracy: 0.7863
Epoch 78/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5783 - accuracy: 0.7794
Epoch 79/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5786 - accuracy: 0.7828
Epoch 80/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5896 - accuracy: 0.7785
Epoch 81/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5737 - accuracy: 0.7878
Epoch 82/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5646 - accuracy: 0.7847
Epoch 83/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5656 - accuracy: 0.7897
Epoch 84/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5647 - accuracy: 0.7804
Epoch 85/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5708 - accuracy: 0.7908
Epoch 86/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5767 - accuracy: 0.7785
Epoch 87/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5617 - accuracy: 0.7886
Epoch 88/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5733 - accuracy: 0.7884
Epoch 89/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5681 - accuracy: 0.7824
Epoch 90/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5696 - accuracy: 0.7811
Epoch 91/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5603 - accuracy: 0.7880
Epoch 92/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5715 - accuracy: 0.7865
Epoch 93/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5657 - accuracy: 0.7903
Epoch 94/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5742 - accuracy: 0.7845
Epoch 95/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5683 - accuracy: 0.7871
Epoch 96/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5641 - accuracy: 0.7882
Epoch 97/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5597 - accuracy: 0.7897
Epoch 98/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5516 - accuracy: 0.7921
Epoch 99/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5700 - accuracy: 0.7897
Epoch 100/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5631 - accuracy: 0.7910

In [ ]:
model_2014.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2014.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
146/146 [==============================] - 2s 4ms/step - loss: 0.5626 - accuracy: 0.7850
Epoch 2/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5705 - accuracy: 0.7867
Epoch 3/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5777 - accuracy: 0.7910
Epoch 4/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5660 - accuracy: 0.7908
Epoch 5/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5721 - accuracy: 0.7819
Epoch 6/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5754 - accuracy: 0.7807
Epoch 7/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5714 - accuracy: 0.7826
Epoch 8/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5650 - accuracy: 0.7901
Epoch 9/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5713 - accuracy: 0.7839
Epoch 10/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5725 - accuracy: 0.7886
Epoch 11/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5644 - accuracy: 0.7852
Epoch 12/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5600 - accuracy: 0.7839
Epoch 13/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5544 - accuracy: 0.7899
Epoch 14/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5648 - accuracy: 0.7936
Epoch 15/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5608 - accuracy: 0.7863
Epoch 16/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5663 - accuracy: 0.7875
Epoch 17/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5650 - accuracy: 0.7931
Epoch 18/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5692 - accuracy: 0.7807
Epoch 19/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5642 - accuracy: 0.7942
Epoch 20/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5702 - accuracy: 0.7850
Epoch 21/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5622 - accuracy: 0.7869
Epoch 22/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5686 - accuracy: 0.7863
Epoch 23/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5648 - accuracy: 0.7802
Epoch 24/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5627 - accuracy: 0.7828
Epoch 25/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5722 - accuracy: 0.7886
Epoch 26/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5765 - accuracy: 0.7884
Epoch 27/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5604 - accuracy: 0.7886
Epoch 28/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5733 - accuracy: 0.7824
Epoch 29/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5572 - accuracy: 0.7869
Epoch 30/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5682 - accuracy: 0.7826
Epoch 31/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5513 - accuracy: 0.7957
Epoch 32/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5683 - accuracy: 0.7895
Epoch 33/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5620 - accuracy: 0.7880
Epoch 34/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5602 - accuracy: 0.7959
Epoch 35/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5677 - accuracy: 0.7843
Epoch 36/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5698 - accuracy: 0.7809
Epoch 37/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5736 - accuracy: 0.7860
Epoch 38/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5625 - accuracy: 0.7875
Epoch 39/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5634 - accuracy: 0.7828
Epoch 40/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5569 - accuracy: 0.7936
Epoch 41/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5694 - accuracy: 0.7794
Epoch 42/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5615 - accuracy: 0.7869
Epoch 43/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5702 - accuracy: 0.7888
Epoch 44/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5744 - accuracy: 0.7871
Epoch 45/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5636 - accuracy: 0.7867
Epoch 46/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5654 - accuracy: 0.7850
Epoch 47/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5577 - accuracy: 0.7897
Epoch 48/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5708 - accuracy: 0.7826
Epoch 49/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5759 - accuracy: 0.7822
Epoch 50/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5632 - accuracy: 0.7897
Epoch 51/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5681 - accuracy: 0.7841
Epoch 52/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5714 - accuracy: 0.7843
Epoch 53/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5706 - accuracy: 0.7856
Epoch 54/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5610 - accuracy: 0.7850
Epoch 55/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5734 - accuracy: 0.7774
Epoch 56/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5750 - accuracy: 0.7828
Epoch 57/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5748 - accuracy: 0.7841
Epoch 58/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5650 - accuracy: 0.7796
Epoch 59/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5605 - accuracy: 0.7912
Epoch 60/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5638 - accuracy: 0.7828
Epoch 61/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5759 - accuracy: 0.7919
Epoch 62/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5661 - accuracy: 0.7908
Epoch 63/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5715 - accuracy: 0.7819
Epoch 64/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5652 - accuracy: 0.7863
Epoch 65/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5639 - accuracy: 0.7878
Epoch 66/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5666 - accuracy: 0.7867
Epoch 67/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5683 - accuracy: 0.7850
Epoch 68/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5626 - accuracy: 0.7895
Epoch 69/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5657 - accuracy: 0.7832
Epoch 70/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5555 - accuracy: 0.7906
Epoch 71/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5560 - accuracy: 0.7813
Epoch 72/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5703 - accuracy: 0.7843
Epoch 73/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5697 - accuracy: 0.7882
Epoch 74/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5707 - accuracy: 0.7841
Epoch 75/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5708 - accuracy: 0.7791
Epoch 76/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5706 - accuracy: 0.7947
Epoch 77/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5708 - accuracy: 0.7873
Epoch 78/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5645 - accuracy: 0.7959
Epoch 79/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5596 - accuracy: 0.7882
Epoch 80/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5512 - accuracy: 0.7888
Epoch 81/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5612 - accuracy: 0.7934
Epoch 82/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5570 - accuracy: 0.7880
Epoch 83/100
146/146 [==============================] - 1s 6ms/step - loss: 0.5670 - accuracy: 0.7882
Epoch 84/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5589 - accuracy: 0.7891
Epoch 85/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5555 - accuracy: 0.7929
Epoch 86/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5630 - accuracy: 0.7888
Epoch 87/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5630 - accuracy: 0.7839
Epoch 88/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5666 - accuracy: 0.7863
Epoch 89/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5662 - accuracy: 0.7830
Epoch 90/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5672 - accuracy: 0.7863
Epoch 91/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5828 - accuracy: 0.7753
Epoch 92/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5538 - accuracy: 0.7912
Epoch 93/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5612 - accuracy: 0.7882
Epoch 94/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5720 - accuracy: 0.7811
Epoch 95/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5612 - accuracy: 0.7940
Epoch 96/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5670 - accuracy: 0.7882
Epoch 97/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5802 - accuracy: 0.7809
Epoch 98/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5651 - accuracy: 0.7871
Epoch 99/100
146/146 [==============================] - 1s 4ms/step - loss: 0.5763 - accuracy: 0.7794
Epoch 100/100
146/146 [==============================] - 1s 5ms/step - loss: 0.5588 - accuracy: 0.7962

In [ ]:
model_2014.save("/content/drive/MyDrive/FYP/Trained Models/2014.keras")

In [ ]:
accuracies = []

In [ ]:
predictions = model_2014(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
# print(accuracy) This accuracy was without dropout regularization

In [ ]:
loss, accuracy = model_2014.evaluate(X_test, y_test)

73/73 [==============================] - 0s 3ms/step - loss: 0.5998 - accuracy: 0.7841

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

XGBoost Accuracy: 0.7879444926279271

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2014.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.

## Splitting the data into training and testing sets 2015

#### Random sampling

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features_2015, labels_2015, test_size=0.2)

In [ ]:
y_train = y_train.astype(int)

In [ ]:
X_train.shape, y_train.shape

((382, 8), (382,))

In [ ]:
y_train[:5]

array([18, 12,  5, 14, 16])

### Stratified sampling

In [ ]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=3)

In [ ]:
i = 0
for x, y in kf.split(features_2015, labels_2015):
  if i == 0:
    fold1 = x, y
    i += 1
  if i == 1:
    fold2 = x, y
    i += 1
  if i == 2:
    fold3 = x, y
    i += 1

In [ ]:
type(features_2015)

numpy.ndarray

In [ ]:
fold1[0]

array([ 19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
        32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 136,
       137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
       150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
       163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
       185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197,
       198, 199, 200, 201, 202, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 314, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342,
       343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355,
       356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 368, 369, 379,
       380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392,
       393, 394, 395, 396, 397, 419, 420, 421, 422, 423, 424, 425, 426,
       427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439,
       440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452,
       453, 454, 455, 456, 457, 458, 459, 460, 461, 468, 469, 470, 471,
       472, 473, 474, 475, 476, 477])

In [ ]:
# First iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold1[0]:
  if i == 0:
    X_train = features_2015[x]
    y_train = labels_2015[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2015[x]))
    y_train = np.vstack((y_train, labels_2015[x]))
# Testing set of fold 1:
i = 0
for x in fold1[1]:
  if i == 0:
    X_test = features_2015[x]
    y_test = labels_2015[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2015[x]))
    y_test = np.vstack((y_test, labels_2015[x]))

In [ ]:
# Second iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold2[0]:
  if i == 0:
    X_train = features_2015[x]
    y_train = labels_2015[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2015[x]))
    y_train = np.vstack((y_train, labels_2015[x]))
# Testing set of fold 1:
i = 0
for x in fold2[1]:
  if i == 0:
    X_test = features_2015[x]
    y_test = labels_2015[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2015[x]))
    y_test = np.vstack((y_test, labels_2015[x]))

In [ ]:
# Third iteration of Stratified KFold
# Training set of fold 1:
i = 0
for x in fold3[0]:
  if i == 0:
    X_train = features_2015[x]
    y_train = labels_2015[x]
    i += 1
  else:
    X_train = np.vstack((X_train, features_2015[x]))
    y_train = np.vstack((y_train, labels_2015[x]))
# Testing set of fold 1:
i = 0
for x in fold3[1]:
  if i == 0:
    X_test = features_2015[x]
    y_test = labels_2015[x]
    i += 1
  else:
    X_test = np.vstack((X_test, features_2015[x]))
    y_test = np.vstack((y_test, labels_2015[x]))

In [ ]:
y_train.shape

(318, 1)

## Model Training 2015

In [ ]:
model_2015 = Sequential()

In [ ]:
model_2015.add(Dense(units=520, activation="relu"))
model_2015.add(Dropout(0.5))
model_2015.add(Dense(units=250, activation="relu"))
model_2015.add(Dropout(0.3))
model_2015.add(Dense(units=128, activation="relu"))
model_2015.add(Dropout(0.3))
model_2015.add(Dense(units=64, activation="relu"))
model_2015.add(Dropout(0.3))
model_2015.add(Dense(units=45, activation="relu"))
model_2015.add(Dropout(0.2))
model_2015.add(Dense(units=28, activation="relu"))
model_2015.add(Dense(units=20, activation="softmax"))

In [ ]:
model_2015.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
# Learning rate: 0.001
try:
  model_2015.fit(X_train, y_train, epochs=200)
except Exception as ex:
  print(ex)

Epoch 1/200
10/10 [==============================] - 9s 11ms/step - loss: 2.9726 - accuracy: 0.0629
Epoch 2/200
10/10 [==============================] - 0s 10ms/step - loss: 2.8439 - accuracy: 0.1226
Epoch 3/200
10/10 [==============================] - 0s 10ms/step - loss: 2.6555 - accuracy: 0.1069
Epoch 4/200
10/10 [==============================] - 0s 9ms/step - loss: 2.5445 - accuracy: 0.1258
Epoch 5/200
10/10 [==============================] - 0s 9ms/step - loss: 2.3826 - accuracy: 0.1761
Epoch 6/200
10/10 [==============================] - 0s 10ms/step - loss: 2.2999 - accuracy: 0.1761
Epoch 7/200
10/10 [==============================] - 0s 10ms/step - loss: 2.2227 - accuracy: 0.1887
Epoch 8/200
10/10 [==============================] - 0s 11ms/step - loss: 2.1692 - accuracy: 0.2138
Epoch 9/200
10/10 [==============================] - 0s 11ms/step - loss: 2.0572 - accuracy: 0.2579
Epoch 10/200
10/10 [==============================] - 0s 9ms/step - loss: 1.9334 - accuracy: 0.2673
Epoch 11/200
10/10 [==============================] - 0s 8ms/step - loss: 1.8393 - accuracy: 0.3145
Epoch 12/200
10/10 [==============================] - 0s 10ms/step - loss: 1.7617 - accuracy: 0.3428
Epoch 13/200
10/10 [==============================] - 0s 10ms/step - loss: 1.6906 - accuracy: 0.3113
Epoch 14/200
10/10 [==============================] - 0s 9ms/step - loss: 1.6983 - accuracy: 0.3365
Epoch 15/200
10/10 [==============================] - 0s 9ms/step - loss: 1.6585 - accuracy: 0.3365
Epoch 16/200
10/10 [==============================] - 0s 8ms/step - loss: 1.6226 - accuracy: 0.3679
Epoch 17/200
10/10 [==============================] - 0s 10ms/step - loss: 1.5154 - accuracy: 0.3679
Epoch 18/200
10/10 [==============================] - 0s 12ms/step - loss: 1.4791 - accuracy: 0.3805
Epoch 19/200
10/10 [==============================] - 0s 11ms/step - loss: 1.4422 - accuracy: 0.4308
Epoch 20/200
10/10 [==============================] - 0s 11ms/step - loss: 1.4734 - accuracy: 0.4182
Epoch 21/200
10/10 [==============================] - 0s 9ms/step - loss: 1.4121 - accuracy: 0.4119
Epoch 22/200
10/10 [==============================] - 0s 10ms/step - loss: 1.3577 - accuracy: 0.4591
Epoch 23/200
10/10 [==============================] - 0s 11ms/step - loss: 1.3203 - accuracy: 0.4686
Epoch 24/200
10/10 [==============================] - 0s 11ms/step - loss: 1.3533 - accuracy: 0.4528
Epoch 25/200
10/10 [==============================] - 0s 9ms/step - loss: 1.3113 - accuracy: 0.4623
Epoch 26/200
10/10 [==============================] - 0s 13ms/step - loss: 1.3416 - accuracy: 0.4686
Epoch 27/200
10/10 [==============================] - 0s 11ms/step - loss: 1.2894 - accuracy: 0.4811
Epoch 28/200
10/10 [==============================] - 0s 10ms/step - loss: 1.2854 - accuracy: 0.5000
Epoch 29/200
10/10 [==============================] - 0s 11ms/step - loss: 1.1992 - accuracy: 0.5157
Epoch 30/200
10/10 [==============================] - 0s 11ms/step - loss: 1.1987 - accuracy: 0.4811
Epoch 31/200
10/10 [==============================] - 0s 12ms/step - loss: 1.2323 - accuracy: 0.5063
Epoch 32/200
10/10 [==============================] - 0s 13ms/step - loss: 1.1898 - accuracy: 0.5535
Epoch 33/200
10/10 [==============================] - 0s 9ms/step - loss: 1.1439 - accuracy: 0.5314
Epoch 34/200
10/10 [==============================] - 0s 7ms/step - loss: 1.1246 - accuracy: 0.5440
Epoch 35/200
10/10 [==============================] - 0s 8ms/step - loss: 1.1644 - accuracy: 0.5314
Epoch 36/200
10/10 [==============================] - 0s 8ms/step - loss: 1.0003 - accuracy: 0.5943
Epoch 37/200
10/10 [==============================] - 0s 8ms/step - loss: 1.1209 - accuracy: 0.5094
Epoch 38/200
10/10 [==============================] - 0s 8ms/step - loss: 1.0358 - accuracy: 0.5786
Epoch 39/200
10/10 [==============================] - 0s 7ms/step - loss: 1.0524 - accuracy: 0.5881
Epoch 40/200
10/10 [==============================] - 0s 8ms/step - loss: 1.0514 - accuracy: 0.5975
Epoch 41/200
10/10 [==============================] - 0s 7ms/step - loss: 1.0506 - accuracy: 0.5566
Epoch 42/200
10/10 [==============================] - 0s 11ms/step - loss: 0.9448 - accuracy: 0.6384
Epoch 43/200
10/10 [==============================] - 0s 9ms/step - loss: 0.9489 - accuracy: 0.6258
Epoch 44/200
10/10 [==============================] - 0s 8ms/step - loss: 0.9968 - accuracy: 0.6132
Epoch 45/200
10/10 [==============================] - 0s 8ms/step - loss: 0.9787 - accuracy: 0.6132
Epoch 46/200
10/10 [==============================] - 0s 9ms/step - loss: 0.9821 - accuracy: 0.6352
Epoch 47/200
10/10 [==============================] - 0s 7ms/step - loss: 1.0122 - accuracy: 0.5786
Epoch 48/200
10/10 [==============================] - 0s 9ms/step - loss: 0.9692 - accuracy: 0.6006
Epoch 49/200
10/10 [==============================] - 0s 8ms/step - loss: 0.9301 - accuracy: 0.5912
Epoch 50/200
10/10 [==============================] - 0s 8ms/step - loss: 0.9426 - accuracy: 0.5786
Epoch 51/200
10/10 [==============================] - 0s 8ms/step - loss: 0.9586 - accuracy: 0.6195
Epoch 52/200
10/10 [==============================] - 0s 8ms/step - loss: 0.9170 - accuracy: 0.6384
Epoch 53/200
10/10 [==============================] - 0s 9ms/step - loss: 0.9030 - accuracy: 0.6132
Epoch 54/200
10/10 [==============================] - 0s 8ms/step - loss: 0.8815 - accuracy: 0.6132
Epoch 55/200
10/10 [==============================] - 0s 10ms/step - loss: 0.8852 - accuracy: 0.6384
Epoch 56/200
10/10 [==============================] - 0s 7ms/step - loss: 0.8837 - accuracy: 0.6258
Epoch 57/200
10/10 [==============================] - 0s 8ms/step - loss: 0.8761 - accuracy: 0.6384
Epoch 58/200
10/10 [==============================] - 0s 8ms/step - loss: 0.8716 - accuracy: 0.6132
Epoch 59/200
10/10 [==============================] - 0s 9ms/step - loss: 0.8181 - accuracy: 0.6572
Epoch 60/200
10/10 [==============================] - 0s 8ms/step - loss: 0.8523 - accuracy: 0.6447
Epoch 61/200
10/10 [==============================] - 0s 10ms/step - loss: 0.8535 - accuracy: 0.6289
Epoch 62/200
10/10 [==============================] - 0s 8ms/step - loss: 0.7921 - accuracy: 0.6761
Epoch 63/200
10/10 [==============================] - 0s 9ms/step - loss: 0.8545 - accuracy: 0.6289
Epoch 64/200
10/10 [==============================] - 0s 8ms/step - loss: 0.8168 - accuracy: 0.6792
Epoch 65/200
10/10 [==============================] - 0s 9ms/step - loss: 0.8475 - accuracy: 0.6541
Epoch 66/200
10/10 [==============================] - 0s 8ms/step - loss: 0.7891 - accuracy: 0.6667
Epoch 67/200
10/10 [==============================] - 0s 9ms/step - loss: 0.8170 - accuracy: 0.6855
Epoch 68/200
10/10 [==============================] - 0s 8ms/step - loss: 0.8379 - accuracy: 0.6289
Epoch 69/200
10/10 [==============================] - 0s 8ms/step - loss: 0.7928 - accuracy: 0.6635
Epoch 70/200
10/10 [==============================] - 0s 8ms/step - loss: 0.7533 - accuracy: 0.6824
Epoch 71/200
10/10 [==============================] - 0s 8ms/step - loss: 0.7920 - accuracy: 0.7201
Epoch 72/200
10/10 [==============================] - 0s 8ms/step - loss: 0.8199 - accuracy: 0.6415
Epoch 73/200
10/10 [==============================] - 0s 11ms/step - loss: 0.8168 - accuracy: 0.6541
Epoch 74/200
10/10 [==============================] - 0s 9ms/step - loss: 0.7599 - accuracy: 0.6887
Epoch 75/200
10/10 [==============================] - 0s 8ms/step - loss: 0.8574 - accuracy: 0.6541
Epoch 76/200
10/10 [==============================] - 0s 8ms/step - loss: 0.7484 - accuracy: 0.6824
Epoch 77/200
10/10 [==============================] - 0s 7ms/step - loss: 0.7409 - accuracy: 0.6698
Epoch 78/200
10/10 [==============================] - 0s 8ms/step - loss: 0.7012 - accuracy: 0.7107
Epoch 79/200
10/10 [==============================] - 0s 7ms/step - loss: 0.7450 - accuracy: 0.6950
Epoch 80/200
10/10 [==============================] - 0s 8ms/step - loss: 0.7129 - accuracy: 0.6918
Epoch 81/200
10/10 [==============================] - 0s 7ms/step - loss: 0.8164 - accuracy: 0.6730
Epoch 82/200
10/10 [==============================] - 0s 8ms/step - loss: 0.8030 - accuracy: 0.6855
Epoch 83/200
10/10 [==============================] - 0s 10ms/step - loss: 0.8059 - accuracy: 0.6855
Epoch 84/200
10/10 [==============================] - 0s 8ms/step - loss: 0.7482 - accuracy: 0.6792
Epoch 85/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7959 - accuracy: 0.6824
Epoch 86/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7337 - accuracy: 0.6981
Epoch 87/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7208 - accuracy: 0.6855
Epoch 88/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7365 - accuracy: 0.7327
Epoch 89/200
10/10 [==============================] - 0s 5ms/step - loss: 0.8374 - accuracy: 0.6635
Epoch 90/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7431 - accuracy: 0.6792
Epoch 91/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7512 - accuracy: 0.6981
Epoch 92/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6963 - accuracy: 0.7044
Epoch 93/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6846 - accuracy: 0.7075
Epoch 94/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6726 - accuracy: 0.7201
Epoch 95/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7332 - accuracy: 0.7107
Epoch 96/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7664 - accuracy: 0.6792
Epoch 97/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6917 - accuracy: 0.7201
Epoch 98/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7508 - accuracy: 0.6887
Epoch 99/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6570 - accuracy: 0.7327
Epoch 100/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6772 - accuracy: 0.6981
Epoch 101/200
10/10 [==============================] - 0s 7ms/step - loss: 0.7026 - accuracy: 0.7201
Epoch 102/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6758 - accuracy: 0.7358
Epoch 103/200
10/10 [==============================] - 0s 6ms/step - loss: 0.7514 - accuracy: 0.7170
Epoch 104/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7572 - accuracy: 0.6918
Epoch 105/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7249 - accuracy: 0.6981
Epoch 106/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7080 - accuracy: 0.7075
Epoch 107/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7034 - accuracy: 0.7013
Epoch 108/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6893 - accuracy: 0.7233
Epoch 109/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6917 - accuracy: 0.7233
Epoch 110/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7058 - accuracy: 0.7201
Epoch 111/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6856 - accuracy: 0.7201
Epoch 112/200
10/10 [==============================] - 0s 5ms/step - loss: 0.7232 - accuracy: 0.7107
Epoch 113/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6703 - accuracy: 0.7516
Epoch 114/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6412 - accuracy: 0.7516
Epoch 115/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6638 - accuracy: 0.7516
Epoch 116/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6503 - accuracy: 0.7327
Epoch 117/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6391 - accuracy: 0.7421
Epoch 118/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6241 - accuracy: 0.7421
Epoch 119/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6504 - accuracy: 0.7421
Epoch 120/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6738 - accuracy: 0.7264
Epoch 121/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6992 - accuracy: 0.7264
Epoch 122/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6932 - accuracy: 0.7170
Epoch 123/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6666 - accuracy: 0.7421
Epoch 124/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6361 - accuracy: 0.7516
Epoch 125/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6640 - accuracy: 0.7233
Epoch 126/200
10/10 [==============================] - 0s 6ms/step - loss: 0.5860 - accuracy: 0.7704
Epoch 127/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6580 - accuracy: 0.7421
Epoch 128/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6183 - accuracy: 0.7579
Epoch 129/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6259 - accuracy: 0.7233
Epoch 130/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6487 - accuracy: 0.7264
Epoch 131/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6309 - accuracy: 0.7421
Epoch 132/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6710 - accuracy: 0.7201
Epoch 133/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6212 - accuracy: 0.7642
Epoch 134/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5998 - accuracy: 0.7579
Epoch 135/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6203 - accuracy: 0.7358
Epoch 136/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6140 - accuracy: 0.7579
Epoch 137/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6527 - accuracy: 0.7453
Epoch 138/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6130 - accuracy: 0.7579
Epoch 139/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6717 - accuracy: 0.7390
Epoch 140/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6448 - accuracy: 0.7421
Epoch 141/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6290 - accuracy: 0.7358
Epoch 142/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6122 - accuracy: 0.7296
Epoch 143/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6359 - accuracy: 0.7453
Epoch 144/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6340 - accuracy: 0.7642
Epoch 145/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6150 - accuracy: 0.7547
Epoch 146/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6387 - accuracy: 0.7547
Epoch 147/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6393 - accuracy: 0.7642
Epoch 148/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6277 - accuracy: 0.7201
Epoch 149/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6257 - accuracy: 0.7358
Epoch 150/200
10/10 [==============================] - 0s 7ms/step - loss: 0.6132 - accuracy: 0.7642
Epoch 151/200
10/10 [==============================] - 0s 7ms/step - loss: 0.6322 - accuracy: 0.7233
Epoch 152/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6011 - accuracy: 0.7642
Epoch 153/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5904 - accuracy: 0.7453
Epoch 154/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6158 - accuracy: 0.7484
Epoch 155/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5907 - accuracy: 0.7799
Epoch 156/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5789 - accuracy: 0.7830
Epoch 157/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5776 - accuracy: 0.7484
Epoch 158/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6020 - accuracy: 0.7327
Epoch 159/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6300 - accuracy: 0.7264
Epoch 160/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6164 - accuracy: 0.7484
Epoch 161/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5975 - accuracy: 0.7327
Epoch 162/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6504 - accuracy: 0.7484
Epoch 163/200
10/10 [==============================] - 0s 8ms/step - loss: 0.6039 - accuracy: 0.7516
Epoch 164/200
10/10 [==============================] - 0s 8ms/step - loss: 0.6248 - accuracy: 0.7453
Epoch 165/200
10/10 [==============================] - 0s 9ms/step - loss: 0.5973 - accuracy: 0.7547
Epoch 166/200
10/10 [==============================] - 0s 8ms/step - loss: 0.5911 - accuracy: 0.7610
Epoch 167/200
10/10 [==============================] - 0s 9ms/step - loss: 0.5754 - accuracy: 0.7579
Epoch 168/200
10/10 [==============================] - 0s 8ms/step - loss: 0.6598 - accuracy: 0.7170
Epoch 169/200
10/10 [==============================] - 0s 8ms/step - loss: 0.5394 - accuracy: 0.7453
Epoch 170/200
10/10 [==============================] - 0s 7ms/step - loss: 0.6287 - accuracy: 0.7421
Epoch 171/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5931 - accuracy: 0.7516
Epoch 172/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5966 - accuracy: 0.7547
Epoch 173/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5393 - accuracy: 0.7799
Epoch 174/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5618 - accuracy: 0.7421
Epoch 175/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5843 - accuracy: 0.7736
Epoch 176/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5499 - accuracy: 0.7673
Epoch 177/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5722 - accuracy: 0.7830
Epoch 178/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5916 - accuracy: 0.7673
Epoch 179/200
10/10 [==============================] - 0s 9ms/step - loss: 0.5499 - accuracy: 0.7767
Epoch 180/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5572 - accuracy: 0.7579
Epoch 181/200
10/10 [==============================] - 0s 9ms/step - loss: 0.5708 - accuracy: 0.7767
Epoch 182/200
10/10 [==============================] - 0s 8ms/step - loss: 0.5745 - accuracy: 0.7893
Epoch 183/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5570 - accuracy: 0.7767
Epoch 184/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5629 - accuracy: 0.7547
Epoch 185/200
10/10 [==============================] - 0s 7ms/step - loss: 0.6056 - accuracy: 0.7830
Epoch 186/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5938 - accuracy: 0.7547
Epoch 187/200
10/10 [==============================] - 0s 7ms/step - loss: 0.6297 - accuracy: 0.7673
Epoch 188/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5564 - accuracy: 0.7673
Epoch 189/200
10/10 [==============================] - 0s 8ms/step - loss: 0.5922 - accuracy: 0.7421
Epoch 190/200
10/10 [==============================] - 0s 8ms/step - loss: 0.5822 - accuracy: 0.7610
Epoch 191/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5384 - accuracy: 0.7925
Epoch 192/200
10/10 [==============================] - 0s 9ms/step - loss: 0.5409 - accuracy: 0.7736
Epoch 193/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5643 - accuracy: 0.7704
Epoch 194/200
10/10 [==============================] - 0s 8ms/step - loss: 0.5909 - accuracy: 0.7547
Epoch 195/200
10/10 [==============================] - 0s 8ms/step - loss: 0.5910 - accuracy: 0.7642
Epoch 196/200
10/10 [==============================] - 0s 8ms/step - loss: 0.5623 - accuracy: 0.7799
Epoch 197/200
10/10 [==============================] - 0s 7ms/step - loss: 0.5661 - accuracy: 0.7704
Epoch 198/200
10/10 [==============================] - 0s 8ms/step - loss: 0.5541 - accuracy: 0.7201
Epoch 199/200

In [ ]:
model_2015.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0005
try:
  model_2015.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
10/10 [==============================] - 2s 6ms/step - loss: 0.5492 - accuracy: 0.7862
Epoch 2/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5361 - accuracy: 0.7925
Epoch 3/100
10/10 [==============================] - 0s 7ms/step - loss: 0.5576 - accuracy: 0.7673
Epoch 4/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5169 - accuracy: 0.7673
Epoch 5/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5082 - accuracy: 0.8082
Epoch 6/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5576 - accuracy: 0.7484
Epoch 7/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5048 - accuracy: 0.8050
Epoch 8/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5282 - accuracy: 0.7862
Epoch 9/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5250 - accuracy: 0.7862
Epoch 10/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5829 - accuracy: 0.7610
Epoch 11/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5101 - accuracy: 0.8145
Epoch 12/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4978 - accuracy: 0.8082
Epoch 13/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5276 - accuracy: 0.8050
Epoch 14/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5010 - accuracy: 0.7893
Epoch 15/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4877 - accuracy: 0.8050
Epoch 16/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5058 - accuracy: 0.8113
Epoch 17/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5229 - accuracy: 0.7767
Epoch 18/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4988 - accuracy: 0.8082
Epoch 19/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4914 - accuracy: 0.7893
Epoch 20/100
10/10 [==============================] - 0s 7ms/step - loss: 0.5061 - accuracy: 0.7987
Epoch 21/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5021 - accuracy: 0.8019
Epoch 22/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4874 - accuracy: 0.8208
Epoch 23/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4719 - accuracy: 0.8113
Epoch 24/100
10/10 [==============================] - 0s 6ms/step - loss: 0.5183 - accuracy: 0.7956
Epoch 25/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4825 - accuracy: 0.8019
Epoch 26/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5006 - accuracy: 0.8176
Epoch 27/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4577 - accuracy: 0.8145
Epoch 28/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4703 - accuracy: 0.8019
Epoch 29/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5219 - accuracy: 0.7830
Epoch 30/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5339 - accuracy: 0.8019
Epoch 31/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5044 - accuracy: 0.7862
Epoch 32/100
10/10 [==============================] - 0s 4ms/step - loss: 0.4584 - accuracy: 0.8113
Epoch 33/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4668 - accuracy: 0.7956
Epoch 34/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4975 - accuracy: 0.7862
Epoch 35/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4633 - accuracy: 0.8082
Epoch 36/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4726 - accuracy: 0.8302
Epoch 37/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5257 - accuracy: 0.7893
Epoch 38/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5012 - accuracy: 0.8019
Epoch 39/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4932 - accuracy: 0.7987
Epoch 40/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5118 - accuracy: 0.7987
Epoch 41/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4827 - accuracy: 0.8239
Epoch 42/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5050 - accuracy: 0.8239
Epoch 43/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5116 - accuracy: 0.8113
Epoch 44/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4871 - accuracy: 0.8176
Epoch 45/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5376 - accuracy: 0.7893
Epoch 46/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4970 - accuracy: 0.8019
Epoch 47/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4787 - accuracy: 0.8239
Epoch 48/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5169 - accuracy: 0.7799
Epoch 49/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4858 - accuracy: 0.8050
Epoch 50/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5038 - accuracy: 0.7956
Epoch 51/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4880 - accuracy: 0.8050
Epoch 52/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5296 - accuracy: 0.8050
Epoch 53/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4892 - accuracy: 0.7830
Epoch 54/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4821 - accuracy: 0.7987
Epoch 55/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4656 - accuracy: 0.8333
Epoch 56/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4601 - accuracy: 0.8302
Epoch 57/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4454 - accuracy: 0.8333
Epoch 58/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5062 - accuracy: 0.8113
Epoch 59/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4433 - accuracy: 0.8270
Epoch 60/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4059 - accuracy: 0.8459
Epoch 61/100
10/10 [==============================] - 0s 8ms/step - loss: 0.5221 - accuracy: 0.7799
Epoch 62/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4750 - accuracy: 0.7956
Epoch 63/100
10/10 [==============================] - 0s 6ms/step - loss: 0.5022 - accuracy: 0.7925
Epoch 64/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4826 - accuracy: 0.8302
Epoch 65/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4291 - accuracy: 0.8208
Epoch 66/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4833 - accuracy: 0.7925
Epoch 67/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4674 - accuracy: 0.8145
Epoch 68/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4929 - accuracy: 0.8113
Epoch 69/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4817 - accuracy: 0.8145
Epoch 70/100
10/10 [==============================] - 0s 9ms/step - loss: 0.5010 - accuracy: 0.7956
Epoch 71/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4346 - accuracy: 0.8428
Epoch 72/100
10/10 [==============================] - 0s 8ms/step - loss: 0.5186 - accuracy: 0.7767
Epoch 73/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4386 - accuracy: 0.8333
Epoch 74/100
10/10 [==============================] - 0s 8ms/step - loss: 0.5266 - accuracy: 0.7862
Epoch 75/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4587 - accuracy: 0.8176
Epoch 76/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4255 - accuracy: 0.8239
Epoch 77/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4823 - accuracy: 0.8113
Epoch 78/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4787 - accuracy: 0.7956
Epoch 79/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4298 - accuracy: 0.8333
Epoch 80/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4651 - accuracy: 0.8176
Epoch 81/100
10/10 [==============================] - 0s 9ms/step - loss: 0.4936 - accuracy: 0.8113
Epoch 82/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4236 - accuracy: 0.8459
Epoch 83/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4911 - accuracy: 0.7987
Epoch 84/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4955 - accuracy: 0.7799
Epoch 85/100
10/10 [==============================] - 0s 10ms/step - loss: 0.4229 - accuracy: 0.8145
Epoch 86/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4721 - accuracy: 0.8270
Epoch 87/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4568 - accuracy: 0.8145
Epoch 88/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4648 - accuracy: 0.8145
Epoch 89/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4492 - accuracy: 0.8302
Epoch 90/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4556 - accuracy: 0.8428
Epoch 91/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4603 - accuracy: 0.8302
Epoch 92/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4175 - accuracy: 0.8302
Epoch 93/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4718 - accuracy: 0.8145
Epoch 94/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4590 - accuracy: 0.8302
Epoch 95/100
10/10 [==============================] - 0s 8ms/step - loss: 0.5213 - accuracy: 0.7893
Epoch 96/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4460 - accuracy: 0.8239
Epoch 97/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4554 - accuracy: 0.8113
Epoch 98/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4586 - accuracy: 0.7893
Epoch 99/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4386 - accuracy: 0.8270
Epoch 100/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4437 - accuracy: 0.8113

In [ ]:
model_2015.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.0001
try:
  model_2015.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
10/10 [==============================] - 3s 5ms/step - loss: 0.4439 - accuracy: 0.8302
Epoch 2/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4250 - accuracy: 0.8239
Epoch 3/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4104 - accuracy: 0.8365
Epoch 4/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4136 - accuracy: 0.8208
Epoch 5/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4575 - accuracy: 0.8302
Epoch 6/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4832 - accuracy: 0.7862
Epoch 7/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4107 - accuracy: 0.8365
Epoch 8/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4282 - accuracy: 0.8113
Epoch 9/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4248 - accuracy: 0.8428
Epoch 10/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4599 - accuracy: 0.8145
Epoch 11/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4136 - accuracy: 0.8491
Epoch 12/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3983 - accuracy: 0.8365
Epoch 13/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3851 - accuracy: 0.8616
Epoch 14/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4565 - accuracy: 0.8396
Epoch 15/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4507 - accuracy: 0.8082
Epoch 16/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4198 - accuracy: 0.8333
Epoch 17/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4663 - accuracy: 0.8176
Epoch 18/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3969 - accuracy: 0.8239
Epoch 19/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4396 - accuracy: 0.8270
Epoch 20/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4443 - accuracy: 0.8365
Epoch 21/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4307 - accuracy: 0.8396
Epoch 22/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4254 - accuracy: 0.8302
Epoch 23/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3720 - accuracy: 0.8585
Epoch 24/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4017 - accuracy: 0.8239
Epoch 25/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4171 - accuracy: 0.8428
Epoch 26/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4139 - accuracy: 0.8428
Epoch 27/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4539 - accuracy: 0.8082
Epoch 28/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4084 - accuracy: 0.8459
Epoch 29/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3838 - accuracy: 0.8396
Epoch 30/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3839 - accuracy: 0.8491
Epoch 31/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4347 - accuracy: 0.8333
Epoch 32/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3716 - accuracy: 0.8585
Epoch 33/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4601 - accuracy: 0.8270
Epoch 34/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4461 - accuracy: 0.8208
Epoch 35/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4152 - accuracy: 0.8208
Epoch 36/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4211 - accuracy: 0.8365
Epoch 37/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4199 - accuracy: 0.8239
Epoch 38/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4175 - accuracy: 0.8333
Epoch 39/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4293 - accuracy: 0.8648
Epoch 40/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4107 - accuracy: 0.8208
Epoch 41/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4258 - accuracy: 0.8050
Epoch 42/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3963 - accuracy: 0.8648
Epoch 43/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4249 - accuracy: 0.8428
Epoch 44/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4198 - accuracy: 0.8302
Epoch 45/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4119 - accuracy: 0.8428
Epoch 46/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4086 - accuracy: 0.8333
Epoch 47/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4542 - accuracy: 0.8270
Epoch 48/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3947 - accuracy: 0.8428
Epoch 49/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4122 - accuracy: 0.8396
Epoch 50/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4357 - accuracy: 0.8365
Epoch 51/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4427 - accuracy: 0.8239
Epoch 52/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4160 - accuracy: 0.8522
Epoch 53/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4285 - accuracy: 0.8239
Epoch 54/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4148 - accuracy: 0.8208
Epoch 55/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4033 - accuracy: 0.8270
Epoch 56/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4013 - accuracy: 0.8679
Epoch 57/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4150 - accuracy: 0.8522
Epoch 58/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4647 - accuracy: 0.8145
Epoch 59/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3980 - accuracy: 0.8428
Epoch 60/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4084 - accuracy: 0.8113
Epoch 61/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3951 - accuracy: 0.8459
Epoch 62/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4367 - accuracy: 0.8270
Epoch 63/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4154 - accuracy: 0.8491
Epoch 64/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3962 - accuracy: 0.8491
Epoch 65/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3746 - accuracy: 0.8648
Epoch 66/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3848 - accuracy: 0.8585
Epoch 67/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4416 - accuracy: 0.8145
Epoch 68/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4318 - accuracy: 0.8176
Epoch 69/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3984 - accuracy: 0.8459
Epoch 70/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3771 - accuracy: 0.8522
Epoch 71/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3944 - accuracy: 0.8491
Epoch 72/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3972 - accuracy: 0.8239
Epoch 73/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4009 - accuracy: 0.8396
Epoch 74/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3999 - accuracy: 0.8522
Epoch 75/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4309 - accuracy: 0.8333
Epoch 76/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4041 - accuracy: 0.8302
Epoch 77/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4315 - accuracy: 0.8176
Epoch 78/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4034 - accuracy: 0.8302
Epoch 79/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3763 - accuracy: 0.8491
Epoch 80/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3656 - accuracy: 0.8333
Epoch 81/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4327 - accuracy: 0.8239
Epoch 82/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3668 - accuracy: 0.8585
Epoch 83/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4075 - accuracy: 0.8428
Epoch 84/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3983 - accuracy: 0.8333
Epoch 85/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3710 - accuracy: 0.8679
Epoch 86/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4058 - accuracy: 0.8365
Epoch 87/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4099 - accuracy: 0.8302
Epoch 88/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3825 - accuracy: 0.8459
Epoch 89/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3734 - accuracy: 0.8428
Epoch 90/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4211 - accuracy: 0.8302
Epoch 91/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3847 - accuracy: 0.8711
Epoch 92/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4296 - accuracy: 0.8176
Epoch 93/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3806 - accuracy: 0.8459
Epoch 94/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4052 - accuracy: 0.8239
Epoch 95/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4153 - accuracy: 0.8333
Epoch 96/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3974 - accuracy: 0.8428
Epoch 97/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4175 - accuracy: 0.8270
Epoch 98/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3845 - accuracy: 0.8553
Epoch 99/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4093 - accuracy: 0.8553
Epoch 100/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3729 - accuracy: 0.8459

In [ ]:
model_2015.compile(optimizer=tf.keras.optimizers.Adam(0.00005),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.00005
try:
  model_2015.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
10/10 [==============================] - 2s 5ms/step - loss: 0.4383 - accuracy: 0.8176
Epoch 2/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4011 - accuracy: 0.8553
Epoch 3/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3750 - accuracy: 0.8459
Epoch 4/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4246 - accuracy: 0.8396
Epoch 5/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4070 - accuracy: 0.8491
Epoch 6/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4094 - accuracy: 0.8302
Epoch 7/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4047 - accuracy: 0.8428
Epoch 8/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3965 - accuracy: 0.8302
Epoch 9/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3845 - accuracy: 0.8491
Epoch 10/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3919 - accuracy: 0.8333
Epoch 11/100
10/10 [==============================] - 0s 10ms/step - loss: 0.3929 - accuracy: 0.8459
Epoch 12/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3933 - accuracy: 0.8365
Epoch 13/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3688 - accuracy: 0.8459
Epoch 14/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3982 - accuracy: 0.8396
Epoch 15/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3888 - accuracy: 0.8585
Epoch 16/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3850 - accuracy: 0.8428
Epoch 17/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4098 - accuracy: 0.8365
Epoch 18/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4313 - accuracy: 0.8239
Epoch 19/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4192 - accuracy: 0.8176
Epoch 20/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3548 - accuracy: 0.8585
Epoch 21/100
10/10 [==============================] - 0s 9ms/step - loss: 0.4296 - accuracy: 0.8176
Epoch 22/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3812 - accuracy: 0.8648
Epoch 23/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4021 - accuracy: 0.8491
Epoch 24/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3604 - accuracy: 0.8553
Epoch 25/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4214 - accuracy: 0.8365
Epoch 26/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4411 - accuracy: 0.8145
Epoch 27/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4478 - accuracy: 0.8145
Epoch 28/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3833 - accuracy: 0.8302
Epoch 29/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4000 - accuracy: 0.8522
Epoch 30/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3711 - accuracy: 0.8491
Epoch 31/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3976 - accuracy: 0.8208
Epoch 32/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4416 - accuracy: 0.8208
Epoch 33/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4207 - accuracy: 0.8302
Epoch 34/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3824 - accuracy: 0.8491
Epoch 35/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4245 - accuracy: 0.8396
Epoch 36/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3745 - accuracy: 0.8585
Epoch 37/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4079 - accuracy: 0.8302
Epoch 38/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4141 - accuracy: 0.8113
Epoch 39/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4030 - accuracy: 0.8553
Epoch 40/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3843 - accuracy: 0.8616
Epoch 41/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4070 - accuracy: 0.8365
Epoch 42/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3462 - accuracy: 0.8679
Epoch 43/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4264 - accuracy: 0.8270
Epoch 44/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4148 - accuracy: 0.8522
Epoch 45/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4586 - accuracy: 0.8428
Epoch 46/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3814 - accuracy: 0.8459
Epoch 47/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3726 - accuracy: 0.8585
Epoch 48/100
10/10 [==============================] - 0s 9ms/step - loss: 0.4223 - accuracy: 0.8302
Epoch 49/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3565 - accuracy: 0.8679
Epoch 50/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3827 - accuracy: 0.8459
Epoch 51/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3519 - accuracy: 0.8711
Epoch 52/100
10/10 [==============================] - 0s 9ms/step - loss: 0.3680 - accuracy: 0.8648
Epoch 53/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3789 - accuracy: 0.8585
Epoch 54/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4045 - accuracy: 0.8333
Epoch 55/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3803 - accuracy: 0.8491
Epoch 56/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3858 - accuracy: 0.8491
Epoch 57/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3597 - accuracy: 0.8491
Epoch 58/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3868 - accuracy: 0.8396
Epoch 59/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3850 - accuracy: 0.8522
Epoch 60/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3379 - accuracy: 0.8774
Epoch 61/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3564 - accuracy: 0.8522
Epoch 62/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3957 - accuracy: 0.8365
Epoch 63/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3959 - accuracy: 0.8428
Epoch 64/100
10/10 [==============================] - 0s 9ms/step - loss: 0.4075 - accuracy: 0.8585
Epoch 65/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3756 - accuracy: 0.8333
Epoch 66/100
10/10 [==============================] - 0s 9ms/step - loss: 0.3508 - accuracy: 0.8711
Epoch 67/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4250 - accuracy: 0.8333
Epoch 68/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4469 - accuracy: 0.8176
Epoch 69/100
10/10 [==============================] - 0s 9ms/step - loss: 0.3436 - accuracy: 0.8805
Epoch 70/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3886 - accuracy: 0.8459
Epoch 71/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3783 - accuracy: 0.8616
Epoch 72/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3990 - accuracy: 0.8522
Epoch 73/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3718 - accuracy: 0.8522
Epoch 74/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3778 - accuracy: 0.8428
Epoch 75/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3791 - accuracy: 0.8522
Epoch 76/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4416 - accuracy: 0.8396
Epoch 77/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4068 - accuracy: 0.8270
Epoch 78/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3852 - accuracy: 0.8491
Epoch 79/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3757 - accuracy: 0.8616
Epoch 80/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3880 - accuracy: 0.8302
Epoch 81/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4071 - accuracy: 0.8491
Epoch 82/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3605 - accuracy: 0.8491
Epoch 83/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3660 - accuracy: 0.8616
Epoch 84/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3655 - accuracy: 0.8522
Epoch 85/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4041 - accuracy: 0.8208
Epoch 86/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4104 - accuracy: 0.8396
Epoch 87/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3450 - accuracy: 0.8648
Epoch 88/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3852 - accuracy: 0.8302
Epoch 89/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4038 - accuracy: 0.8553
Epoch 90/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4080 - accuracy: 0.8428
Epoch 91/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4312 - accuracy: 0.8239
Epoch 92/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3927 - accuracy: 0.8365
Epoch 93/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3258 - accuracy: 0.8805
Epoch 94/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3893 - accuracy: 0.8459
Epoch 95/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3917 - accuracy: 0.8396
Epoch 96/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4036 - accuracy: 0.8616
Epoch 97/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3472 - accuracy: 0.8522
Epoch 98/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3946 - accuracy: 0.8396
Epoch 99/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4374 - accuracy: 0.8270
Epoch 100/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4131 - accuracy: 0.8491

In [ ]:
model_2015.compile(optimizer=tf.keras.optimizers.Adam(0.000001),
              loss=tf.keras.losses.sparse_categorical_crossentropy,
              metrics=['accuracy'])
# Learning rate: 0.000001
try:
  model_2015.fit(X_train, y_train, epochs=100)
except Exception as ex:
  print(ex)

Epoch 1/100
10/10 [==============================] - 2s 5ms/step - loss: 0.4083 - accuracy: 0.8585
Epoch 2/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4157 - accuracy: 0.8396
Epoch 3/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4074 - accuracy: 0.8239
Epoch 4/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3907 - accuracy: 0.8522
Epoch 5/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3749 - accuracy: 0.8491
Epoch 6/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4448 - accuracy: 0.8145
Epoch 7/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3918 - accuracy: 0.8428
Epoch 8/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3963 - accuracy: 0.8522
Epoch 9/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3794 - accuracy: 0.8459
Epoch 10/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3960 - accuracy: 0.8553
Epoch 11/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3711 - accuracy: 0.8553
Epoch 12/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4137 - accuracy: 0.8428
Epoch 13/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3731 - accuracy: 0.8396
Epoch 14/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4126 - accuracy: 0.8333
Epoch 15/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3785 - accuracy: 0.8522
Epoch 16/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3818 - accuracy: 0.8491
Epoch 17/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3849 - accuracy: 0.8742
Epoch 18/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4065 - accuracy: 0.8459
Epoch 19/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3534 - accuracy: 0.8553
Epoch 20/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3861 - accuracy: 0.8522
Epoch 21/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3561 - accuracy: 0.8522
Epoch 22/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3806 - accuracy: 0.8459
Epoch 23/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4177 - accuracy: 0.8302
Epoch 24/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4042 - accuracy: 0.8428
Epoch 25/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3762 - accuracy: 0.8459
Epoch 26/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3795 - accuracy: 0.8270
Epoch 27/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4352 - accuracy: 0.8176
Epoch 28/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3712 - accuracy: 0.8679
Epoch 29/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3715 - accuracy: 0.8616
Epoch 30/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3743 - accuracy: 0.8522
Epoch 31/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3891 - accuracy: 0.8459
Epoch 32/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4231 - accuracy: 0.8333
Epoch 33/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3682 - accuracy: 0.8491
Epoch 34/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3527 - accuracy: 0.8711
Epoch 35/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4497 - accuracy: 0.8050
Epoch 36/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3603 - accuracy: 0.8522
Epoch 37/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4308 - accuracy: 0.8491
Epoch 38/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3849 - accuracy: 0.8553
Epoch 39/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3907 - accuracy: 0.8616
Epoch 40/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3321 - accuracy: 0.8742
Epoch 41/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3959 - accuracy: 0.8428
Epoch 42/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4084 - accuracy: 0.8333
Epoch 43/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3613 - accuracy: 0.8711
Epoch 44/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3990 - accuracy: 0.8522
Epoch 45/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3926 - accuracy: 0.8302
Epoch 46/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4054 - accuracy: 0.8333
Epoch 47/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3814 - accuracy: 0.8428
Epoch 48/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3617 - accuracy: 0.8553
Epoch 49/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3657 - accuracy: 0.8585
Epoch 50/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3929 - accuracy: 0.8585
Epoch 51/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4207 - accuracy: 0.8270
Epoch 52/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3936 - accuracy: 0.8365
Epoch 53/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4174 - accuracy: 0.8396
Epoch 54/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3931 - accuracy: 0.8585
Epoch 55/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3683 - accuracy: 0.8585
Epoch 56/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3913 - accuracy: 0.8459
Epoch 57/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4070 - accuracy: 0.8428
Epoch 58/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3857 - accuracy: 0.8428
Epoch 59/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3946 - accuracy: 0.8616
Epoch 60/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4399 - accuracy: 0.8270
Epoch 61/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3767 - accuracy: 0.8648
Epoch 62/100
10/10 [==============================] - 0s 5ms/step - loss: 0.4002 - accuracy: 0.8396
Epoch 63/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3495 - accuracy: 0.8711
Epoch 64/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3911 - accuracy: 0.8365
Epoch 65/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3855 - accuracy: 0.8365
Epoch 66/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3554 - accuracy: 0.8491
Epoch 67/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3889 - accuracy: 0.8396
Epoch 68/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3787 - accuracy: 0.8365
Epoch 69/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3860 - accuracy: 0.8270
Epoch 70/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3844 - accuracy: 0.8365
Epoch 71/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3709 - accuracy: 0.8459
Epoch 72/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3756 - accuracy: 0.8616
Epoch 73/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3629 - accuracy: 0.8491
Epoch 74/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3876 - accuracy: 0.8302
Epoch 75/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4050 - accuracy: 0.8396
Epoch 76/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3904 - accuracy: 0.8585
Epoch 77/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3712 - accuracy: 0.8616
Epoch 78/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3458 - accuracy: 0.8679
Epoch 79/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3912 - accuracy: 0.8459
Epoch 80/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4177 - accuracy: 0.8365
Epoch 81/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4277 - accuracy: 0.8208
Epoch 82/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4015 - accuracy: 0.8365
Epoch 83/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3970 - accuracy: 0.8333
Epoch 84/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4135 - accuracy: 0.8270
Epoch 85/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4189 - accuracy: 0.8333
Epoch 86/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3825 - accuracy: 0.8428
Epoch 87/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3780 - accuracy: 0.8459
Epoch 88/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3969 - accuracy: 0.8459
Epoch 89/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4212 - accuracy: 0.8522
Epoch 90/100
10/10 [==============================] - 0s 9ms/step - loss: 0.4179 - accuracy: 0.8302
Epoch 91/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4072 - accuracy: 0.8396
Epoch 92/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4035 - accuracy: 0.8428
Epoch 93/100
10/10 [==============================] - 0s 7ms/step - loss: 0.4207 - accuracy: 0.8302
Epoch 94/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3765 - accuracy: 0.8459
Epoch 95/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3956 - accuracy: 0.8365
Epoch 96/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3757 - accuracy: 0.8553
Epoch 97/100
10/10 [==============================] - 0s 10ms/step - loss: 0.4175 - accuracy: 0.8239
Epoch 98/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4061 - accuracy: 0.8302
Epoch 99/100
10/10 [==============================] - 0s 8ms/step - loss: 0.4507 - accuracy: 0.8239
Epoch 100/100
10/10 [==============================] - 0s 8ms/step - loss: 0.3833 - accuracy: 0.8585

In [ ]:
model_2015.save("/content/drive/MyDrive/FYP/Trained Models/2015.keras")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/FYP/Trained Models/2015.keras'

In [ ]:
accuracies = []

In [ ]:
predictions = model_2015(X_test)

In [ ]:
# Convert softmax output to predicted class labels
predicted_labels = np.argmax(predictions, axis=1)

In [ ]:
from sklearn.metrics import accuracy_score
# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

In [ ]:
accuracy

0.7625

In [ ]:

params = {
    'objective': 'multi:softmax',    # for multiclass classification
    'num_class': 20,        # number of classes in your dataset
    'eval_metric': 'merror',         # evaluation metric (multiclass error rate)
    'max_depth': 6                   # maximum depth of trees
}
dtrain = xgb.DMatrix(X_train, label=y_train)
model = xgb.train(params, dtrain)

In [ ]:
dval = xgb.DMatrix(x_val)
predictions = model.predict(dval)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming 'predictions' contains the predicted labels for the test data
accuracy = accuracy_score(y_val, predictions)

print("XGBoost Accuracy:", accuracy)

In [ ]:
# Saving XGBoost
# Save the model to a file
with open("/content/drive/MyDrive/FYP/Machine Learning Models/2015.xgb", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully.")