## Importing Libraries

In [44]:
import pandas as pd
import spacy

In [45]:
import tensorflow as tf

In [46]:
import numpy as np

In [47]:
from sklearn.preprocessing import LabelEncoder

## Data Preprocessing

In [48]:
data_frame = pd.read_csv('/content/drive/MyDrive/Sentiment Analysis Using Transformer Architecture/IMDB Dataset.csv')

In [49]:
nlp_spacy = spacy.load('en_core_web_sm')

In [50]:
# Show full text for pandas cells
pd.set_option('display.max_colwidth', None)

In [51]:
data_frame.columns

Index(['review', 'sentiment'], dtype='object')

In [52]:
data_frame.head(5)

,review,sentiment
0,"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.",positive
1,"A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only ""has got all the polari"" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.",positive
2,"I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I'd laughed at one of Woody's comedies in years (dare I say a decade?). While I've never been impressed with Scarlet Johanson, in this she managed to tone down her ""sexy"" image and jumped right into a average, but spirited young woman.<br /><br />This may not be the crown jewel of his career, but it was wittier than ""Devil Wears Prada"" and more interesting than ""Superman"" a great comedy to go see with friends.",positive
3,"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.",negative
4,"Petter Mattei's ""Love in the Time of Money"" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situations we encounter. <br /><br />This being a variation on the Arthur Schnitzler's play about the same theme, the director transfers the action to the present time New York where all these different characters meet and connect. Each one is connected in one way, or another to the next person, but no one seems to know the previous point of contact. Stylishly, the film has a sophisticated luxurious look. We are taken to see how these people live and the world they live in their own habitat.<br /><br />The only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. A big city is not exactly the best place in which human relations find sincere fulfillment, as one discerns is the case with most of the people we encounter.<br /><br />The acting is good under Mr. Mattei's direction. Steve Buscemi, Rosario Dawson, Carol Kane, Michael Imperioli, Adrian Grenier, and the rest of the talented cast, make these characters come alive.<br /><br />We wish Mr. Mattei good luck and await anxiously for his next work.",positive

In [53]:
le = LabelEncoder()

In [54]:
reviews = data_frame['review']

In [55]:
sentiments = data_frame['sentiment']

In [56]:
sentiments = le.fit_transform(sentiments)

In [57]:
sentiments

array([1, 1, 1, ..., 0, 0, 0])

In [58]:
def lower_replace(series):
  # Make all text lower case
  output = series.str.lower()
  # Remove Punctuation
  output = output.str.replace(r'[^\w\s]', '', regex=True)
  # Remove Square Brackets
  output = output.str.replace(r'\[.*?\]', '', regex=True)
  return output

In [59]:
reviews.head(2)

0    One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.
Name: review, dtype: object

In [70]:
reviews = lower_replace(reviews)

In [79]:
def token_lemma_nonstop(text):
  # Creating Spacing Document
  doc = nlp_spacy(text)
  # Tokenization, lemmatization, &
  output = [token.lemma_ for token in doc if not token.is_stop]
  output = ' '.join(output)
  return output

In [80]:
token_lemma_nonstop(reviews[0])

'reviewer mention watch 1 oz episode ll hook right exactly happen mebr br thing strike oz brutality unflinche scene violence set right word trust faint hearted timid pull punch regard drug sex violence hardcore classic use wordbr br call oz nickname give oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inward privacy high agenda em city home manyaryan muslims gangstas latinos christians italian irish moreso scuffle death stare dodgy dealing shady agreement far awaybr br main appeal fact go show not dare forget pretty picture paint mainstream audience forget charm forget romanceoz not mess episode see strike nasty surreal not ready watch develop taste oz get accustom high level graphic violence violence injustice crook guard ll sell nickel inmate ll kill order away mannered middle class inmate turn prison bitch lack street skill prison experience watch oz comfortable uncomfortable viewingthat touch dark'

In [81]:
reviews = reviews.apply(token_lemma_nonstop)

In [82]:
reviews

0        reviewer mention watch 1 oz episode ll hook right exactly happen mebr br thing strike oz brutality unflinche scene violence set right word trust faint hearted timid pull punch regard drug sex violence hardcore classic use wordbr br call oz nickname give oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inward privacy high agenda em city home manyaryan muslims gangstas latinos christians italian irish moreso scuffle death stare dodgy dealing shady agreement far awaybr br main appeal fact go show not dare forget pretty picture paint mainstream audience forget charm forget romanceoz not mess episode see strike nasty surreal not ready watch develop taste oz get accustom high level graphic violence violence injustice crook guard ll sell nickel inmate ll kill order away mannered middle class inmate turn prison bitch lack street skill prison experience watch oz comfortable uncomfortable viewingthat touch dark
1                                                                                                                                                                                                                                                                                                                                                                                                                        wonderful little production br br filming technique unassuming oldtimebbc fashion give comfort discomforte sense realism entire piece br br actor extremely choose michael sheen get polari voice pat truly seamless editing guide reference williams diary entry worth watching terrificly write perform piece masterful production great master comedy life br br realism come home little thing fantasy guard use traditional dream technique remain solid disappear play knowledge sense particularly scene concern orton halliwell set particularly flat halliwell mural decorate surface terribly
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        think wonderful way spend time hot summer weekend sit air condition theater watch lighthearted comedy plot simplistic dialogue witty character likable bread suspect serial killer disappoint realize match point 2 risk addiction think proof woody allen fully control style grow lovebr br d laugh woodys comedy year dare decade ve impress scarlet johanson manage tone sexy image jump right average spirited young womanbr br crown jewel career witty devil wear prada interesting superman great comedy friend
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           basically s family little boy jake think s zombie closet   parent fight timebr br movie slow soap opera suddenly jake decide rambo kill zombiebr br ok go film decide thriller drama drama movie watchable parent divorce   argue like real life jake closet totally ruin film expect boogeyman similar movie instead watch drama meaningless thriller spotsbr br 3 10 play parent   descent dialog shot jake ignore
4                                                                                                                                                                                                           petter matteis love time money visually stunning film watch mr mattei offer vivid portrait human relation movie tell money power success people different situation encounter br br variation arthur schnitzler play theme director transfer action present time new york different character meet connect connect way person know previous point contact stylishly film sophisticated luxurious look take people live world live habitatbr br thing get soul picture different stage loneliness inhabit big city exactly good place human relation find sincere fulfillment discern case people encounterbr br acting good mr matteis direction steve buscemi rosario dawson carol kane michael imperioli adrian grenier rest talented cast character come alivebr br wish mr mattei good luck await anxiously work
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ...
49995                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 think movie right good job not creative original expect lotta fun think like come dvd m go pay money proudly cent sharon stone great movie horriblecatwoman movie not movie underrated lifetime probably classic like 20 yr not wait classic watch enjoy not expect masterpiece s grip soul touch allow life involve theirsbr br movie entertaining recommend people not see critic box office not count know enjoy tip hat moviebr br 810
49996                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bad plot bad dialogue bad acting idiotic direct annoying porn groove soundtrack run continually overact script crappy copy vhs redeem consume liquor trust stick turkey end pathetically bad figure fourthrate spoof springtime hitlerbr br girl play janis joplin faint spark interest sing well originalbr br want watch similar thousand time well watch valley doll
49997                                                                                                                                                                                                                                                                                        catholic teach parochial elementary school nun teach jesuit priest high school   college practice catholic consider good catholic church eye not believe certain thing act certain way church tell tobr br movieit bad people kill nun suppose satire embodiment female religious figurehead comedy satire acting diane keaton see play different movie goodbr br think gun fake shoot plan female lead student attempt demonstrate sister marys emotional intellectual bigotry faith turn bullet real story tragedythe tragedy loss life studentsthe life aborted baby life student mom tragedy dogmatic authority love people tragedy organized religion replace true faith god wrong todays islam yesterday judaism christianity
49998                                                                                                                                                                                                                                                                               m go disagree previous comment maltin second rate excessively vicious western creak groan try central theme wild west tame kick aside steady march time like tradition butch cassidy sundance kid lack film poignancy charm andrew mclaglens direction limp final 30 minute real botch incomprehensible strategy hero charlton heston chris mitchum holler explain set hillside fire callous treatment rape scene womans reaction certainly ring true coburn plenty nasty half breed escape convict revenge fellow escapee underdeveloped like bowl pin knock story lurch forward michael park give typically shifty lethargic mumbling performance case appropriate modern style sheriff symbolize complacency technological progress bring
49999                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     expect star trek movie high art fan expect movie good good episode unfortunately movie muddle implausible plot leave cringe   far bad far movie chance watch know character interact movie not save movie   include goofy scene kirk spock mccoy yosemitebr br movie worth rental hardly worth watch true fan need movie rent movie way ll   cable channel avoid movie
Name: review, Length: 50000, dtype: object

In [83]:
type(reviews)

pandas.core.series.Series

In [86]:
reviews.to_pickle('/content/drive/MyDrive/Sentiment Analysis Using Transformer Architecture/reviews_pipeline.pkl')

In [88]:
reviews.to_csv('/content/drive/MyDrive/Sentiment Analysis Using Transformer Architecture/reviews_pipeline.csv', index=False)